### PR TITLE
tests/nested/manual/fde-on-classic: fix wrong gadget.yaml

### PR DESCRIPTION
**Pull request by valentindavid**

### CODE REVIEW

**Review by mvo5 — APPROVED** [review]
Thank you

**Review by sergiocazzolato — APPROVED** [review]
Nice thanks for the fix

**Review by alfonsosanchezbeato — COMMENTED** [review]
The fix looks good, but I'm not sure if I agree with removing gadget.yaml and instead using the one we ship in the gadget. We will eventually have a different gadget for classic almost for sure, and the things we want to test do not necessarily coincide with what we ship in the official gadget anyway (for instance, I have a test in another PR that adds new stuff to the gadget that we do not have or will have in the pc gadget soon).

**Comment by valentindavid** [comment]
I have added an explanation that we need to switch the classic gadget snap when available.

**Review by alfonsosanchezbeato — APPROVED** [review]
Thanks

**Pull request merged**
