### PR TITLE
interfaces: updates for default, browser-support, desktop, opengl, upower and stub-resolv.conf

### PR DESCRIPTION
**Pull request by jdstrand**
- interfaces/browser-support: add a few more udev and /sys/devices read accesses
- interfaces/opengl: add /sys/devices access for drm and udev/data for soc:gpu
- interfaces/desktop: allow access to io.snapcraft.Launcher OpenURL
- interfaces: allow use of 'nohup' by default
- interfaces/many: allow read on /run/systemd/resolve/stub-resolv.conf for 17.10
- interfaces/upower-observe: allow GetDisplayDevice

### CODE REVIEW

**Comment by mvo5** [comment]
Should we cherry-pick  7b176f99c1bae50af8cf478947b9134a7661fd29 for 2.28?

**Comment by jdstrand** [comment]
@mvo5 - AFAIC, all of this is suitable for 2.28. All small and simple policy changes that only add more access, not less.

**Comment by jdstrand** [comment]
@mvo, PR for 2.28: https://github.com/snapcore/snapd/pull/3921

**Comment by jdstrand** [comment]
Merging since https://github.com/snapcore/snapd/pull/3921 (the PR for 2.28) was merged with two +1s and it is identical to this one.

**Pull request merged**
