### PR TITLE
usersession/userd: add "apt" to the white list of URL schemes handled by xdg-open

### PR DESCRIPTION
**Pull request by oSoMoN**
Fixes: https://bugs.launchpad.net/snapd/+bug/1776873

### CODE REVIEW

**Comment by anonymouse64** [comment]
The tests are fine, except that openSUSE is having a hard time today, but nothing from this PR

**Comment by anonymouse64** [comment]
@oSoMoN we should wait for @jdstrand before merging this PR

**Comment by oSoMoN** [comment]
@jdstrand this PR is blocked waiting on your input, please comment when you get a chance. Thanks!

**Comment by bboozzoo** [comment]
The bug report also mentions a number of other schemes that frequently pop up in user problem reports. Any chance we could make the handling finer and maybe check if there's a local handler for given uri-scheme before returning an error?

From https://bugs.launchpad.net/snapd/+bug/1776873/comments/4, the following are also mentioned (on top of apt):

- steam
 - ssh
 - tg
 - magnet

**Comment by oSoMoN** [comment]
> I'm mildly worried, what is the application that is broken by allowing apt URL handler. What is the interaction with system services. Does this allow applications to install Debian packages with a single click confirmation from the user?

In Ubuntu (and other deb based distributions with a GNOME desktop environment, the apt URL handler will open gnome-software on the details page for the requested package. The user will then be able to install it, but this requires proper authentication. I think `apt:` hyperlinks are a fairly popular way of recommending users to install a given piece of software from repositories, at least on Ubuntu forums and documentation (that is until snaps completely take over). So all browser applications would benefit from this change.

**Comment by oSoMoN** [comment]
> From https://bugs.launchpad.net/snapd/+bug/1776873/comments/4, the following are also mentioned (on top of apt):

From other comments in the same bug, the following additional schemes have been mentioned (in no particular order):
 - git
 - irc
 - spotify
 - zoommtg
 - urn

**Comment by bboozzoo** [comment]
Did a quick experiment. Maybe we could do something like `xdg-mime query default x-scheme-handler/<scheme>` in userd, and if that returns a desktop file, we accept the request?

This is what I get on my system:
```
$ for scheme in http https spotify irc zoommtg urn git ssh tg magnet steam; do \
    echo "$scheme $(maybe="$(xdg-mime query default x-scheme-handler/$scheme)"; test -n "$maybe" && echo "$maybe" || echo '<none>')"; \
    done | column -t   
http     firefox.desktop
https    firefox.desktop
spotify  spotify.desktop
irc      io.github.Hexchat.desktop
zoommtg  <none>
urn      <none>
git      <none>
ssh      <none>
tg       telegramdesktop.desktop
magnet   <none>
steam    steam-native.desktop
```

**Comment by jdstrand** [comment]
> Did a quick experiment. Maybe we could do something like `xdg-mime query default x-scheme-handler/<scheme>` in userd, and if that returns a desktop file, we accept the request?

I like this idea a lot. The xdg-mime man talks about querying the desktop session, etc, which suggests the mimetypes are going to be limited to desktop things (see my PR review for more thoughts). If we can confirm this is the case, it might help us avoid maintaining the list (maybe we still want a largish candidate list though... needs discussion).

**Comment by jdstrand** [comment]
> I'm mildly worried, what is the application that is broken by allowing apt URL handler. What is the interaction with system services. Does this allow applications to install Debian packages with a single click confirmation from the user?

No. What it does is allow an application to pass something like 'apt:hello' to the handler for installing packages. The mime handlers for apt are going to be things like gnome-software, apturl, etc. These applications are written to use some service that is protected by policykit to install packages (eg, PackageKit, AptDaemon, etc; they have to have something do the install since they don't run as root). When the application is called with the url, that application opens a window that has some sort of prompt mechanism (aka, an 'Install this thing' button). Unless changed by a site administrator, default policy for the policykit-using services do not allow installing software without prompting the user (specifically an admin user, like one in the sudo group). You can prove this to yourself by calling this in your terminal (ie, not from a snap): `xdg-open apt:hello` (be aware that the policy may be set to timeout after a while, so if you do this twice quickly, the 2nd time may not prompt).

**Comment by jdstrand** [comment]
@zyga - does my answer to your question address your concerns?

**Comment by oSoMoN** [comment]
Thanks @jdstrand for the detailed analysis!

**Pull request merged**
