### PR TITLE
many: merge snap-confine into snapd

### PR DESCRIPTION
**Pull request by zyga**
This branch commences the process of merging snap-confine into snapd.

Subsequent branches will make the code more in line with snapd. This includes support for merged packaging, for spread tests and for nice layout of cmd/* commands.

### CODE REVIEW

**Comment by tyhicks** [comment]
I'd prefer that snap-confine continue to live in its own project. It sounds like this PR is meant to address technical problems (making it easier to share spread tests, for example) and my preference to keep it separate is more geared towards review processes.

The Ubuntu Security team reviews all of the changes, of any considerable complexity, to snap-confine since it is such a security sensitive piece of code. Moving snap-confine into snapd will make the security team review requirement harder to enforce since the security team doesn't have the resources to keep an eye on all of the snapd PRs. Maybe github has a technical solution for this?

**Comment by Conan-Kudo** [comment]
@tyhicks In my view, it's also an organizational nightmare. Separate repositories do not necessarily mean that the releases have to occur separately, though. When making snapd releases, snapd, snap-confine, snapd-glib, and snapd-xdg-open tarballs can be uploaded with it.

At least from my perspective as co-maintainer of the packages in Fedora, I *don't* want a merged tree because it makes things more difficult for me. If I wanted to have all the sources in one source package, I can do that easily without contorting the source tree. I believe dsc style Debian packaging also provides a similar mechanism.

As for testing frameworks, if spread cannot pull in both snap-confine and snapd at the same time, that's a failing of spread. Fixing that will require supporting some kind of coordination mechanism. Perhaps in the PR comment, indicate the snap-confine branch to be tested with the snapd PR (if not mentioned, default to master).

**Comment by zyga** [comment]
The main motivation for the change is development experience and simplicity. We're about to prototype a new feature (classic confinement) and keeping everything confined to a simple branch is far easier to experience and experiment with than to keep two branches in sync (especially since fewer people are used to building snap-confine from source).

**Comment by zyga** [comment]
@tyhicks this process can be maintained, e.g. by using labels for security reviews (I think more than just snap confine could use security reviews actually).

**Comment by Conan-Kudo** [comment]
I disagree, as the labels and such are only the outward expression of the review, that is, after the code has been examined. Mixing everything together makes the codebase a big mess. If you're making changes all over the place, it'll be less obvious by definition because now the scope of the repository is less defined.

**Comment by zyga** [comment]
@Conan-Kudo please note that many changes in snapd today also require security review. I'm proposing on making that more uniform by keeping all related changes in the same repository and to use a label for easier filtering.

**Comment by mvo5** [comment]
Fwiw, while I see that there are some benefits I'm concerned about the added complexity in e.g. the packaging. This is not a show-stopper, but I wonder if we could archive the benefits (e.g. spread tests) without going all-in with the merging of the repos?

**Comment by zyga** [comment]
I have a branch that lets us test against snap-confine master built from git. We can land that as a first step but I'm still keen on landing this and working our way towards unifying everything.

**Comment by jdstrand** [comment]
"@tyhicks this process can be maintained, e.g. by using labels for security reviews (I think more than just snap confine could use security reviews actually)."

@zyga, @tyhicks and I discussed this a bit today. My concern is that snap-confine as a separate project conveyed to developers that it was 'special' in some way (indeed, it is a setuid executable) and Tyler is right that it is easier to track changes. As Zygmunt said though, it should be possible to denote snap-confine after merging with snapd as 'special' and whatever process we do for snap-confine, we should extend to other parts of the tree (eg, interfaces/* which today is largely handled with people knowing they should ping me on IRC and/or in the PR).

I'm not familiar enough with github to suggest a technical solution for this. In my mind, automatically adding a label to a PR (eg, via a bot or otherwise) that touches snap-confine (or interfaces/*) may be enough of a cue to snappy developers to not commit without pinging the security team. Can people subscribe to labels?

+0 from me on this PR but if it goes forward, please lets define a process as @zyga suggested.

**Comment by tyhicks** [comment]
Just to be clear, my previous comment stating my preference to leave snap-confine as a separate project is only a preference and not a hard requirement from the Ubuntu security team. We do request that snap-confine PRs be labeled with a security-team label and block on our approval. I don't believe that it is possible today to automatically add a label based on which file paths are touched by a PR but can this be done by a bot in the near term?

Security team +0 if you use manual PR labeling (as this process may eventually fail and something questionable may be merged without security review) and +1 if you are able to do automatic PR labeling so that we can filter on it.

**Comment by niemeyer** [comment]
This looks almost there. I suggest fixing at least the following things before we merge:

* Remove VERSION file from /, and use the version from snapd itself for snap-confine.
* Remove configure.ac and Makefile.am from the root directory and teach debian/rules to look there.
* Remove docs/* and copy files to the wiki as-is instead. We can make them look nicer (if necessary) and integrate in the documentation index later, but let's just move for now.

Then, after merging we need to fix the following:

* Gradually move spread tests into /tests, and fix the convention to match the existing ones while we do that.

**Comment by niemeyer** [comment]
@tyhicks @jdstrand It seems unnecessary to add a label to every single PR that touches snap-confine. A relevant portion of the code in snapd is just as sensitive, and we haven't been doing that. Even when we touch interfaces, not every single review go through (or needs to go through) the security team.

My proposal, instead, is that we keep doing what we've been doing: when we touch areas of the code where we benefit from expertise from particular parties, we should invite them to have a look. We have good evidence that we've been doing that effectively, as @jdstrand will probably agree, being regularly invited to provide a final review on sensitive interface code that would benefit from his input (highly appreciated, in fact).

**Comment by niemeyer** [comment]
@Conan-Kudo We understand the packaging will be a bit more troublesome, but this is an important step to ensure these projects are updated in lock-step. In fact, it's precisely the cross-distribution scene that makes this most relevant. Today it's too easy for these projects to be updated in isolation without realizing that they are very tightly dependent on each other. We will fix that by distributing and versioning them together.

**Comment by Conan-Kudo** [comment]
@niemeyer That's all well and good if there isn't going to be more snappy contributors, but if snappy is successful and it grows, it's going to be a lot harder to keep that model working.

The separate repositories makes it easier for people to compartmentalize the kinds of changes that need to happen, and given that they're not even written in the same language or have the same scope, it doesn't make a lot of sense for them to be in one repository.

And snapd is only becoming more and more complicated, and snap-confine will grow with it. Fundamentally, it just makes it harder to figure out what the heck is going on.

**Comment by niemeyer** [comment]
@Conan-Kudo The code is not any less or more complex because it sits in a separate repository or in a separate directory of the same repository. It's exactly the same code in either place, and people that are interested to contribute can do so whether they live in one place or the other. It's also unfortunately not the case that snap-confine can be freely hacked on without realizing how snapd uses it, as history clearly shows. The truth is that snap-confine is an implementation detail of snapd, not a project on its own.

**Comment by chipaca** [comment]
I think @Conan-Kudo is right in that if we have a large number of contributors this will hinder us. But we're not there yet, and we can easily (and happily) revert this change in a year from now or ten.

**Comment by chipaca** [comment]
happening

**Pull request merged**
