### PR TITLE
packaging: make sure debhelper-generated snippet is invoked on postrm

### PR DESCRIPTION
**Pull request by stolowski**
Make sure debhelper-generated snippet is invoked on postrm to remove symlinks for systemd units on apt-get purge (fixes https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1622045)

### CODE REVIEW

**Comment by zyga** [comment]
Looks good to me

**Comment by mbiebl** [comment]
If you are adding ```#DEBHELPER#```, there should be no need to clean up the symlinks manually, as dh-systemd will generate cleanup code automatically.
So you should either do it manually or via the autogenerated code, but not both.

**Comment by stolowski** [comment]
@mbiebl Thanks for looking at it, you're right indeed! I did #DEBHELPER# first but concluded it didn't work due to a mistake and some confusion around how debian packaging handles all this... Anyway, yes, just #DEBHELPER# works on the symlinks are removed on apt-get purge.

**Comment by zyga** [comment]
Interesting, I've learned something about systemd packaging today

**Comment by mvo5** [comment]
Yay, thank you @stolowski

**Pull request merged**
