### PR TITLE
many: add altlinux support

### PR DESCRIPTION
**Pull request by shaba**

### CODE REVIEW

**Review by mvo5 — APPROVED** [review]
Thank you, this looks fine

**Comment by shaba** [comment]
I was add my second email to account in launchpad, please restart cla-check.

**Comment by mardy** [comment]
> I was add my second email to account in launchpad, please restart cla-check.

Hi Alexey, I restarted the check but it is still failing.

**Comment by shaba** [comment]
Sorry, i am sign the contributor agreement now.

**Review by zyga — APPROVED** [review]
Looks all-right.

**Comment by mvo5** [comment]
Thank for your contribution! I manually checked our internal database and the CLA check is clean. I will chase why the automatic one is not working.

**Review by bboozzoo — APPROVED** [review]
LGTM, thanks!

**Comment by mvo5** [comment]
One thing that might have tripped up the CLA check is that the commti is authored by the (at)altlinux email and the CLA is signed with (at)gmail.com :/

**Review by bboozzoo — APPROVED** [review]
Thank you

**Comment by bboozzoo** [comment]
@shaba would it be possible for you to reset the author to your email @gmail.com (the one that the CLA was signed with) and force push the branch again?

**Comment by shaba** [comment]
> @shaba would it be possible for you to reset the author to your email @gmail.com (the one that the CLA was signed with) and force push the branch again?

Done.

**Pull request merged**
