### PR TITLE
spread, tests: add Fedora 37, drop Fedora 35

### PR DESCRIPTION
**Pull request by bboozzoo**
Fedora 35 is EOL since 2022-12-13. Fedora 37 is the latest release.

IDK if I'll have much time to work on this, so feel free to pick up the PR.

### CODE REVIEW

**Comment by sergiocazzolato** [comment]
Added Fedora 37 image and tests retriggered

**Comment by sergiocazzolato** [comment]
I see this error in the microk8s test: 

Jan 02 13:06:49 jan021226-437154 snapd[125971]: + snapctl is-connected k8s-kubelet
Jan 02 13:06:49 jan021226-437154 snapd[125971]: + snapctl restart microk8s.daemon-containerd
Jan 02 13:06:49 jan021226-437154 snapd[125971]: error: error running snapctl: cannot perform the following tasks:
Jan 02 13:06:49 jan021226-437154 snapd[125971]: - Run service command "restart" for services ["daemon-containerd"] of snap "microk8s" (systemctl command [start snap.microk8s.daemon-containerd.service] failed with exit status 1: Job for snap.microk8s.daemon-containerd.service failed because the control process exited with error code.
Jan 02 13:06:49 jan021226-437154 snapd[125971]: See "systemctl status snap.microk8s.daemon-containerd.service" and "journalctl -xeu snap.microk8s.daemon-containerd.service" for details.
Jan 02 13:06:49 jan021226-437154 snapd[125971]: )

**Review by sergiocazzolato — APPROVED** [review]
Thanks for the change. I already added the new fedora 37 gce image.
I see an error in microk8s test in the logs, the rest seems to be ok

**Comment by mvo5** [comment]
Thanks @sergiocazzolato ! Looks like only microk8s is unhappy so we should probably disable that for now and I can ask the k8s team in our next meeting if they can have a look

**Comment by mvo5** [comment]
> Thanks @sergiocazzolato ! Looks like only microk8s is unhappy so we should probably disable that for now and I can ask the k8s team in our next meeting if they can have a look

I updated the PR now to skip microk8s-smoke on fedora-37 until the issue is understood.

**Pull request merged**
