### PR TITLE
tests: fix interfaces-libvirt test

### PR DESCRIPTION
**Pull request by sergiocazzolato**
The test is failing after it has been moved to focal, the change
includes:
 . Add new dependency for focal
 . Use the new group libvirt instead of the old one libvirtd

### CODE REVIEW

**Comment by sergiocazzolato** [comment]
The test still fails on focal:
This is the error
+ su -l -c test-snapd-libvirt-consumer.machine-up test
error: Failed to create domain from /snap/test-snapd-libvirt-consumer/current/vm/ping-unikernel.xml
error: internal error: child reported (status=125): unable to open /snap/test-snapd-libvirt-consumer/current/tests/test_ping_serve/test_ping_serve.virtio: Read-only file system

this is what I see in dmesg: 
[  992.268513] audit: type=1400 audit(1630519106.665:71): apparmor="DENIED" operation="open" profile="snap.test-snapd-libvirt-consumer.machine-up" name="/proc/24877/net/psched" pid=24877 comm="virsh" requested_mask="r" denied_mask="r" fsuid=12345 ouid=0
[  992.270891] audit: type=1400 audit(1630519106.669:72): apparmor="DENIED" operation="ptrace" profile="libvirtd" pid=24523 comm="libvirtd" requested_mask="read" denied_mask="read" peer="snap.test-snapd-libvirt-consumer.machine-up"

**Comment by anonymouse64** [comment]
This needs to be rebased on master now that @mvo5 landed https://github.com/snapcore/snapd/pull/10714

**Review by mvo5 — APPROVED** [review]
Thank for fixing this

**Review by mardy — APPROVED** [review]
LGTM!

**Comment by bboozzoo** [comment]
Needs a merge from master or a rebase now. The latest spread run executed the test on 16.04 apparently.

**Comment by bboozzoo** [comment]
The test is still failing. Maybe the actual test snap needs an update?

```
 2021-09-02 13:39:20 Restoring google:ubuntu-20.04-64:tests/main/system-usernames-illegal (sep021257-456831)...
Error: 2021-09-02 13:39:21 Error executing google:ubuntu-20.04-64:tests/main/interfaces-libvirt (sep021257-456887) : 
-----
+ echo 'The interface is not connected by default'
The interface is not connected by default
+ MATCH '^- +test-snapd-libvirt-consumer:libvirt'
+ snap interfaces -i libvirt

'snap interfaces' is deprecated; use 'snap connections'.
+ echo 'When the plug is connected'
When the plug is connected
+ snap connect test-snapd-libvirt-consumer:libvirt
+ echo 'Then the snap is able to create the unikernel domain'
Then the snap is able to create the unikernel domain
+ su -l -c test-snapd-libvirt-consumer.machine-up test
error: Failed to create domain from /snap/test-snapd-libvirt-consumer/current/vm/ping-unikernel.xml
error: internal error: child reported (status=125): unable to open /snap/test-snapd-libvirt-consumer/current/tests/test_ping_serve/test_ping_serve.virtio: Read-only file system
-----
```

**Review by bboozzoo — APPROVED** [review]
LGTM

**Pull request merged**
