### PR TITLE
many: drop fontconfig cache generation

### PR DESCRIPTION
**Pull request by valentindavid**
fontconfig cache generation is not needed, and the fc-cache binaries we are providing are only for old version of the cache which less and less likely to be used.

This is needed for #13370

### CODE REVIEW

**Review by xnox — APPROVED** [review]
Approved with prejudice

**Review by Meulengracht — APPROVED** [review]
Thanks, but please update the PR with a description

**Review by bboozzoo — APPROVED** [review]
Thanks

**Comment by bboozzoo** [comment]
BTW. there are some tweaks in the selinux profile which can be dropped now or in a followup

**Pull request merged**
