### PR TITLE
interfaces/appstream-metadata: Re-create app-info links to swcatalog

### PR DESCRIPTION
**Pull request by robert-ancell**
Builds on https://github.com/snapcore/snapd/pull/11592

### CODE REVIEW

**Review by mardy — APPROVED** [review]
LGTM!

**Review by bboozzoo — APPROVED** [review]
LGTM

**Comment by bboozzoo** [comment]
@robert-ancell hope you don't mind, but I merged latest master, fixed the conflicts and pushed to your branch. Please take a look at the changes.

**Comment by robert-ancell** [comment]
@bboozzoo thanks, changes look good to me.

The unit-tests are failing, but seems to be unrelated to this change:
```
xargs: misspell: No such file or directory
```

**Pull request merged**
