### PR TITLE
sandbox,quota: ensure cgroup is available when creating mem quotas

### PR DESCRIPTION
**Pull request by mvo5**
This commit ensures that quotas can only be created/updated if
the memory cgroup is available. Without having the memory cgroup
the snapd memory quota system will not work.

### CODE REVIEW

**Comment by mvo5** [comment]
Followup for https://github.com/snapcore/snapd/pull/11577 to do the same for memory quotas.

**Review by MiguelPires — APPROVED** [review]
LGTM

**Review by mardy — APPROVED** [review]
LGTM!

**Review by bboozzoo — APPROVED** [review]
LGTM

**Pull request merged**
