### PR TITLE
cmd: use libtool for the internal library

### PR DESCRIPTION
**Pull request by morphis**
This just cuts some hassle integration with how the helper library is
built. I could never get to pass the right -fPIC/-fpie combination
otherwise.

Signed-off-by: Zygmunt Krynicki <me@zygoon.pl>

### CODE REVIEW

**Comment by mvo5** [comment]
The test error in here look real though.

**Comment by morphis** [comment]
@mvo5 in spread I only see
```
2017-04-11 05:40:06 Discarding linode:ubuntu-16.04-32 (Spread-06), cannot connect: cannot connect to linode:ubuntu-16.04-32 (Spread-06): ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain
```

**Comment by morphis** [comment]
Ok, the autopkgtest's highlight the problem:

```
/usr/lib/snapd/snap-confine: error while loading shared libraries: libcap.so.2: cannot open shared object file: No such file or directory
```

Looking into that now.

**Comment by morphis** [comment]
Closing again as this is not going to work out as it should in a sane way for all platforms. Need to find a proper way how to deal with this problem.

**Pull request closed without merging**
