### PR TITLE
i/b/bool-file: Allow configuring trigger, delay_on and delay_off fiel…

### PR DESCRIPTION
**Pull request by bugraaydogar**
The led driver available as part of the linux-kernel defines the concept of `trigger`. The configuration is possible via sysfs. For more infromation about the use case, you can refer to
https://docs.kernel.org/leds/leds-class.html

This PR aims to provide access to the `trigger, delay_on and delay_off` leads of led driver's sysfs interface.

### CODE REVIEW

**Comment by bugraaydogar** [comment]
Hi @alexmurray,

Could you please expedite the review of this PR? Thank you.

**Review by alexmurray — COMMENTED** [review]
Does `boolFileLedPattern` also need to be added to `boolFileAllowedPathPatterns`?

**Comment by bugraaydogar** [comment]
Nope, the `boolFileAllowedPathPatterns` implicity has it via `/sys/class/leds` definition and essentially, the `/sys/class/` is just a symlik to the actual device interfaces.  There is a logic inside the interface that dereferences symbolic links and adds them to the AppArmor profiles.

**Review by alexmurray — APPROVED** [review]
Ah thank you for explaining that @bugraaydogar - LGTM!

**Review by mvo5 — COMMENTED** [review]
Thanks, this looks fine, it would be nice to have a small unit test addition though (but if you are too busy I can look at this myself or ask someone from the team).

**Review by mvo5 — APPROVED** [review]
Very nice, thank you!

**Pull request merged**
