### PR TITLE
overlord: properly mock usr-lib-snapd tests to mimic an Ubuntu Core system

### PR DESCRIPTION
**Pull request by bboozzoo**
Add mocking that makes the host look like an Ubuntu Core system.

### CODE REVIEW

**Review by mvo5 — APPROVED** [review]
Nice catch!

**Review by stolowski — APPROVED** [review]
LGTM, thanks for investigating this.

**Review by anonymouse64 — APPROVED** [review]
nice catch, thanks for figuring this out

**Comment by bboozzoo** [comment]
@mvo5 can we land this?

**Pull request merged**
