### PR TITLE
tests: add nested test variant that adds 4k sector size

### PR DESCRIPTION
**Pull request by mvo5**
This test would have caught
https://bugs.launchpad.net/snappy/+bug/1968356 where UC22 does
not install on devices that have 4k physical sector sizes.

The downside of course is that it makes the nested tests slower.
Alternatively we could simply unconditionally set all basic tests
to 4k and rely on the other tests to catch possible regressions
with physical sector size of 512 (which is the default).

### CODE REVIEW

**Review by bboozzoo — APPROVED** [review]
LGTM

**Review by sergiocazzolato — CHANGES_REQUESTED** [review]
The image in nested/core is created when the suite is prepared, to test a new variant with a different image we need to locate the test in nested/manual and call the following tool while the test is prepared
 tests.nested build-image core
 tests.nested create-vm core

**Comment by sergiocazzolato** [comment]
I see this error in the log running in uc22

[   29.135179] snapd[1095]: -----
Jun 10 12:47:28 ubuntu snapd[1095]: 2022/06/10 12:47:28.015044 install.go:145: encrypted filesystem device /dev/mapper/ubuntu-save
Jun 10 12:47:28 ubuntu snapd[1095]: 2022/06/10 12:47:28.015462 content.go:50: DEBUG: create ext4 filesystem on /dev/mapper/ubuntu-save with label "ubuntu-save"
Jun 10 12:47:28 ubuntu snapd[1095]: 2022/06/10 12:47:28.022268 task.go:343: DEBUG: 2022-06-10T12:47:28Z ERROR cannot install system: cannot make filesystem for partition system-save:
Jun 10 12:47:28 ubuntu snapd[1095]: -----
Jun 10 12:47:28 ubuntu snapd[1095]: mke2fs 1.46.5 (30-Dec-2021)
Jun 10 12:47:28 ubuntu snapd[1095]: mkfs.ext4: Invalid argument while setting blocksize; too small for device
Jun 10 12:47:28 ubuntu snapd[1095]: -----
Jun 10 12:47:28 ubuntu snapd[1095]: 2022/06/10 12:47:28.022308 taskrunner.go:271: [change 2 "Setup system for run mode" task] failed: cannot install system: cannot make filesystem for partition system-save:
Jun 10 12:47:28 ubuntu snapd[1095]: -----
Jun 10 12:47:28 ubuntu snapd[1095]: mke2fs 1.46.5 (30-Dec-2021)
Jun 10 12:47:28 ubuntu snapd[1095]: mkfs.ext4: Invalid argument while setting blocksize; too small for device
Jun 10 12:47:28 ubuntu snapd[1095]: -----

**Comment by mvo5** [comment]
> @mvo5 I see this error in the log running in uc22
> 
> [ 29.135179] snapd[1095]: ----- Jun 10 12:47:28 ubuntu snapd[1095]: 2022/06/10 12:47:28.015044 install.go:145: encrypted filesystem device /dev/mapper/ubuntu-save Jun 10 12:47:28 ubuntu snapd[1095]: 2022/06/10 12:47:28.015462 content.go:50: DEBUG: create ext4 filesystem on /dev/mapper/ubuntu-save with label "ubuntu-save" Jun 10 12:47:28 ubuntu snapd[1095]: 2022/06/10 12:47:28.022268 task.go:343: DEBUG: 2022-06-10T12:47:28Z ERROR cannot install system: cannot make filesystem for partition system-save: Jun 10 12:47:28 ubuntu snapd[1095]: ----- Jun 10 12:47:28 ubuntu snapd[1095]: mke2fs 1.46.5 (30-Dec-2021) Jun 10 12:47:28 ubuntu snapd[1095]: mkfs.ext4: Invalid argument while setting blocksize; too small for device Jun 10 12:47:28 ubuntu snapd[1095]: ----- Jun 10 12:47:28 ubuntu snapd[1095]: 2022/06/10 12:47:28.022308 taskrunner.go:271: [change 2 "Setup system for run mode" task] failed: cannot install system: cannot make filesystem for partition system-save: Jun 10 12:47:28 ubuntu snapd[1095]: ----- Jun 10 12:47:28 ubuntu snapd[1095]: mke2fs 1.46.5 (30-Dec-2021) Jun 10 12:47:28 ubuntu snapd[1095]: mkfs.ext4: Invalid argument while setting blocksize; too small for device Jun 10 12:47:28 ubuntu snapd[1095]: -----

Thanks! That's expected because https://github.com/snapcore/snapd/pull/11857 was not merged yet. I mergd it now and pushed master to this PR so hopefully this error goes away :)

**Comment by mvo5** [comment]
Fwiw, the changes from Sergio look great! :+1:

**Review by sergiocazzolato — APPROVED** [review]

**Pull request merged**
