### PR TITLE
snap: add additional checks for snap run symlinks

### PR DESCRIPTION
**Pull request by mvo5**
When a symlink like `~/hello-world.env -> /usr/bin/snap` is created and then `~/hello-world.env` is run, this will behave exactly the same as if it was run from /snap/bin/hello-world.env. As jdstrand pointed out this behaviour might be confusing so this branch changes it and will error for appname like symlinks that do not come from /snap/bin/.

### CODE REVIEW

**Comment by zyga** [comment]
Looks good, +1

**Comment by chipaca** [comment]
test failures seem zomg real

**Comment by niemeyer** [comment]
Needs love.

**Comment by mvo5** [comment]
Closing for now as this needs further investigation. The shell will set os.Argv[0] to to just the command name, not the full path, i.e.:
```
# strace -e trace=execve -f home-consumer.reader
execve("/snap/bin/home-consumer.reader", ["home-consumer.reader"], [/* 44 vars */]) = 0
```
When this reaches `/usr/bin/snap` all that sees in os.Argv[0] is the `home-consumer.reader` and not the full path.

**Pull request closed without merging**
