### PR TITLE
cmd/snap,cmd/snap-exec: support running hooks via snap-exec.

### PR DESCRIPTION
**Pull request by kyrofa**
This PR makes progress on LP: [#1586465](https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1586465) by updating snap-exec to allow running hooks, and updating `snap run` to utilize that functionality.

### CODE REVIEW

**Comment by mvo5** [comment]
From a first quick look its fine, we may want to land https://github.com/snapcore/snapd/pull/1489 first though (there will be conflicts).

**Comment by kyrofa** [comment]
> we may want to land #1489 first though (there will be conflicts).

Fine by me.

**Comment by kyrofa** [comment]
retest this please.

**Comment by mvo5** [comment]
:+1:

**Comment by mvo5** [comment]
#1542 had a :+1: from @zyga as well, so once the tests are green this can go in I think

**Pull request merged**
