### PR TITLE
interfaces: allow use of mksquashfs and unsquashfs from snap contexts

### PR DESCRIPTION
**Pull request by bugraaydogar**
Ubuntu Core ships `mksquashfs` and `unsquashfs` utilities as part of the rootfs. Some developers/customers reported that they are not able to leverage existing `squashfs-tools` as part of rootfs but need to stage-package `squashfs-tools` as part of their snap. This PR provides access to `squashfs-tools` from any snap context.

### CODE REVIEW

**Comment by bugraaydogar** [comment]
@alexmurray depending on the project and purpose of the device, customer hardware might have a very limited capacity. Therefore, they would like to save as much as possible and use what is already available as part of the system.

**Comment by alexmurray** [comment]
Thanks @bugraaydogar  - so if we take this reasoning to its logical conclusion, then I wonder if we should try and make sure the base declaration includes all (non-privileged) binaries that are shipped in the core base snaps?

**Comment by bugraaydogar** [comment]
Ideally yes. It is quite important for the customers who have limited disk capacity. We could add this to the backlog of the Core team.

**Comment by mvo5** [comment]
@bugraaydogar Hey, I wonder a bit about the use-case for this, is this snap related or is mksquashfs/unsquashfs used for something unrelated to snaps? Mostly asking because we will make snaps richer than squashfs with the dm-verity additions so this tooling will not be enough very soon.

**Comment by pedronis** [comment]
We want the option to remove things that are/become niche or get removed by Ubuntu itself as bases evolve from series to series and also as we try to keep size of bases partially under control. OTOH anything that was exposed and then gets removed  is a possible friction point for people using it when they upgrade their snap from a old base to new one, which is also something that we want to happen regularly. So it means we should be cautious when adding access to binaries to the template. We already have a few binaries listed in the template that are not present in newer bases since core. Anyway in this particular case I'm -0 on this, I will leave further decisions on this to @mvo5.

**Comment by bugraaydogar** [comment]
Hi @mvo5, 
It is a snap related and very specific use case. Some of our customers deploy their devices in offline environment and handles the update or installation of the new snaps themselves by using snapd-rest-api. The core problem is that; it is not possible to expand the snap metadata with additional information. Therefore, one specific customer deployed a metadata as part of the snap and use unsquash command to fetch it from the snap before the installation.

**Review by alexmurray — APPROVED** [review]
LGTM - @mvo5 re your comment:

> we will make snaps richer than squashfs with the dm-verity additions so this tooling will not be enough very soon.

In that case, we should then ensure that the required tooling to similarly unpack a snap is available when that change is introduced.

**Comment by mvo5** [comment]
> LGTM - @mvo5 re your comment:
> 
> > we will make snaps richer than squashfs with the dm-verity additions so this tooling will not be enough very soon.
> 
> In that case, we should then ensure that the required tooling to similarly unpack a snap is available when that change is introduced.

I am not sure we would do that for all bases, we ship a version of "unsquashfs" and "mksquashfs" in snapd so we don't really need it in the bases. Also the fact that a snap is a squashfs is just an implementation detail. 

Maybe instead there could be a (hidden) `snap unpack --src xxx --dst yyy` that is just a tiny wrapper around our snap.Container interface? That seems much more supportable to me and it would guaranteed not break as we already use this codepath to extract data from the snaps with this container interface (cc @pedronis ).

**Comment by mvo5** [comment]
I had a discussion about this again and I still am not convinved about this, the direction should that we use less from the bases. E.g. the mksquashfs tooling is part of the snapd snap since a while and snapd will use it by default so there is really no need to have it in the bases anymore afaict.

**Comment by bugraaydogar** [comment]
@pedronis @ernestl  could you please share your final conclusion on this topic?

**Comment by pedronis** [comment]
> @pedronis @ernestl could you please share your final conclusion on this topic?

given that the direction we are going is to try to make coreXX smaller and that snapd ships with its own of these, I would say we do not want to go forward with this

**Comment by mapero** [comment]
> Maybe instead there could be a (hidden) `snap unpack --src xxx --dst yyy` that is just a tiny wrapper around our snap.Container interface? That seems much more supportable to me and it would guaranteed not break as we already use this codepath to extract data from the snaps with this container interface.

@mvo5 Just want to pick this up again, not sure if you have discussed/considered it as an alternative. This would fulfill our requirements (if it is callable by the rest api and/or snapctl). Additionally it would not require us to use unsquashfs and implement a solution based on an implementation details.

**Comment by pedronis** [comment]
(mvo5 is not working on snapd anymore).

mvo5 proposal was for `snap`, not `snapctl` or the API. Is not a natural operation of snaps to look into/unpack snaps. We could add it to `snap` as mentioned, but then `snap` is not easily available, but we could consider making it accessible under snapd-control or some other interface.

@mapero can you remind me though why the need/use case to unpack snaps on the device?  maybe there is a solution that makes sense in the API

**Pull request closed without merging**
