### PR TITLE
interfaces/builtin: add google titan v2 to u2f-devices interface

### PR DESCRIPTION
**Pull request by sbachstein**
Add the new Google Titan v2 security key

```Bus 005 Device 006: ID 18d1:9470 Google Inc. Titan Security Key v2```

### CODE REVIEW

**Comment by alexmurray** [comment]
Is there any publicly available documentation which references this new ProductID?

**Comment by sbachstein** [comment]
> Is there any publicly available documentation which references this new ProductID?

I couldn't find any, unfortunately.

**Comment by alexmurray** [comment]
Ideally we would have some way to verify this is the correct ProductID but given we now also have a duplicate PR in https://github.com/snapcore/snapd/pull/13413 from a separate contributor, that feels reasonable to independently confirm that this is correct. +1 from me.

**Review by Meulengracht — APPROVED** [review]

**Comment by Meulengracht** [comment]
@sbachstein You must sign the CLA, https://www.ubuntu.com/legal/contributors

**Comment by sbachstein** [comment]
> @sbachstein You must sign the CLA, https://www.ubuntu.com/legal/contributors

Done!

**Comment by Meulengracht** [comment]
Did you sign with the email belonging to your github account (according to this mail@sbachstein.de)

**Review by ernestl — APPROVED** [review]
Thanks

**Comment by ernestl** [comment]
The CLA check passed, and the change is trivial. Force merging.

**Pull request merged**
