### PR TITLE
cmd/snap-confine: apply global mount namespace initialization for confined and classic snaps

### PR DESCRIPTION
**Pull request by bboozzoo**
Extracted from #7302 

With parallel instances of classic snaps, the basic initialization of mount namespace (creating /run/snapd/ns, switching it to private propagation) can now happen globally for confined and classic snaps.

### CODE REVIEW

**Comment by zyga** [comment]
@mvo5 there is no regression potential. There is no actual change to classic snaps per se, just to the initialisation path that prepares `/run/snapd/ns` for classic snaps, just like we do for non-classic snaps. The initialisation always happens in the initial mount namespace so a classic snap can already observe this if other snaps are present on the system.

**Comment by bboozzoo** [comment]
@mvo5 chatted with @zyga bit more, given that the user can do pretty much anything, the change can cause regression. I guess, the question now is how far does the promise of being like it's a local program extends for local snaps?

To avoid the regression, we'd need drop this change and backtrack a bit in #7302 and do /var/snap and $SNAP_MOUNT_DIR bind mounts only in the code path for parallel instance of a classic snap.

**Comment by jdstrand** [comment]
> While this is an observable difference it was never something we explicitly supported (and all non-classic snaps behaved this way already). I think it is in line with the semantics of classic snaps.

Note that some applications are (obviously) going to call unshare. It is known that container managers and browsers (eg, chromium based) will do this. OTOH, I'm not aware of what classic snaps are using unshare, but they can do anything, so there is a potential for regression here (as @bboozzoo said).

I appreciate @zyga's point that we should unconditionally do this because if we don't, then a classic snap and a parallel installed classic snap will be operating under a slightly different environment. Not applying this PR and limiting to parallel installs means that the applications that would've broken due to this PR would still break as parallel installed classic snaps, which is undesirable.

IME, we should apply this PR, but only when we have SC_FEATURE_PARALLEL_INSTANCES. In this manner, classic snap publishers can enable the feature and test their existing classic snap and parallel classic snap. This way we only introduce the change when we are confident things won't break or, if there is regression, we can then limit this to only parallel installed classic snaps and document the limitation.

**Comment by pedronis** [comment]
I agree with @jdstrand reasoning around the change vs the flag for now

**Comment by bboozzoo** [comment]
> IME, we should apply this PR, but only when we have SC_FEATURE_PARALLEL_INSTANCES. In this manner, classic snap publishers can enable the feature and test their existing classic snap and parallel classic snap. This way we only introduce the change when we are confident things won't break or, if there is regression, we can then limit this to only parallel installed classic snaps and document this as a limitation of the feature.

Do you mean to have s-c joining of pid 1 mount ns driven by parallel-instances feature flag too?

**Comment by jdstrand** [comment]
> > IME, we should apply this PR, but only when we have SC_FEATURE_PARALLEL_INSTANCES. In this manner, classic snap publishers can enable the feature and test their existing classic snap and parallel classic snap. This way we only introduce the change when we are confident things won't break or, if there is regression, we can then limit this to only parallel installed classic snaps and document this as a limitation of the feature.
> 
> Do you mean to have s-c joining of pid 1 mount ns driven by parallel-instances feature flag too?

Yes. Ie, without the parallel-instances feature flag there is no change in classic snap behavior. This allows us and the community (eg, via a call for testing) to test their classic snaps with the flag enabled and see if their non-parallel installed classic snap still operates ok. It's simply a way to minimize regressions and maximize testing before going live with joining of pid 1

> > IME, we should apply this PR, but only when we have SC_FEATURE_PARALLEL_INSTANCES. In this manner, classic snap publishers can enable the feature and test their existing classic snap and parallel classic snap. This way we only introduce the change when we are confident things won't break or, if there is regression, we can then limit this to only parallel installed classic snaps and document this as a limitation of the feature.
> 
> Do you mean to have s-c joining of pid 1 mount ns driven by parallel-instances feature flag too?

Yes, though I was speaking to the fact that we're reassociating, running sc_ensure_shared_snap_mount() and running parts of sc_initialize_mount_ns(), not just reassociating like your question seems to imply.

The idea is that we don't change the behavior of classic snaps by default at all with this PR, only when parallel-instances feature flag is present. In this manner, we can be confident in not regressing and can perform a call for testing for classic snap publishers to test their classic snap with the feature flag present for a normal, non-parallel installs to get a baseline on the chance for regression when it is enabled by default.

**Comment by bboozzoo** [comment]
I should probably roll this back into #7302

**Pull request closed without merging**
