### PR TITLE
packaging: add missing dependencies, disable centos-9

### PR DESCRIPTION
**Pull request by zyga**
We need to be able to iterate and at present master is broken, requiring a force-merge that only few people can use. Let's agressively fix master so that we can iterate and make things better bit-by-bit.

### CODE REVIEW

**Review by bboozzoo — APPROVED** [review]

**Review by MiguelPires — COMMENTED** [review]
I'm confused, how is centos-9 preventing merging PRs if it's not a required suite?

**Comment by zyga** [comment]
@MiguelPires it wasn't - I didn't realize it was optional when I made the PR.

The real fix is debian

**Review by andrewphelpsj — APPROVED** [review]
Thanks!

**Review by MiguelPires — APPROVED** [review]
Ok then should we remove that part from this PR? I'm approving anyway to not block the rest

**Comment by zyga** [comment]
@andrewphelpsj @MiguelPires I'll revert the centos PR in a follow-up.

Thanks for looking!

**Pull request merged**
