### PR TITLE
Add "jetbrains" to the whitelist of URL schemes handled by xdg-open

### PR DESCRIPTION
**Pull request by kamildoleglo**
I based this PR on https://github.com/snapcore/snapd/pull/8254 to add Jetbrains Toolbox support

### CODE REVIEW

**Comment by kamildoleglo** [comment]
Hi! Is there anything I can help you with in merging this PR? @pedronis

**Review by alexmurray — COMMENTED** [review]
I was under the impression that with https://github.com/snapcore/snapd/pull/11200 in place we would not necessarily need additional hard-coded URI schemes. Is this new proposed change definitely needed?

**Comment by alexmurray** [comment]
@kamildoleglo can you comment on my query above?

**Comment by kamildoleglo** [comment]
Oh, sorry, missed the message. I think so too, but we had one person with issues. I'll try to check if they used some old Snapd version. In the meantime we can probably close this PR

**Pull request closed without merging**
