### PR TITLE
daemon: allow snaps to get snap metadata

### PR DESCRIPTION
**Pull request by robert-ancell**
This is needed for snapd-desktop-integration to show appropriate information (icon, title, publisher etc) on UI elements. Depends on https://github.com/snapcore/snapd/pull/13120

I would expect the snap-find interface to be easily accessible for many snaps, as this information can be accessed easily by contacting the store directly. The snap-snaps interface needs a bit more care, as this allows your system to be scanned for what snaps are installed.

### CODE REVIEW

**Comment by robert-ancell** [comment]
I named the interfaces snap-snaps and snap-find to match the API endpoints. I don't think these are great names, open to suggestions on what they should be.

**Review by jhenstridge — COMMENTED** [review]
I think this is going to be a tough sell in its current form. A few initial points:

1. So far, the mini-APIs we've exposed to snaps have been their own thing over in the `/v1/accessories` tree. These are existing core APIs, so needs a conscious decision to be made about whether this is the right direction.
2. Does it make sense to control access to these APIs behind different interfaces?
3. We've got a pattern in naming interfaces `*-observe` for effectively read-only access, and `*-control` for write access. Would it make sense to extend that to the naming of these interfaces?

**Comment by robert-ancell** [comment]
Discussed with @jhenstridge alternative ways of doing this. We think that making this part of the prompting interface makes sense, and other cases that want to access the same APIs can use different interfaces for that. This will be proposed as part of the prompting PRs.

**Comment by robert-ancell** [comment]
FYI proposal in prompting branch - https://github.com/olivercalder/snapd/pull/18

**Pull request closed without merging**
