### PR TITLE
cmd/snap,  tests/main/classic-confinement: fix snap-exec path when running under classic confinement

### PR DESCRIPTION
**Pull request by bboozzoo**
Addresses this bug: https://bugs.launchpad.net/snapd/+bug/1736939

See https://github.com/snapcore/snapd/commit/563795fd8d628c64da4019aee3f5c6a845eb0fe7 commit message for details.

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
@mvo5 I don't know if you're planning a new release from 2.30 branch, but if you are, can you cherry-pick this in?

**Comment by rcmin17** [comment]
I have both `snapd-2.30-1`  _and_ `snap-confine-2.30-1` installed, and cannot install a classically confined snap (Anbox). I would love it if anyone could offer me guidance on troubleshooting this. My end goal is to install Anbox.

Thanks!

**Comment by bboozzoo** [comment]
@rcmin17 can you open a topic on https://forum.snapcraft.io/ ?

**Comment by rcmin17** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1546896

**Pull request merged**
