### PR TITLE
Add rules for Media API to the BlueZ D-Bus policy.

### PR DESCRIPTION
**Pull request by lhartung**
This PR adds rules to the BlueZ D-Bus policy to enable access to the Media API. It is required for integration with Pulseaudio such as when connecting Bluetooth audio devices.

I have also signed the contributor agreement.

### CODE REVIEW

**Comment by mvo5** [comment]
As for the contributor agreement, what launchpad account did you use to sign the contributions agreement (or did you sign it not using LP?).

**Comment by lhartung** [comment]
I signed with my name and email but left the launchpad ID empty because I couldn't find it. The "Don't know your Launchpad ID?" link does not seem to work any longer. I had the impression that the ID is numeric, but actually, mine might just be lhartung. I can redo it if necessary. Thanks!

**Comment by lhartung** [comment]
Sorry for closing. I hit the wrong button.

**Comment by chipaca** [comment]
The "launchpad id" it asks for is actually your nickname (the thing after the `~` to which launchpad redirects when you're logged in and go to https://launchpad.net/~ ). In your case I believe it's https://launchpad.net/~lhartung -- and I don't yet see you in the apprpriate lp group (meaning admin hasn't processed your form yet, or haven't connected the dots and will need manual intervention). I'll chase it down.

**Comment by chipaca** [comment]
@mvo5 I can confirm @lhartung has signed the CLA.

**Comment by mvo5** [comment]
Adding @jdstrand as this touches security

**Pull request merged**
