### PR TITLE
Mount with x-gdu.hide option

### PR DESCRIPTION
**Pull request by azzar1**
Once https://bugzilla.gnome.org/attachment.cgi?id=364324&action=diff and https://github.com/storaged-project/udisks/pull/460/ get merged this will allow to hide snapd squashfs from gnome-disk-utility.

### CODE REVIEW

**Comment by zyga** [comment]
@azzar1 note that you have to patch some unit tests too. It should be very easy (just `go test` in the directory you changed things in). If you cannot do it soon I can do it next week.

**Comment by mvo5** [comment]
Thanks for this PR @azzar1 ! I updated the unit tests and this can go in as soon as travis is green :)

**Comment by azzar1** [comment]
Thanks @mvo5. Please note that this will not work until upstream accepts the two patches linked in the description. I've already talked with upstream last week and they agreed on the proposed solution.

**Comment by mvo5** [comment]
@azzar1 Thats fine, at least our side will be ready.

**Pull request merged**
