### PR TITLE
interfaces/apparmor: do not fail during initialization when there is no AppArmor profile for snap-confine

### PR DESCRIPTION
**Pull request by bboozzoo**
Another take at making snapd work on openSUSE Leap with NFS homes or overlayfs (see #9739 for the previous proposal).

Some distros support AppArmor in the kernel and have the necessary userspace
tools, but the snapd package (specifically the snap-confine binary) is built
without AppArmor support. In this case, the AppArmor profiles files will not be
present on the host.

Should such distro run with /home on NFS, or overlay set up for /, the apparmor
backend initialization would fail on trying to update the profile files, this
preventing snapd from operating at all. In particular, this happens on openSUSE
Leap 15.x where the snapd package is built with AppArmor support disabled.

See https://forum.snapcraft.io/t/snapd-doesnt-start-on-opensuse-leap-15-1/13710
for more details.

### CODE REVIEW

**Review by mvo5 — APPROVED** [review]
This looks reasonable to me. If for whatever reason snap-confine is not confined we should not fail hard. OTOH I wonder a bit why it is not confined ?

**Comment by bboozzoo** [comment]
> This looks reasonable to me. If for whatever reason snap-confine is not confined we should not fail hard. OTOH I wonder a bit why it is not confined ?

In case of openSUSE Leap, it was a decision to not enable appamor that probably dates back to Leap 42 (which was a release that preceded Leap 15.x) due to missing pieces in the AA kernel or userland support. Apparently even though things got updated in Leap 15, the decision was upheld for the stable releases: https://github.com/snapcore/snapd/pull/9740#pullrequestreview-543996730

**Review by stolowski — APPROVED** [review]
LGTM

**Review by alexmurray — APPROVED** [review]
LGTM as is but I wonder if this perhaps should be a bit smarter though - ie can we perhaps make snapd know whether snap-confine was compiled with apparmor support or not? Perhaps we could add a command-line option to snap-confine to allow it to be introspected (ie `snap-confine --supported`  which could then return `apparmor`, `selinux`, `seccomp` or similar) - then at startup snapd could interrogate snap-confine to find out and know for sure. In that case then we could have snapd hard-fail if snap-confine says it supports apparmor but no apparmor profile is present?

**Comment by bboozzoo** [comment]
> LGTM as is but I wonder if this perhaps should be a bit smarter though - ie can we perhaps make snapd know whether snap-confine was compiled with apparmor support or not? Perhaps we could add a command-line option to snap-confine to allow it to be introspected (ie `snap-confine --supported` which could then return `apparmor`, `selinux`, `seccomp` or similar) - then at startup snapd could interrogate snap-confine to find out and know for sure. In that case then we could have snapd hard-fail if snap-confine says it supports apparmor but no apparmor profile is present?

Yeah, it'd be nice if we had the ability to interrogate s-c at runtime to see what features it was built with. The only problem is that it will probably take a while to add it. It is not a high priority though, we've only hit this problem on openSUSE, where I already carry this patch as part of the packaging.

**Pull request merged**
