### PR TITLE
interfaces: grant access to speech-dispatcher socket (bug 1787245)

### PR DESCRIPTION
**Pull request by lissyx**

### CODE REVIEW

**Review by seb128 — APPROVED** [review]
I'm not a snapd maintainer so can't ack it but from a desktop perspective it makes sense, we want the snaps to be able to use the speech-dispatcher service

**Review by alexmurray — APPROVED** [review]
LGTM!

**Review by mvo5 — APPROVED** [review]
Code looks okay. I do wonder why only in desktop_legacy, is the modern way of speech dispatcher different?

**Comment by lissyx** [comment]
> Code looks okay. I do wonder why only in desktop_legacy, is the modern way of speech dispatcher different?

because I was told to mimic `at-spi` and this is where it was.

**Comment by seb128** [comment]
@mvo5 to which other interface should be add it?

**Comment by mvo5** [comment]
@seb128 I am not sure - if was just wondering :) Happy to start with `desktop_legacy` and if it's needed on `desktop` or `unity7` we can always add it there as well.

**Comment by lissyx** [comment]
@alexmurray @mvo5 What remaining steps would be needed to merge ?

**Comment by seb128** [comment]
> @seb128 I am not sure - if was just wondering :) Happy to start with `desktop_legacy` and if it's needed on `desktop` or `unity7` we can always add it there as well.

I checked with Ken and desktop_legacy is enough

**Review by mardy — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
