### PR TITLE
bootloader/assets/grub: adjust fwsetup menuentry label

### PR DESCRIPTION
**Pull request by xnox**
Make fwsetup menuentry label match upstream, classic, .iso installers.

Thanks for helping us make a better snapd!
Have you signed the [license agreement](https://www.ubuntu.com/legal/contributors) and read the [contribution guide](https://github.com/snapcore/snapd/blob/master/CONTRIBUTING.md)?

### CODE REVIEW

**Review by stolowski — APPROVED** [review]
LGTM

**Review by mvo5 — APPROVED** [review]

**Comment by zyga** [comment]
@xnox please adjust tests, some things measure that.

**Review by bboozzoo — APPROVED** [review]
Thanks for the fix. I've regenerated the assets and pushed a patch. The tests should be passing now.

**Comment by bboozzoo** [comment]
Hmm, more fun apparently. 
```
‽ 19779+xnox@users.noreply.github.com privacy-enabled github web edit email address
Logging into Launchpad...
🛇 19779+xnox@users.noreply.github.com has no Launchpad account
```

@xnox can you reset the author of the first commit and use the same email address as you are using on LP? (or the @canonical.com one). The github privacy emails are rejected since we landed #9301

**Comment by mvo5** [comment]
@bboozzoo we can probably also fix this ourselfs and force-push if xox is too busy?

**Comment by bboozzoo** [comment]
Hmm, this is unexpected:
```
 🛇 19779+xnox@users.noreply.github.com has no Launchpad account
✓ maciej.zenon.borzecki@canonical.com already on master
🛇 xnox@ubuntu.com                     (https://api.launchpad.net/1.0/~xnox) has NOT signed the CLA
```

**Comment by xnox** [comment]
My commits where done with email `@canonical.com`

So I'm not sure what's wrong with my lp account that it makes it look as if cla was not signed =( are Signed-Off-by lines now required too? I don't think I added that before.

**Comment by bboozzoo** [comment]
> My commits where done with email `@canonical.com`
> 
> So I'm not sure what's wrong with my lp account that it makes it look as if cla was not signed =( are Signed-Off-by lines now required too? I don't think I added that before.
> 
> Do i need to uncheck private email option in github profile?

No clue. I tried to salvage what's there and did a rebase with your email in `--author='.... @canonical.com'`, but for some weird reason the privacy email still pops up. Maybe it's worth trying to open a new branch with just those 2 commits on top? (or make it just one, just `cd bootloader/assets && go generate`).

**Comment by xnox** [comment]
> > My commits where done with email `@canonical.com`
> > So I'm not sure what's wrong with my lp account that it makes it look as if cla was not signed =( are Signed-Off-by lines now required too? I don't think I added that before.
> > Do i need to uncheck private email option in github profile?
> 
> No clue. I tried to salvage what's there and did a rebase with your email in `--author='.... @canonical.com'`, but for some weird reason the privacy email still pops up. Maybe it's worth trying to open a new branch with just those 2 commits on top? (or make it just one, just `cd bootloader/assets && go generate`).

Well, I did the rebase. I can squash the two things.

Somehow three emails are validated, instead of just two. As if there is a merge commit generated by github from me, using my privacy email, which is then checked for cla.

**Comment by bboozzoo** [comment]
Can you try disabling the privacy email then? Maybe it comes up in the merge commit.

**Comment by xnox** [comment]
```
  Branches:
  * (HEAD detached at pull/9482/merge) b7f37f240a8 Merge 42b5bfcfc2a5cf2c048958d994cb639573c83160 into 7d2642f1c3bd05066929c3d6c4dda72eba2e8e42
    master                             7d2642f1c3b Merge pull request #9480 from mvo5/snap-pack-exitcode
```

If I locally add 
```
[remote "origin"]
	url = https://github.com/snapcore/snapd.git
	fetch = +refs/heads/*:refs/remotes/origin/*
	fetch = +refs/pull/*:refs/remotes/origin/pull/*
```

I can then see that the cla check is done on the merge commit, not on the pull request HEAD.

```
commit b7f37f240a80403dd21ffbdf705de5b9d2eb5ad9 (origin/pull/9482/merge)
gpg: Signature made Tue 13 Oct 2020 09:26:34 BST
gpg:                using RSA key 4AEE18F83AFDEB23
gpg: Good signature from "GitHub (web-flow commit signing) <noreply@github.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 5DE3 E050 9C47 EA3C F04A  42D3 4AEE 18F8 3AFD EB23
Merge: 7d2642f1c3 42b5bfcfc2
Author: Dimitri John Ledkov <19779+xnox@users.noreply.github.com>
Date:   Tue Oct 13 08:26:34 2020 +0000

    Merge 42b5bfcfc2a5cf2c048958d994cb639573c83160 into 7d2642f1c3bd05066929c3d6c4dda72eba2e8e42

commit 42b5bfcfc2a5cf2c048958d994cb639573c83160 (HEAD -> fwsetup-label-fix, xnox/fwsetup-label-fix, origin/pull/9482/head)
gpg: Signature made Tue 13 Oct 2020 09:26:14 BST
gpg:                using RSA key EE240A052A231AD8925841D79B8EC849D5EF70ED
gpg: Good signature from "Dimitri John Ledkov <xnox@spi-inc.org>" [ultimate]
gpg:                 aka "Dimitri John Ledkov <xnox@debian.org>" [ultimate]
gpg:                 aka "Dimitri John Ledkov <xnox@ubuntu.com>" [ultimate]
gpg:                 aka "Dimitri John Ledkov <dimitri.ledkov@canonical.com>" [ultimate]
gpg:                 aka "Dimitri John Ledkov <dimitri.ledkov@surgut.co.uk>" [ultimate]
Author: Maciej Borzecki <maciej.zenon.borzecki@canonical.com>
```

It feels to me that we should be doing CLA check on `pull/9482/head` not on `pull/9482/merge`. As otherwise we prohibit anybody contributing who have their email set to private in the github profile.

**Comment by xnox** [comment]
Horay! managed to fix cla-check

```
* (HEAD detached at ed1622b77d6) ed1622b77d6 Fix cla check to check pull/#/head, instead of auto-generated pull/#/merge
    master                         7d2642f1c3b Merge pull request #9480 from mvo5/snap-pack-exitcode
Need to check 2 emails:
✓ dimitri.ledkov@canonical.com        already on master
✓ maciej.zenon.borzecki@canonical.com already on master
```

Note that now cla-check checkous out the tip of the branch being proposed to merge, rather than the autogenerated merge.

I bet that the autogenerated names were alllowed in the original cla-check, because of testing merge commits.

Should that be split into a separate pull request now? Also, not sure what to do about the failing spread tests =(

**Comment by xnox** [comment]
@bboozzoo @stolowski @mvo5 can this be merged? or how do I trigger tumbleweed to go green? does it even matter? since grub-recovery assets are not used on tumbleweed.

**Comment by bboozzoo** [comment]
Let's wait for the ci jobs to finish and we should merge it then.

**Comment by xnox** [comment]
@bboozzoo centos and tumbleweed are red and failing on master branch, why is merging this PR blocked on centos & tumbleweed passing, given that it is green across all others?

See the ubuntu-20.10 no longer devel merge by yourself at https://github.com/snapcore/snapd/commits/master currently third from the top.

**Comment by bboozzoo** [comment]
> @bboozzoo centos and tumbleweed are red and failing on master branch, why is merging this PR blocked on centos & tumbleweed passing, given that it is green across all others?
> 
> See the ubuntu-20.10 no longer devel merge by yourself at https://github.com/snapcore/snapd/commits/master currently third from the top.

The spread job on 18.04 failed and I've since restarted the job. As of the time I'm writing this comment, it's still running, although AFAICT it should finish soon. If it keeps failing, it's probably better if @mvo5 uses his superpowers to merge the PR anyway.

**Pull request merged**
