### PR TITLE
dirs: add "gentoo" to altDirDistros

### PR DESCRIPTION
**Pull request by zmedico**
Signed-off-by: Zac Medico <zmedico@gmail.com>

Hello! This is my first contribution, and I've signed the [contributor agreement](http://www.ubuntu.com/legal/contributors) just now.

### CODE REVIEW

**Review by zyga — COMMENTED** [review]
Would you mind altering `cmd/autogen.sh` with a representative gentoo configuration line?

**Review by bboozzoo — APPROVED** [review]
Thanks!

**Comment by bboozzoo** [comment]
I think you need to force push and use the same email address in the author field as you used when signing the CLA.

**Review by zyga — APPROVED** [review]
LGTM

**Comment by zmedico** [comment]
> I think you need to force push and use the same email address in the author field as you used when signing the CLA.

Done. Thanks!

**Comment by bboozzoo** [comment]
Thanks, just the @gmail.com address int the log now which looks ok. @mvo5 do you know if we need to poke someone to have the the CLA status is reflected in LP?

**Comment by mvo5** [comment]
@zmedico Thanks for this PR :)

@bboozzoo I will take care of the contributor agreement poking

**Comment by bboozzoo** [comment]
Can you pull master and rebase the PR on top of it? We've landed a fix for unit tests in the morning and they should be passing now.

**Comment by zmedico** [comment]
> @zmedico Can you pull master and rebase the PR on top of it? We've landed a fix for unit tests in the morning and they should be passing now.

Done. I see some more failures though.

**Pull request merged**
