### PR TITLE
cmd,snap,wrappers: systemd reload command support

### PR DESCRIPTION
**Pull request by cyberb**

### CODE REVIEW

**Comment by niemeyer** [comment]
Thanks, that looks good. Can we have some testing for it? A spread test is perhaps the best candidate, as it'll verify the implementation end-to-end.

**Comment by cyberb** [comment]
If you are asking me, I do not how to do that, do you have a similar example?

**Comment by fgimenez** [comment]
Hi @cyberb we store the spread tests here https://github.com/snapcore/snapd/tree/master/tests/main All of them are defined from an end user perspective, how could you setup the initial state of the system, what should you type on the command line to exercise the feature under test, what output or observable changes are expected and what is actually obtained. 

For your case maybe good examples are the interface tests (those beginning with `interface-`), `snap-info`, `snap connect`, etc. You could, for instance, create a transient service, change its configuration file in some controlled way, issue a reload command and check that the service was actually reloaded and the new config read, not sure if this would cover the feature added, please correct me if I'm wrong and of course feel free to define your test(s) as you find it more appropriate.

Do not hesitate to ask for more info if anything is unclear, thanks!

**Comment by cyberb** [comment]
All I really wanted is to be able to execute systemd reload snap.platform-nginx. And I had failing test in our integration test suite (https://github.com/syncloud/platform/blob/master/integration/verify.py)
Sorry I do not really have time at the moment for another integration test.

**Comment by mvo5** [comment]
@cyberb Thanks for your contribution and no worries, we will add the tests :)

**Comment by mvo5** [comment]
I added #2721 with a spread test.

**Pull request merged**
