### PR TITLE
snapcraft: update riscv snapcraft

### PR DESCRIPTION
**Pull request by xnox**
riscv64 master builds have been failing lately

https://launchpad.net/~snappy-dev-riscv64/+snap/snapd-master-riscv64/+build/2021585

i guess this is because of missing apparmor snapcraft.yaml changes.

merging master to update the riscv64 branch.

### CODE REVIEW

**Comment by xnox** [comment]
@mvo5 not sure that any tests are relevant for this branch. the snapcraft.yaml diff between old master-riscv64 and its merge-base with master, is the same as the one proposed here. What is new is the addition of the apparmor build.

**Comment by xnox** [comment]
Previous diff between master and master-riscv64:

```
$ git diff 2c7476aaf636ee034fd95383c21ae01c3c392257 origin/master-riscv64 > previous-riscv64-branch.diff
```

```diff
diff --git a/build-aux/snap/snapcraft.yaml b/build-aux/snap/snapcraft.yaml
index ac8ec3267b..b065772fa4 100644
--- a/build-aux/snap/snapcraft.yaml
+++ b/build-aux/snap/snapcraft.yaml
@@ -11,7 +11,7 @@ description: |
 adopt-info: snapd-deb
 # build-base is needed here for snapcraft to build this snap as with "modern"
 # snapcraft
-build-base: core
+build-base: core20
 grade: stable
 license: GPL-3.0
 
@@ -28,10 +28,15 @@ license: GPL-3.0
 parts:
   snapd-deb:
     plugin: nil
-    source: .
-    build-snaps: [go/1.13/stable]
+    source-type: git
+    source: https://git.launchpad.net/snapd
+    source-branch: master
+    build-snaps:
+      - on riscv64: [go/1.16/stable]
+      - else: [go/1.13/stable]
     override-pull: |
       snapcraftctl pull
+      [ -e packaging/ubuntu-20.04 ] || ln -s ubuntu-16.04 packaging/ubuntu-20.04
       # Ensure that ./debian/ packaging which we are about to use
       # matches the current `build-base` release. I.e. ubuntu-16.04
       # for build-base:core, etc.
@@ -94,7 +99,7 @@ parts:
     stage-packages:
       - libc6
       - libc-bin
-      - libgcc1
+      - libgcc-s1
     stage:
       - lib/*
       - usr/lib/*
@@ -116,7 +121,7 @@ parts:
     build-packages: [python3-apt]
     source: https://github.com/snapcore/fc-cache-static-builder.git
     override-build: |
-      ./build-from-security.py xenial
+      [ "$(uname -m)" = "riscv64" ] && cp /bin/true fc-cache-xenial || ./build-from-security.py xenial
       mkdir -p $SNAPCRAFT_PART_INSTALL/bin
       cp -a fc-cache-xenial $SNAPCRAFT_PART_INSTALL/bin/fc-cache-v6
     prime:
@@ -127,7 +132,7 @@ parts:
     build-packages: [python3-apt]
     source: https://github.com/snapcore/fc-cache-static-builder.git
     override-build: |
-      ./build-from-security.py bionic
+      [ "$(uname -m)" = "riscv64" ] && cp /bin/true fc-cache-bionic || ./build-from-security.py bionic
       mkdir -p $SNAPCRAFT_PART_INSTALL/bin
       cp -a fc-cache-bionic $SNAPCRAFT_PART_INSTALL/bin/fc-cache-v7
     prime:
```

New diff between new master and proposed master-riscv64:

```
git diff 0a2ff46f1f0137d9933247b46cb740694bdccac7 94d257a97cde42ddc3aab96ccd472afeb245dbfb > new.diff
```

```diff
diff --git a/build-aux/snap/snapcraft.yaml b/build-aux/snap/snapcraft.yaml
index e5fb355328..8caa34567e 100644
--- a/build-aux/snap/snapcraft.yaml
+++ b/build-aux/snap/snapcraft.yaml
@@ -11,7 +11,7 @@ description: |
 adopt-info: snapd-deb
 # build-base is needed here for snapcraft to build this snap as with "modern"
 # snapcraft
-build-base: core
+build-base: core20
 package-repositories:
   - type: apt
     ppa: snappy-dev/image
@@ -31,8 +31,12 @@ license: GPL-3.0
 parts:
   snapd-deb:
     plugin: nil
-    source: .
-    build-snaps: [go/1.13/stable]
+    source-type: git
+    source: https://git.launchpad.net/snapd
+    source-branch: master
+    build-snaps:
+      - on riscv64: [go/1.16/stable]
+      - else: [go/1.13/stable]
     # these packages are needed to call mkversion.sh in override-pull, all other
     # dependencies are installed using apt-get build-dep
     build-packages:
@@ -41,6 +45,7 @@ parts:
     after: [apparmor]
     override-pull: |
       snapcraftctl pull
+      [ -e packaging/ubuntu-20.04 ] || ln -s ubuntu-16.04 packaging/ubuntu-20.04
       # set version, this needs dpkg-parsechangelog (from dpkg-dev) and git
       snapcraftctl set-version "$(./mkversion.sh --output-only)"
       # Ensure that ./debian/ packaging which we are about to use
@@ -127,7 +132,7 @@ parts:
     stage-packages:
       - libc6
       - libc-bin
-      - libgcc1
+      - libgcc-s1
     stage:
       - lib/*
       - usr/lib/*
@@ -149,7 +154,7 @@ parts:
     build-packages: [python3-apt]
     source: https://github.com/snapcore/fc-cache-static-builder.git
     override-build: |
-      ./build-from-security.py xenial
+      [ "$(uname -m)" = "riscv64" ] && cp /bin/true fc-cache-xenial || ./build-from-security.py xenial
       mkdir -p $SNAPCRAFT_PART_INSTALL/bin
       cp -a fc-cache-xenial $SNAPCRAFT_PART_INSTALL/bin/fc-cache-v6
     prime:
@@ -160,7 +165,7 @@ parts:
     build-packages: [python3-apt]
     source: https://github.com/snapcore/fc-cache-static-builder.git
     override-build: |
-      ./build-from-security.py bionic
+      [ "$(uname -m)" = "riscv64" ] && cp /bin/true fc-cache-bionic || ./build-from-security.py bionic
       mkdir -p $SNAPCRAFT_PART_INSTALL/bin
       cp -a fc-cache-bionic $SNAPCRAFT_PART_INSTALL/bin/fc-cache-v7
     prime:
```

New changes that are being added to the riscv64 branch:

```
$ git diff origin/master-riscv64 HEAD -- build-aux/snap/snapcraft.yaml > new-to-riscv64-branch.patch
```

```diff
diff --git a/build-aux/snap/snapcraft.yaml b/build-aux/snap/snapcraft.yaml
index b065772fa4..8caa34567e 100644
--- a/build-aux/snap/snapcraft.yaml
+++ b/build-aux/snap/snapcraft.yaml
@@ -12,6 +12,9 @@ adopt-info: snapd-deb
 # build-base is needed here for snapcraft to build this snap as with "modern"
 # snapcraft
 build-base: core20
+package-repositories:
+  - type: apt
+    ppa: snappy-dev/image
 grade: stable
 license: GPL-3.0
 
@@ -34,9 +37,17 @@ parts:
     build-snaps:
       - on riscv64: [go/1.16/stable]
       - else: [go/1.13/stable]
+    # these packages are needed to call mkversion.sh in override-pull, all other
+    # dependencies are installed using apt-get build-dep
+    build-packages:
+      - git
+      - dpkg-dev
+    after: [apparmor]
     override-pull: |
       snapcraftctl pull
       [ -e packaging/ubuntu-20.04 ] || ln -s ubuntu-16.04 packaging/ubuntu-20.04
+      # set version, this needs dpkg-parsechangelog (from dpkg-dev) and git
+      snapcraftctl set-version "$(./mkversion.sh --output-only)"
       # Ensure that ./debian/ packaging which we are about to use
       # matches the current `build-base` release. I.e. ubuntu-16.04
       # for build-base:core, etc.
@@ -46,8 +57,6 @@ parts:
       export DEBCONF_NONINTERACTIVE_SEEN=true
       sudo -E apt-get build-dep -y ./
       ./get-deps.sh --skip-unused-check
-      # set version after installing dependencies so we have all the tools here
-      snapcraftctl set-version "$(./mkversion.sh --output-only)"
     override-build: |
       # unset the LD_FLAGS and LD_LIBRARY_PATH vars that snapcraft sets for us
       # as those will point to the $SNAPCRAFT_STAGE which on re-builds will 
@@ -66,6 +75,23 @@ parts:
       # bother compressing it too much)
       dpkg-buildpackage -b -Zgzip -zfast
       dpkg-deb -x $(pwd)/../snapd_*.deb $SNAPCRAFT_PART_INSTALL
+      # not included in the deb as it's only used with UC20 preseeding.
+      cp -a data/preseed.json $SNAPCRAFT_PART_INSTALL/usr/lib/snapd/
+      # Note that this check should run *after* dpkg-buildpackage was run
+      # as this will re-run "go generate" which may cause a dirty tree
+      #
+      # TODO: when something like "craftctl get-version" is ready, then we can
+      # use that, but until then, we have to re-run mkversion.sh to check if the
+      # version number was set as "dirty" from the override-pull step or during
+      # the build step
+      if sh -x ./mkversion.sh --output-only | grep "dirty"; then
+        mkdir -p $SNAPCRAFT_PART_INSTALL/usr/lib/snapd
+        (
+          echo "dirty git tree during build detected:"
+          git status
+          git diff
+        ) > $SNAPCRAFT_PART_INSTALL/usr/lib/snapd/dirty-git-tree-info.txt
+      fi
 
   # xdelta is used to enable delta downloads (even if the host does not have it)
   xdelta3:
@@ -92,6 +118,13 @@ parts:
       - liblzma5
     stage:
       - lib/*
+  # Needed by squashfs-tools and fc-cache
+  zlib:
+    plugin: nil
+    stage-packages:
+      - zlib1g
+    stage:
+      - lib/*
   # libc6 is part of core but we need it in the snapd snap for
   # CommandFromSystemSnap
   libc6:
@@ -137,3 +170,37 @@ parts:
       cp -a fc-cache-bionic $SNAPCRAFT_PART_INSTALL/bin/fc-cache-v7
     prime:
       - bin/fc-cache-v7
+  apparmor:
+    plugin: autotools
+    build-packages: [bison, flex, gettext, g++, pkg-config]
+    source: https://launchpad.net/apparmor/3.0/3.0.7/+download/apparmor-3.0.7.tar.gz
+    override-build: |
+      cd $SNAPCRAFT_PART_BUILD/libraries/libapparmor
+      ./autogen.sh
+      ./configure --prefix=/usr --disable-man-pages --disable-perl --disable-python --disable-ruby
+      make -j$(nproc)
+      # place libapparmor into staging area for use by snap-confine
+      make -C src install DESTDIR=$SNAPCRAFT_STAGE
+      cd $SNAPCRAFT_PART_BUILD/parser
+      # copy in a pregenerated list of network address families so that the
+      # parser gets built to support as many as possible even if glibc in
+      # the current build environment does not support them
+      # For some reason, some snapcraft version remove the "build-aux" folder
+      # and move the contents up when the data is uploaded; this conditional
+      # manages it.
+      if [ -d "$SNAPCRAFT_PROJECT_DIR/build-aux" ]; then
+        cp $SNAPCRAFT_PROJECT_DIR/build-aux/snap/local/apparmor/af_names.h .
+      else
+        cp $SNAPCRAFT_PROJECT_DIR/snap/local/apparmor/af_names.h .
+      fi
+      make -j$(nproc)
+      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/lib/snapd
+      cp -a apparmor_parser $SNAPCRAFT_PART_INSTALL/usr/lib/snapd/
+      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/lib/snapd/apparmor
+      cp -a parser.conf $SNAPCRAFT_PART_INSTALL/usr/lib/snapd/apparmor/
+      cd $SNAPCRAFT_PART_BUILD/profiles
+      make -j$(nproc)
+      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/lib/snapd/apparmor.d
+      cp -a apparmor.d/abi $SNAPCRAFT_PART_INSTALL/usr/lib/snapd/apparmor.d/
+      cp -a apparmor.d/abstractions $SNAPCRAFT_PART_INSTALL/usr/lib/snapd/apparmor.d/
+      cp -a apparmor.d/tunables $SNAPCRAFT_PART_INSTALL/usr/lib/snapd/apparmor.d/
```

**Comment by xnox** [comment]
@alexmurray @mvo5 @mardy @pedronis - once apparmor vendoring landed in master (after a bit of back in forth) it broke riscv64 builds as build-aux/ changes on master were not done on the riscv64 branch.

Please review this pull request. Separately, I wonder if this branch should be automatically managed with github actions => sed snapcraft.yaml from master branch and blindly commit here?

Also without a similar change on beta branch, riscv64 builds will be broken for an upcoming release on riscv64.

**Comment by xnox** [comment]
i guess i will update official builds snap to use my repo

**Comment by Meulengracht** [comment]
> @alexmurray @mvo5 @mardy @pedronis - once apparmor vendoring landed in master (after a bit of back in forth) it broke riscv64 builds as build-aux/ changes on master were not done on the riscv64 branch.
> 
> Please review this pull request. Separately, I wonder if this branch should be automatically managed with github actions => sed snapcraft.yaml from master branch and blindly commit here?
> 
> Also without a similar change on beta branch, riscv64 builds will be broken for an upcoming release on riscv64.

I think something went wrong with your merge of master - because you are trying to merge 5000 commits with 170K adds. Makes it a bit hard to review

**Comment by xnox** [comment]
FYI the target of this merge is not "master" branch, but the ancient fork "master-riscv64" which is only used by the riscv64 snap build recipe.

**Comment by Meulengracht** [comment]
> FYI the target of this merge is not "master" branch, but the ancient fork "master-riscv64" which is only used by the riscv64 snap build recipe. This is a merge of master, into "master-riscv64".

Thank you for the detailed explanation, this clears it up for me.

**Review by mvo5 — APPROVED** [review]
Thanks, ideally we cherry pick all the bits we can merge into master from here. Once https://github.com/snapcore/snapd/pull/12224 and https://github.com/snapcore/snapd/pull/12554 are merged this branch is hopefully no longer needed

**Pull request merged**
