### PR TITLE
tests: remove snapd16 test

### PR DESCRIPTION
**Pull request by sergiocazzolato**
This test w'ont be fixed so it is removed.

### CODE REVIEW

**Review by andrewphelpsj — APPROVED** [review]
Thanks! Although, why not just remove it if we’re not gonna deal with it?

**Review by pedronis — CHANGES_REQUESTED** [review]
I think we should fully remove it at this point

**Review by Meulengracht — APPROVED** [review]
Thank you

**Review by pedronis — APPROVED** [review]
thanks

**Pull request merged**
