### PR TITLE
wayland: add support for eglstream on Core

### PR DESCRIPTION
**Pull request by Saviq**
I understand this is a relatively big hammer, but I've not found a way to lock this down more. The socket is created in the proprietary Nvidia driver userspace and handed to the client and server along here:

https://github.com/NVIDIA/egl-wayland/blob/30c5a951a849f835acc9f11ea4ca4e1d3380b7eb/src/wayland-eglstream.c#L95

Without this the denials were as follows:

```plain
[ 6515.841573] audit: type=1400 audit(1678471973.620:2177): apparmor="DENIED" operation="file_receive" profile="snap.ubuntu-frame.daemon" pid=14652 comm="Mir/Wayland" family="unix" sock_type="stream" protocol=0 requested_mask="send receive" denied_mask="send receive" addr=none peer_addr=none peer="snap.graphics-test-tools.glmark2-es2-wayland"
[ 6515.841577] audit: type=1400 audit(1678471973.620:2178): apparmor="DENIED" operation="file_receive" profile="snap.graphics-test-tools.glmark2-es2-wayland" pid=14652 comm="Mir/Wayland" family="unix" sock_type="stream" protocol=0 requested_mask="send receive" denied_mask="send receive" addr=none peer_addr=none peer="snap.ubuntu-frame.daemon"
```

There's nothing that identifies the stream better that I've found ("Mir/Wayland" is the thread name for the Mir Wayland connector, so not something we should key on, and in any case AppArmor doesn't seem to have facilities for that).

### CODE REVIEW

**Comment by Saviq** [comment]
Not sure if there's anything I can do about the CI failures?

**Review by alexmurray — APPROVED** [review]
LGTM

**Comment by Meulengracht** [comment]
> Not sure if there's anything I can do about the CI failures?

No they should be fine, they are not related to this PR.

**Review by Meulengracht — APPROVED** [review]
LGTM

**Review by mvo5 — APPROVED** [review]
Thanks, this looks fine

**Pull request merged**
