### PR TITLE
snap: use snap.SideInfo in test to fix build with gccgo

### PR DESCRIPTION
**Pull request by mvo5**
We currently see build failures on powerpc (which uses gccgo)
because the test is using "SideInfo" instead of "snap.SideInfo".

### CODE REVIEW

**Comment by bboozzoo** [comment]
There's a couple of other places that do the same:
```snap/info_test.go
1340:   snapd := &snap.Info{SideInfo: snap.SideInfo{RealName: "snapd"}}

snap/snapenv/snapenv_test.go
58:     SideInfo: snap.SideInfo{
65:     SideInfo: snap.SideInfo{

store/details_v2_test.go
154:            SideInfo: snap.SideInfo{
202:            SideInfo: snap.SideInfo{

image/image_test.go
706:                                    SideInfo: snap.SideInfo{
714:                                    SideInfo: snap.SideInfo{
841:            SideInfo: snap.SideInfo{
914:                                    SideInfo: snap.SideInfo{
1074:                                   SideInfo: snap.SideInfo{
1082:                                   SideInfo: snap.SideInfo{

daemon/api_test.go
722:    info := snap.Info{SideInfo: snap.SideInfo{RealName: "hello", Revision: snap.R(1)}}
1506:           SideInfo: snap.SideInfo{
1567:           SideInfo: snap.SideInfo{
1602:           SideInfo: snap.SideInfo{
1631:           SideInfo: snap.SideInfo{
1734:           SideInfo: snap.SideInfo{
1761:           SideInfo: snap.SideInfo{
1853:           SideInfo: snap.SideInfo{
1900:           SideInfo: snap.SideInfo{
1938:           SideInfo: snap.SideInfo{
1971:                   SideInfo: snap.SideInfo{
1977:                   SideInfo: snap.SideInfo{
1983:                   SideInfo: snap.SideInfo{
2033:           SideInfo: snap.SideInfo{
2078:           SideInfo: snap.SideInfo{

wrappers/desktop_test.go
206:    snap := &snap.Info{SideInfo: snap.SideInfo{RealName: "foo", Revision: snap.R(12)}}

wrappers/services_gen_test.go
166:                    SideInfo:      snap.SideInfo{Revision: snap.R(44)},
187:                    SideInfo:      snap.SideInfo{Revision: snap.R(44)},
257:                    SideInfo:      snap.SideInfo{Revision: snap.R(44)},
305:                    SideInfo:      snap.SideInfo{Revision: snap.R(44)},
361:                    SideInfo:      snap.SideInfo{Revision: snap.R(44)},
385:                    SideInfo:      snap.SideInfo{Revision: snap.R(44)},
428:                    SideInfo:      snap.SideInfo{Revision: snap.R(44)},
552:                            SideInfo:      snap.SideInfo{Revision: snap.R(44)},

overlord/snapstate/backend_test.go
194:            SideInfo: snap.SideInfo{
298:            SideInfo: snap.SideInfo{

overlord/snapstate/backend/mountunit_test.go
70:             SideInfo: snap.SideInfo{
100:            SideInfo: snap.SideInfo{

overlord/hookstate/ctlcmd/services_test.go
59:                     SideInfo: snap.SideInfo{
68:             SideInfo: snap.SideInfo{
74:     }, {SideInfo: snap.SideInfo{

overlord/snapshotstate/backend/backend_test.go
441:    info := &snap.Info{SideInfo: snap.SideInfo{RealName: "hello-snap", Revision: snap.R(42)}, Version: "v1.33"}

overlord/assertstate/assertstate_test.go
739:            SideInfo: snap.SideInfo{RealName: "foo", SnapID: "foo-id", Revision: snap.R(9)},
768:            SideInfo: snap.SideInfo{RealName: "foo", SnapID: "foo-id", Revision: snap.R(9)},
797:            SideInfo: snap.SideInfo{RealName: "foo", SnapID: "foo-id", Revision: snap.R(9)},
865:            SideInfo: snap.SideInfo{RealName: "foo", SnapID: "foo-id", Revision: snap.R(9)},
934:            SideInfo: snap.SideInfo{RealName: "foo", SnapID: "foo-id", Revision: snap.R(9)},
1006:           SideInfo: snap.SideInfo{
1067:           SideInfo: snap.SideInfo{
1080:           SideInfo: snap.SideInfo{
1105:           SideInfo: snap.SideInfo{
```

What is the actual error raised by gccgo?

**Comment by mvo5** [comment]
@bboozzoo The error is with SideInfo is:
```
$ go-8 test
# github.com/snapcore/snapd/snap_test
./info_test.go:1341:3: error: use of undefined type ‘SideInfo’
   SideInfo: snap.SideInfo{RealName: "snapd"},
```
what is interessting is that this does not fail in the other places.Maybe it is used as snap.Info there?

**Comment by bboozzoo** [comment]
Intersting, so we have a sample like this:
```
wrappers/desktop_test.go
206:    snap := &snap.Info{SideInfo: snap.SideInfo{RealName: "foo", Revision: snap.R(12)}}
```
Which is both `*snap.Info` and also shadows the `snap` package`. Could you rename `snap` to `info` and try with gccgo?

**Comment by mvo5** [comment]
@bboozzoo Its very odd, in wrappers gcc-8 does not complain about the same line. I would like to keep exploring but I'm also keen to fix the powerpc test

**Pull request merged**
