### PR TITLE
refactor the dialer init code

### PR DESCRIPTION
**Pull request by teknoraver**
refactor the dialer init code

remove an unused returned function pointer

### CODE REVIEW

**Comment by teknoraver** [comment]
Build failure, maybe context is go 1.7+ only?

**Comment by chipaca** [comment]
I think it was a function so it only did the checks once? (maybe it had more expensive logic in there before?).

I think now it'd be fine to just do the checks as you go, i.e. instead of OpenFile use Dial directly and check the error

**Comment by mvo5** [comment]
Can you please merge master into this branch?

**Comment by niemeyer** [comment]
The suggested change means the logic inside the preamble of that function will be called every single time the function is called, while today it is executed only once. The existence of the function was not an accident or leftover.

**Pull request closed without merging**
