### PR TITLE
tests: move core and regression suites to snaps-state tool

### PR DESCRIPTION
**Pull request by sergiocazzolato**
First part of the migration

### CODE REVIEW

**Review by bboozzoo — APPROVED** [review]
LGTM

**Review by stolowski — APPROVED** [review]
Nice, +1

**Comment by bboozzoo** [comment]
This one failed:

```
2020-09-30T21:05:47.0289975Z 2020-09-30 21:05:47 Restoring google:ubuntu-18.04-64:tests/lib/tools/suite/mountinfo.query (sep302004-060194)...
2020-09-30T21:05:47.3215717Z ##[error]2020-09-30 21:05:47 Error preparing google:ubuntu-18.04-64:tests/regression/lp-1813963 (sep302004-060211) : 
2020-09-30T21:05:47.3226960Z -----
2020-09-30T21:05:47.3228999Z + /home/gopath/src/github.com/snapcore/snapd/tests/lib/prepare-restore.sh --prepare-project-each
2020-09-30T21:05:47.3230856Z + set -e
2020-09-30T21:05:47.3231849Z + . /home/gopath/src/github.com/snapcore/snapd/tests/lib/quiet.sh
2020-09-30T21:05:47.3233257Z + . /home/gopath/src/github.com/snapcore/snapd/tests/lib/boot.sh
2020-09-30T21:05:47.3234830Z ++ GRUB_EDITENV=grub-editenv
...
2020-09-30T21:05:47.3405118Z ++ MEDIA_DIR=/media
2020-09-30T21:05:47.3405435Z ++ case "$SPREAD_SYSTEM" in
2020-09-30T21:05:47.3405999Z + install_local test-snapd-sh
2020-09-30T21:05:47.3406472Z /bin/bash: line 87: install_local: command not found
2020-09-30T21:05:47.3406980Z -----
```

**Review by zyga — COMMENTED** [review]
The diffs look okay but I understand there's a bit missing. Please ping for a re-review.

In hindsight, `snap-state` would read better than `snaps-state` but I guess that ship has sailed (for now).

**Comment by zyga** [comment]
@sergiocazzolato please use imperative style in commit messages, for summary at the very least.

**Pull request merged**
