### PR TITLE
tests: new test for hardware-random-control interface

### PR DESCRIPTION
**Pull request by sergiocazzolato**
Adding this test to check the hardware-random-control interface.

### CODE REVIEW

**Comment by mvo5** [comment]
Those failures: 
- linode:debian-unstable-64:tests/main/interfaces-hardware-random-control
- linode:fedora-25-64:tests/main/interfaces-hardware-random-control
look real though

**Comment by sergiocazzolato** [comment]
@mvo5 is there any naming convention for the test snaps? I see some of them starting with test-snapd and some others not.

**Comment by sergiocazzolato** [comment]
@mvo5 @zyga in fedora is allways accessing even when I removed the plug for the interface in the snap.yaml. See log:
https://paste.ubuntu.com/25811518/

I am adding a change to remove debian for the execution

**Comment by sergiocazzolato** [comment]
fedora fixed, still missing to fix debian, there the files that we check don't exist so the test fails because of that.

**Comment by zyga** [comment]
I'll boot debian and see what I see there shortly, just moving my VMs aroudn.

**Pull request merged**
