### PR TITLE
snapenv: add SNAP_ARCH_TRIPLET

### PR DESCRIPTION
**Pull request by mvo5**
This adds a new environment variable for the snaps that identifies
the normalized GNU architecture triplet for the given architecutre.

This is useful for finding multi-arch paths inside snaps, e.g.
if there is a $SNAP/usr/lib/x86_64-linux-gnu/ then this can
now be written as "$SNAP/usr/lib/${SNAP_ARCH_TRIPLET}/.

There is a complication here - there might be subtle differences between distros. So we may need to make this base specific. For example on fedora the arm-32bit target uses "arm-linux-gnueabi" but on ubuntu we use "arm-linux-gnueabihf" which indicates that fedora is using soft-float here.

This addresses https://bugs.launchpad.net/snapd/+bug/1742565

### CODE REVIEW

**Comment by mvo5** [comment]
@chipaca Good point, I renamed it to NormalizedGNUTriplet()

**Comment by zyga** [comment]
@mvo5 I think the values will depend on the base but we can cross that bridge later.

**Comment by bboozzoo** [comment]
Travis job failed:
```
2018-01-11 17:26:44 Error executing linode:ubuntu-16.04-64:tests/main/snap-env : 
-----
+ echo 'Collect SNAP and XDG environment variables'
Collect SNAP and XDG environment variables
+ sort
+ egrep '^SNAP_'
+ test-snapd-tools.env
+ sort
+ egrep '^XDG_'
+ test-snapd-tools.env
+ sort
+ egrep '^EXTRA_'
+ test-snapd-tools.env
+ echo 'Collect PATH and HOME environment variables'
Collect PATH and HOME environment variables
+ sort
+ egrep '^(SNAP|PATH|HOME)='
+ test-snapd-tools.env
+ echo 'Ensure that SNAP environment variables are what we expect'
Ensure that SNAP environment variables are what we expect
+ MATCH '^SNAP_ARCH=(amd64|i386|arm64|armhf|ppc64el)$'
-----
```

**Comment by mvo5** [comment]
Setting to blocked until this is discussed further with @niemeyer

**Comment by Conan-Kudo** [comment]
> For example on fedora the arm-32bit target uses "arm-linux-gnueabi" but on ubuntu we use "arm-linux-gnueabihf" which indicates that fedora is using soft-float here.

I don't know what's going on here, but our `arm-linux-gnueabi` is in fact a `arm-linux-gnueabihf` target. Something is very weird here...

**Comment by mvo5** [comment]
Some more discussion here: https://forum.snapcraft.io/t/gnu-triplet-via-snap-arch-triplet/3530

@Conan-Kudo Thanks for clarifying - a good question why the two triplets are different then (and also sad!).

**Comment by mvo5** [comment]
Closing for now based on the forum discussion there is no clear path forward.

**Pull request closed without merging**
