### PR TITLE
tests: add debug output what keeps `/home` busy

### PR DESCRIPTION
**Pull request by mvo5**
We have quite a few failures like when the nfs `/home` cannot
be unmounted because it's busy.

This commit adds a debug section to get to the bottom of this.

### CODE REVIEW

**Review by mardy — APPROVED** [review]
LGTM!

**Review by mardy — COMMENTED** [review]
You need to move the `debug` section after `prepare` and `restore`, though.

**Review by MiguelPires — APPROVED** [review]
LGTM

**Comment by sergiocazzolato** [comment]
@mvo, I reproduced the test and the output is this:

google:ubuntu-20.04-64 .../tests/main/nfs-support# lsof | grep /home
bash      25840                            root  cwd       DIR               0,51     4096     529601 /home/gopath/src/github.com/snapcore/snapd/tests/main/nfs-support (localhost:/home)
bash      25847                            root  cwd       DIR               0,51     4096     529601 /home/gopath/src/github.com/snapcore/snapd/tests/main/nfs-support (localhost:/home)
lsof      25860                            root  cwd       DIR               0,51     4096     529601 /home/gopath/src/github.com/snapcore/snapd/tests/main/nfs-support (localhost:/home)
grep      25861                            root  cwd       DIR               0,51     4096     529601 /home/gopath/src/github.com/snapcore/snapd/tests/main/nfs-support (localhost:/home)
lsof      25862                            root  cwd       DIR               0,51     4096     529601 /home/gopath/src/github.com/snapcore/snapd/tests/main/nfs-support (localhost:/home)
google:ubuntu-20.04-64 .../tests/main/nfs-support# fuser -mv /home
                     USER        PID ACCESS COMMAND
/home:               root     kernel mount /home
                     root     kernel knfsd /home
                     root      25840 ..c.. bash
                     root      25847 ..c.. bash

**Comment by mvo5** [comment]
We poked a bit more at this and sergio can more easily reproduce it if the "cgroup-tracking" test is run right before the nfs-mount test.

With https://github.com/snapcore/snapd/compare/master...mvo5:nfs-support-test-more-targeted?expand=1 we got a slightly different debug output: https://paste.ubuntu.com/p/25ZYBH284h/ still a bit unclear what might trigger the dbus-daemon in this pastebin, one possible explaination might be that the unset of the `refresh-app-awareness` is somehow not complete and triggers a dbus-daemon to get launched. but a bit of speculation at this point (and might be a red-herrin).

**Review by bboozzoo — APPROVED** [review]
Thanks

**Pull request merged**
