### PR TITLE
i/b/fwupd: allow to write to some EFI path for some capsules

### PR DESCRIPTION
**Pull request by valentindavid**
See https://github.com/fwupd/fwupd/blob/e69ffa1b713b7e21177bae7483cbbff1596a6284/plugins/uefi-capsule/fu-uefi-cod-device.c#L177

### CODE REVIEW

**Review by alexmurray — APPROVED** [review]
LGTM!

**Comment by LaiderLai** [comment]
Tested under the Dell EGW 3200 (https://ubuntu.com/certified/202202-29962) with Jammy server environment.
Got the error "Failed to create file “/boot/efi/EFI/UpdateCapsule/fwupd-80a2f406-fd10-4734-b752-c987ba23747b.cap.V7HV01”: Permission denied"

Could you help to refine the commit with the correct path? The UpdateCapsule directory is under the EFI, not under the EFI/*
I think it should be /boot/efi/EFI/UpdateCapsule/** rw,

Tks.

**Comment by alexmurray** [comment]
Ah yes I agree - looking at the mentioned fwupd code a bit closer:

```c
g_build_filename(esp_path, "EFI", "UpdateCapsule", basename, NULL);
```

which would appear to be `/boot/efi/EFI/UpdateCapsule/` as the prefix - as such this AppArmor rule should be changed to:

```
/boot/efi/EFI/UpdateCapsule/fwupd* rw,
```

**Review by pedronis — COMMENTED** [review]
+1

**Pull request merged**
