### PR TITLE
many: allow building without bolt using nobolt tag

### PR DESCRIPTION
**Pull request by zyga**
This is a re-creation of https://github.com/snapcore/snapd/pull/13532 from my personal fork.

Bolt is an abandoned project. Upstream is not accepting any patches.
Debian has three versions of bolt, none of which build on riscv64 due to
the lack of appropriate architecture tags.

In Debian, bolt is not built from the vendored package but instead from
the distribution package, one of three in the archive, each capturing a
different, outdated and differently patched fork.

Fortunately, bolt is not really heavily used in snapd. While we try to
address the issue regarding bolt and riscv64, we can continue to build
snapd on riscv64 without the ability to store information only used by
command-not-found helpers.

Allow advisor to fail with advisor.ErrNotSupported when snapd is built without
bolt support. Tests for the store, overlord package and the "snap advise"
command are adjusted to skip certain tests when that error is returned.

Debian-Bug: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1010686

### CODE REVIEW

**Comment by zyga** [comment]
When running locally this seems to operate fine. The only side effect I can see is this error message logged in debug mode:

```
2024/02/01 10:25:25.878293 stateengine.go:149: state ensure error: not supported
```

I've pushed a tweak to adjust the name so that it will say "advisor is not supported" instead.

**Review by bboozzoo — COMMENTED** [review]
Waybe worth adding a unit test run with 'nobolt' to the github workflow. I think the apt hook should work fine as it, as we only return something when there is a match, I don't think --command is used by anything else than command-not-found, but it may be worth double checking if it's not broken by any chance.

**Review by bboozzoo — APPROVED** [review]
LGTM

**Comment by zyga** [comment]
I need to rebase the patch that we carry in `debian/patches`

**Comment by zyga** [comment]
I've decided to drop that patch instead. See the commit for rationale.

**Review by Meulengracht — APPROVED** [review]
Thank you

**Review by andrewphelpsj — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
