### PR TITLE
interfaces/kubernetes-support: allow autobind to journald socket

### PR DESCRIPTION
**Pull request by jdstrand**
k8s.io/apiserver/pkg/storage/etcd3/logger.go pulls in go-systemd via
go.etcd.io/etcd/clientv3 and several k8s services use
apiserver/pkg/storage. go-systemd connects to the journald socket using
the 'autobind' feature of bind(). While an argument could be made to add
this support to the default policy since we generally want all snaps to
be able to log to journald, due to LP: 1867216, we cannot use the
specific 'unix (bind) type=dgram addr=none' rule and must instead use a
less specific rule that allows bind() to arbitrary SOCK_DGRAM abstract
socket names (separate send and receive rules are still required for
communicating over the socket). For now, since the rule would allow
snaps to DoS each other and the system by allowing them to bind to
well-known socket names, omit this from default (and other interface)
policy and add a new kubernetes-support flavor (autobind-unix). In this
manner, any k8s service can utilize this logging API without granting
the more privileged rules for kubelet and kubeproxy. The journald rules
are included in all the flavors (and default), while the
autobind-unix flavor only has the journald rules.

References:
https://github.com/coreos/go-systemd/blob/master/journal/journal.go#L211
https://bugs.launchpad.net/apparmor/+bug/1867216

### CODE REVIEW

**Comment by zyga** [comment]
That was quick :)

**Comment by zyga** [comment]
I am still reviewing it, even though it was merged.

**Comment by jdstrand** [comment]
> LGTM, but should we eventually move allowing autobind sockets to something like `network-bind` when that can be finely mediated? I.e. add a
> 
> ```go
> `
> # TODO: add the fine grained access rule for autobind to network-bind 
> # see LP 1867216
> #unix (bind) type=dgram addr=none,
> `
> ```
> 
> to `network-bind`?

Not yet. It has been years now where no one has asked for this access and I discussed with jj and this is going to need a kernel fix. It is unclear what we will want if we add it to an auto-connecting interface like network-bind.

**Comment by anonymouse64** [comment]
Thanks for the explanation Jamie

**Pull request merged**
