### PR TITLE
usersession/userd: add "slack" to the white list of URL schemes handled by xdg-open

### PR DESCRIPTION
**Pull request by troyready**
This will allow apps (namely Chromium) to launch the Slack desktop chat app directly (instead of silently failing to launch).

I can't find any official documentation on the URL format, but there are [other examples of it in use around](https://github.com/NixOS/nixpkgs/issues/18791#issuecomment-576400722).

### CODE REVIEW

**Comment by troyready** [comment]
I expect I'm going to fail the CLA PR bot again -- I attempted to load the CLA site again, but am still experiencing [the same issue I described in an earlier PR](https://github.com/snapcore/snapd/pull/8254#issuecomment-601446144).

Change here is trivial, feel free to incorporate it directly without any attribution to me.

**Comment by jhenstridge** [comment]
Note that in future (after snapd 2.44.2) changes like this will not be necessary on systems with xdg-desktop-portal installed.

(this isn't a reason not to accept this PR though).

**Comment by zyga** [comment]
@troyready this pull request cannot be checked before the CLA checker reports that you have signed the snapd CLA

**Comment by anonymouse64** [comment]
Marking blocked until Jamie reviews this

**Comment by troyready** [comment]
Just submitted my individual CLA again (it seems that the image generation for the captcha is broken, but I just noticed that the audio file generation still works):

image

**Comment by zyga** [comment]
@troyready could you please share the name of your launchpad account?

**Comment by jdstrand** [comment]
> Slack is using classic confinement and therefore might be attacked with a crafted URL that exercises a bug in the client, offering programs a way out of their confinement.
> 
> Having said that, with the inevitable support for opening URLs via portals this is not going to be any different.
> 
> I don't recall our policy on this perfectly, but if I recall correctly we wanted to be extra careful about granting ability to open other URL schemes. Having said that we are clearly allowing more, as zoom is there as well.
> 
> With that +1 because that bridge has been crossed and this improves usability over copy-pasting URLs.

@zyga - please see my comments here: 

> Slack is using classic confinement and therefore might be attacked with a crafted URL that exercises a bug in the client, offering programs a way out of their confinement.
> 
> Having said that, with the inevitable support for opening URLs via portals this is not going to be any different.
> 
> I don't recall our policy on this perfectly, but if I recall correctly we wanted to be extra careful about granting ability to open other URL schemes. Having said that we are clearly allowing more, as zoom is there as well.
> 
> With that +1 because that bridge has been crossed and this improves usability over copy-pasting URLs.

@zyga - we discussed this at length here: https://github.com/snapcore/snapd/pull/7731#pullrequestreview-362900171. Thus far, the criteria I've personally been applying since then is examining the URI scheme to see if there is anything worrisome.

**Comment by troyready** [comment]
@zyga sure thing - it's the same as my GitHub username, `troyready`

**Comment by jdstrand** [comment]
> Slack is using classic confinement and therefore might be attacked with a crafted URL that exercises a bug in the client, offering programs a way out of their confinement.

While I think this PR is fine to apply, I do think it is worth recognizing @zyga's point. I did mention in https://github.com/snapcore/snapd/pull/7731#pullrequestreview-362900171:
"
_While I'm not overly concerned about the security impact of typical URLs (we only pass the url to the handler and no arguments), I do want to be sure that we can't pass file paths or crafted urls in to the handlers (so a snap can't call xdg-open foo:$SNAP_USER_DATA/crafted.thing to try to break out of the sandbox. This might mean we do some more filtering on the decoded addr in usersession/userd/launcher.go:OpenURL()_ 
"

Today we are already using net/url's [Parse()](https://golang.org/src/net/url/url.go?s=13410:13449#L464) which performs some validation but AFAICS, launcher_test.go lacks invalid URL tests. It would be good to add some (again, not a blocker for this PR).

**Comment by jeantil** [comment]
what is the status of this PR ? required cla-check seems to have been addressed but it hasn't been updated. no idea what the "spread" is ...

**Comment by anonymouse64** [comment]
This PR seems to have been opened mid-way through our travis -> github actions transition and so some of the checks here were stuck. I merged master, so that at least the checks run now, but we currently have other issues plaguing master affecting tests so this may be red for other reasons now anyways. 

Also, it seems that the cla-check failed again not recognizing the user. I think there may be an error with our CLA checker, I will ask relevant folks to look into this.

**Comment by anonymouse64** [comment]
> Note that in future (after snapd 2.44.2) changes like this will not be necessary on systems with xdg-desktop-portal installed.

Just to clarify this comment is referring to the great work done in https://github.com/snapcore/snapd/pull/8289, which unfortunately did not make it into the release/2.44 branch, but is a part of 2.45 and so it will be in the next snapd release after 2.44.5 is released (which should be soon as it's already in beta) and that change indeed is already available on the snapd snap on edge.

**Comment by jdstrand** [comment]
Adding the 2.45 milestone so this isn't forgotten.

**Comment by jdstrand** [comment]
@mvo5 - I deconflicted this but it looks like the cla-check is still failing. https://launchpad.net/~troyready appears to be the LP name (it has the same email address as the github account and shows that the code of conduct was signed).

**Comment by jdstrand** [comment]
To expedite things, I created https://github.com/snapcore/snapd/pull/8800 which is this PR against the 2.45 branch. This will allow this feature to be in 2.45 while the cla-check details are being worked out.

**Comment by mvo5** [comment]
Thanks for this PR! I'm chasing  internally why the CLA check is failing, maybe some internal process did not finish correctly or something.

**Comment by mvo5** [comment]
I checked and the CLA is signed, I will chase why the LP check is failing but this should not block this PR.

**Pull request merged**
