### PR TITLE
tests: running tests on opensuse leap 15.2

### PR DESCRIPTION
**Pull request by sergiocazzolato**

### CODE REVIEW

**Review by mvo5 — APPROVED** [review]
Change looks fine, interestingly it only fails in a single test right now: `getent passwd daemon` apparently.

**Comment by bboozzoo** [comment]
This line needs to be updated too: https://github.com/snapcore/snapd/blob/master/tests/main/system-usernames/task.yaml#L22

**Comment by bboozzoo** [comment]
Hm it's something else after all, ignore my previous comment.

**Comment by bboozzoo** [comment]
We need to install `system-user-daemon` package for the `daemon` user to be added automatically on 15.2. I don't know how that package made its way to the 15.1 image, or why lsb-release does not pull it in even though `daemon` is a required user by LSB spec.

Since we depend on the `daemon` user to exist for system usernames feature, perhaps we should add it to `Requires` list in the RPM spec? (cc @zyga)

**Pull request merged**
