### PR TITLE
tests: enable lxd tests on impish system

### PR DESCRIPTION
**Pull request by sergiocazzolato**
It is done now because the lxd images have been published.

### CODE REVIEW

**Review by mvo5 — APPROVED** [review]
Thank you

**Review by mardy — APPROVED** [review]
LGTM!

**Review by bboozzoo — APPROVED** [review]
LGTM. tests/main/lxd is failing on 21.10 like it's failing on 21.04, but that's unrelated to the PR

**Comment by mvo5** [comment]
This PR fails in a slightly different way - it's *not* the my-inner-ubuntu that fails, it's already the regular container:
```
...
2021-11-02T20:28:25.6038465Z Ensure we can use snapd inside lxd
2021-11-02T20:28:25.6039731Z + lxd.lxc exec my-ubuntu snap install test-snapd-sh
2021-11-02T20:28:25.6040782Z error: cannot perform the following tasks:
2021-11-02T20:28:25.6042302Z - Setup snap "core" (11993) security profiles (cannot run udev triggers: exit status 1
2021-11-02T20:28:25.6043801Z udev output:
2021-11-02T20:28:25.6045712Z LNXSYSTM:00: Failed to write 'change' to '/sys/devices/LNXSYSTM:00/uevent': Permission denied
2021-11-02T20:28:25.6047749Z LNXPWRBN:00: Failed to write 'change' to '/sys/devices/LNXSYSTM:00/LNXPWRBN:00/uevent': Permission denied
2021-11-02T20:28:25.6049930Z wakeup6: Failed to write 'change' to '/sys/devices/LNXSYSTM:00/LNXPWRBN:00/wakeup/wakeup6/uevent': Permission denied
2021-11-02T20:28:25.6052312Z LNXSLPBN:00: Failed to write 'change' to '/sys/devices/LNXSYSTM:00/LNXSLPBN:00/uevent': Permission denied
...
```

**Comment by anonymouse64** [comment]
@mvo5 that failure is what I was referring to in my initial comment on this PR, you have to essentially install the core snap twice in order for it to work for some mysterious udev related reason.

**Review by anonymouse64 — COMMENTED** [review]
the code changes here look correct but it would be great if we could get to the bottom of why the initial seeding/install of our snapd from the branch fails _the first time_ due to udev things

**Pull request merged**
