### PR TITLE
config: rename "virtual" config to "external" config

### PR DESCRIPTION
**Pull request by mvo5**
Samuele suggested to use the term "external configuration" instead
of "virtual configuration" in the code that deals with e.g. the
timezone or hostname configuration [1].

This commit updates the code to implement this suggestion. There is an
additional commit on top of the rename that removes some obsolete comments.
Probably easiest to review the two commits separately.

[1] https://github.com/snapcore/snapd/pull/10562#discussion_r679302808

### CODE REVIEW

**Review by mardy — APPROVED** [review]
LGTM, although between the two options I'd personally stick to "virtual", since with "external" it's not very clear what's the subject ("external" to what?).

Other suggestions include "dynamic" and "runtime".

**Comment by mvo5** [comment]
Thanks! I have no strong opinion about the exact name, happy to discuss this further and leave this up for more discussions.

**Review by anonymouse64 — APPROVED** [review]
LGTM, I think that external configuration makes more sense than virtual, since the configuration is indeed managed/exists external to snapd. Alternative to external would be "passthrough" maybe?

**Comment by mvo5** [comment]
After talking to Samuele we will go with external.

**Pull request merged**
