### PR TITLE
packaging: fix unneeded errtracker patches

### PR DESCRIPTION
**Pull request by andrewphelpsj**
These patches no longer apply since the errtracker code was removed.

### CODE REVIEW

**Review by mvo5 — APPROVED** [review]
Thank you!

**Comment by mvo5** [comment]
> Thank you!

Fwiw, I had to tweak the diff a little bit because the patches concerned both "advisor" and "boltdb".

**Comment by mvo5** [comment]
Marked as 2.61 as it is required for the deb/rpm releases

**Review by MiguelPires — APPROVED** [review]
LGTM, thanks

**Pull request merged**
