### PR TITLE
.github/workflows/labeler.yaml: try work-around to not sync labels

### PR DESCRIPTION
**Pull request by anonymouse64**
This was suggested in the upstream bug at https://github.com/actions/labeler/issues/104

Also apply the YAML linter that my editor applies to every YAML file :-)

### CODE REVIEW

**Review by bboozzoo — APPROVED** [review]
Let's land this and see what happens when when we open new PRs

**Review by mvo5 — COMMENTED** [review]
Thanks for this. It's slightly unfortunate (IMO) that it mixes a function change (adding sync-labels) with format changes (indent, moving from ' -> " quotes). Maybe worth splitting into two commits? One with the style and one with the function change?

**Comment by anonymouse64** [comment]
@mvo5 ok, I force pushed a rebase splitting out the changes into two commits, so if this doesn't work again after merging we can cleanly just revert 8fdbd9ed6354f533c63654e57be46dd9d38fa5ef

**Review by mvo5 — APPROVED** [review]
\o/ Thank you

**Pull request merged**
