### PR TITLE
interfaces/builtin: allow kwalletd version 6

### PR DESCRIPTION
**Pull request by nteodosio**
https://launchpad.net/bugs/2058840: KDE 6 comes with Kwalletd6, so the profile needs updating.

### CODE REVIEW

**Review by bboozzoo — APPROVED** [review]
LGTM

**Review by ernestl — APPROVED** [review]
Looks good, thanks

**Review by alexmurray — CHANGES_REQUESTED** [review]
Do we really need to future proof this for a possible future KDE 9? KDE 5 was released in 2014 and KDE 6 was now in 2024 - given this I don't even think a KDE7 is worth adding here - hence I would prefer to see this as just:

```
path=/modules/kwalletd{,[56]}
```

**Comment by nteodosio** [comment]
I rebase on main to get the spread test bug fix as suggested by @ernestl.

@alexmurray, I saw no reason not to, but I edited the commit to only use 6.

Thank you all for the review.

**Review by zyga — APPROVED** [review]
This looks good

**Review by alexmurray — APPROVED** [review]
LGTM - thanks.

**Pull request merged**
