### PR TITLE
spread-shellcheck: correctly attribute suite errors

### PR DESCRIPTION
**Pull request by zyga**
Thanks to James for spotting my earlier mistake

Signed-off-by: Zygmunt Krynicki <me@zygoon.pl>

### CODE REVIEW

**Review by mvo5 — APPROVED** [review]
Thanks

**Review by jhenstridge — APPROVED** [review]
Looks good.  The nested executors seem a little weird, but mostly harmless given there's likely to be only one `spread.yaml` to check.

**Comment by zyga** [comment]
Nested executors seem to push the self-imposed 10 second timeout to the limit. This is fixed in the follow-up https://github.com/snapcore/snapd/pull/9493

**Comment by zyga** [comment]
We could close this and merge https://github.com/snapcore/snapd/pull/9493 which contains this branch entirely.

**Pull request merged**
