### PR TITLE
i/b/kubernetes_support: add access to Java certificates

### PR DESCRIPTION
**Pull request by mardy**
These are the same rules found in the greengrass-support interface.

### CODE REVIEW

**Review by mvo5 — APPROVED** [review]
This looks fine but needs either security or Samuele +1.

**Review by anonymouse64 — APPROVED** [review]
lgtm

**Review by alexmurray — APPROVED** [review]
LGTM however it would be good to understand what the use-case is for these - can you explain further @mardy?

**Comment by mardy** [comment]
> LGTM however it would be good to understand what the use-case is for these - can you explain further @mardy?

I've now added a comment to https://bugs.launchpad.net/apparmor/+bug/1816372

**Pull request merged**
