### PR TITLE
Revert: "many: Vendor apparmor-3.0.3 into the snapd snap"

### PR DESCRIPTION
**Pull request by anonymouse64**
This reverts commit 6f5a4ac6c1eb79c17a5cda2d86a60a54b9dca6ba from #9939

#9939 introduced snapd to start writing policy via apparmor_parser from AppArmor version 3, which among other things appears to include support for parsing/understanding `capability bpf`, which does not appear to be supported in the versions of AppArmor in at least focal and earlier. This is not problematic in and of itself, but it is problematic in that the aforementioned PR did not make any update to the service snapd.apparmor.service which runs a script snapd-apparmor, which runs on some distros (notably in our CI this appears to be Ubuntu Core 16, 18, and 20). This script does not have any logic for using the vendored apparmor_parser in the snapd snap when booting up, so what happens is that we have policy from AppArmor version 3 written out to disk, and then on boot the system tries to load this using the snapd-apparmor script early on, and that script will use apparmor_parser from the host which doesn't understand the `capability bpf` and thus will break snapd in various ways leading to all our CI ubuntu core systems to just die and never come back.

There are a few ways we can fix this issue in snapd-apparmor, but in the meantime in order to have meaningful CI results for other PR's (and to not break folks using edge), we need to revert this change.

cc @alexmurray sorry for the bad news :-/

### CODE REVIEW

**Comment by alexmurray** [comment]
Gah thanks @anonymouse64, apologies for not thinking of that. I'll take a look on Monday and try and add a spread test for snapd-apparmor.service as well as a fix for it to use the vendored apparmor and will resubmit a hopefully better version of #9399.

**Comment by anonymouse64** [comment]
@alexmurray it's totally not your fault, I'm still extremely puzzled and disturbed why our spread tests did not catch this, given that they failed on bits of code from the PR that were incorrect indicating that your code from that PR was being tested... Clearly there is something missing in our testing that results in this only making tests fail when the code is already in master which is quite bad for our tests... I wasn't able to find anything there so if you have ideas about why that might have happened I would be all ears, but we will be digging into this more on Monday anyways

That being said, my first idea about how to fix this in snapd-apparmor is basically the following:
1. in snapd-apparmor either trigger generation of the system-key or otherwise wait for it (I can't quite figure out the ordering of when this service runs vs snapd, it appears to run before I think)
2. in snapd-apparmor, check the system-key for “snapd-internal” inside "apparmor-parser-features"
3. if we are using snapd-internal for apparmor_parser, then use the trick to execute it from the snapd snap (we cannot executie it directly as it will be linked differently than what will probably be on $PATH I think, we have to execute it using the interpreter shipped inside the snap snap like what snapdtool.CommandFromSystemSnap does

But all of that complexity seems like it might be time to write this snapd-apparmor in Go instead of shell. A simpler implementation might be to just always assume that if apparmor_parser exists inside the snapd snap to assume we should use it, but that draws into question whether we should do this on some distros, since some distros will disable re-exec and we thus don't want to use apparmor_parser from the snapd snap at all then (I think this case would be handled correctly with the system-key implementation mentioned above).

Perhaps @pedronis and @mvo5 can comment on the desired direction to fix snapd-apparmor on Monday

**Review by adligit2 — APPROVED** [review]

**Comment by alexmurray** [comment]
Regarding various tests not failing when this was not on master - there are a bunch of tests which install the snapd snap so these will only see the snapd snap on master, not on the branch which triggers the tests to run - hence why it was great you added the snapd-snap spread test so that we could exercise the snapd-snap from the branch in question - but perhaps there is a better way we could do this - would it be possible to have the snapd-snap spread test actually upload the output of the snap build to the store but under some temporary branch name, and then have any spread tests which use the snapd snap install it from this temporary branch in the store?

Regarding how best to fix this - if we want to keep snapd.apparmor.service as a shell script, instead of consulting `snap debug sandbox-features` how about we add a new `snap debug apparmor-arguments` or similar, which would output an array containing both the location of the `apparmor_parser` binary which is in use, as well as the arguments which should be used to invoke it? The #9939 PR already added support for getting any additional command-line arguments which should be used for the parser to `FindAppArmorParser()` so this should be relatively straight-forward, and it would ensure that the arguments used do not get out-of-sync between this script and what snapd itself is using, and finally it would mean we wouldn't have to special-case the `parser:snapd-internal` bit in this script either - we could just use the arguments (and the parser) which snapd tells it to use.

Otherwise if this is implemented in Go, we could use the same kind of logic there too - we just don't have to expose the details via `snap debug` - I'm happy to go either way, (or on some other path if you prefer) - let me know and I'll cook something up :)

**Review by mardy — APPROVED** [review]

**Comment by alexmurray** [comment]
I've started looking at implementing snapd-apparmor in Go, and will have this then use the correct apparmor_parser and command-line arguments etc - will post something for review in the next day. But let me know if you want this to go in another direction and I can change course.

**Review by bboozzoo — APPROVED** [review]
Thanks

**Comment by bboozzoo** [comment]
> I've started looking at implementing snapd-apparmor in Go, and will have this then use the correct apparmor_parser and command-line arguments etc - will post something for review in the next day. But let me know if you want this to go in another direction and I can change course.

I figure that even when implemented in Go the resulting binary should be of reasonable size since it's basically stdlib only.

**Comment by anonymouse64** [comment]
So I figured out the reason we didn't catch this regression until after it was merged to edge/master. All of our tests do re-build snapd in order to test it, and indeed there were tests that the PR in question broke at various points in time, so indeed the Go code changes inside snapd were made and tested correctly, but critically only the changes for almost every test "monkey-patch" the changes from the deb into the snapd snap and core snap we use everywhere instead of building and using the snapd snap that is built from the branch. The only test that doesn't do this is actually the snapd-snap spread test which was extended as part of said PR, but critically that does not trigger snapd-apparmor to run when we install the new snapd snap, even though it does trigger a new system-key to be written and thus new apparmor profiles to be compiled.

So we need to think about what we should do, but I think it would go a long way to work on finally implementing a mechanism to consume the snapd snap we build as part of the CI tests in spread tests instead of this monkey-patching the deb into the snap which works for almost all the time except crucially this specific instance.

@alexmurray in the short term to get proper coverage I think you should extend the snapd-snap spread test after all the existing checks we do there to either:
1. (simple) just do `systemctl restart snapd.apparmor.service`, when I do this the test fails on 9939 for me
2. (hard) stop snapd, wipe the system-key from the system, and reboot via SPREAD_REBOOT and make sure that the system comes back up happy, etc. This will be more work but is probably more realistic

@pedronis it would still be great if you could comment on the suggested direction to take snapd-apparmor, I think reimplementing it in Go makes sense but would be great to get your opinion

**Comment by alexmurray** [comment]
@anonymouse64 I was planning to do the simple option `systemctl restart snapd.apparmor.service` already since that is an easy win for the PR. I also think we should do the hard option too so will spend some time looking into that as well. Thanks for the guidance.

**Comment by alexmurray** [comment]
Ok see #11096 where I have ported snapd-apparmor to Go and added some tests for it, plus updated the snapd-snap spread test to restart `snapd.apparmor.service` to ensure this is tested and still works as a result (ie. the easy option @anonymouse64 mentioned above).

**Pull request merged**
