### PR TITLE
sysconfig/cloudinint: accept exit status 2 as not an error

### PR DESCRIPTION
**Pull request by valentindavid**

### CODE REVIEW

**Comment by valentindavid** [comment]
See https://manpages.ubuntu.com/manpages/noble/en/man1/cloud-init.1.html

> 2 - Recoverable error - Cloud-init completed but experienced errors.

**Review by alfonsosanchezbeato — APPROVED** [review]
LGTM, thanks - maybe it is worth though to add a log entry saying that cloud-init finished with recoverable error status.

**Comment by valentindavid** [comment]
Yes, but did not we want to stop the log spam? Should I put it in debug?

**Review by sergiocazzolato — APPROVED** [review]
thanks

**Comment by alfonsosanchezbeato** [comment]
> Yes, but did not we want to stop the log spam? Should I put it in debug?

One entry hopefully is not considered spam :slightly_smiling_face:

**Comment by Meulengracht** [comment]
Does it keep checking `cloud-init status` when CloudInitDone is returned? In that case no log message. But that would sound like a flow issue as well?

**Comment by valentindavid** [comment]
@alfonsosanchezbeato Done.

**Comment by alfonsosanchezbeato** [comment]
> @alfonsosanchezbeato Done.

Thank you!

**Pull request merged**
