### PR TITLE
bootloader/assets/data/grub-recovery.cfg: set root when chainloading

### PR DESCRIPTION
**Pull request by valentindavid**
Upstream grub does not pass to LoadImage the correct path to the
loaded binary. This results in second grub not knowing where it was
loaded from and loading the wrong grub.cfg. If we set "root", then the
path becomes correct.

Currently in mantic, the Ubuntu patch that used to be applied to 2.06
is not applied to 2.12. So we are we are back to upstream behavior.

The common use case for chainloading in EFI with grub (see
30_os-prober) always sets root. So we should do it and not get broken
again.

### CODE REVIEW

**Review by alfonsosanchezbeato — COMMENTED** [review]
Do we need to do the same in the other cases where chainloader is called in grub-recovery.cfg and grub.cfg? In these other cases you do not chainload to a different partition, but was wondering still...

**Comment by valentindavid** [comment]
> Do we need to do the same in the other cases where chainloader is called in grub-recovery.cfg and grub.cfg? In these other cases you do not chainload to a different partition, but was wondering still...

Correct. `root` is already set. So in those cases we do not need to do anything. Also it would be `set root=$root`, since it is in this variable we know what the boot device is.

**Review by alfonsosanchezbeato — APPROVED** [review]
LGTM, thanks

**Review by olivercalder — APPROVED** [review]
Looks good to me as well, thanks!

**Comment by alfonsosanchezbeato** [comment]
FTR snapd is not updating grub config in the seed partition at the moment, we will need that so we can remodel UC22 -> UC24.

**Pull request merged**
