### PR TITLE
cmd: use libtool for the internal library

### PR DESCRIPTION
**Pull request by morphis**
This just cuts some hassle integration with how the helper library is
built. I could never get to pass the right -fPIC/-fpie combination
otherwise.

Signed-off-by: Zygmunt Krynicki <me@zygoon.pl>

----

Pushing this for further discussion as we ship this patch on other distributions (openSUSE, Fedora) to get snap-confine properly built.

### CODE REVIEW

**Comment by zyga** [comment]
We want to try to integrate this with #3039 - we *need* 3039 so if we can marry them I'm +1000

**Comment by morphis** [comment]
@zyga Can you take this change then and integrate it in your #3039 PR?

**Comment by zyga** [comment]
@morphis I just read your request; sure I'll do it.

**Comment by morphis** [comment]
@zyga Thanks. Closing this PR then.

**Pull request closed without merging**
