### PR TITLE
o/state: Reduce number of days refresh is inhibited from 14 days to 4

### PR DESCRIPTION
**Pull request by robert-ancell**
As shown in updated design:
image-20230712-103620

### CODE REVIEW

**Comment by MiguelPires** [comment]
Hi. Is there a spec for this?

**Comment by pedronis** [comment]
What's the reasoning here, to reduce this to a single digit? Why exactly 4?

**Comment by robert-ancell** [comment]
I'll work on a spec for this getting input from the designers as to why the value should be changed.

**Comment by sergio-costas** [comment]
What about using a setting in snapd? Something like "snap set snapd force-refresh-period XX".

**Comment by sergio-costas** [comment]
I prepared a spec https://docs.google.com/document/d/1ZdKwvu-WRyAKLahFD7Tq_gEAwdt38VBu4KU6w31TZjo and a new MR https://github.com/snapcore/snapd/pull/13485 (I tried to add the changes in this MR, but I had no permissions).

**Comment by pedronis** [comment]
https://github.com/snapcore/snapd/pull/13485 was landed instead. Closing this

**Comment by pedronis** [comment]
https://github.com/snapcore/snapd/pull/13485 was landed instead. Closing this

**Pull request closed without merging**
