### PR TITLE
cmd/snap-repair: integrate root public keys for repairs

### PR DESCRIPTION
**Pull request by pedronis**
The pattern used is similar to what we do in asserts/sysdb.

### CODE REVIEW

**Comment by mvo5** [comment]
We might consider adding a check in the debian/rules like we have for snapd:
```
	[ $$(strings _build/bin/snap-repair|grep -c -E "public-key-sha3-384: [a-zA-Z0-9_-]{64}") -eq 1 ]
        strings _build/bin/snap-repair|grep -c "^public-key-sha3-384: nttW6NfBXI_E-00u38W-KH6eiksfQNXuI7IiumoV49_zkbhM0sYTzSnFlwZC-W4t$
```

**Comment by pedronis** [comment]
@mvo5 yes about the check, should we add it now?   I suppose we can, even if the final packing will change again

**Comment by mvo5** [comment]
@pedronis either way is fine with me, if we add it later we should put it on the todo list in the forum. If we do it now we just need to adjust it when the packaging changes which should be straightforward. But happy to merge as it to move forward.

**Comment by pedronis** [comment]
@mvo5 pushed, I wonder if it makes sense to build snap-repair 14.04, given it's not for core systems, otoh maybe it's a pain not to

**Pull request merged**
