### PR TITLE
interfaces/builtin: allow access to /usr/share/javascript/{sphinxdoc,jquery} and /usr/share/sphinx_rtd_theme

### PR DESCRIPTION
**Pull request by nteodosio**
[LP:2032992](https://launchpad.net/bugs/2032992) reports that documentation cannot be read in browsers because of the lack of allowance for /usr/share/javascript/jquery/.

I opened [a discussion at the Snapcraft forum](https://forum.snapcraft.io/t/documentation-packages-attempt-to-access-usr-share-javascript-but-fail) and was suggested this interface.

Is it the proper one? If yes I'll extend the test file accordingly.

### CODE REVIEW

**Review by alexmurray — APPROVED** [review]
LGTM.

**Comment by nteodosio** [comment]
Thanks for the review. I included extended the test file as promised.

The automated tests check the pull request title, is that really important? I'd expect it to not go beyond the commit title. Anyway, I edited it, but you'll need to manually trigger the test again apparently.

**Comment by lissyx** [comment]
What is missing to land this @nteodosio ?

**Comment by nteodosio** [comment]
I think one more person needs to approve it, judging by the fragment in the reviewers section:

"At least 2 approving reviews are required to merge this pull request."

**Review by zyga — APPROVED** [review]
While the new mount entries look relatively harmless I think there's going to be a point where we need to re-think how such documentation is accessed.

It cannot be extended indefinitely without causing problems to what is in the mount namespace.

**Comment by lissyx** [comment]
e.g., https://bugzilla.mozilla.org/show_bug.cgi?id=1768303

**Comment by Meulengracht** [comment]
@nteodosio please rebase on top of master and resolve conflicts

@zyga let's talk about this at the upcoming sprint

**Comment by Meulengracht** [comment]
@nteodosio the unit tests are failing, please handle those

**Comment by ernestl** [comment]
Checked with Nathan, this is low priority and will not be addressed in time for 2.62, moving to 2.63

**Comment by mkaply** [comment]
Can I ask why you consider this low priority? Not being able to read the docs in browsers is kind of important. There's a patch ready to go here.

**Comment by olivercalder** [comment]
I've rebased on master to pull in the latest changes, and I added the missing tests for the mount spec.

**Comment by olivercalder** [comment]
Pending spread test passage, this should be good to ship with 2.62.

**Comment by nteodosio** [comment]
> Can I ask why you consider this low priority? Not being able to read the docs in browsers is kind of important.

I meant there were higher priority items on my list and that I'd look into it today or tomorrow. Thanks Oliver for taking care of it!

**Review by Meulengracht — APPROVED** [review]
Thank you, LGTM

**Pull request merged**
