### PR TITLE
interfaces/builtin: add TOKEN2 FIDO2 u2fdevice

### PR DESCRIPTION
**Pull request by RomanNovacek**
Adding Token2 FIDO2 key

### CODE REVIEW

**Review by alexmurray — COMMENTED** [review]
Thanks - so at https://www.token2.com/shop/page/using-token2-fido2-keys-under-linux I can see the `0010` product ID listed but not `0012` - do you know if there is any public documentation that mentions this other product ID?

**Comment by Meulengracht** [comment]
> Adding Token2 FIDO2 key
> 
> Thanks for helping us make a better snapd! Have you signed the [license agreement](https://www.ubuntu.com/legal/contributors) and read the [contribution guide](https://github.com/snapcore/snapd/blob/master/CONTRIBUTING.md)?

Could I ask you to sign the contributor agreement [here](https://ubuntu.com/legal/contributors/agreement)?

**Comment by RomanNovacek** [comment]
My token is detected by Ubunutu as 
```
lsusb | grep TOKEN
Bus 003 Device 056: ID 349e:0012 TOKEN2 FIDO2 Security Key
```
Thats the rason, why I add _0012_.

**Comment by stijnb1234** [comment]
@RomanNovacek Could  you check this out?

**Comment by pedronis** [comment]
closing as per https://github.com/snapcore/snapd/pull/12984

**Pull request closed without merging**
