### PR TITLE
snap: add support for `snap watch --last={revert,enable,disable,switch}`

### PR DESCRIPTION
**Pull request by mvo5**
While looking at our code I noticed that we are a bit inconsistent
in our changeIDMixin about where we accept the "short" form for
a change and where we don't. E.g. for the change type `install-snap`
we support the short form `install` but for others like `revert-snap`
we do not.

This commit unifies this some more and fixes a bug in our testsuite
along the way where we use `snap watch --last=revert?` which does
not work today.

### CODE REVIEW

**Comment by anonymouse64** [comment]
> fixes a bug in our testsuite along the way where we use snap watch --last=revert? which does not work today.

Where was this fixed? I only see a one line change not in any tests?

**Review by mardy — APPROVED** [review]
LGTM!

**Comment by mvo5** [comment]
> > fixes a bug in our testsuite along the way where we use snap watch --last=revert? which does not work today.
> 
> Where was this fixed? I only see a one line change not in any tests?

Sorry, I explained myself badly. We have a place in `tests/core/gadget-kernel-refs-update-pc` that runs `snap watch --last=revert?`. However I do not believe this actually works because there is no change of kind `revert` available (only `revert-snap`). So this works by chance AFAICT today. But with this fix `snap watch --last=revert` will work.

**Review by anonymouse64 — APPROVED** [review]
lgtm, thanks for the explanation too

**Pull request merged**
