### PR TITLE
tests: add minimal smoke test for microstack

### PR DESCRIPTION
**Pull request by mvo5**
Now that we have the microstack interface we want to make sure that
things keep working on our side and not break it accidently. This
commit is a first step to do basic smoke testing.

### CODE REVIEW

**Review by anonymouse64 — APPROVED** [review]
lgtm, should it be nightly though? do we know how long it takes to run?

**Comment by mvo5** [comment]
If night or not is a really good question, the "microstack" init took around 10min for me.

**Comment by mvo5** [comment]
@mardy Thanks, I moved it to main now - I don't think I can remove the 10min because that is how long  `  microstack init --auto --control` takes which we can't avoid AIUI or the subsequent commands will not run (?).

**Review by mardy — APPROVED** [review]
LGTM! We can always move it later if needed.

**Comment by mvo5** [comment]
Looks like this found the first issue already:
```
2021-09-14T10:54:24.6601231Z ##[error]2021-09-14 10:54:24 Error executing google:ubuntu-20.04-64:tests/main/microstack-smoke (sep141044-825318) : 
2021-09-14T10:54:24.6629394Z -----
2021-09-14T10:54:24.6630284Z + echo 'Init microstack'
2021-09-14T10:54:24.6631962Z Init microstack
2021-09-14T10:54:24.6632907Z + microstack init --auto --control
2021-09-14T10:54:24.6636052Z 2021-09-14 10:54:18,082 - microstack_init - INFO - Configuring clustering ...
2021-09-14T10:54:24.6637794Z 2021-09-14 10:54:18,200 - microstack_init - INFO - Setting up as a control node.
2021-09-14T10:54:24.6639067Z 2021-09-14 10:54:21,903 - microstack_init - INFO - Configuring networking ...
2021-09-14T10:54:24.6674348Z Traceback (most recent call last):
2021-09-14T10:54:24.6675297Z   File "/snap/microstack/233/bin/microstack", line 11, in <module>
2021-09-14T10:54:24.6676656Z     load_entry_point('microstack==0.0.1', 'console_scripts', 'microstack')()
2021-09-14T10:54:24.6677915Z   File "/snap/microstack/233/lib/python3.8/site-packages/microstack/main.py", line 44, in main
2021-09-14T10:54:24.6678743Z     cmd()
2021-09-14T10:54:24.6679739Z   File "/snap/microstack/233/lib/python3.8/site-packages/init/main.py", line 60, in wrapper
2021-09-14T10:54:24.6680793Z     return func(*args, **kwargs)
2021-09-14T10:54:24.6681874Z   File "/snap/microstack/233/lib/python3.8/site-packages/init/main.py", line 227, in init
2021-09-14T10:54:24.6682702Z     question.ask()
2021-09-14T10:54:24.6683745Z   File "/snap/microstack/233/lib/python3.8/site-packages/init/questions/question.py", line 210, in ask
2021-09-14T10:54:24.6684509Z     self.yes(awr)
2021-09-14T10:54:24.6685537Z   File "/snap/microstack/233/lib/python3.8/site-packages/init/questions/__init__.py", line 189, in yes
2021-09-14T10:54:24.6686493Z     enable('ovs-vswitchd')
2021-09-14T10:54:24.6687581Z   File "/snap/microstack/233/lib/python3.8/site-packages/init/shell.py", line 162, in enable
2021-09-14T10:54:24.6688873Z     check('snapctl', 'start', 'microstack.{}'.format(service), '--enable')
2021-09-14T10:54:24.6690087Z   File "/snap/microstack/233/lib/python3.8/site-packages/init/shell.py", line 69, in check
2021-09-14T10:54:24.6691349Z     raise subprocess.CalledProcessError(proc.returncode, " ".join(args))
2021-09-14T10:54:24.6693283Z subprocess.CalledProcessError: Command 'snapctl start microstack.ovs-vswitchd --enable' returned non-zero exit status 1.
```

**Comment by mvo5** [comment]
This is blocked right now because the microstack snap has no "microstack-support" plug yet because there is no snapd released that supports it. The plan of action is:

1) snapd with microstack-support is released;
2) https://review.opendev.org/c/x/microstack/+/807570 is merged, tested against latest/stable snapd;
3) microstack is released into latest/edge;
4) snapd smoke checks for latest/edge microstack re-enabled;
5) ... latest/beta microstack is released after some time to give the users' snapd estate to update

So I'm closing this one for now until a new version of the snap is available.

**Pull request closed without merging**
