### PR TITLE
static tests: add spell check

### PR DESCRIPTION
**Pull request by elopio**

### CODE REVIEW

**Comment by zyga** [comment]
Looks interesting nad there is a lot of value in the fixed words and sentences. Please have a look at the test failure. It seem to fail because GOBIN is not set

**Comment by elopio** [comment]
@zyga done.

**Comment by mvo5** [comment]
Fun! I like it :+1: - would be great if you could merge master in so that we get a run in the autopkgtest environment as well.

**Comment by elopio** [comment]
Ok, this is ready. Please don't make any more typos so it can land :)

**Comment by mvo5** [comment]
@elopio Thanks! it needs a second review to land, lets see if someone gets to it today :)

**Pull request merged**
