### PR TITLE
tests: remove old ubuntu-core-transition nightly tests

### PR DESCRIPTION
**Pull request by sergiocazzolato**
These old tests are failing on nightly run since the new shared-memory
interface was added.

The idea is to remove them as those are very old and shouldn't represent
a usefull scenario currently

+ snap download --edge ubuntu-core
Fetching snap "ubuntu-core"
Fetching assertions for "ubuntu-core"
Install the snap with:
   snap ack ubuntu-core_1797.assert
   snap install ubuntu-core_1797.snap
+ snap ack ./ubuntu-core_1797.assert
+ snap install ./ubuntu-core_1797.snap
error: cannot perform the following tasks:
- Mount snap "ubuntu-core" (1797) (installation not allowed by
"shared-memory" slot rule of interface "shared-memory")

### CODE REVIEW

**Comment by sergiocazzolato** [comment]
@mvo, could you please validate if my assumption is correct?
Thanks

**Comment by bboozzoo** [comment]
The branch has conflicts now. Do you have a log of a failed test?

**Comment by sergiocazzolato** [comment]
@bboozzoo, this is solved now

**Review by bboozzoo — APPROVED** [review]
LGTM

**Review by MiguelPires — APPROVED** [review]
LGTM

**Pull request merged**
