### PR TITLE
data/selinux: allow messages from policykit

### PR DESCRIPTION
**Pull request by bboozzoo**
snapd talks to polkitd over DBus and calls
org.freedesktop.PolicyKit1.Authority.CheckAuthorization() method. The default
SELinux policy prevents polkitd from sending a reply back to snapd.

Resolves: https://forum.snapcraft.io/t/selinux-blocking-snapd-since-update-on-fedora-27/3002

Quoting dbus-daemon manual (SELinux section):

  > First, any time a message is routed from one connection to another connection,
  > the bus daemon will check permissions with the security context of the first
  > connection as source, security context of the second connection as target,
  > object class "dbus" and requested permission "send_msg".

The change adds adjusts the policy to allow DBus messages (dbus send_msg) to be
sent from processes with type polkit_t (polkitd) to processes with type
snappy_t (snapd).

@Conan-Kudo this affects the SELinux policy files.

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
@bboozzoo It looks good to me, but is there any need for a corresponding policy declaration for receiving messages and for `snappy_t` to send messages?

**Comment by Conan-Kudo** [comment]
@bboozzoo Can you please bump the version of the snapd-selinux policy? https://github.com/snapcore/snapd/blob/master/data/selinux/snappy.te#L20

**Comment by bboozzoo** [comment]
Bumped the policy version to 0.0.13

> @bboozzoo It looks good to me, but is there any need for a corresponding policy declaration for snappy_t to send messages?

I went through https://github.com/fedora-selinux/selinux-policy-contrib and the pattern is to use `optional_policy` and a `*_dbus_chat` interface, eg. `policykit_dbus_chat(<yourtype_t>)`. Fixed this accordingly.

**Comment by Conan-Kudo** [comment]
🎉

**Comment by Conan-Kudo** [comment]
@mvo5 Can you make sure to cherry-pick this back into 2.30 branch?

**Pull request merged**
