### PR TITLE
interfaces: add new u2f token2 security keys

### PR DESCRIPTION
**Pull request by token2**
Token2 is planning the launch of three new security keys, which will feature OpenPGP applets accessible via USB. These keys use a different set of PID (depending on transport combination) that need to be recognized by snapd

Thanks for helping us make a better snapd!
Have you signed the [license agreement](https://www.ubuntu.com/legal/contributors) and read the [contribution guide](https://github.com/snapcore/snapd/blob/master/CONTRIBUTING.md)?

### CODE REVIEW

**Review by token2 — COMMENTED** [review]
Signed the agreement

**Review by zyga — APPROVED** [review]
Looks reasonable to me

**Review by ernestl — APPROVED** [review]
Thanks

**Review by jslarraz — APPROVED** [review]
LGTM

**Pull request merged**
