### PR TITLE
interfaces: add pcscd interface

### PR DESCRIPTION
**Pull request by nteodosio**
To access smart cards under a snapped program ([bug 1843392][1]), we need to allow it to communicate with the reader drivers via the pcscd socket.

This has already been discussed with the security team as the comment #1 in the linked bug report describes.

To create this interface I simply copied jack1.go and changed the appropriate parts.

[1]: https://bugs.launchpad.net/ubuntu/+source/firefox/+bug/1843392

### CODE REVIEW

**Review by alexmurray — APPROVED** [review]
LGTM for the simple purpose of this interface.

**Review by mvo5 — COMMENTED** [review]
This looks good but needs a quick double check from Samuele for awareness and for ensuring the naming is consistent.

**Review by mvo5 — APPROVED** [review]
Thanks, but please consider updating the summary as Samuele suggested.

**Comment by nteodosio** [comment]
Thanks for the suggestion, I incorporated the proposed change.

**Pull request merged**
