### PR TITLE
cmd/snap: allow snap help vs --all to diverge purposefully

### PR DESCRIPTION
**Pull request by pedronis**
this allows two things:

  * for some commands (and possibly entire categories) to appear only
    under `snap help --all`
  * to split in precise categories the commands that appear under
    "...Other" (now) in `snap help`

it makes "snap debug" not hidden anymore and makes it appear under --all.

### CODE REVIEW

**Comment by pedronis** [comment]
based on #9399

**Comment by pedronis** [comment]
@degville , @mvo5 this are the enhancement for "snap help" vs "snap help --all" that we discussed.  Output is like this:

```
$snap help
The snap command lets you install, configure, refresh and remove snaps.
Snaps are packages that work across many different Linux distributions,
enabling secure delivery and operation of the latest apps and utilities.

Usage: snap <command> [<options>...]

Commands can be classified as follows:

           Basics: find, info, install, remove, list
          ...more: refresh, revert, switch, disable, enable
          History: changes, tasks, abort, watch
          Daemons: services, start, stop, restart, logs
      Permissions: connections, interface, connect, disconnect
    Configuration: get, set, unset, wait
      App Aliases: alias, aliases, unalias, prefer
          Account: login, logout, whoami
        Snapshots: saved, save, check-snapshot, restore, forget
           Device: model, reboot, recovery
         ...Other: warnings, okay, known, ack, version
      Development: download, pack, run, try

For more information about a command, run 'snap help <command>'.
For a short summary of all commands, run 'snap help --all'.
```

```
$ snap help --all
The snap command lets you install, configure, refresh and remove snaps.
Snaps are packages that work across many different Linux distributions,
enabling secure delivery and operation of the latest apps and utilities.

Usage: snap <command> [<options>...]

Commands can be classified as follows:


  Basics (basic snap management):
    find            Find packages to install
    info            Show detailed information about snaps
    install         Install snaps on the system
    remove          Remove snaps from the system
    list            List installed snaps

  ...more (slightly more advanced snap management):
    refresh         Refresh snaps in the system
    revert          Reverts the given snap to the previous state
    switch          Switches snap to a different channel
    disable         Disable a snap in the system
    enable          Enable a snap in the system

  History (manage system change transactions):
    changes         List system changes
    tasks           List a change's tasks
    abort           Abort a pending change
    watch           Watch a change in progress

  Daemons (manage services):
    services        Query the status of services
    start           Start services
    stop            Stop services
    restart         Restart services
    logs            Retrieve logs for services

  Permissions (manage permissions):
    connections     List interface connections
    interface       Show details of snap interfaces
    connect         Connect a plug to a slot
    disconnect      Disconnect a plug from a slot

  Configuration (system administration and configuration):
    get             Print configuration options
    set             Change configuration options
    unset           Remove configuration options
    wait            Wait for configuration

  App Aliases (manage aliases):
    alias           Set up a manual alias
    aliases         List aliases in the system
    unalias         Remove a manual alias, or the aliases for an entire snap
    prefer          Enable aliases from a snap, disabling any conflicting aliases

  Account (authentication to snapd and the snap store):
    login           Authenticate to snapd and the store
    logout          Log out of snapd and the store
    whoami          Show the email the user is logged in with

  Snapshots (archives of snap data):
    saved           List currently stored snapshots
    save            Save a snapshot of the current data
    check-snapshot  Check a snapshot
    restore         Restore a snapshot
    forget          Delete a snapshot

  Device (manage device):
    model           Get the active model for this device
    reboot          Reboot into selected system and mode
    recovery        List available recovery systems

  Special Purpose (special activities):
    create-cohort   Create cohort keys for a set of snaps
    prepare-image   Prepare a device image

  Warnings (manage warnings):
    warnings        List warnings
    okay            Acknowledge warnings

  Assertions (manage assertions):
    known           Show known assertions of the provided type
    ack             Add an assertion to the system

  Introspection (introspection and debugging):
    version         Show version details
    debug           Run debug commands

  Development (developer-oriented features):
    download        Download the given snap
    pack            Pack the given directory as a snap
    run             Run the given snap command
    try             Test an unpacked snap in the system

For more information about a command, run 'snap help <command>'.
```

@degville the last line of "snap help" maybe needs clarifying somehow that some commands will be only in "snap help --all" perhpas ?  Also open to suggestions for "Special Purpose (special activities):..."

**Review by degville — APPROVED** [review]
Thanks Samuele. This all looks good to me. A couple of non-essential suggestions...

>           ...more: refresh, revert, switch, disable, enable
>          ...Other: warnings, okay, known, ack, version

I like the additional ellipses. Maybe use lowercase _O_ for `...other` for consistency?  

> Commands can be classified as follows:

I know it adds programming complexity, but I think the above line should be the focus for mentioning `snap help` only showing the most commonly used commands, eg: `Commonly used commands can be classified as follows:`

**Comment by pedronis** [comment]
> I like the additional ellipses. Maybe use lowercase O for ...other for consistency?

I kept the capital case, because in the case of "...more" is continues/expands the previous category. While in the case of "...Other" it's a new standalone set of commands. Too idiosyncratic perhaps?

> I know it adds programming complexity, but I think the above line should be the focus for mentioning snap help only showing the most commonly used commands, eg: Commonly used commands can be classified as follows:

no, it's fine and answers my question. I will do that.

**Comment by degville** [comment]
> I kept the capital case, because in the case of "...more" is continues/expands the previous category. While in the case of "...Other" it's a new standalone set of commands. Too idiosyncratic perhaps?

No, I think you're right. I'm being pedantic.

```
  Special Purpose (special activities):
    create-cohort   Create cohort keys for a set of snaps
    prepare-image   Prepare a device image
```
I think this is good too. I do think there's probably a better term for these commands, but I can't think of it (yet!). Another thing we should maybe consider (for a future PR) is that I don't think we should repeat words from the category name in the descriptive extra words we put in brackets.

**Comment by pedronis** [comment]
@degville @mvo5 , another solution for

>  Special Purpose (special activities):

is to add 'prepare-image' to development in "snap help --all" only  and add create-cohort at the end of "...more" only there as well

**Review by stolowski — COMMENTED** [review]
Looks fine, but one comment about introspection category. Also, I think debug should be made visible. Thank you

**Comment by pedronis** [comment]
@degville and @stolowski  I applied some improvements based on your feedback in https://github.com/snapcore/snapd/pull/9424/commits/ecaeb33193510c97d6d79d5745ee75310cc19aa7 (sorry for the force push I added already rebased locally before Pawel commented)

current outputs:

```
$ ./snap help
The snap command lets you install, configure, refresh and remove snaps.
Snaps are packages that work across many different Linux distributions,
enabling secure delivery and operation of the latest apps and utilities.

Usage: snap <command> [<options>...]

Commonly used commands can be classified as follows:

         Basics: find, info, install, remove, list
        ...more: refresh, revert, switch, disable, enable, create-cohort
        History: changes, tasks, abort, watch
        Daemons: services, start, stop, restart, logs
    Permissions: connections, interface, connect, disconnect
  Configuration: get, set, unset, wait
    App Aliases: alias, aliases, unalias, prefer
        Account: login, logout, whoami
      Snapshots: saved, save, check-snapshot, restore, forget
         Device: model, reboot, recovery
      ... Other: warnings, okay, known, ack, version
    Development: download, pack, run, try

For more information about a command, run 'snap help <command>'.
For a short summary of all commands, run 'snap help --all'.
```

```
$ ./snap help --all
The snap command lets you install, configure, refresh and remove snaps.
Snaps are packages that work across many different Linux distributions,
enabling secure delivery and operation of the latest apps and utilities.

Usage: snap <command> [<options>...]

Commands can be classified as follows:


  Basics (basic snap management):
    find            Find packages to install
    info            Show detailed information about snaps
    install         Install snaps on the system
    remove          Remove snaps from the system
    list            List installed snaps

  ...more (slightly more advanced snap management):
    refresh         Refresh snaps in the system
    revert          Reverts the given snap to the previous state
    switch          Switches snap to a different channel
    disable         Disable a snap in the system
    enable          Enable a snap in the system
    create-cohort   Create cohort keys for a set of snaps

  History (manage system change transactions):
    changes         List system changes
    tasks           List a change's tasks
    abort           Abort a pending change
    watch           Watch a change in progress

  Daemons (manage services):
    services        Query the status of services
    start           Start services
    stop            Stop services
    restart         Restart services
    logs            Retrieve logs for services

  Permissions (manage permissions):
    connections     List interface connections
    interface       Show details of snap interfaces
    connect         Connect a plug to a slot
    disconnect      Disconnect a plug from a slot

  Configuration (system administration and configuration):
    get             Print configuration options
    set             Change configuration options
    unset           Remove configuration options
    wait            Wait for configuration

  App Aliases (manage aliases):
    alias           Set up a manual alias
    aliases         List aliases in the system
    unalias         Remove a manual alias, or the aliases for an entire snap
    prefer          Enable aliases from a snap, disabling any conflicting aliases

  Account (authentication to snapd and the snap store):
    login           Authenticate to snapd and the store
    logout          Log out of snapd and the store
    whoami          Show the email the user is logged in with

  Snapshots (archives of snap data):
    saved           List currently stored snapshots
    save            Save a snapshot of the current data
    check-snapshot  Check a snapshot
    restore         Restore a snapshot
    forget          Delete a snapshot

  Device (manage device):
    model           Get the active model for this device
    reboot          Reboot into selected system and mode
    recovery        List available recovery systems

  Warnings (manage warnings):
    warnings        List warnings
    okay            Acknowledge warnings

  Assertions (manage assertions):
    known           Show known assertions of the provided type
    ack             Add an assertion to the system

  Introspection (introspection and debugging of snapd):
    version         Show version details
    debug           Run debug commands

  Development (developer-oriented features):
    download        Download the given snap
    pack            Pack the given directory as a snap
    run             Run the given snap command
    try             Test an unpacked snap in the system
    prepare-image   Prepare a device image

For more information about a command, run 'snap help <command>'.
```

**Comment by pedronis** [comment]
I fixed as well the extra blank line here (it existed on master already):

```
Commands can be classified as follows:

  <---- oops
  Basics (basic snap management):
```

**Review by stolowski — APPROVED** [review]
Looks good, thank you

**Comment by degville** [comment]
Looks good to me too - thanks for updating this. :+1:

**Review by mvo5 — APPROVED** [review]

**Pull request merged**
