### PR TITLE
build-aux,.github/workflows: limit make processes with nproc

### PR DESCRIPTION
**Pull request by alfonsosanchezbeato**
Limit the number of processes created by make by using the value returned by nproc, so it adapts to the device it is running on.

### CODE REVIEW

**Review by mvo5 — APPROVED** [review]
Thank you

**Review by MiguelPires — APPROVED** [review]
LGTM

**Comment by MiguelPires** [comment]
@alfonsosanchezbeato this has a conflict

**Comment by alfonsosanchezbeato** [comment]
> @alfonsosanchezbeato this has a conflict

Rebased now, thanks for the heads up!

**Pull request merged**
