### PR TITLE
tests: small adjustments to fix vuln spread tests

### PR DESCRIPTION
**Pull request by anonymouse64**
Small fixes that should help address some of the failures of the new spread tests that were added with 2.54.3.

The individual commit messages have descriptions of the changes.

### CODE REVIEW

**Review by sergiocazzolato — APPROVED** [review]
Thanks for these fixes

**Review by mvo5 — APPROVED** [review]
Thank you

**Review by mardy — APPROVED** [review]
LGTM!

**Comment by anonymouse64** [comment]
I realized just now that 3f896f5ffc0afc3fdcc3d310e5cd54a632175033 is entirely unneeded so I will force push it out of existence here, this is a small PR so hopefully that is not too inconvenient to folks to re-review this

**Comment by anonymouse64** [comment]
hmm `google:ubuntu-16.04-64:tests/main/snap-run-devmode-classic:snapd_first` is still failing, but the other mentioned tests in this PR are happy so I think this can go in under the premise it doesn't make things worse even if it doesn't fully solve all the issues :-)

**Review by bboozzoo — APPROVED** [review]
Thanks

**Review by mardy — APPROVED** [review]
LGTM!

**Review by sergiocazzolato — APPROVED** [review]
Nice, thanks for those improvements

**Pull request merged**
