### PR TITLE
snapcraft.yaml: add workaround for LP:#1791871

### PR DESCRIPTION
**Pull request by mvo5**
The snapcraft building currently fails with a strange error. This
is probably bug https://bugs.launchpad.net/snapcraft/+bug/1791871

This PR adds a workaround for this.

### CODE REVIEW

**Comment by sparkiegeek** [comment]
LGTM :+1:

**Comment by mvo5** [comment]
Hm, it looks like this workaround does not actually work :(
```
+ snapcraft
DEPRECATED: Custom plugins should now be placed in 'snap/plugins'.
See http://snapcraft.io/docs/deprecation-notices/dn2 for more information.
Searching for local plugin for x-builddeb
DEPRECATED: Custom plugins should now be placed in 'snap/plugins'.
See http://snapcraft.io/docs/deprecation-notices/dn2 for more information.
Pulling snapd 
fatal: repository '.' does not exist
```

**Comment by sparkiegeek** [comment]
:pensive: using `snapcraft` from beta on snapd master (i.e. without this fix but with https://github.com/snapcore/snapcraft/pull/2256 ), I get past this failure but then hit a `govendor` issue (probably because Go has strict rules about where it wants to be in my home directory which I disagree with)

**Comment by bboozzoo** [comment]
Still no luck.
```
+ snapcraft
DEPRECATED: Custom plugins should now be placed in 'snap/plugins'.
See http://snapcraft.io/docs/deprecation-notices/dn2 for more information.
Searching for local plugin for x-builddeb
DEPRECATED: Custom plugins should now be placed in 'snap/plugins'.
See http://snapcraft.io/docs/deprecation-notices/dn2 for more information.
Sorry, Snapcraft ran into an error when trying to running through its
lifecycle that generated a trace that has been put in '/tmp/tmpcdsfeu0t/trace.txt'.
"Submitting this error to the Snapcraft developers is not possible through the CLI
without Raven installed.
If you wish to report this issue, please copy the contents of the previous traceback
and submit manually at https://launchpad.net/snapcraft/+filebug.
-----
```

**Pull request merged**
