### PR TITLE
tests/nested/manual/minimal-smoke: use 384MB of RAM for nested UC20

### PR DESCRIPTION
**Pull request by bboozzoo**
LP#1878541 is fixed, revert to using the same amount of memory for all variants
of Ubuntu Core.

### CODE REVIEW

**Comment by bboozzoo** [comment]
The grub bug may be fixed, but I'm still seeing this:
Screenshot from 2020-09-28 10-28-34

**Review by zyga — APPROVED** [review]
LGTM if it passes

**Comment by bboozzoo** [comment]
Filed https://bugs.launchpad.net/snapd/+bug/1897533 for pc-kernel.

**Comment by sergiocazzolato** [comment]
This is the error in the log, so the issue is not fixed yet on edge.

3hBdsDxe: loading Boot0002 "UEFI Misc Device" from PciRoot(0x0)/Pci(0x5,0x0)
BdsDxe: starting Boot0002 "UEFI Misc Device" from PciRoot(0x0)/Pci(0x5,0x0)
error: out of resources.


  Failed to boot both default and fallback entries.


Press any key to continue...

GNU GRUB  version 2.04

**Comment by bboozzoo** [comment]
The minimal resources test passed on UC20 with 384MB of RAM. @mvo5 can you land the PR?

**Pull request merged**
