### PR TITLE
tests/fde-on-classic: fix fde sizes

### PR DESCRIPTION
**Pull request by xnox**
Fixup sizes, and add more comments.

### CODE REVIEW

**Review by mardy — APPROVED** [review]
LGTM, thanks!

**Review by alfonsosanchezbeato — COMMENTED** [review]
Thank you - this is fine, but I think some adjustments in sfdisk invocation in https://github.com/snapcore/snapd/blob/master/tests/nested/manual/fde-on-classic/mk-image.sh#L43 are needed.

**Review by alfonsosanchezbeato — APPROVED** [review]
LGTM, thank you! Re-running tests now.

**Comment by alfonsosanchezbeato** [comment]
> @alfonsosanchezbeato @mvo5 are my changes here really breaking all the unit tests in all other cases?

don't think so, maybe rebasing to master will clean up tests a bit

**Pull request merged**
