### PR TITLE
interfaces/u2f-devices: add Solo V2

### PR DESCRIPTION
**Pull request by rolandd**
Add device ID 1209:BEEE for newly released SoloKeys Solo V2, see

    https://github.com/solokeys/solo2-cli/blob/09a4f8edbd43f5b4ffe7e715e05143b9fc815535/README.md

This is needed for my new security key to work with snap-packaged Firefox.

### CODE REVIEW

**Review by alexmurray — APPROVED** [review]
LGTM

**Comment by mardy** [comment]
Thanks Roland, the change looks good!

Can you please sign the [contributor's agreement](https://ubuntu.com/legal/contributors)? Or if you did already, it may be that you need to amend the commit and use the same author e-mail address that you used to sign the agreement.

**Review by bboozzoo — APPROVED** [review]
Thank you

**Comment by rolandd** [comment]
I did sign the contributor agreement but did not accept the invite to CanonicalContributorAgreement github org.  Did that now.

**Pull request merged**
