### PR TITLE
add mir to implicit for running gui snaps on unity8 classic desktop

### PR DESCRIPTION
**Pull request by kgunnfront**
adding this will enable folks to create snaps for apps on unity8, which helps converge the untiy8 desktop as a daily driver with the snap world

### CODE REVIEW

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by niemeyer** [comment]
Do we want mir to show up in 16.04?

**Comment by kgunnfront** [comment]
@niemeyer well, Mir is in main and has been for a long time (since 14.10 I think), unity8 desktop experience is in universe and we're working on placing unity8 in main for 16.10. Even without unity8-desktop, Mir can run on  top of X actually (it's a tinker toy :) Do you foresee a problem or a risk of making the interface part of implicit classic?

**Comment by niemeyer** [comment]
@kgunnfront It would feel slightly more polished to only expose that interface on systems that can actually run mir, but I don't have a big reason to block this either.

**Comment by niemeyer** [comment]
@kgunn Sorry, but this will conflict once more once #1871 goes in. Luckily, though, the point of that PR is precisely to kill these repetitive conflicts due to dumb number bumping. Can you please merge @zyga's branch into this one, so that we can get both in without conflicts? I'm just waiting for tests to finish there before merging it.

@jdstrand There are some new changes here about /run/udev. I assume these are fine too?

**Comment by kgunnfront** [comment]
apologies, i forgot i had this PR open. I need to remove the mir implicit portion and limit the PR to only the addition of the /run/udev/data paths

**Pull request closed without merging**
