### PR TITLE
interfaces: add flipper zero to u2f devices under existing STMicro based products

### PR DESCRIPTION
**Pull request by ikilledmypc**
Instead of adding it as a new device I added it under the existing entry for STMicroelectronics based devices which use the same VendorID for STM

### CODE REVIEW

**Review by alexmurray — APPROVED** [review]
LGTM

**Review by mvo5 — APPROVED** [review]
Thank you

**Comment by ikilledmypc** [comment]
I tried fixing the checks by amending the author of the commit to change the email used from my work email to my private one linked to my launchpad account. However now I can't see why the other checks failed since it reset :(

**Comment by mvo5** [comment]
> I tried fixing the checks by amending the author of the commit to change the email used from my work email to my private one linked to my launchpad account. However now I can't see why the other checks failed since it reset :(

Could you please double check that you signed the CLA under https://ubuntu.com/legal/contributors ? It looks like the check fails with: `- timsmeets@rocketmail.com ✕ (has not signed the CLA)`

**Review by olivercalder — APPROVED** [review]
LGTM

**Pull request merged**
