### PR TITLE
t/m/snapd-homedirs-vendored: disable on 23+, snapd is too new

### PR DESCRIPTION
**Pull request by Meulengracht**
On mantic, the snapd deb is version 2.60.3 which is post-vendored apparmor. The test, which is actually a regression test, verifies that on systems where we have an older snapd (pre vendored apparmor) deb package, and the snap itself is upgraded to vendored apparmor, apparmor snippets continue to work.

Thus there is no reason to test the upgrade path from non-vendored to vendored on mantic.

### CODE REVIEW

**Review by ZeyadYasser — COMMENTED** [review]
Thank you for the PR! Just a small question, can't we install older snapd revision through snap store instead of apt?
I saw a similar approach [here](https://github.com/snapcore/snapd/pull/13119/files#diff-eded40ab2594bdc6dd09baf899cefc3167010bc497eed7058256fce957ebda62R27) by @sergiocazzolato. I might be missing something here of course.

**Comment by Meulengracht** [comment]
> Thank you for the PR! Just a small question, can't we install older snapd revision through snap store instead of apt? I saw a similar approach [here](https://github.com/snapcore/snapd/pull/13119/files#diff-eded40ab2594bdc6dd09baf899cefc3167010bc497eed7058256fce957ebda62R27) by @sergiocazzolato. I might be missing something here of course.

AFAIK we have to use the older version of the deb, as the

**Comment by Meulengracht** [comment]
> Thank you for the PR! Just a small question, can't we install older snapd revision through snap store instead of apt? I saw a similar approach [here](https://github.com/snapcore/snapd/pull/13119/files#diff-eded40ab2594bdc6dd09baf899cefc3167010bc497eed7058256fce957ebda62R27) by @sergiocazzolato. I might be missing something here of course.

The issue was when we upgraded to a newer snapd snap which has the vendored apparmor, but while using an older deb package. This resulted in the wrong apparmor_parser being used. So if the deb package is newer than when we started to ship vendored apparmor (or that version), AFAIU then it's not relevant

**Review by ZeyadYasser — APPROVED** [review]
LGTM, Thank you!

**Comment by pedronis** [comment]
do we understand the error:

```
2023-09-14T01:52:34.2065213Z + sudo -u home-sweet-home -i test-snapd-sh.cmd echo 'Hello world'
2023-09-14T01:52:34.2065722Z + MATCH 'Sorry, home directories outside of /home needs configuration'
2023-09-14T01:52:34.2066160Z grep error: pattern not found, got:
2023-09-14T01:52:34.2066742Z cannot perform operation: mount --rbind /dev /tmp/snap.rootfs_md2fhi//dev: No such file or directory
```

it seems related to some mimatch, but not clear it relates directly to vendoring or homedirs?

**Comment by Meulengracht** [comment]
> --rbind

Yea, this comes from this issue:

```
Sep 14 14:28:14 sep141332-995569 snapd[127504]: snapmgr.go:384: cannot read snap info of snap "core" at revision 16176: cannot find installed snap "core" at revision 16176: missing file /snap/core/16176/meta/snap.yaml
Sep 14 14:28:14 sep141332-995569 snapd[127504]: snapmgr.go:384: cannot read snap info of snap "core" at revision 16176: cannot find installed snap "core" at revision 16176: missing file /snap/core/16176/meta/snap.yaml
Sep 14 14:28:14 sep141332-995569 snapd[127504]: backends.go:58: AppArmor status: apparmor is enabled and all features are available (using snapd provided apparmor_parser)
Sep 14 14:28:14 sep141332-995569 snapd[127504]: helpers.go:137: cannot add snap "core" to interface repository: snap is broken: cannot find installed snap "core" at revision 16176: missing file /snap/core/16176/meta/snap.yaml
Sep 14 14:28:14 sep141332-995569 snapd[127504]: snapmgr.go:384: cannot read snap info of snap "core" at revision 16176: cannot find installed snap "core" at revision 16176: missing file /snap/core/16176/meta/snap.yaml
Sep 14 14:28:14 sep141332-995569 snapd[127504]: snapmgr.go:384: cannot read snap info of snap "core" at revision 16176: cannot find installed snap "core" at revision 16176: missing file /snap/core/16176/meta/snap.yaml
Sep 14 14:28:14 sep141332-995569 snapd[127504]: snapmgr.go:384: cannot read snap info of snap "core" at revision 16176: cannot find installed snap "core" at revision 16176: missing file /snap/core/16176/meta/snap.yaml
Sep 14 14:28:14 sep141332-995569 snapd[127504]: snapmgr.go:384: cannot read snap info of snap "core" at revision 16176: cannot find installed snap "core" at revision 16176: missing file /snap/core/16176/meta/snap.yaml
Sep 14 14:28:14 sep141332-995569 snapd[127504]: snapmgr.go:384: cannot read snap info of snap "core" at revision 16176: cannot find installed snap "core" at revision 16176: missing file /snap/core/16176/meta/snap.yaml
Sep 14 14:28:14 sep141332-995569 snapd[127504]: snapmgr.go:384: cannot read snap info of snap "core" at revision 16176: cannot find installed snap "core" at revision 16176: missing file /snap/core/16176/meta/snap.yaml
Sep 14 14:28:14 sep141332-995569 snapd[127504]: snapmgr.go:384: cannot read snap info of snap "core" at revision 16176: cannot find installed snap "core" at revision 16176: missing file /snap/core/16176/meta/snap.yaml
Sep 14 14:28:14 sep141332-995569 snapd[127504]: snapmgr.go:384: cannot read snap info of snap "core" at revision 16176: cannot find installed snap "core" at revision 16176: missing file /snap/core/16176/meta/snap.yaml
Sep 14 14:28:14 sep141332-995569 snapd[127504]: snapmgr.go:384: cannot read snap info of snap "core" at revision 16176: cannot find installed snap "core" at revision 16176: missing file /snap/core/16176/meta/snap.yaml
Sep 14 14:28:14 sep141332-995569 snapd[127504]: snapmgr.go:384: cannot read snap info of snap "core" at revision 16176: cannot find installed snap "core" at revision 16176: missing file /snap/core/16176/meta/snap.yaml
Sep 14 14:28:15 sep141332-995569 snapd[127504]: helpers.go:212: cannot regenerate apparmor profiles
Sep 14 14:28:15 sep141332-995569 snapd[127504]: helpers.go:214: cannot setup profiles for snap "core": cannot create host snap-confine apparmor configuration: cannot compute snap-confine profile: cannot open apparmor profile for vanilla snap-confine: open /snap/core/16176/etc/apparmor.d/usr.lib.snapd.snap-confine: no such file or directory
```

**Comment by mvo5** [comment]
There is definitely something finish going on. The mount for /snap/core/16256/ vanished during the test, this is why we have this error from "test-snapd-sh.cmd". It happens when doing `snap install --dangerous snapd_modified.snap`:
```
...
qemu:ubuntu-23.10-64 .../tests/main/snapd-homedirs-vendored# apt install -yqq --allow-downgrades snapd=2.60.3+23.10.1
...

qemu:ubuntu-23.10-64 .../tests/main/snapd-homedirs-vendored# ls -l /snap/core/16256/
total 0
drwxr-xr-x  2 root root 1975 Sep 27 02:12 bin
...
qemu:ubuntu-23.10-64 .../tests/main/snapd-homedirs-vendored#     snap install --dangerous snapd_modified.snap
2023-09-27T14:08:39+02:00 INFO Waiting for automatic snapd restart...
snapd 2.60.4+git1351.gbbcde77 installed
qemu:ubuntu-23.10-64 .../tests/main/snapd-homedirs-vendored# ls -l /snap/core/16256/
total 0
...
```
The `journalctl -u snapd` output shows that the core snap data cannot be read anymore after the snapd restart.

**Comment by mvo5** [comment]
Another interesting data point:
``
qemu:ubuntu-23.10-64 .../tests/main/snapd-homedirs-vendored# systemctl show snap-core-16256.mount`
...
After=system.slice snap.mount dev-loop0.device snapd.mounts-pre.target blockdev>
```
so the failure 
```
Failed to restart snapd.mounts-pre.target: Operation refused, unit snapd.mounts-pre.target may be requested by dependency only (it is configured to refuse manual start/stop).
```
is most likely causing this?

**Comment by Meulengracht** [comment]
Closing this, this is no longer an issue

**Pull request closed without merging**
