### PR TITLE
interfaces: add the USB-ID of Thetis Fido U2F Key to u2f-devices

### PR DESCRIPTION
**Pull request by gunterkoenigsmann**
The Fido2 Key I just bought from Amazon requires an additional udev rule. Let's add it to the Chromium and Firefox snap.

### CODE REVIEW

**Comment by gunterkoenigsmann** [comment]
This pull request should resolve https://github.com/snapcore/snapd/pull/12466

**Review by mvo5 — APPROVED** [review]
Thank you, this looks fine and is aligned with https://github.com/Yubico/libfido2/blob/main/udev/70-u2f.rules#L153

**Comment by mvo5** [comment]
@gunterkoenigsmann Could you please consider signing the CLA under https://ubuntu.com/legal/contributors so that the CLA check test passes?

**Comment by gunterkoenigsmann** [comment]
I was convinced that I already had signed that agreement what feels to be about 10 Years ago.
Signed it again right now.

**Comment by gunterkoenigsmann** [comment]
@mvo5 : during signing the agreement they asked me to add a contact. Hope "mvo5" was right choice.

**Review by alexmurray — APPROVED** [review]
LGTM from Security!

**Review by Meulengracht — APPROVED** [review]

**Pull request merged**
