### PR TITLE
tests: run spread tests in ubuntu bionic 32bits

### PR DESCRIPTION
**Pull request by sergiocazzolato**
Changes to support running spread tests in ubuntu-18.04-32 system

The idea is then to remove ubuntu-16.04-32 in a following PR

### CODE REVIEW

**Review by mvo5 — APPROVED** [review]
Thank you

**Review by mardy — APPROVED** [review]
LGTM, thanks!

**Comment by sergiocazzolato** [comment]
I see this error, it is the only one for bionic 32bit

2021-07-02 12:31:54 Error executing google:ubuntu-18.04-32:tests/main/snap-run (jul021141-148769) : 
-----
+ echo 'Running a trivial command causes no DENIED messages'
Running a trivial command causes no DENIED messages
+ test-snapd-sh.sh -c 'echo hello'
hello
+ not grep DENIED
+ dmesg
[ 3007.310867] audit: type=1400 audit(1625229114.699:62073): apparmor="DENIED" operation="open" profile="snap-update-ns.test-snapd-sh" name="/sys/devices/system/cpu/online" pid=16689 comm="5" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
[ 3007.311201] audit: type=1400 audit(1625229114.699:62074): apparmor="DENIED" operation="open" profile="snap-update-ns.test-snapd-sh" name="/proc/stat" pid=16689 comm="5" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
[ 3007.311362] audit: type=1400 audit(1625229114.699:62075): apparmor="DENIED" operation="open" profile="snap-update-ns.test-snapd-sh" name="/proc/cpuinfo" pid=16689 comm="5" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
-----

**Comment by sergiocazzolato** [comment]
> I see this error, it is the only one for bionic 32bit
> 
> 2021-07-02 12:31:54 Error executing google:ubuntu-18.04-32:tests/main/snap-run (jul021141-148769) :
> 
> * echo 'Running a trivial command causes no DENIED messages'
>   Running a trivial command causes no DENIED messages
> * test-snapd-sh.sh -c 'echo hello'
>   hello
> * not grep DENIED
> * dmesg
>   [ 3007.310867] audit: type=1400 audit(1625229114.699:62073): apparmor="DENIED" operation="open" profile="snap-update-ns.test-snapd-sh" name="/sys/devices/system/cpu/online" pid=16689 comm="5" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
>   [ 3007.311201] audit: type=1400 audit(1625229114.699:62074): apparmor="DENIED" operation="open" profile="snap-update-ns.test-snapd-sh" name="/proc/stat" pid=16689 comm="5" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
>   [ 3007.311362] audit: type=1400 audit(1625229114.699:62075): apparmor="DENIED" operation="open" profile="snap-update-ns.test-snapd-sh" name="/proc/cpuinfo" pid=16689 comm="5" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
> 
> @bboozzoo any idea?

**Comment by sergiocazzolato** [comment]
Also I see the command 
snap run --strace test-snapd-sh.sh -c 'echo hello-world'
is getting stuck, I could reproduce it manually

**Comment by bboozzoo** [comment]
I suspect it's Go's runtime doing. s-u-n doesn't really care how many CPUs are around.

**Comment by bboozzoo** [comment]
I've investigated a bit, and so far have no clue why those denials are triggered. I can reproduce it when I run the test, but cannot reproduce it on subsequent attempts, even if I manually unload the profiles and confirm they are gone via /sys/kernel/security/apparmor/profiles. Also, they are only triggered when running the snap for the first time, not happening when I discard the mount ns and it's recreated.

**Comment by mvo5** [comment]
Fwiw, this seems to come from glibc-2.27 - https://github.com/bminor/glibc/blob/release/2.27/master/sysdeps/unix/sysv/linux/getsysstats.c#L126 which is used by e.g. sysconf(_SC_NPROCESSORS_ONLN) but it's a bit unclear where this comes from. Golang itself uses the sched_getaffinity syscall to get the amount of cpus (quite cleverly I should add).

**Comment by bboozzoo** [comment]
> Fwiw, this seems to come from glibc-2.27 - https://github.com/bminor/glibc/blob/release/2.27/master/sysdeps/unix/sysv/linux/getsysstats.c#L126 which is used by e.g. sysconf(_SC_NPROCESSORS_ONLN) but it's a bit unclear where this comes from. Golang itself uses the sched_getaffinity syscall to get the amount of cpus (quite cleverly I should add).

Nice find. So the Go source code mentions that on systems with glibc, when creating a new arena for mallock it will poke /sys/devices/system/cpu/online (and actually the other 2 files files if a failure occurs). The question still is, why don't we see this on the 64bit system? I also found this: https://github.com/golang/go/issues/25628#issuecomment-613036233

**Comment by bboozzoo** [comment]
I've updated the snap-update-ns template to allow access only to /sys/devices/system/cpu/online which should make glibc happy again. Please see the commit message for details.

**Comment by bboozzoo** [comment]
Oh, and we already allow `  /sys/devices/system/cpu/** r,` in the base template for snaps, so I don't think we need to involve security for a review of this PR.

**Comment by sergiocazzolato** [comment]
@bboozzoo thanks for the update

**Pull request merged**
