### PR TITLE
vendor: upgrade to godbus v5.0.3

### PR DESCRIPTION
**Pull request by jhenstridge**
This PR upgrades our vendored godbus to the latest tagged release.  New versions use Go Modules style versioning and have changed the import path to `github.com/godbus/dbus/v5`.  We can get similar behaviour with govendor through the use of both the `path` and `origin` keys for the relevant packages.

### CODE REVIEW

**Comment by jhenstridge** [comment]
As expected, this causes problems for distros not using vendored dependencies.  Even for distros shipping recent godbus, they often don't expose it using the new import path.  In particular:

1. Debian has 5.0.3, but is missing the new import path: filed as [bug #974892](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=974892).
2. Fedora's 5.0.3-2 package [adds the new import path](https://src.fedoraproject.org/rpms/golang-github-godbus-dbus/c/7b21b43d4cbc49407c4974560cb7cb10f8b20e19?branch=master), but that only seems to be in Fedora 33 at present.
3. CentOS/Amazon Linux are as above.

**Comment by bboozzoo** [comment]
Thanks, I've filed https://bugzilla.redhat.com/show_bug.cgi?id=1898056 for Fedora. 

> CentOS/Amazon Linux are as above.

Those distros use vendored dependencies.

**Comment by bboozzoo** [comment]
Still no movement in the Fedora bug I filed. I'll try poking people and if that doesn't prove fruitful, I can either open a PR and try to land it we may need to wait until F32 hits EOL (still blocked in Debian though).

**Comment by bboozzoo** [comment]
Fedora 32 will EOL in a week on 25.05.2021 (see https://fedorapeople.org/groups/schedule/f-34/f-34-key-tasks.html). Once that happens, we'll be able to update and land the PR. AFAICT the packages this PR depends on are good in Fedora 33 and 34.

**Comment by bboozzoo** [comment]
Failed on sid
```
/usersession/userd github.com/snapcore/snapd/usersession/userd/ui github.com/snapcore/snapd/usersession/xdgopenproxy github.com/snapcore/snapd/wrappers github.com/snapcore/snapd/x11
src/github.com/snapcore/snapd/cmd/snap/cmd_run.go:38:2: cannot find package "github.com/godbus/dbus/v5" in any of:
	/usr/lib/go-1.15/src/github.com/godbus/dbus/v5 (from $GOROOT)
	/home/gopath/src/github.com/snapcore/snapd/_build/src/github.com/godbus/dbus/v5 (from $GOPATH)
src/github.com/snapcore/snapd/usersession/userd/userd.go:26:2: cannot find package "github.com/godbus/dbus/v5/introspect" in any of:
	/usr/lib/go-1.15/src/github.com/godbus/dbus/v5/introspect (from $GOROOT)
	/home/gopath/src/github.com/snapcore/snapd/_build/src/github.com/godbus/dbus/v5/introspect (from $GOPATH)
```

**Comment by bboozzoo** [comment]
I looked at sid a bit, they do not provide a compatibility symlink of `/usr/share/gocode/src/github.com/godbus/dbus/` -> `/usr/share/gocode/src/github.com/godbus/dbus/v5`. In contrast in Fedora, there's a `compat-*` package that does that.

**Comment by anonymouse64** [comment]
What's the status of this PR?

**Comment by jhenstridge** [comment]
There hasn't been any forward movement on the Debian bug report. We're not testing on Fedora 32 any more, so that distro is fine.

It does seem that there is limited interest in maintaining these kind of compatibility symlinks for old non-module aware builds, so maybe upgrading this dependency isn't worth pursuing (at least separate from a conversion to Go modules).

**Comment by anonymouse64** [comment]
@jhenstridge so if we switch to using go modules then we can make this upgrade without waiting for the debian bug? FWIW, we are working on transitioning to go modules.

**Comment by jhenstridge** [comment]
I put together a trivial example Go package here:

https://code.launchpad.net/~jamesh/+git/go-mod-test

It does the following:
* Uses modules
* Imports godbus as `github.com/godbus/dbus/v5`
* Builds against the Debian packaged version of godbus

I had to override dh_golang's build and test targets, and perform a "go mod edit" call to point the compiler at the packaged godbus source. It'd be nice if dh_golang supported a module-aware build, but it might get us unblocked on moving over to modules (which in turn would make upgrading godbus easier).

**Comment by anonymouse64** [comment]
@jhenstridge now that we are on go modules can this be move forward?

**Comment by mvo5** [comment]
I wonder if we can try this again? But it seems there was no movement in the debian bugreport and  `$ dpkg -L golang-dbus-dev|grep v5` comes back empty

**Comment by Meulengracht** [comment]
@jhenstridge do you think this is still relevant? Otherwise I'll close it soon, but feel free to reopen

**Comment by jhenstridge** [comment]
@Meulengracht: it's probably best to close this PR.

I think it is worthwhile upgrading the godbus version, since we're currently pinned to an almost 5 year old snapshot that doesn't correspond to any release. There's about 200 

At the time I made this PR, snapd had not yet moved to Go modules and some supported distros couldn't build in modules mode. Some of those issues might have resolved themselves since then.

If we tried to upgrade again, it might be better to start from scratch rather than build off this old PR.

**Comment by Meulengracht** [comment]
@jhenstridge Thank you, i'll close it and create a ticket for upgrading godbus

**Pull request closed without merging**
