### PR TITLE
release: 2.53.3

### PR DESCRIPTION
**Pull request by anonymouse64**
Update changelogs with the 2.53.3 changes.

### CODE REVIEW

**Review by pedronis — APPROVED** [review]
thx

**Review by mvo5 — APPROVED** [review]
Thank you!

**Comment by GlenPickle** [comment]
Would it be possible to get https://github.com/snapcore/snapd/pull/11052 into 2.53.3? I'd ideally like to import released versions of snapd rather than using git meta tags to avoid any unexpected bugs.

**Comment by anonymouse64** [comment]
@GlenPickle that PR is not approved yet and we need to get 2.53.3 moving ASAP in order to get it released before folks leave for the end of the year, so unfortunately no it is not possible to include that PR in 2.53.3. That PR should get into 2.53.4 or 2.54 which we plan to start in January first thing after the break.

**Comment by GlenPickle** [comment]
@anonymouse64 Thanks, I'll stick with git meta tags for now and start pinning to snapd release versions starting at 2.53.4 then.

**Comment by anonymouse64** [comment]
(had to force push to fix a typo)

**Comment by anonymouse64** [comment]
Whelp 2.53.3 was not happy in LP without also pulling in https://github.com/snapcore/snapd/pull/11020, so I have pulled that into a 2.53.4, hopefully that goes through and now in January we will have 2.53.5 :-)

**Comment by bboozzoo** [comment]
I understand there's a bit of a chicken and egg problem with tagging the release and then finding out it doesn't build on LP for reasons.Could this have been avoided by either replicating the LP build environment outside of LP or introducing release candidates which we are fine with if they don't build and we can patch the branch as needed?

**Comment by anonymouse64** [comment]
@bboozzoo

1) yes if we had a way to reproduce the same test env that LP has that would be great to have, as it is I don't know of such an environment
2) I proposed before tagging a release after it has gone through the release process etc (but before it hits stable) so that we can have a more rolling and less manual release process but that has issues with how we do the traditional linux packaging. At some point now that I've done the release process more and understand it better I'd like to re-analyze this and see how we could get more efficient at pushing out new snapd versions more quickly since it has become very clear that we are constantly under pressure to deliver more and more more quickly.

**Pull request merged**
