### PR TITLE
Add an interface to access the usb drives

### PR DESCRIPTION
**Pull request by axelebas**
Theses changes add a new interface "usb". It gives access to the usb drives.

### CODE REVIEW

**Comment by morphis** [comment]
This conflicts with the plugable-storage interface we're implementing in https://github.com/snapcore/snapd/pull/1674

Also 'usb' is far too generic as name for what this interface here is going to do.

**Comment by axelebas** [comment]
You are right,, I had developed this interface because it was not possible for the moment to use the USB ports to communicate with an application. I had not seen the plugable-storage interface, which actually seems much better . Will it be available in the next release of snapd ?

**Comment by morphis** [comment]
@axelebas We hope so. There are just a few points which @jdstrand mentioned yesterday which we have to resolve.

**Comment by niemeyer** [comment]
Yeah, #1674 should solve your needs. Please let us know if it doesn't for some reason.

**Pull request closed without merging**
