### PR TITLE
tests: update to support nested kvm without reboots on UC20

### PR DESCRIPTION
**Pull request by sergiocazzolato**
We are already using a new ubuntu 20.04 image which is using an old kernel (4.15.0-1078-gcp) which does not produce
reboots.

### CODE REVIEW

**Review by zyga — APPROVED** [review]
Magic!

**Review by cmatsuoka — APPROVED** [review]
Removing special case handling is good. I wonder what exactly broke in the kernel to cause this problem, but the only way to know for sure would be a huge bisect.

**Review by bboozzoo — APPROVED** [review]
Nice, 36 minutes instead of 50 (or even 8* as we saw 2 weeks ago)

**Comment by bboozzoo** [comment]
The preseed failure seems relate to the image change, but best if @stolowski could take a look:
```
2020-09-18T19:05:13.0999958Z --- system-key.real	2020-09-18 19:05:13.064768240 +0000
2020-09-18T19:05:13.1000486Z +++ system-key.preseeded	2020-09-18 19:04:28.980506641 +0000
2020-09-18T19:05:13.1000896Z @@ -1 +1 @@
2020-09-18T19:05:13.1004096Z -{"version":10,"build-id":"225ba792cf717d7c56b577bd8025a01ef947ca2f","apparmor-features":["caps","dbus","domain","file","mount","namespaces","network","network_v8","policy","ptrace","query","rlimit","signal"],"apparmor-parser-mtime":1589907589,"apparmor-parser-features":["unsafe"],"nfs-home":false,"overlay-root":"","seccomp-features":["allow","errno","kill_process","kill_thread","log","trace","trap","user_notif"],"seccomp-compiler-version":"f9c76097f79312489d7a3ac36f006b764aff331e 2.4.3 9b218ef9a4e508dd8a7f848095cb8875d10a4bf28428ad81fdc3f8dac89108f7 bpf-actlog","cgroup-version":"1"}
2020-09-18T19:05:13.1006312Z \ No newline at end of file
2020-09-18T19:05:13.1010611Z +{"version":10,"build-id":"225ba792cf717d7c56b577bd8025a01ef947ca2f","apparmor-features":["caps","dbus","domain","file","mount","namespaces","network","policy","ptrace","query","rlimit","signal"],"apparmor-parser-mtime":1589907589,"apparmor-parser-features":["unsafe"],"nfs-home":false,"overlay-root":"","seccomp-features":["allow","errno","kill_process","kill_thread","log","trace","trap"],"seccomp-compiler-version":"f9c76097f79312489d7a3ac36f006b764aff331e 2.4.3 9b218ef9a4e508dd8a7f848095cb8875d10a4bf28428ad81fdc3f8dac89108f7 bpf-actlog","cgroup-version":"1"}
2020-09-18T19:05:13.1013090Z \ No newline at end of file
```

The real preseed key has `network_v8` in apparmor features, and `user_notif` in seccomp features.

**Comment by stolowski** [comment]
> The preseed failure seems relate to the image change, but best if @stolowski could take a look:
> 
> ```
> 2020-09-18T19:05:13.0999958Z --- system-key.real	2020-09-18 19:05:13.064768240 +0000
> 2020-09-18T19:05:13.1000486Z +++ system-key.preseeded	2020-09-18 19:04:28.980506641 +0000
> 2020-09-18T19:05:13.1000896Z @@ -1 +1 @@
> 2020-09-18T19:05:13.1004096Z -{"version":10,"build-id":"225ba792cf717d7c56b577bd8025a01ef947ca2f","apparmor-features":["caps","dbus","domain","file","mount","namespaces","network","network_v8","policy","ptrace","query","rlimit","signal"],"apparmor-parser-mtime":1589907589,"apparmor-parser-features":["unsafe"],"nfs-home":false,"overlay-root":"","seccomp-features":["allow","errno","kill_process","kill_thread","log","trace","trap","user_notif"],"seccomp-compiler-version":"f9c76097f79312489d7a3ac36f006b764aff331e 2.4.3 9b218ef9a4e508dd8a7f848095cb8875d10a4bf28428ad81fdc3f8dac89108f7 bpf-actlog","cgroup-version":"1"}
> 2020-09-18T19:05:13.1006312Z \ No newline at end of file
> 2020-09-18T19:05:13.1010611Z +{"version":10,"build-id":"225ba792cf717d7c56b577bd8025a01ef947ca2f","apparmor-features":["caps","dbus","domain","file","mount","namespaces","network","policy","ptrace","query","rlimit","signal"],"apparmor-parser-mtime":1589907589,"apparmor-parser-features":["unsafe"],"nfs-home":false,"overlay-root":"","seccomp-features":["allow","errno","kill_process","kill_thread","log","trace","trap"],"seccomp-compiler-version":"f9c76097f79312489d7a3ac36f006b764aff331e 2.4.3 9b218ef9a4e508dd8a7f848095cb8875d10a4bf28428ad81fdc3f8dac89108f7 bpf-actlog","cgroup-version":"1"}
> 2020-09-18T19:05:13.1013090Z \ No newline at end of file
> ```
> 
> The real preseed key has `network_v8` in apparmor features, and `user_notif` in seccomp features.

Yes, correct, there is a change in apparmor and seccomp features between spread host system and the image. We should refresh nested images to match.

**Comment by sergiocazzolato** [comment]
@stolowski thanks for the review, which change is needed for the nested image?

**Review by anonymouse64 — APPROVED** [review]
This is great work, thanks for the great investigative work finding a kernel/userspace combo that works with this!

**Pull request merged**
