### PR TITLE
integration-tests: remove daemon to use the log-observe interface 

### PR DESCRIPTION
**Pull request by fgimenez**
We don't need a daemon to use the log-observe interface, this PR simplifies the test by removing the service and the client. It should also prevent the flaky results.

### CODE REVIEW

**Comment by mvo5** [comment]
:+1:

**Comment by fgimenez** [comment]
retest this please

**Comment by fgimenez** [comment]
retest this please

**Comment by fgimenez** [comment]
retest this please

**Comment by zyga** [comment]
+1

**Pull request merged**
