### PR TITLE
po: sync translations from launchpad

### PR DESCRIPTION
**Pull request by mvo5**
This add the translations we got from launchpad back into git master.

### CODE REVIEW

**Comment by chipaca** [comment]
Wooo! is this automated now? :-)

**Comment by chipaca** [comment]
With the commit I just pushed you get
```
NB: main.go:160: argument "ack"'s "forutsetningsfil>" should be wrapped in <>s
NL: main.go:152: description of sign's "k" is lowercase: "naam van de te gebruiken sleutel, gebruik anders de standaardsleutel"
NL: main.go:152: description of install's "dangerous" is lowercase: "installeer het opgegeven snapbestand zelfs indien er geen vooraf erkende handtekeningen voor zijn, hetgeen betekent dat het niet werd geverifieerd en dus gevaarlijk zou kunnen zijn (--devmode impliceert dit)"
```
at the end of the i18n test

**Comment by chipaca** [comment]
Note that all these errors are either fixed or have their fix suggested already; I'm not sure where the translations were imported _from_, but, in order:
* `NB: main.go:160: argument "ack"'s "forutsetningsfil>" should be wrapped in <>s`
  https://translations.launchpad.net/ubuntu/cosmic/+source/snapd/+pots/snappy/nb/23/+translate
  > Translated by John Lenton on 2017-10-18
  > Reviewed by Åka Sikrom on 2018-04-19

* `NL: main.go:152: description of sign's "k" is lowercase: "naam van de te gebruiken sleutel [...]"`
  https://translations.launchpad.net/ubuntu/cosmic/+source/snapd/+pots/snappy/nl/169/+translate
  > Suggested by John Lenton on 2018-09-26
* `NL: main.go:152: description of install's "dangerous" is lowercase: "installeer het opgegeven snapbestand [...]`
  https://translations.launchpad.net/ubuntu/cosmic/+source/snapd/+pots/snappy/nl/143/+translate
  > Suggested by Daniel Llewellyn on 2018-09-26

**Comment by mvo5** [comment]
@chipaca Thanks for fixing this! The translations were imported from the cosmic package translations. AIUI if the fix is only suggested we get the incorrect version of the string until some translator approves the fix. So that seems to be what happend here, no?

**Comment by chipaca** [comment]
@mvo5 the last two, yes, are still pending review. The first one says it's already reviewed. Maybe it's missing another step I don't know.

**Pull request merged**
