### PR TITLE
interfaces: add Ledger NanoS+ and Stax to u2f devices

### PR DESCRIPTION
**Pull request by xchapron-ledger**

### CODE REVIEW

**Review by sportron-ledger — APPROVED** [review]

**Comment by xchapron-ledger** [comment]
@pedronis Hello :)
We like this to be merged and deployed as soon as possible as this is impacting some of our users now that Firefox changed things on their U2F support.
What should I do? Who can I ping?
Thanks!
Xavier

**Comment by pedronis** [comment]
the soonest it could get released would be with 2.60.2

**Comment by xchapron-ledger** [comment]
> the soonest it could get released would be with 2.60.2

Thanks, the sooner the better :) Let me know if I can do anything.

**Review by alexmurray — CHANGES_REQUESTED** [review]
I went searching for any official documentation as to where the product IDs are defined for these devices but I couldn't find anything - would it be possible to provide a link which lists the vendor ID and product IDs for these devices? Thanks.

**Comment by xchapron-ledger** [comment]
@alexmurray Hello :)
I don't have a clean doc to share with you.
Mostly because Ledger vid is stable to 2C97 but the pid depend on the device model and on the endpoints the application running on the device exposes.

See:
- this link for the recommended dev-rules: https://github.com/LedgerHQ/udev-rules/blob/master/add_udev_rules.sh
- and these links for the implementation:
  - Nanos + default base pid: https://github.com/LedgerHQ/ledger-secure-sdk/blob/master/lib_stusb_impl/usbd_impl.c#L192
  - Ledger Stax default base pid: https://github.com/LedgerHQ/ledger-secure-sdk/blob/master/lib_stusb_impl/usbd_impl.c#L213
  - Additional mask on the pid: https://github.com/LedgerHQ/ledger-secure-sdk/blob/master/lib_stusb_impl/usbd_impl.c#L734-L748
  
Which gives the combination I put in the PR, as described here: https://github.com/Yubico/libfido2/pull/712/files#diff-68a02b3990c2e1d18609828b60bb882ff7a7a72c7a4b16b874b37b4275c7ba81R219-R236

**Review by alexmurray — APPROVED** [review]
Excellent - thanks for the details @xchapron-ledger - LGTM!

**Review by ZeyadYasser — APPROVED** [review]

**Comment by xchapron-ledger** [comment]
@alexmurray @ZeyadYasser Thanks!
I saw the CLA-check failure and signed the contribution agreement. Can you rerun the job please.

**Comment by ZeyadYasser** [comment]
Hello @xchapron-ledger, I re-ran the CLA check, it is still failing.
Could you please make sure that the email used for the commit matches the email used to sign the CLA?
```
Checking the following users on GitHub:
- xchapron-ledger ✕ (issue checking CLA status [HttpError: User does not exist or is not a member of the organization])

Checking the following users on Launchpad:
- xavier.chapron@ledger.fr ✕ (has no Launchpad account)
```

**Comment by xchapron-ledger** [comment]
> Hello @xchapron-ledger, I re-ran the CLA check, it is still failing. Could you please make sure that the email used for the commit matches the email used to sign the CLA?
> 
> ```
> Checking the following users on GitHub:
> - xchapron-ledger ✕ (issue checking CLA status [HttpError: User does not exist or is not a member of the organization])
> 
> Checking the following users on Launchpad:
> - xavier.chapron@ledger.fr ✕ (has no Launchpad account)
> ```

@ZeyadYasser I confirm this is the email I registered with and the email I see in https://login.launchpad.net/.
Maybe a cache issue somewhere? :man_shrugging:

**Comment by xchapron-ledger** [comment]
@ZeyadYasser sorry I missed a notification to join the organisation in my emails. Maybe this is linked.
I've just accept the invitation. can you retry at some point?
thanks.

**Comment by ZeyadYasser** [comment]
@xchapron-ledger I re-ran the CLA check. It is passing now, Thank you!

**Comment by xchapron-ledger** [comment]
> @xchapron-ledger I re-ran the CLA check. It is passing now, Thank you!

Great!
I'd say the other failing jobs are not due to my patch, correct?

**Comment by ZeyadYasser** [comment]
> Great! I'd say the other failing jobs are not due to my patch, correct?

I don't think your patch is causing those failing jobs.

**Pull request merged**
