### PR TITLE
tests: improve `nested_get_image_name` to avoid accidential reuse

### PR DESCRIPTION
**Pull request by mvo5**
The code in `nested.sh` will reuse images with the same name. This
can lead to subtle bugs like when a nested test uses a different
model but does not specify an `NESTED_IMAGE_ID`. Because the
code in `nested_get_image_name` does not take the model into
account an image build before can get reused. This happend in
the `gadget-connections` test where depending on the test order
one test would get the wrong image.

Instead of pushing the burden to the individual tests to remember
to set `NESTED_IMAGE_ID` this commit makes `nested_get_image_name`
smarter so that it takes the spread task name and variant into account
when building the image name.

This should prevent bugs like the one we saw with the
`gadget-connections` test.

### CODE REVIEW

**Comment by sergiocazzolato** [comment]
@mvo, in this case the image used depends on the NESTED_IMAGE_ID specified in the test. No other tests have the same NESTED_IMAGE_ID than this test, so should not reuse any other image and it should create a new one. 

The idea os the manual tests is that each test has its own NESTED_IMAGE_ID so each test is not reusing the image created by other one. 

Perhaps I am missing something, do you have either a link or a description about the error so I can check it? 

Thanks for dealing with this error

**Review by mvo5 — COMMENTED** [review]
Thank you for this update Sergio

**Review by sergiocazzolato — APPROVED** [review]
Thanks

**Review by mardy — APPROVED** [review]
LGTM, thanks!

**Comment by mvo5** [comment]
Looks like this is no longer needed as upstream changed it.

**Pull request closed without merging**
