### PR TITLE
cmd,tests: forcibly discard mount namespace when bases change

### PR DESCRIPTION
**Pull request by zyga**
We were alerted that when an existing snap, that used to use core as the
implicit base snap, is refreshed to explicitly use core18, then sometimes
that snap would fail to start.

The problem was debugged to a case where snap-confine would reuse the old mount
namespace, even though it knew it was stale, because an application was still
running and making the mount namespace "busy".

When the refreshed snap requires updated libraries from the new base snap it
could segvfault or misbehave in some other way. As such, before we have
refresh-app-awareness ready and deployed (when refresh would be postponed until
the application quits), snap-confine now detects this situation and forcibly
re-creates the mount namespace.

Fixes: https://bugs.launchpad.net/snapd/+bug/1819875

### CODE REVIEW

**Comment by zyga** [comment]
Tests here fail because of https://bugs.launchpad.net/snapd/+bug/1822660. I have pushed a fix for that separately as https://github.com/snapcore/snapd/pull/6675

**Comment by zyga** [comment]
The bug is fixed now, this branch should now pass.

**Comment by pedronis** [comment]
I wonder using os-release feels a bit fragile and too precise, one could imagine some special bases which are base os + libraries, and then two variant of that would have the same os-release but something else changed.

Can't we dedicate some path under var/lib/snapd to mount a tmpfs were we write information about the base when we construct the namespace.

**Comment by jdstrand** [comment]
Not only what @pedronis said, but erf, I really don't like that we are adding text parsing of files in (admittedly restricted) base/os snaps. Is there no other way that is cheap and covers most cases? I mean, if this is fixed with refresh-app-awareness maybe not introduce this temporary fix at all?

**Comment by zyga** [comment]
@jdstrand I am reworking this but the fix will be required even with refresh app awareness in place. We need to ensure that at all times an application executes on top of the base snap it designates.

The reworked version will roughly look like this:
- snap-confine writes `/run/snapd/ns/snap.$SNAP_INSTANCE_NAME.info` with key=value pairs
- the first key=value pair is base snap name of the newly created mount namespace
- on each subsequent startup we check if we diverge the base snap and discard if so
- when discarding the mount namespace we remove the `.info` files as well

**Comment by zyga** [comment]
I'm working on this now.

**Comment by zyga** [comment]
I am reworking this but the scope of changes will be such that it is easier to propose new PRs.

**Pull request closed without merging**
