### PR TITLE
snap-bootstrap: Mount as private

### PR DESCRIPTION
**Pull request by valentindavid**
Mounts within `/run/mnt` do not need shared propagation, as they are mostly bind mounted later. Shared propagation duplicates mount points. For example any mount within `/` will be propagated back to `/run/mnt/base`, creating a duplicated entry in `/proc/mounts`.

### CODE REVIEW

**Comment by bboozzoo** [comment]
There are some conflicts with master that need addressing

**Comment by valentindavid** [comment]
Rebased.

**Review by mardy — APPROVED** [review]
LGTM!

**Review by bboozzoo — APPROVED** [review]
LGTM

**Comment by mvo5** [comment]
I merged master to get a clean test run (hopefully) - happy to merge this but would really like spread to be happy first.

**Comment by mvo5** [comment]
The core{20,22} tests are happy so I merge this one. Thanks for the PR!

**Pull request merged**
