### PR TITLE
cmd/snap, daemon: detect and bail purge on multi-snap

### PR DESCRIPTION
**Pull request by chipaca**
it would be better to actually pass the purge in, but that's probably
gnarly (i haven't looked tbh).

fixes lp:1878902

### CODE REVIEW

**Comment by stolowski** [comment]
This looks good code-wise, thank you! But yes, I think it would be more natural to simply pass flags (purge is the only flag we have) to snapstate.RemoveMany (and from there to Remove, it currently passes nil); this actually looks straightforward, so perhaps we should do this rather than restricting remove --purge. cc @pedronis

**Comment by stolowski** [comment]
> This looks good code-wise, thank you! But yes, I think it would be more natural to simply pass flags (purge is the only flag we have) to snapstate.RemoveMany (and from there to Remove, it currently passes nil); this actually looks straightforward, so perhaps we should do this rather than restricting remove --purge. cc @pedronis

Ah, I just realized it is not as simple on the api side. TBD.

**Comment by anonymouse64** [comment]
Let's see how green this is with a fresh master merge...

**Comment by anonymouse64** [comment]
I fixed the spread test here so this should be green now :crossed_fingers:

**Pull request merged**
