### PR TITLE
integration-tests: add buildtags for classic-only and all-snaps-only tests

### PR DESCRIPTION
**Pull request by elopio**

### CODE REVIEW

**Comment by elopio** [comment]
This is an alternative to #1213, for discussion during tomorrow's QA meeting.

**Comment by elopio** [comment]
restest this please

**Comment by elopio** [comment]
retest this please

**Comment by mvo5** [comment]
Thanks, this looks good, I think I prefer the tag over the name in the alternative branch as it seems (slightly) cleaner to me. Please de-conflict and close one of the two branches (depending on your internal discussion).

**Comment by fgimenez** [comment]
:+1: nicer than the alternative. 

I'd only include a classic or all-snaps tag in the references to tags like `excludereboots` or `rollbackstress` in the `integration-tests/README.md` file, so that it's clear that the system type tag must be present in order to execute the complete suite for each type of system.

**Comment by mvo5** [comment]
Please de-conflict and then just merge, looks nice!

**Comment by elopio** [comment]
Thanks mvo!

**Pull request merged**
