### PR TITLE
tests/core20-boot-config-update: wait for the reboot before the watch

### PR DESCRIPTION
**Pull request by alfonsosanchezbeato**
In some cases the reboot was happening while running "snap watch", it makes more sense to run this after the reboot to ensure that the change has finished.

### CODE REVIEW

**Review by pedronis — APPROVED** [review]
lgtm

**Review by ZeyadYasser — APPROVED** [review]
LGTM, Thank you!

**Comment by alfonsosanchezbeato** [comment]
@pedronis I had to change this again: the test installs a new snapd that updates `grub.cfg`, and it was assuming that a reboot happened only if that implied changes in the kernel command line. However, the current code would ask for a reboot whenever `grub.cfg` is updated. It is not clear to me when the test started to fail or when the behavior of snapd changed, but anyway to me it makes sense that it reboots for any change of grub.cfg. If you think differently, it would not be difficult to change to the old behavior by modifying `updateManagedBootConfigForBootloader` from `boot/boot.go`.

**Comment by pedronis** [comment]
> @pedronis I had to change this again: the test installs a new snapd that updates grub.cfg, and it was assuming that a reboot happened only if that implied changes in the kernel command line. However, the current code would ask for a reboot whenever grub.cfg is updated. It is not clear to me when the test started to fail or when the behavior of snapd changed, but anyway to me it makes sense that it reboots for any change of grub.cfg. If you think differently, it would not be difficult to change to the old behavior by modifying updateManagedBootConfigForBootloader from boot/boot.go.

as discussed the old logic was trying to capture the idea to reboot only on things that affected runtime/changed the measurements but booting more is likely not an issue as it's not like we change grub.cfg often

**Pull request merged**
