### PR TITLE
tests/main/interfaces-pulseaudio: use custom pulseaudio script, set kill timeout

### PR DESCRIPTION
**Pull request by bboozzoo**
This is an attempt to fix/address the current random failures we see in the test on 20.04.

Use a custom pulseaudio server script to ensure that we are not unnecessarily
loading any other modules that may break the daemon startup process. Make sure
to include module-snap-policy as it's used in Ubuntu by default.

Increase exit timeout time of the daemon to 5m to make sure it does not exit too
early. However have the test execution time be limited to 3m.

Use verbose logging to help debug the test failures.

### CODE REVIEW

**Comment by anonymouse64** [comment]
Seems this failed again, I will try combining these changes with my changes I worked on but didn't push and see if we can get something working. If so, I'll push an update here.

**Comment by anonymouse64** [comment]
I think I have been able to robustly fix this test, I would like to land a follow-up to this which combines this setup with interfaces-audio-playback-record, as I have seen similar failures there as well and don't want to duplicate all of this logic.

**Comment by bboozzoo** [comment]
@anonymouse64 thanks for the updates. I've pushed little tweaks on top. I'd be nice to extract a wrapper/helper lib for managing user sessions, but that's probably a material for another PR.

**Comment by anonymouse64** [comment]
Grr this still doesn't seem to be robust enough: https://pastebin.ubuntu.com/p/NWDTyNzgmc/

**Comment by bboozzoo** [comment]
Pushed a couple more tweaks. Worked with with my tiny sample of 5 runs :smile:

**Comment by bboozzoo** [comment]
This isn't worse than it was before, so I'll merge it and if the problems keep appearing, we'll need to investigate again.

**Pull request merged**
