### PR TITLE
snap-confine: revert, with comment, explicit unix deny for nested lxd

### PR DESCRIPTION
**Pull request by jdstrand**
While snap-confine itself doesn't require unix rules and therefore all
unix rules are implicitly denied, adding an explicit deny for unix to
silence noisy denials breaks nested lxd when it shouldn't:
```
  $ sudo snap install lxd
  $ sudo lxd init
  $ sudo lxc launch ubuntu:18.04 c1 -c security.nesting=true
  $ lxc exec c1 -- snap install lxd
  error: cannot perform the following tasks:
  - Start snap "lxd" (12631) services ([start snap.lxd.activate.service]
    failed with exit status 1: Job for snap.lxd.activate.service failed
    because the control process exited with error code.
```
Until the cause is determined, do not use an explicit deny for unix.

Reference:
- https://bugs.launchpad.net/snapd/+bug/1855355

### CODE REVIEW

**Comment by anonymouse64** [comment]
Note this supercedes my PR at https://github.com/snapcore/snapd/pull/7855 so I will close that one, but I will open a different PR with the regression test demonstrating this.

Also the ubuntu spread tests will fail because there's an Ubuntu 16.04 image issue with the mount namespaces.

**Comment by anonymouse64** [comment]
https://github.com/snapcore/snapd/pull/7857 should address the ubuntu mount ns spread test failure.

**Comment by jdstrand** [comment]
> Also the ubuntu spread tests will fail because there's an Ubuntu 16.04 image issue with the mount namespaces.

Ah, the `google:ubuntu-16.04-64:tests/main/mount-ns:inherit` failure I've seen from all the PRs. I'll keep an eye on the fix.

**Comment by zyga** [comment]
Can we please get a spread test with nested LXD inside this branch to confirm the fix is sufficient and real.

**Comment by jdstrand** [comment]
> Can we please get a spread test with nested LXD inside this branch to confirm the fix is sufficient and real.

@anonymouse64 did https://github.com/snapcore/snapd/pull/7858 for just that reason.

**Pull request merged**
