### PR TITLE
secboot: add boot manager profile to pcr protection profile

### PR DESCRIPTION
**Pull request by cmatsuoka**
Add the UEFI boot manager code and boot attempts profile to the PCR
protection profile, to restrict access to a sealed key to a specific
set of binaries started from the UEFI boot manager and which are
measured to PCR 4.

Signed-off-by: Claudio Matsuoka <claudio.matsuoka@canonical.com>

### CODE REVIEW

**Review by mvo5 — APPROVED** [review]
This looks good to me from a code/testing POV.

**Comment by pedronis** [comment]
marked blocked mostly because I think we want reseal done first

**Comment by mvo5** [comment]
Once 9355 and 9341 have landed we will merge master and then run nested tests and that is the final PR we need for 2.47~rc1 :)

**Comment by mvo5** [comment]
I removed blocked now, one prereq is merged, the other needs some work unfortunately. But kernel spread tests also need work.

**Review by pedronis — APPROVED** [review]
thank you, do

**Comment by pedronis** [comment]
marking blocked wondering if we should merge into this the improved reseal tests first perhaps?? @mvo5 feel free to mark unblocked again if you want to proceed differently

**Comment by mvo5** [comment]
Master with the updated tests got merged.

**Pull request merged**
