### PR TITLE
snap,store: drop support/consideration for anonymous download urls

### PR DESCRIPTION
**Pull request by pedronis**
v2 store APIs never provided them

v1 has for a long time returned the same value for both kind of URLs

### CODE REVIEW

**Review by MiguelPires — COMMENTED** [review]
There's another usage:
```
diff --git a/store/details_v2_test.go b/store/details_v2_test.go
index a9b668d91d..955bb0cefb 100644
--- a/store/details_v2_test.go
+++ b/store/details_v2_test.go
@@ -306,8 +306,7 @@ func (s *detailsV2Suite) TestInfoFromStoreSnap(c *C) {
 		"Tracks",   // handled at a different level (see TestInfo)
 		"Layout",
 		"SideInfo.Channel",
-		"SideInfo.EditedLinks",         // TODO: take this value from the store
-		"DownloadInfo.AnonDownloadURL", // TODO: going away at some point
+		"SideInfo.EditedLinks", // TODO: take this value from the store
 		"SystemUsernames",
 	}
 	var checker func(string, reflect.Value)
```

There are others in the fakestore as well but they're for /v1 and they're the same values as the `download_url` so those seem reasonable

**Review by MiguelPires — APPROVED** [review]
LGTM

**Review by mvo5 — APPROVED** [review]
Thank you!

**Review by mardy — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
