### PR TITLE
interfaces: fix typo in network_manager_observe

### PR DESCRIPTION
**Pull request by d-loose**
This fixes a typo in the `network_manager_observe` interface: `NetworkManger` -> `NetworkManager`.

### CODE REVIEW

**Review by MiguelPires — APPROVED** [review]
LGTM, thanks

**Review by zyga — APPROVED** [review]
Looks good.

**Review by mvo5 — APPROVED** [review]

**Comment by setharnold** [comment]
How was this issue spotted? I'm surprised the old typo could live for four years without being spotted. Is this code used? Are these rules redundant?

Thanks

**Comment by d-loose** [comment]
I haven't personally encountered any problems related to that interface - I spotted it while trying to get an overview over which XDG DBus APIs are exposed via a snap interface.
Found the typo in the output of `grep -RE "^\s*interface=org\.freedesktop\." . | grep -v DBus | sort -u`, according to my bash history.

**Comment by alexmurray** [comment]
@mvo5 I am also quite surprised that these typos remained for so long - either no-one has ever used this part of `network-manager-observe` OR these rules are redundant (as perhaps some other access overshadows them) OR they are not being correctly enforced. I wonder if we should just remove them from this interface in that case instead?

**Comment by alfonsosanchezbeato** [comment]
Probably apps that wanted to observe/control NetworkManager have used the network-manager plug instead.

And actually, the NM **slot** will have permissions to send/receive using `/org/freedesktop/NetworkManager{,/**}` to a confined client only if a plug is connected (see `networkManagerConnectedSlotAppArmor`). So I think that these rules have never worked.

**Comment by alfonsosanchezbeato** [comment]
Ah, nevermind, I see that the rules are in connected plug/slot in this interface as well.

**Pull request merged**
