### PR TITLE
tests/many: stop importing osutil from dirs, mock ProcSelfMountInfo more

### PR DESCRIPTION
**Pull request by anonymouse64**
The over-arching goal of this PR is this exactly this commit and only this commit: https://github.com/snapcore/snapd/commit/0ca4b01749d50fce5edfe70b80d6a740e97a61cf

... however doing that is quite difficult because `dirs` depends on `osutil`, so we have to eliminate an import cycle by: 
* moving apparmor dirs definitions to sandbox/apparmor
* fix many tests which depend on implicitly reading `/proc/self/mountinfo` for the system-keyas they now actually attempt to read `<test rootdir>/proc/self/mountinfo`
* don't try to read mountinfo at all in some places where we would need to mock a more complicated mountinfo like in the systemd tests for selinux and in the interfaces tests with IsRootWritableOverlay

I would break it up more if I could, but really the only independent change here that doesn't depend on the changes here is https://github.com/snapcore/snapd/pull/8441 (which is also needed otherwise we have to mock root writable overlays in the tests' ProcSelfMountInfo).

### CODE REVIEW

**Comment by pedronis** [comment]
@anonymouse64 you should have probably discussed this beforehand, we don't want to import dirs from osutil either

**Comment by anonymouse64** [comment]
@pedronis, mmmm that's unfortunate but I can also make osutil not import dirs either so they're both independent of each other... It shouldn't be a large change, just that some of the osutil helpers would now take an argument like `IsRootOverlayWritable(mountinfoFile string)`. Then ProcSelfMountInfo would be defined in dirs directly. A bit awkward, but arguably it is more awkward right now for me to add a fourth way to mock the mountinfo file to our test corpus. 

I'll comment when I have a patch for this.

**Comment by pedronis** [comment]
> A bit awkward, but arguably it is more awkward right now for me to add a fourth way to mock the mountinfo file to our test corpus.

can we chat today, I'm not even sure I fully understand the problem atm. 

As I explained elsewehere, the reason for no dirs in *util is that util packages should only use the stdlib and other util packages  (so that things like asserts have a cleaner footprint), I'm sure we might have some violations that need fixing over time.

**Comment by anonymouse64** [comment]
Alright this no longer has osutil depend on dirs. Perhaps this was not clear, but the issue to me is that I now need to mock proc/self/mountinfo from another place (if not possibly 2 - boot pkg + cmd/snap-bootstrap tests), and so if we don't do something like this the number of places we mock that information just keeps going up and it's in different ways. I would prefer a centralized way that we do this. 

Additionally, this exposed to me the fact that numerous of our tests are having state from the system the test is being run on leak into the tests, i.e. whether or not you have NFS or a writable overlay on root would change the results of the test. Because while many places were mocking mountinfo, many more were not mocking it at all and just happened to work because the system the test was being run on was similar to the "expected" system. Now, we guarantee that we have a clean system for the tests by mocking /proc/self/mountinfo as needed.

**Comment by anonymouse64** [comment]
https://github.com/snapcore/snapd/pull/8449 is now broken out from this PR as an independent change

**Comment by anonymouse64** [comment]
Closing this to break up into smaller independent PR's.

**Pull request closed without merging**
