### PR TITLE
.github: run woke tool on PR's 

### PR DESCRIPTION
**Pull request by anonymouse64**
Run the woke tool as part of the PR checks.

Based on top of https://github.com/snapcore/snapd/pull/11499

### CODE REVIEW

**Review by MiguelPires — COMMENTED** [review]
The new check is complaining about 'hang' even when it's middle of the word 'changelog':
.woke.yaml:3:28: [warning] `hang` may be insensitive, use `stop responding`, `stall` instead

**Comment by anonymouse64** [comment]
@MiguelPires I think that's because it doesn't recognize changelog as a word, so it checks to see if unknown words contain any exclusive language, perhaps we need to specifically, the config that this action is using is from https://github.com/petesfrench/inclusive-naming-action/blob/master/config.yml#L42
I think setting `word_boundary: true` may resolve that to only consider matches that start/end with a word boundary

**Review by bboozzoo — APPROVED** [review]
Thanks

**Review by mardy — APPROVED** [review]
LGTM, it would be nice to see a test run, but even if there are issues we can always just change the `fail-on-error` flag, I guess.

**Comment by bboozzoo** [comment]
I temporarily had a patch that triggered woke to find errors, see: https://github.com/snapcore/snapd/compare/d0ad285c00f5d644ebf83b7757ea61c23f7b2c71..d15c0e37f17c188493a251aefc4bff468491008b

**Review by mvo5 — APPROVED** [review]
Sounds great, let's do it

**Pull request merged**
