### PR TITLE
cmd/snap: prevent passing --prefer in multi-snap installs

### PR DESCRIPTION
**Pull request by ZeyadYasser**
I noticed that when passing `--prefer` when installing multiple snaps works and `--prefer` is ignored silently, this is because it is not being passed in the [client](https://github.com/snapcore/snapd/blob/d9e4ab8c5eeafda96bdf01df9e38dce0b684ec54/client/snap_op.go#L262) unlike for single [snap ops](https://github.com/snapcore/snapd/blob/d9e4ab8c5eeafda96bdf01df9e38dce0b684ec54/client/snap_op.go#L228).

This PR prevents `snap install --prefer snap1 snap2`, which was ignored silently before.

### CODE REVIEW

**Review by mvo5 — COMMENTED** [review]
Nice catch, thank you! Would you mind also adding this error case to the alias spread test?

**Comment by ZeyadYasser** [comment]
> Nice catch, thank you! Would you mind also adding this error case to the alias spread test?

Added, thank you for the review!

**Review by MiguelPires — APPROVED** [review]
LGTM, thanks

**Review by mvo5 — APPROVED** [review]
Thank you

**Pull request merged**
