### PR TITLE
interfaces/builtin: fix fcitx support in unity7

### PR DESCRIPTION
**Pull request by chihchun**
* Fix typo - s/bus=fcitx/bus=session/ and s/bus=accessibility/bus=session/
* Refine the coding style to be aligned with other rules.

### CODE REVIEW

**Comment by zyga** [comment]
Looks good to me. I wonder how we've missed the initial, odd values

**Comment by jdstrand** [comment]
I'm confused by this commit since fcitx creates its own bus and so does accessibility.

Where are you seeing the denials that prompted this PR? Can you provide clear steps on how to reproduce?

**Comment by chihchun** [comment]
1) Please install fcitx on Ubuntu Desktop.
$ sudo apt install fcitx-pinyin fcitx
2) Install and run a Qt-based app, said telegram-sergiusens
$ snap install telegram-sergiusens
$ /snap/bin/telegram-sergiusens.telegram
3) Once it launched, the Qt client (telegram here) will fail to create a the Input Context via DBus.

Kenrel log -
DENIED" operation="dbus_method_call"  bus="session" path="/inputmethod" interface="org.fcitx.Fcitx.InputMethod" member="CreateICv3" mask="send" name="org.fcitx.Fcitx-0" pid=2690 label="snap.telegram-sergiusens.telegram" peer_pid=6273 peer_label="unconfined"

**Comment by chihchun** [comment]
Please make sure that you have the following env vars, or it will not load the right im modules

% env|grep -i fcitx|sort -n
GTK_IM_MODULE=fcitx
QT4_IM_MODULE=fcitx
QT_IM_MODULE=fcitx
XMODIFIERS=@im=fcitx

**Comment by niemeyer** [comment]
@jdstrand Can you please re-review this?

**Comment by jdstrand** [comment]
I cannot reproduce this:
```
$ dpkg -l |grep fcitx
ii  fcitx                                      1:4.2.9.1-1ubuntu1                                          all          Flexible Input Method Framework
ii  fcitx-bin                                  1:4.2.9.1-1ubuntu1                                          amd64        Flexible Input Method Framework - essential binaries
ii  fcitx-config-common                        0.4.8-3                                                     all          graphic Fcitx configuration tool - common files
ii  fcitx-config-gtk                           0.4.8-3                                                     amd64        graphic Fcitx configuration tool - Gtk+ 3 version
ii  fcitx-data                                 1:4.2.9.1-1ubuntu1                                          all          Flexible Input Method Framework - essential data files
ii  fcitx-frontend-all                         1:4.2.9.1-1ubuntu1                                          all          Flexible Input Method Framework - frontends metapackage
ii  fcitx-frontend-gtk2                        1:4.2.9.1-1ubuntu1                                          amd64        Flexible Input Method Framework - GTK+ 2 IM Module frontend
ii  fcitx-frontend-gtk3                        1:4.2.9.1-1ubuntu1                                          amd64        Flexible Input Method Framework - GTK+ 3 IM Module frontend
ii  fcitx-frontend-qt4                         1:4.2.9.1-1ubuntu1                                          amd64        Flexible Input Method Framework - Qt4 IM Module frontend
ii  fcitx-frontend-qt5:amd64                   1.0.5-1                                                     amd64        Free Chinese Input Toy of X - Qt5 IM Module frontend
ii  fcitx-module-dbus                          1:4.2.9.1-1ubuntu1                                          amd64        Flexible Input Method Framework - D-Bus module and IPC frontend
ii  fcitx-module-kimpanel                      1:4.2.9.1-1ubuntu1                                          amd64        Flexible Input Method Framework - KIMPanel protocol module
ii  fcitx-module-lua                           1:4.2.9.1-1ubuntu1                                          amd64        Flexible Input Method Framework - Lua module
ii  fcitx-module-x11                           1:4.2.9.1-1ubuntu1                                          amd64        Flexible Input Method Framework - X11 module and XIM frontend
ii  fcitx-modules                              1:4.2.9.1-1ubuntu1                                          amd64        Flexible Input Method Framework - core modules
ii  fcitx-pinyin                               1:4.2.9.1-1ubuntu1                                          amd64        Flexible Input Method Framework - classic Pinyin engine
ii  fcitx-ui-classic                           1:4.2.9.1-1ubuntu1                                          amd64        Flexible Input Method Framework - Classic user interface
ii  libfcitx-config4:amd64                     1:4.2.9.1-1ubuntu1                                          amd64        Flexible Input Method Framework - configuration support library
ii  libfcitx-core0:amd64                       1:4.2.9.1-1ubuntu1                                          amd64        Flexible Input Method Framework - library of core funtions
ii  libfcitx-gclient0:amd64                    1:4.2.9.1-1ubuntu1                                          amd64        Flexible Input Method Framework - D-Bus client library for Glib
ii  libfcitx-qt0:amd64                         1:4.2.9.1-1ubuntu1                                          amd64        Flexible Input Method Framework - Meta package for Qt library
ii  libfcitx-qt5-1:amd64                       1.0.5-1                                                     amd64        Free Chinese Input Toy of X - D-Bus client libraries for Qt5
ii  libfcitx-utils0:amd64                      1:4.2.9.1-1ubuntu1                                          amd64        Flexible Input Method Framework - utility support library


$ env|grep -i fcitx|sort -n
GTK_IM_MODULE=fcitx
QT4_IM_MODULE=fcitx
QT_IM_MODULE=fcitx
XMODIFIERS=@im=fcitx

$ telegram-sergiusens
```

There are no fcitx denials.

fcitx wasn't running though. I need to go into Language support in Settings, install Chinese, then choose 'fcitx'. I seemed to have to logout and drag Chinese to before English in Language settings and set the Chinese keyboard as first in the list with in Text Entry. At this point I was able to use the keyboard selector and choose Chinese. I do see fcitx in the environment as you said it needed to be set.

Then I was able to see in ps ouput:
```
/usr/bin/dbus-daemon --fork --print-pid 5 --print-address 7 --config-file /usr/share/fcitx/dbus/daemon.conf
```

Looking in /usr/share/fcitx/dbus/daemon.conf I see
```
<busconfig>
  <!-- Our well-known bus type, don't change this -->
  <type>fcitx</type>
```

This means that 'dbus bus=fcitx' should be used (not 'dbus bus=session'). I then removed the fcitx rules from /var/lib/snapd/apparmor/profiles/snap.telegram-sergiusens.telegram-sergiusens and was unable to see any fcitx access (on the fcitx or session bus).

I did confirm that 'bus=fcitx' is correct for gtk3 apps though: I was able to add a 'file,' rule to the telegram-sergiusens profile and then use 'aa-exec -p snap.telegram-sergiusens.telegram-sergiusens -- gnome-calculator' and trigger fcitx denials when they were commented out. All of them used 'bus=fcitx'. Once I uncommented them, there were no session bus denials for fcitx. I did the same with gedit (had to add 'dbus (bind) bus=session name=org.gnome.gedit,') and konsole (had to add 'dbus (bind) bus=session name=org.kde.konsole*,'), they use fcitx but no sessions bus denials for either.

I have several questions:
- How did you get telegram-sergiusens to use fcitx?
- How did you get fcitx to listen on the session bus? Are you using non-Ubuntu packages?
- Can you start with a clean desktop 16.04 VM with English install and give exact steps to reproduce?

**Comment by niemeyer** [comment]
@jdstrand's question is a week old, and the actual activity on this branch is a month old.

Closing, but please feel free to bring it back once you have more details for @jdstrand.

**Comment by jdstrand** [comment]
Ok, a testcase was found in https://bugs.launchpad.net/snappy/+bug/1634089. A PR to fix the issue is in https://github.com/snapcore/snapd/pull/2287.

**Pull request closed without merging**
