### PR TITLE
update-copyright.sh: add tool to update copyright year

### PR DESCRIPTION
**Pull request by mardy**
We will actually update the copyright in another PR, to avoid conflicts. For the moment, just run this tool locally (without parameters) and see what it does.

### CODE REVIEW

**Review by MiguelPires — COMMENTED** [review]
Nice, thanks :) A couple of suggestions:
* we could call this in `./run-checks` so we don't have to remember to run it. If we do, then it would be better to only check the changed files (`git ls-files --modified`) to avoid adding a 20 second delay to every run
* this will update the last date of every file at the start of every year, I was under the impression that we only wanted to update the license if the content changed. AFAIK, the point of the copyright dates is to state when the content was created/modified so I think it would make sense to only update them when the file is modified

**Comment by mardy** [comment]
> Nice, thanks :) A couple of suggestions:
[...]

Mmm... both of your suggestions imply a usage pattern that is not what I had in mind. What inspired me to create this script (and to use a similar one in my personal projects) is how the QtProject operates: they run this script only once, at the beginning of the new year, and update all their files, regardless of whether they have been modified.

So I guess the core question is if it's fine to bump the copyright year for code that you don't touch; IANAL, but I guess that you can do that at will, as long as you are still maintaining the project.

**Review by MiguelPires — APPROVED** [review]
Ah I assumed the date should be the year a file was last modified but I couldn't find any conclusive information one way or another. Assuming that's fine then this looks great. Thanks!

**Comment by mardy** [comment]
I've been told that @jhenstridge might be the best person to review this, so here you go :-)

**Review by jhenstridge — COMMENTED** [review]
One concern I have here is files that contain multiple Copyright lines. It seems uncommon in the snapd tree, with only three files:

```
bootloader/assets/genasset/main_test.go:2
bootloader/assets/genasset/main.go:2
i18n/xgettext-go/main_test.go:2
```

These are code generators that spit out a copyright message in the generated file, but don't include a numeric year.

It also looks like we have a few files using `//` single line comments for their copyright notice block, which won't match some of the regexps you're using.

Here are a few questions I'd want to see answers to:

1. Is it worth the hassle of supporting year ranges? If someone wants to know when the copyright on a particular version of a file expires, only the most recent date matters. The earlier years might indicate when copyright expires on earlier versions of the file, but not the current one. The majority of files list a single year, but that could just indicate laziness in updating the copyright message than intentional action.
2. Is there a rationale for changing the copyright years of otherwise unmodified files? If files are considered individual works rather than part of a single larger work, then it may not make sense to update otherwise unmodified files.
3. It's a bit of an edge case, as most people aren't going to be working over the new year, but should this script run with a fixed time zone?
4. If the intent is to keep copyright notices up to date, would it make sense to structure this as a static check to make sure all modified files in a PR have the current year in their copyright notice? What if the PR author is not a Canonical employee?

I don't have answers to all these questions, but they seem like they'd affect what the script does.

**Comment by MiguelPires** [comment]
@mvo5 should we close this for now? It seems like this needs another look and we don't have the bandwidth right now

**Pull request closed without merging**
