### PR TITLE
interfaces/builtin: added support for Token2 U2F keys

### PR DESCRIPTION
**Pull request by stijnb1234**
Superseeds #12662

### CODE REVIEW

**Review by alexmurray — COMMENTED** [review]
@stijnb1234 is there any documentation / resources that we can reference these vendor / product IDs from?

**Comment by stijnb1234** [comment]
> @stijnb1234 is there any documentation / resources that we can reference these vendor / product IDs from?

Can't find a list online. I will request a list from their support.

**Comment by stijnb1234** [comment]
> @stijnb1234 is there any documentation / resources that we can reference these vendor / product IDs from?

The list is now available on: https://www.token2.com/shop/page/using-token2-fido2-keys-under-linux

**Review by alexmurray — APPROVED** [review]
LGTM!

**Comment by stijnb1234** [comment]
@mvo5 I'm sorry, resigned CLA on the correct account, could you re-run it again?

**Pull request merged**
