### PR TITLE
DT-728: fix "being refreshed" notifications

### PR DESCRIPTION
**Pull request by sergio-costas**
The current code in "snap run" checks if the snap is locked due to being refreshed, and waits until it is unlocked before showing a notification saying that the snap is locked.

This, obviously, is wrong: it should check if the snap is locked, and if it is, first show the notification and after that, wait until it is unlocked.

The bug relies in a single piece of code located before the call that checks whether snap is running in a graphics session or a text one. This MR just removes that piece of code and everything works as expected.

Thanks for helping us make a better snapd!
Have you signed the [license agreement](https://www.ubuntu.com/legal/contributors) and read the [contribution guide](https://github.com/snapcore/snapd/blob/master/CONTRIBUTING.md)?

### CODE REVIEW

**Comment by pedronis** [comment]
I need to look at the code again, but the intention was to wait a little bit of time before showing the notification, so that we show the notification only if a noticeable wait is in play. Maybe the code is trying to do that or maybe something else is going on and there is a bug. But the intention is not to show the notification straight away in all cases.

**Comment by sergio-costas** [comment]
The problem is that, with the current code, the notification is never shown...

**Comment by sergio-costas** [comment]
I can add a delay...

**Comment by sergio-costas** [comment]
Changed the code to wait two seconds before showing the notification.

**Comment by sergio-costas** [comment]
Ok, added a delay of 2 seconds. Tell me if you want to set it to a different value.

**Comment by sergio-costas** [comment]
@pedronis  Ok, my fault. I was simulating a lock with `echo refresh > /var/lib/snapd/inhibit/firefox.lock`, but it added a NL at the end of the file and that confused the HINT code.

So we can close this, or we can repurpose this MR to add a little timeout before showing the notification...

**Pull request closed without merging**
