### PR TITLE
tests: run spread tests in fedora-35

### PR DESCRIPTION
**Pull request by sergiocazzolato**
This change adds support to fedora-35 in spread tests and move to manual fedora-33

### CODE REVIEW

**Review by mardy — APPROVED** [review]
LGTM!

**Comment by bboozzoo** [comment]
I'll try to find out what's going on with the failing tests.

**Comment by bboozzoo** [comment]
Ok, so it's as I suspected, it's enough to run just 2 tests, one after another, this is the sequence that triggers it:
```
google:fedora-35-64:tests/main/parallel-install-services
google:fedora-35-64:tests/main/snap-mgmt
```
I think that it's caused by the fact that s-c will remount /var/lib/snapd/snap onto itself to make it a mountpoint and then change the propagation. Need to investigate this further.

**Comment by bboozzoo** [comment]
Yup:
```
google:fedora-35-64 .../tests/main/snap-mgmt# findmnt 
TARGET                        SOURCE                              FSTYPE     OPTIONS
/                             /dev/sda5[/root]                    btrfs      rw,relatime,seclabel,compress=zstd:1,space_cache,subvolid=256,subvol=/root
├─/proc                       proc                                proc       rw,nosuid,nodev,noexec,relatime
│ └─/proc/sys/fs/binfmt_misc  systemd-1                           autofs     rw,relatime,fd=36,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=15352
├─/sys                        sysfs                               sysfs      rw,nosuid,nodev,noexec,relatime,seclabel
│ ├─/sys/kernel/security      securityfs                          securityfs rw,nosuid,nodev,noexec,relatime
│ ├─/sys/fs/cgroup            cgroup2                             cgroup2    rw,nosuid,nodev,noexec,relatime,seclabel,nsdelegate,memory_recursiveprot
│ ├─/sys/fs/pstore            pstore                              pstore     rw,nosuid,nodev,noexec,relatime,seclabel
│ ├─/sys/firmware/efi/efivars efivarfs                            efivarfs   rw,nosuid,nodev,noexec,relatime
│ ├─/sys/fs/bpf               none                                bpf        rw,nosuid,nodev,noexec,relatime,mode=700
│ ├─/sys/fs/selinux           selinuxfs                           selinuxfs  rw,nosuid,noexec,relatime
│ ├─/sys/kernel/debug         debugfs                             debugfs    rw,nosuid,nodev,noexec,relatime,seclabel
│ ├─/sys/kernel/tracing       tracefs                             tracefs    rw,nosuid,nodev,noexec,relatime,seclabel
│ ├─/sys/fs/fuse/connections  fusectl                             fusectl    rw,nosuid,nodev,noexec,relatime
│ └─/sys/kernel/config        configfs                            configfs   rw,nosuid,nodev,noexec,relatime
├─/dev                        devtmpfs                            devtmpfs   rw,nosuid,seclabel,size=1851656k,nr_inodes=462914,mode=755,inode64
│ ├─/dev/shm                  tmpfs                               tmpfs      rw,nosuid,nodev,seclabel,inode64
│ ├─/dev/pts                  devpts                              devpts     rw,nosuid,noexec,relatime,seclabel,gid=5,mode=620,ptmxmode=000
│ ├─/dev/hugepages            hugetlbfs                           hugetlbfs  rw,relatime,seclabel,pagesize=2M
│ └─/dev/mqueue               mqueue                              mqueue     rw,nosuid,nodev,noexec,relatime,seclabel
├─/run                        tmpfs                               tmpfs      rw,nosuid,nodev,seclabel,size=749372k,nr_inodes=819200,mode=755,inode64
│ └─/run/user/0               tmpfs                               tmpfs      rw,nosuid,nodev,relatime,seclabel,size=374684k,nr_inodes=93671,mode=700,inode64
├─/boot                       /dev/sda2                           ext4       rw,relatime,seclabel
│ └─/boot/efi                 /dev/sda1                           vfat       rw,relatime,fmask=0077,dmask=0077,codepage=437,iocharset=ascii,shortname=winnt,errors=remount-ro
├─/home                       /dev/sda5[/home]                    btrfs      rw,relatime,seclabel,compress=zstd:1,space_cache,subvolid=258,subvol=/home
├─/tmp                        tmpfs                               tmpfs      rw,nosuid,nodev,seclabel,size=1873428k,nr_inodes=409600,inode64
├─/var/lib/nfs/rpc_pipefs     sunrpc                              rpc_pipefs rw,relatime
├─/var/lib/snapd/snap         /dev/sda5[/root/var/lib/snapd/snap] btrfs      rw,relatime,seclabel,compress=zstd:1,space_cache,subvolid=256,subvol=/root
└─/var/snap                   /dev/sda5[/root/var/snap]           btrfs      rw,relatime,seclabel,compress=zstd:1,space_cache,subvolid=256,subvol=/root
```

**Comment by bboozzoo** [comment]
What's left to fix is the SELinux denials that popped up after merging current master. I've fixed those in https://github.com/snapcore/snapd/pull/11158

**Review by bboozzoo — APPROVED** [review]
LGTM for the bits I didn't touch

**Pull request merged**
