### PR TITLE
travis-ci: add go import path

### PR DESCRIPTION
**Pull request by sd-hd**
Make travis run on forked branches.

### CODE REVIEW

**Comment by zyga** [comment]
The test failure is puzzling:
```
+ /home/gopath/src/github.com/snapcore/snapd/tests/lib/prepare-restore.sh --restore-project
/bin/bash: line 63: /home/gopath/src/github.com/snapcore/snapd/tests/lib/prepare-restore.sh: No such file or directory
```

**Comment by sd-hd** [comment]
Before adding this path, i got on my private snapd branch errors, like this:

`cannot find package "github.com/snapcore/snapd/tests/lib/fakestore/refresh" `

After adding this, the package are found.

**Comment by sd-hd** [comment]
I just launched another build on my repo, to look at it.

**Comment by sd-hd** [comment]
> The test failure is puzzling:
> 
> ```
> + /home/gopath/src/github.com/snapcore/snapd/tests/lib/prepare-restore.sh --restore-project
> /bin/bash: line 63: /home/gopath/src/github.com/snapcore/snapd/tests/lib/prepare-restore.sh: No such file or directory
> ```

Was this from local spread-test ?

**Comment by anonymouse64** [comment]
@sd-hd that error from @zyga is from the spread tests run against this PR on travis, see https://travis-ci.org/snapcore/snapd/jobs/622552394?utm_medium=notification&utm_source=github_status

**Comment by anonymouse64** [comment]
@sergiocazzolato have you seen this kind of error before?

**Comment by sergiocazzolato** [comment]
@anonymouse64 seems to be a problem in the fedora repo, first time I see this. 
I'll research a bit to see if I can reproduce it here. 
Thanks for letting me know

**Comment by sd-hd** [comment]
@anonymouse64 
@sergiocazzolato 
i found this solution here: https://github.com/ory/hydra/commit/7a60a9abc8798a2b7d93a2cb27f20b5e5eef159a

**Comment by anonymouse64** [comment]
@sd-hd yes I don't think there's a problem with your change, it's just that the spread tests here fail in an unusual way. I'm going to just restart those since all the ubuntu spread tests passed and it was just fedora. For the record though, the full log from this failed spread run is here: https://pastebin.ubuntu.com/p/DNrFTF79cM/

**Comment by bboozzoo** [comment]
@anonymouse64 the tests failed due to COPR being temporarily unavailable. Indeed, it's unrelated to the change.

**Pull request merged**
