### PR TITLE
tests: purge packages installed by accounts, calendar, and contacts interface tests

### PR DESCRIPTION
**Pull request by jhenstridge**
This PR is based on review comments from a different PR, that the tests should clean up any packages they happen to install.  This updates the tests for gnome-online-accounts, and EDS based contacts and calendar interfaces.

### CODE REVIEW

**Comment by zyga** [comment]
```
+ find /etc/dbus-1/system.d -name 'snap.core.*.conf' -execdir rm -f '{}' ';'
find: '/etc/dbus-1/system.d': No such file or directory
```

This looks like the snap-mgmt script needs some love. CC @bboozzoo

**Comment by bboozzoo** [comment]
I've pushed a fix for snap-mgmt to #5420

**Comment by jhenstridge** [comment]
Given that the test failures are just on Arch, I wonder if distro_purge_package is doing something subtly different there, and this change ends up removing more than what was installed?

**Comment by bboozzoo** [comment]
#5420 landed, i've restarted the Travis job and we can merge this one once it's green.

@jhenstridge i think it has to do with which package owns the file/directory. On Arch `/etc/dbus-1/system.d` is not owned by `dbus` package, but rather by individual packages placing their files there. For comparison, in Ubuntu `dbus` owns `/etc/dbus/system.d` (same in Fedora).

**Comment by bboozzoo** [comment]
Something fishy about arch tests, google:arch-linux-64:tests/main/interfaces-location-control runs after google:arch-linux-64:tests/main/interfaces-calendar-service and seems to be hitting a weird problem.

**Pull request closed without merging**
