### PR TITLE
spdx: add EPL-2.0 to licenses.

### PR DESCRIPTION
**Pull request by ralight**
Listed as FSF Free/Libre and OSI Approved on https://spdx.org/licenses/

Signed-off-by: Roger Light <roger@atchoo.org>

### CODE REVIEW

**Comment by pedronis** [comment]
the store and snapd need to agree on the list (we need to revisit implementing some form of https://forum.snapcraft.io/t/keeping-up-with-spdx-license-identifier-updates/7095)

**Comment by zyga** [comment]
@pedronis I honestly believe that just landing this and changing the store is a good improvement of the current state of affairs. I'm very skeptical this will get resolved anytime soon in the store _and_ snapd.

**Comment by pedronis** [comment]
@zyga because atm a license that fails to validate fail Validate, we would get snaps that install on some machines and not others (depending on snapd versions),  we need changes to achieve more consistency before getting there

**Comment by ralight** [comment]
I understand your reasoning here, but am still curious as to how long it might be until adding an EPL-2.0 snap is possible?

**Pull request closed without merging**
