### PR TITLE
cmd/snapd-apparmor: add support for incus (LP: #2042512)

### PR DESCRIPTION
**Pull request by alexmurray**
Add support to snapd-apparmor to properly support running under incus to fix https://bugs.launchpad.net/snapd/+bug/2042512

### CODE REVIEW

**Review by olivercalder — APPROVED** [review]
This looks good to me, thank you!

I see "lxc" and "lxd" appear in a few dozen other files: mostly tests, but also:
```
cmd/snap-confine/mount-support-nvidia.c
cmd/snap-confine/snap-confine.apparmor.in
cmd/snapd-apparmor/main.go
cmd/snapd-apparmor/main_test.go
.coverage/coverage-notags.cov
daemon/api_general_test.go
data/selinux/snappy.te
data/sysctl/rhel7-snap.conf
data/systemd/snapd.service.in
image/preseed/reset.go
interfaces/builtin/kubernetes_support.go
interfaces/builtin/lxd.go
interfaces/builtin/lxd_support.go
interfaces/builtin/lxd_support_test.go
interfaces/builtin/lxd_test.go
interfaces/builtin/mount_observe.go
interfaces/policy/basedeclaration_test.go
interfaces/udev/udev.go
release/release.go
sandbox/cgroup/scanning.go
sandbox/cgroup/scanning_test.go
snap/info_snap_yaml.go
snap/system_usernames.go
store/store_asserts_test.go
syscheck/apparmor_lxd.go
sysconfig/cloudinit_test.go
systemd/emulation.go
systemd/systemd_test.go
wrappers/services_test.go
```

I assume incus is identical enough to lxd at the moment for this to be fine, but should we duplicate some of the other `lx[cd]` awareness to include incus as well?

**Review by ZeyadYasser — APPROVED** [review]
LGTM, Thank you!

**Comment by ZeyadYasser** [comment]
> I assume incus is identical enough to lxd at the moment for this to be fine, but should we duplicate some of the other `lx[cd]` awareness to include incus as well?

I think it might be a good idea to do this incrementally when needed.

**Review by ZeyadYasser — COMMENTED** [review]
Minor nitpick, It would be great if the `TestIsContainerWithInternalPolicy` could be extended to test `incus`.

**Comment by alexmurray** [comment]
Good idea @ZeyadYasser  - updated the `TestIsContainerWithInternalPolicy` test to also test `incus` in https://github.com/snapcore/snapd/pull/13350/commits/aff81847f45ccb7826d979e817bee09e0e7c7637

**Comment by pedronis** [comment]
@alexmurray could you rebase this on master so we get a fresher test run?

**Comment by alexmurray** [comment]
> @alexmurray could you rebase this on master so we get a fresher test run?

Done!

**Comment by alexmurray** [comment]
Only 2 spread test failures, neither appear related to this change from what I can see.

**Review by pedronis — APPROVED** [review]
thanks

**Pull request merged**
