### PR TITLE
release: 2.54.4 changelog

### PR DESCRIPTION
**Pull request by mvo5**
This commit contains the changelog for the 2.54 release.

### CODE REVIEW

**Comment by anonymouse64** [comment]
release/2.54 is broken and missing https://github.com/snapcore/snapd/pull/11248

**Review by anonymouse64 — COMMENTED** [review]
changelog looks good to me, but see my comment about missing a patch

**Comment by mvo5** [comment]
Thanks Ian! Indeed, looks like we need to backport the pre-req first. I asked @mardy to look at https://github.com/snapcore/snapd/pull/11248 for `release/2.54`. It seems not entirely trivial sadly but maybe I'm wrong(?).

**Review by pedronis — APPROVED** [review]
+1

**Review by bboozzoo — APPROVED** [review]
Thanks

**Pull request merged**
