### PR TITLE
packaging/ubuntu-16.04: do not restart snapd.mounts-pre.target

### PR DESCRIPTION
**Pull request by valentindavid**

### CODE REVIEW

**Review by zyga — APPROVED** [review]
Looks good.

Anything else we want to give the same treatment?

**Comment by valentindavid** [comment]
> Anything else we want to give the same treatment?

No. But everything that does not have an `[Install]` section but should still be restarted if started should maybe have `--no-start`. That is `snapd.mounts.target`, `snapd.snap-repair.service`, `snapd.failure.service`.

That would be more correct.  But I can make another PR for that.

**Review by alfonsosanchezbeato — APPROVED** [review]
LGTM

**Review by Meulengracht — APPROVED** [review]
Thank you! This was also bugging me!

**Pull request merged**
