### PR TITLE
cmd/snap-confine: coverity fixes

### PR DESCRIPTION
**Pull request by alexmurray**
Fix a couple minor issues in snap-confine identified by a recent Coverity scan.

### CODE REVIEW

**Review by bboozzoo — APPROVED** [review]
Thank you!

**Comment by alexmurray** [comment]
Oops - thanks for fixing the PR title @bboozzoo  :)

**Review by stolowski — APPROVED** [review]
LGTM, thanks

**Review by mardy — APPROVED** [review]
LGTM, thanks!

Is the coverity report publicly available? Or even internally? :-)

**Comment by alexmurray** [comment]
> Is the coverity report publicly available? Or even internally? :-)

Sure, will see if I can attach it here.

**Comment by alexmurray** [comment]
[cov-errors.log](https://github.com/snapcore/snapd/files/8130289/cov-errors.log)

**Comment by bboozzoo** [comment]
@alexmurray can you merge the latest master and do a push?

**Comment by alexmurray** [comment]
Done - let me know if you would prefer this to be rebased on top of master and then force-pushed instead.

**Pull request merged**
