### PR TITLE
cmd/snap-confine,packaging: import snapd-generated policy

### PR DESCRIPTION
**Pull request by zyga**
This patch allows snap-confine's apparmor profile to be extended with
additional site policy that is generated by snapd. The purpose of the
site policy is so that it can be used to generate some workarounds for
things like $HOME on NFS (the fact of which is not transparent to
confinement, sadly) or encrypted home filesystem. as well as other
quirks that need it specifically in snap-confine's profile (snapd can
already influence profiles of specific snap applications).

It is important to note that the packaging must ensure the directory
/var/lib/snapd/apparmor/snap-confine.d *must* exist or the profile will
fail to compile. I did this for Ubuntu and openSUSE and will coordinate
to make sure this happens in Debian. Other distributions are not
affected as they don't enable AppArmor yet.

Signed-off-by: Zygmunt Krynicki <me@zygoon.pl>

### CODE REVIEW

**Comment by mvo5** [comment]
Ubuntu core tests fail with: 
```
+ su -l -c test-snapd-system-observe-consumer.consumer test

snap-confine has elevated permissions and is not confined but should be. Refusing to continue to avoid permission escalation attacks
```
I assume this is because this dir is missing on the core-image?

**Comment by zyga** [comment]
@mvo5 - yes, this is because adding a subdirectory under /var/lib/snapd/apparmor/snap-confine.d is actually harder than it should be. I'm considering what I can do to avoid that.

Unfortunately apparmor_parser will abort if the directory is not present, I didn't anticipate it would be _hard_ to add a new directory to that structure.

**Comment by zyga** [comment]
I'm marking this as blocked because we have no clear path to adding that directory early at system startup on existing core devices. At the same time this PR is a prerequisite for a priority Canonical commercial project. @mvo5 please advice on suggested action.

**Comment by chipaca** [comment]
@zyga I believe this should now be unblocked

**Comment by mvo5** [comment]
This should be ok to merge now

**Comment by mvo5** [comment]
The test failure in https://travis-ci.org/snapcore/snapd/builds/277188381#L2440 looks real:

**Comment by zyga** [comment]
The failure, whatever it was, got resolved after merging master.

**Pull request merged**
