### PR TITLE
store: small cleanups (more needed)

### PR DESCRIPTION
**Pull request by chipaca**

### CODE REVIEW

**Comment by chipaca** [comment]
This is mostly having a single way of building an `http.Client` in store, and bringing down the number of ways an http.Client is reused from three down to two. Taking it down for one is left for later.

Also opportunistically got rid of a spurious copy.

**Comment by mvo5** [comment]
Looks great, thanks for doing these cleanups!

**Comment by mvo5** [comment]
Unit tests are unhappy, not sure if that is a real failure though.

**Comment by chipaca** [comment]
booo!

yeah, they look real. Fixing...

**Pull request merged**
