### PR TITLE
packaging, systemd: fix socket (re-)start race

### PR DESCRIPTION
**Pull request by xnox**

### CODE REVIEW

**Review by anonymouse64 — APPROVED** [review]
lgtm as a work-around thanks for testing this out

**Review by mvo5 — APPROVED** [review]
\o/

**Review by mvo5 — APPROVED** [review]
Thanks for getting to the bottom of this.

**Comment by mvo5** [comment]
I tested this locally and uploaded it now to jammy to unblock the core22 builds.

**Review by bboozzoo — APPROVED** [review]
Thank you!

**Pull request merged**
