### PR TITLE
progress: switch ansimeter's Spin() to use a spinner

### PR DESCRIPTION
**Pull request by chipaca**
People objected to ansimeter's use of a background throbber, and asked
for a textual spinner instead. I succumb to their wishes.

### CODE REVIEW

**Comment by chipaca** [comment]
For reference: snap install ohmygiraffe

**Comment by chipaca** [comment]
Hmm, looking at the GIF, I'll move the spinner to the other side so the start-of-text doesn't jump around.

GIF-driven development \o/

**Comment by chipaca** [comment]
done: snap install ohmygiraffe

**Comment by mvo5** [comment]
This like the spinner!

**Pull request merged**
