### PR TITLE
wrappers, o/devicestate: remove EnableSnapServices

### PR DESCRIPTION
**Pull request by stolowski**
Remove EnableSnapServices from wrappers and its call from doMarkPreseeded since services are now enabled after install by start-snap-services handler and this workaround is not needed anymore.

### CODE REVIEW

**Review by mvo5 — APPROVED** [review]
Looks fine, we do have spread test coverage for this, right? I.e. we generate a preseed image with a service that we boot and validate that the service runs?

**Review by bboozzoo — APPROVED** [review]
LGTM

**Comment by stolowski** [comment]
> Looks fine, we do have spread test coverage for this, right? I.e. we generate a preseed image with a service that we boot and validate that the service runs?

Yes, we do, nested/manual/preseed test checks lxd services. I discovered however that we don't run nested tests on 20.10 though, only up to 20.04; going to pursue this outside of this PR.

**Review by anonymouse64 — APPROVED** [review]
LGTM, can we merge this now given that we run nested tests on groovy now? Should we merge master here to see the groovy nested tests run here?

**Comment by stolowski** [comment]
> LGTM, can we merge this now given that we run nested tests on groovy now? Should we merge master here to see the groovy nested tests run here?

I'll wait for the other PR to land and merge/re-run this one. I think it should be fine (I tested this manually on 20.10 for nested/snap-preseed when opening the two), but extra run won't hurt.

**Pull request merged**
