### PR TITLE
interfaces: bluez: add a few more tests to verify interface connection works

### PR DESCRIPTION
**Pull request by morphis**
https://github.com/snapcore/snapd/pull/1676 fixed a problem which was a regression with the bluez. This PR adds tests to ensure this doesn't happen again.

### CODE REVIEW

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by zyga** [comment]
Looks good. LGTM when tests pass

**Comment by mvo5** [comment]
:+1:

**Pull request merged**
