### PR TITLE
s/apparmor/notify/listener: fix concurrency test on slow single-core machines

### PR DESCRIPTION
**Pull request by olivercalder**
Thanks @ZeyadYasser for spotting the failure on https://github.com/snapcore/snapd/actions/runs/7486097781/job/20376253469?pr=13469

### CODE REVIEW

**Review by ZeyadYasser — APPROVED** [review]
LGTM, Thanks!

**Review by andrewphelpsj — APPROVED** [review]
Thanks for the changes!

**Comment by olivercalder** [comment]
Didn't mean to re-request @ZeyadYasser and @andrewphelpsj , I think GitHub auto-requested you again when I added Samuele because I hadn't refreshed my page. Sorry!

**Review by andrewphelpsj — APPROVED** [review]

**Review by ZeyadYasser — APPROVED** [review]

**Review by pedronis — APPROVED** [review]
+1

**Pull request merged**
