### PR TITLE
gadget/install: do not assume dm device has same block size as disk

### PR DESCRIPTION
**Pull request by valentindavid**

### CODE REVIEW

**Comment by pedronis** [comment]
@valentindavid please follow the convention that summary messages are lowercase after the :

**Review by mardy — APPROVED** [review]
LGTM!

**Review by mvo5 — COMMENTED** [review]
Thank you! A unit test for this would be ideal.

**Review by mvo5 — APPROVED** [review]

**Review by bboozzoo — APPROVED** [review]
LGTM

**Pull request merged**
