### PR TITLE
spdx: update licenses to current data

### PR DESCRIPTION
**Pull request by mvo5**
The spdx licenses get updated periodically. This PR updates them
and also add hints how to trivially out-generate them. We could
do more fancy stuff here too (use go:generate etc) but YAGNI.

(I also removed the osi var which we don't use)

### CODE REVIEW

**Comment by pedronis** [comment]
There is some discussion in the forum(https://forum.snapcraft.io/t/keeping-up-with-spdx-license-identifier-updates/7095/4) that we should either update them in sync with the store, or keep what we have for a long span.

**Comment by mvo5** [comment]
I added my 2¢ in https://forum.snapcraft.io/t/keeping-up-with-spdx-license-identifier-updates/7095/4 - I'm not sure if we really need to sync the licenses with the store (but maybe I just don't have enough data). I would assume the list changes slowly and people don't adopt new licenses immediately in huge troves. Anyway, if we want to do something more complicated I'm happy to close this PR again.

**Comment by Roadmaster** [comment]
> " I would assume the list changes slowly and people don't adopt new licenses immediately in huge troves".

Apologies for barging in!

This is a reasonable assumption, but even then, we still need to ensure both snapd and the store are (eventually) using the same list. One thing we can do is periodically agree on a specific revision/commit of the spdx license list and refresh both the store and snapd with that. If people want to use a not-yet-supported identifier they'd have to wait for the next periodic update.

What would happen if a user tries to install/refresh a snap whose license is not yet supported by its snapd? (which in theory can only happen within one snapd refresh window of the store/snapd having updated their list). Would snapd reject the update/installation? In the case of refreshes, this would just delay the refresh by 1-2 refresh windows, but in the case of an install, users may be baffled by the inability to install the snap because "license is unknown to snapd" or similar.

Back when https://bugs.launchpad.net/snapstore/+bug/1781013 was filed, I did some work that would let the store do what I described above (putting a specific commit of the SPDX license data on the store to use for license validation, and this only updates when we manually move the copy of SPDX data to whichever commit we agree to), but it was never merged because we also needed to ensure snapd agreed on the list of valid licenses.

**Comment by pedronis** [comment]
do we reject snaps on unrecognized licenses on install?

**Comment by Roadmaster** [comment]
> do we reject snaps on unrecognized licenses on install?

We do. I built a snap with:

`license: unfathomable
`
and I get:

```
$ snap install --dangerous badlic.snap 
error: cannot read snap file: cannot validate license "unfathomable": unknown
       license: unfathomable

```

**Comment by mvo5** [comment]
This is an unfortunate situation because older snapds that do not reexec (e.g. on fedora) will get out of sync.

**Pull request closed without merging**
