### PR TITLE
interfaces/desktop: allow DBus access to plasmashell

### PR DESCRIPTION
**Pull request by alexmurray**
apparmor in Ubuntu 24.04 LTS introduces an AppArmor profile for KDEs plasmashell
called "plasmashell". As such, the various DBus objects are now implemented
by a process that has the apparmor label "plasmashell" instead of
"unconfined" (since previously it did not have an AppArmor profile).

Extend the DBus rules for these objects to include this new
peer label to allow snaps to send notifications as before.

Fixes LP: #2056696

Signed-off-by: Alex Murray <alex.murray@canonical.com>

### CODE REVIEW

**Comment by ernestl** [comment]
**NOTE: Needs additional work to fully solve the LP bug**

**Comment by alexmurray** [comment]
To clarify the comment from @ernestl above - the LP bug mentions two issues - one for desktop notifications, and the other from system tray access - this PR solves the first issue. A subsequent PR will be sent if/when I can reproduce the issue around the system tray. So this PR can be considered complete in its own right (but just not sufficient to completely resolve that single LP bug).

**Review by bboozzoo — APPROVED** [review]
Thank you

**Comment by alexmurray** [comment]
Added two additional commits which resolve the remaining issues from the Launchpad bug. This is now ready for review and merging.

**Review by bboozzoo — APPROVED** [review]
Still LGTM

**Review by zyga — APPROVED** [review]
LGTM

**Pull request merged**
