### PR TITLE
interfaces: add mpris interface

### PR DESCRIPTION
**Pull request by jdstrand**
Proposing this now so it gets wider review. Some notes:

This implements a slot side and a plugs side. This is what vlc would use:
```
apps:
  vlc:
    ...
    slots:
    - mpris
```

This allows vlc to dbus bind to "org.mpris.MediaPlayer2.@{SNAP_NAME}{,.*}" which matches https://specifications.freedesktop.org/mpris-spec/latest/. I plan to adjust to use an attribute for name to override SNAP_NAME, but this could be committed as is and work for vlc.

mpris clients would do something like this:
```
apps:
   mpris-client:
      ...
      plugs: [mpris, ...]
```

With the above I am able to control vlc over dbus with d-feet (unconfined) and with a script in vlc/extras/misc confined (for the relevant dbus bits).

Then see:

```
$ snap interfaces
...
vlc:mpris            mpris-client
```

In addition to adding the dbus bind interface attribute for "name" I also have testsuite fixes, however, the basic policy is working well.

### CODE REVIEW

**Comment by zyga** [comment]
I'd like to ask to swap plug/slot around because currently only slots can be implicitly added to the core snap.

**Comment by jdstrand** [comment]
@zyga - this isn't an implicit slot for ubuntu-core though. A snap can either be a player or be a remote for a player. A player (eg, vlc) would declare the slots side because it implements the mpris2 specification and a remote (eg, some client) would declare a plugs side that allows controlling players. Then the connect allows a particular remote to control a particular player.

**Comment by jdstrand** [comment]
retest this please

**Comment by mvo5** [comment]
:+1:

**Pull request merged**
