### PR TITLE
vendor: refresh everything

### PR DESCRIPTION
**Pull request by zyga**
This patch refreshes all of the vendorized dependencies to their latest
versions. This patch should be landed only after careful review.

Signed-off-by: Zygmunt Krynicki <zygmunt.krynicki@canonical.com>

### CODE REVIEW

**Comment by zyga** [comment]
This fails with `src/github.com/snapcore/snapd/vendor/golang.org/x/crypto/acme/acme.go:18:2: cannot find package "context" in any of:`

**Comment by pedronis** [comment]
@zyga the issue is that upstreams will start legitimately to assume go >1.6 :/

if that is limited we can cheat and we can split the x/crypto deps to just the bits we need, assuming they don't depend on acme

**Comment by stolowski** [comment]
Hmm shouldn't we carefully select what to upgrade on case-by-case basis and only when we know of a problem that particular update fixes? Plus, after checking the bugtrackers of these projects for reports of any recent open issues or regressions? Just a little concerned about upgrading to latest and greatest without some reasearch. Please ignore me if you did resarch on that already!

**Comment by niemeyer** [comment]
Let's please be a bit more careful about the update. We probably don't want all at once, and indeed we should carefully review what has changed.

**Pull request closed without merging**
