### PR TITLE
usersession/userd: add zoommtg url support

### PR DESCRIPTION
**Pull request by anonymouse64**
Originally committed by @troyready in https://github.com/snapcore/snapd/pull/8254

### CODE REVIEW

**Comment by mvo5** [comment]
What's the status here, do we need jamie or can this go in as is?

**Comment by anonymouse64** [comment]
@mvo5 waiting on @jdstrand since Janie didn't approve the original one

**Comment by jdstrand** [comment]
This seemed blocked on me so since I provided my review, I removed the blocked tag.

**Comment by anonymouse64** [comment]
> That said, should we also include "zoomus"? 

@jdstrand let's say no until someone asks us for it. I haven't seen it in the wild either

**Comment by nermolov** [comment]
Why is this the only custom url scheme allowed through, while there are many many other custom url schemes that are still being blocked?

**Comment by troyready** [comment]
@nermolov there's a [broad fix in a testing release now](https://github.com/snapcore/snapd/pull/8761#issuecomment-636191765) that should finally address the core URL problem (instead of the previous strategy of whitelisting them).

(I hesitated to comment here on a closed PR & pollute it with comment spam, but since this is a particularly important issue I think it's relevant to cross-post)

**Pull request merged**
