### PR TITLE
tests: simplify the tests.cleanup tool

### PR DESCRIPTION
**Pull request by sergiocazzolato**
The idea of this change is to avoid preparing and make automatic
restoration of the defered commands.
In case it is required the restore can be invoqued manually.

### CODE REVIEW

**Review by anonymouse64 — APPROVED** [review]
nice, I like this change thank you

**Review by mvo5 — APPROVED** [review]
This is nice, thank you!

**Comment by mvo5** [comment]
The failure in the spread tests looks real:
```
2021-05-17T23:04:27.3544918Z ##[error]2021-05-17 23:04:27 Error executing google:ubuntu-16.04-64:tests/lib/tools/suite/tests.cleanup (may172233-463574) : 
2021-05-17T23:04:27.3583525Z -----
2021-05-17T23:04:27.3584315Z + shellcheck /home/gopath/src/github.com/snapcore/snapd/tests/lib/tools/tests.cleanup
2021-05-17T23:04:27.3585494Z + MATCH 'usage: tests.cleanup defer <cmd> \[args\]'
2021-05-17T23:04:27.3586072Z + tests.cleanup
2021-05-17T23:04:27.3586814Z + MATCH '       tests.cleanup pop'
2021-05-17T23:04:27.3587326Z + tests.cleanup
2021-05-17T23:04:27.3588090Z + MATCH '       tests.cleanup restore'
2021-05-17T23:04:27.3588617Z + tests.cleanup
2021-05-17T23:04:27.3589384Z + MATCH 'usage: tests.cleanup'
2021-05-17T23:04:27.3590160Z + tests.cleanup --help
2021-05-17T23:04:27.3590918Z + MATCH 'usage: tests.cleanup'
2021-05-17T23:04:27.3592688Z + tests.cleanup -h
2021-05-17T23:04:27.3609409Z + MATCH 'tests.cleanup: unknown option --foo'
2021-05-17T23:04:27.3610468Z + tests.cleanup --foo
2021-05-17T23:04:27.3611375Z + MATCH 'tests.cleanup: unknown command foo'
2021-05-17T23:04:27.3611953Z + tests.cleanup foo
2021-05-17T23:04:27.3612468Z + tests.cleanup defer echo one
2021-05-17T23:04:27.3613029Z + tests.cleanup defer echo two
2021-05-17T23:04:27.3613596Z + tests.cleanup defer echo three
2021-05-17T23:04:27.3614143Z + tests.cleanup restore
2021-05-17T23:04:27.3615831Z + diff -u restore.log -
2021-05-17T23:04:27.3616376Z + tests.cleanup restore
2021-05-17T23:04:27.3616889Z + tests.cleanup restore
2021-05-17T23:04:27.3617698Z + test -e defer.sh
2021-05-17T23:04:27.3618246Z -----
```
probably just a test update needed or something.

**Comment by mvo5** [comment]
Thank you!

**Pull request merged**
