### PR TITLE
snapstate: add daemon-reload to fix autopkgtest on yakkety

### PR DESCRIPTION
**Pull request by mvo5**
This branch fixes the autopkgtest failures in yakkety (at least it did in my local autopkgtest run).

### CODE REVIEW

**Comment by elopio** [comment]
Green execution in yakkety:
http://162.213.35.179:8080/job/github-snappy-autopkgtest-cloud/3406/console
:+1:

**Comment by pedronis** [comment]
is this a bug in yakkety systemd or a bug in snapd? if the former we should file a bug and have the bug number in those comments, if the 2nd a better explanation of what are the systemd rules would also be welcome

**Comment by mvo5** [comment]
This is a bug in our code, I'm not sure why we do not see this in xenial, there is a different version in yakkety (230-7) compared to xenial (229-4ubuntu7). The basic rule of systemd is that if a unit file got added or changed the daemon needs to be reloaded. We also do it on remove to ensure its really out of the systemd memory.

**Comment by pedronis** [comment]
@mvo5  ok, so I think comments along "we added/removed a unit therefore we need to reload ..." would be better/clearer for future readers/maintainers

**Comment by chipaca** [comment]
:+1: to this to fix the issue and move on
However, we should at some point come back and make sure we're only doing a daemon-reload once per change, if that makes sense

**Pull request merged**
