### PR TITLE
store: retry on connection reset too

### PR DESCRIPTION
**Pull request by mvo5**
Apparently the CDN is sometimes reset the connections. In this case we should at least retry instead of giving up right away.

Ref: https://bugs.launchpad.net/software-center-agent/+bug/1617765

### CODE REVIEW

**Comment by lool** [comment]
Notes to self: retrying indefinitely super big downloads after a connection reset would be improper, but there's a retry limit implemented around the retry (store/retry.go):
var defaultRetryStrategy = retry.LimitCount(5, retry.LimitTime(33*time.Second,
        retry.Exponential{
                Initial: 100 * time.Millisecond,
                Factor:  2.5,
        },
))

**Comment by mvo5** [comment]
@lool there is also range-request support in the code, so it will not re-download bits that already are on disk.

**Comment by zyga** [comment]
The test failure looks significant. I wonder if I'm reading that correctly, is this `getsockopt` failing?

**Comment by ktiedt** [comment]
How can people with this problem test this w/o starting over from scratch with a new boot image and re-configuring? Hopefully there is a simple way?

Thanks!

**Pull request merged**
