### PR TITLE
client, cmd: change buy command to match UX document

### PR DESCRIPTION
**Pull request by pete-woods**
- Helpful error messages for no payment method / not accepted TOS.
- New messages when purchase is successful.
- No-longer expose payment methods to the user.
- Use new /v2/buy/ready endpoint for pre-flight check instead of /v2/buy/methods.

### CODE REVIEW

**Comment by chipaca** [comment]
I think [this link](https://github.com/pete-woods/snapd/compare/buy-cli-ux-changes...pete-woods:snapd-use-new-store-purchase-apis) should be useful to reviewers of the delta

**Comment by pete-woods** [comment]
Maybe more useful on the other PR? Posting the link there too..

**Comment by chipaca** [comment]
hah! yes i meant to post it in the other one.

**Comment by niemeyer** [comment]
LGTM, thanks Pete. I'm merging this so we can get a clean state on #2011 for commenting.

**Pull request merged**
