### PR TITLE
snap: disable support for socket activation

### PR DESCRIPTION
**Pull request by stolowski**
Removed support or ListeanStream, Socket and SocketMode options of snap.yaml (socket-based activation).

### CODE REVIEW

**Comment by mvo5** [comment]
If nothing is using it, +1. What is the docker snap doing? Back in the day this got added for the previous incarnation of the docker snap.

**Comment by stolowski** [comment]
The currently published docker v1.11.2-9 doesn't use it. I'm waiting for Mathias to find out if they have a way to check all snaps for me on the store side. Unfortunately the search endpoint returns yamls for only a fraction of available snaps, apparently because the functionality for indexing of yamls was not available initially.

**Comment by morphis** [comment]
Why are dropping support for this? There is a valid bug from the LXD project to support socket activation. See https://bugs.launchpad.net/snappy/+bug/1612440

Is this going to come back in a different form?

**Comment by stolowski** [comment]
Hi Simon, yes, this is exactly the plan - to replace it with something more robust (more in line with what that bug suggests).

**Comment by morphis** [comment]
@stolowski Thanks for the info!

**Comment by galgalesh** [comment]
Just want to bring to your attention that socket activation is still described in the docs, after being removed for more than 1 year.

https://docs.snapcraft.io/build-snaps/syntax#listen-stream

**Comment by ogra1** [comment]
https://github.com/snapcore/snapd/pull/3916 added it back ...

**Comment by pvanloo** [comment]
@ogra1 It seems that the schema currently does not support it, which led to the confusion.

https://github.com/snapcore/snapcraft/blob/master/schema/snapcraft.yaml

**Comment by ogra1** [comment]
@pvanloo  the snapcraft part of the implementation admittedly only landed 12 days ago ...
(snapcraft in the edge channel should have it already)

https://github.com/albertodonato/snapcraft/commit/4997673b9ccf3b5c74a1094f1cb3e182641cdc03

**Comment by pvanloo** [comment]
@ogra1 Thanks for the follow up, I'll add the updated syntax to the docs.

**Pull request merged**
