### PR TITLE
tests: fix unity test

### PR DESCRIPTION
**Pull request by fgimenez**
The unity test is failing with:
```
Setting up upstart (1.13.2-0ubuntu21.1) ...
Configuration file '/etc/init/tty1.conf'
 ==> File on system created by you or by a script.
 ==> File also in package provided by package maintainer.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** tty1.conf (Y/I/N/O/D/Z) [default=N] ? dpkg: error processing package upstart (--configure):
```
The `/etc/init/tty1.conf` file is present by default in the linode images, and upstart, which gets installed as a dependency of the required packages and ships that file, complains when finds it in place. These changes move `/etc/init/tty1.conf` during the test.

### CODE REVIEW

**Comment by stolowski** [comment]
How about dpkg-divert? I think that would solve it cleanly with no need for backup and restoration?

**Comment by zyga** [comment]
How about setting DEBCONF_FRONTENT=noninteractive? @mvo5 ?

**Comment by fgimenez** [comment]
@zyga thanks for the comment, I think you suggested this before, that would mask which file is making the clean install fail, maybe we could remove it from the image?

**Comment by zyga** [comment]
@fgimenez that would just make dpkg pick some (default) answer for such questions. Not sure if that's what we want (I suspect the default is to keep the changed file).

**Comment by fgimenez** [comment]
@zyga yep, sorry for being super picky here but if we add `DEBCONF_FRONTEND=noninteractive` and eventually some other file is changed or moved somehow we wouldn't notice it, with the current settings the install process would fail showing that something is wrong..

I don't really understand how this `/etc/init/tty1.conf` file ended up in the ubuntu-16.04-64 image in the first place, this file is provided by upstart and this package is not installed in the image, @niemeyer any idea about the reason for this? Also, could we remove that file from the image?

**Comment by mvo5** [comment]
There are some misconceptions here, the conffile prompt comes from `dpkg` which does not use debconf and does therefore not honor `DEBIAN_FRONTEND` (also note its DEBIAN not DEBCONF). Some packages use `ucf` which will use debconf for configuration file handling. But that is a separate application that works outside of dpkg.

**Pull request merged**
