### PR TITLE
interfaces: add upower-observe interface (LP: #1595813)

### PR DESCRIPTION
**Pull request by jdstrand**

### CODE REVIEW

**Comment by mvo5** [comment]
:+1:

**Comment by morphis** [comment]
LGTM, a small manual test case would be nice.

**Comment by jdstrand** [comment]
I believe I addressed all review feedback.

**Comment by morphis** [comment]
LGTM

**Comment by jdstrand** [comment]
Committing per IRC conversation with @mvo5 (PR from core committer, +1 from core committer, +1 from trusted community)

**Pull request merged**
