### PR TITLE
cmd/snap: display snap license information

### PR DESCRIPTION
**Pull request by bboozzoo**
I'd appreciate comments on what to display when license information is unavailable.

### CODE REVIEW

**Comment by bboozzoo** [comment]
AFAIU we're doing a store round trip each time. For instance some snaps that are not installed on my host look like this:

```
$ ./test-snap info cassandra
name:      cassandra
summary:   Cassandra distributed database
publisher: snapcrafters
contact:   https://github.com/snapcrafters/cassandra/issues
license:   Apache-2.0
description: |
  The Apache Cassandra database
snap-id:     kSMhyGixymOj6ZTMEY9vDdAFhfgg23KE
channels:
  stable:    3.7           (66)  68MB -
  candidate: 3.10-SNAPSHOT (19)  69MB -
  beta:      ↑
  edge:      3.10-SNAPSHOT (211) 67MB -
$ ./test-snap info postgresql10
name:      postgresql10
summary:   PostgreSQL is a powerful, open source object-relational database system.
publisher: cmd
license:   Proprietary
description: |
  PostgreSQL is a powerful, open source object-relational database system. It
  has more than 15 years of active development and a proven architecture that
  has earned it a strong reputation for reliability, data integrity, and
  correctness.
snap-id:     W7TagWOq55vJphD3Ek4ZUtQytGRMeQqK
channels:
  stable:    10.1 (34) 36MB -
  candidate: ↑
  beta:      ↑
  edge:      ↑
$ ./test-snap info vlc
name:      vlc
summary:   The ultimate media player
publisher: videolan
contact:   https://www.videolan.org/support/
license:   GPL-2.0+
description: |
  VLC is the VideoLAN project's media player.

  Completely open source and privacy-friendly, it plays every multimedia file
  and streams.

  It notably plays MKV, MP4, MPEG, MPEG-2, MPEG-4, DivX, MOV, WMV, QuickTime,
  WebM, FLAC, MP3, Ogg/Vorbis files, BluRays, DVDs, VCDs, podcasts, and
  multimedia streams from various network sources. It supports subtitles, closed
  captions and is translated in numerous languages.
snap-id:     RT9mcUhVsRYrDLG8qnvGiy26NKvv6Qkd
channels:
  stable:    3.0.0-rc7              (116) 202MB -
  candidate: 3.0.0-rc7              (116) 202MB -
  beta:      3.0.0-rc7-13-ge9dd62e  (126) 202MB -
  edge:      4.0.0-dev-864-gff0d2f1 (125) 201MB -
```

**Comment by mvo5** [comment]
Thanks, that is a good first step! AFAICT we loose the license information once the snap is installed. That  needs fixing too. It fine in a followup though.

**Comment by chipaca** [comment]
For many of these metadata fields, the store is the 'source of truth', with what snapd has locally (whether from snap.yaml or sideinfo) being a convenient fallback.

The license is different: a publisher can't change the license of something that's already been distributed. The license of a locally-installed snap is the one in snap.yaml. If the snap.yaml doesn't have a license, the license of that snap is unknown (not "undefined", I think, which seems to point the finger at the publisher a bit too much; unknown feels more honest). I'd be fine with just not showing the license field if it's not set in the yaml of a locally installed snap, if that's felt to be cleaner.

Having said this, it should be obvious that the store shouldn't be allowing publishers to touch the license field at all; it comes from the yaml, always, and the only way of changing it should be by pushing a new snap.

Otherwise I think we need support in snapd and all frontends to let users accept license changes, which is a nightmare (whether we need that anyway to notify of license changes on refresh, like we had in snappy in 15, is up for debate, but even so allowing the store to change it would make the workflow a lot harder).

**Comment by chipaca** [comment]
Filed https://bugs.launchpad.net/snapstore/+bug/1745335 about license changeability. Note gustavo also rasied this in the forum discussion on [Snap license metadata](https://forum.snapcraft.io/t/snap-license-metadata/856/17?u=chipaca).

**Pull request merged**
