### PR TITLE
firstboot: generate netplan config rather than ifupdown

### PR DESCRIPTION
**Pull request by mwhudson**
This is one of the last things we need to do to start using console-conf.

### CODE REVIEW

**Comment by mwhudson** [comment]
retest this please

**Comment by mvo5** [comment]
Thanks, the `ubuntu-core-16` spread test fails to reconnect. This can be multiple things, but given that nature of this change I wonder if netplan is fully working in the image yet. Are all package installed to make this work? Or do we need to add something (netplan?) to the image first?

**Comment by mvo5** [comment]
Code itself looks fine, setting to blocked until we know if additional packages are required.

**Comment by mvo5** [comment]
Fwiw (if someone else reviews this). More info about netplan: https://lists.ubuntu.com/archives/ubuntu-devel/2016-July/039464.html

**Comment by mwhudson** [comment]
> Thanks, the ubuntu-core-16 spread test fails to reconnect. This can be multiple things, but given that nature of this change I wonder if netplan is fully working in the image yet. Are all package installed to make this work? Or do we need to add something (netplan?) to the image first?

That's possible -- how is that image made? netplan has been in the os snap built by the livecd-rootfs from the snappy-dev/image ppa for a week or so. But maybe there is somewhere else I need to fiddle!

**Comment by mwhudson** [comment]
So some thoughts. It was discussed that the default should be to run dhcp on all wired interfaces. This can be achieved with a netplan config like:

```
network:
 version: 2
 ethernets:
  all:
   dhcp4: true
   match:
    name: "*"
```

(I've tested that this config works, even with devices hotplugged via the qemu monitor, which is nice).

This is entirely static though, so having it created by snapd.firstboot.service seems daft, we should just bake it into the image somehow. And then we can get rid of this PR and replace it with one that just deletes some code.

One thing left is that it is desired that the gadget snap can override this, but currently how it would do this is not specified.

**Comment by mwhudson** [comment]
(Doing almost anything at all in this area is somewhat blocked on making changes to images and getting snapd CI to use a newer image, btw)

**Comment by mwhudson** [comment]
I've re-worked this to use the netplan config I proposed. This is nicely simpler than the existing code :-)

Still blocked on a new image being used by CI though.

**Comment by mvo5** [comment]
:+1: I like this a lot, the fact that we do not enable whatever happend to be the ethernet at boot time (with the races and all that) makes me very happy.

**Comment by mvo5** [comment]
One issue here is that nplan is not shipping the `/etc/netplan` dir, I investigate what else might be problematic.

**Comment by mvo5** [comment]
https://github.com/snapcore/snapd/pull/1758 has some fixes for this branch that work in my qemu spread environment. For me this is good to go once tests are green. Very happy about this branch.

**Comment by mwhudson** [comment]
Thanks, sorry for all the YAML typos!

**Pull request merged**
