### PR TITLE
i/builtin: adds new JaCarta U2F usb token product id

### PR DESCRIPTION
**Pull request by chkhanu**
I have a real device - [JaCarta U2F token (usb)](https://www.aladdin-rd.ru/catalog/jacarta_u2f/) - and can confirm, that it has the following characteristics:
idVendor=24dc, idProduct=0501

### CODE REVIEW

**Review by alexmurray — COMMENTED** [review]
Is there any publicly available documentation which references this new ProductID?

**Comment by chkhanu** [comment]
Well, I contacted aladdin@aladdin.ru with a request to publish it, waiting for their response. If it is possible, you may also send a request to them, to make it happen faster.

For now, the only guide (in Russian) I've found is this: https://aladdin-rd.ru/upload/guides/Google_U2F_User_Guide.pdf
There on page 35 is noted, that to make it work in Linux a rule within udev is required, from there you can conclude, that this is a valid idVendor/idProduct pair.

**Comment by chkhanu** [comment]
Also, you can see it referenced here:
https://github.com/Yubico/libu2f-host/blob/09e98aacdf8d7b88108ee03f388a1c02f636e91b/70-u2f.rules#L35

**Review by alexmurray — APPROVED** [review]
Thanks for the updated details - the reference to the upstream libu2f-host repo is good enough for me. LGTM!

**Comment by chkhanu** [comment]
Sorry for being impatient, but is there any one else who could review/approve and merge this? It is a really simple MR.
@alexmurray @pedronis

**Comment by alexmurray** [comment]
Is there any public documentation that references this additional product id?

**Comment by chkhanu** [comment]
> For now, the only guide (in Russian) I've found is this: https://aladdin-rd.ru/upload/guides/Google_U2F_User_Guide.pdf There on page 33 is noted, that to make it work in Linux a rule within udev is required, from there you can conclude, that this is a valid idVendor/idProduct pair.

There it is - in Russian, but can be translated via Google Translate.

To be clear - I'm just asking for a second approvement, already got one from @ alexmurray

**Review by pedronis — APPROVED** [review]

**Comment by Meulengracht** [comment]
@chkhanu you need to sign the CLA and also please fix the failing tests.

**Comment by zyga** [comment]
@chkhanu unless you sign the CLA this will not make it for the 2.62 release

**Comment by chkhanu** [comment]
signed cla, rebased

**Comment by chkhanu** [comment]
Could anyone tell me, what's the problem with this CLA signing? Username & email address are the same that used within github and ubuntu one accounts, so I don't know what's wrong with it.

This is really too much hassle for the 5 bytes of "new" code...

**Comment by chkhanu** [comment]
joined, rebased & pushed..

**Pull request merged**
