### PR TITLE
opengl: allow libdrm data files

### PR DESCRIPTION
**Pull request by Saviq**
Since libdrm (and -common) is now part of core22, it only makes sense to allow this.

### CODE REVIEW

**Review by alexmurray — COMMENTED** [review]
On jammy the only file under `/usr/share/libdrm` is `/usr/share/libdrm/amdgpu.ids` from `libdrm-common` - I would prefer to keep this limited to just that file *unless* we know there will likely be other similar files added in the future.

**Review by alexmurray — APPROVED** [review]
LGTM!

**Review by MiguelPires — APPROVED** [review]
LGTM

**Comment by olivercalder** [comment]
Thanks! I have a possibly-related question I'm hoping you might have insight about.

I just noticed last night that the VLC on my machine segfaults on launch, and the first line of the stderr says `/usr/share/libdrm/amdgpu.ids: No such file or directory`. Complete output here: https://pastebin.canonical.com/p/jZz8K6N8Bc/  Does this patch relate to recent changes that you think may have been responsible for this new bug?

I was on the snapd edge/prompting branch and I am using lunar with kernel `6.2.0-20-generic #20+prompt47-Ubuntu` and `apparmor/lunar,now 3.0.8-1ubuntu2+prompt48`, but the same error occurs for me on snapd latest/stable as well.

**Comment by Saviq** [comment]
@olivercalder hey, the VLC snap is `base: core18`, so it has to bring `amdgpu.ids` in the snap (and it does):

```plain
$ snap run --shell vlc -c 'ls $SNAP/usr/share/libdrm/amdgpu.ids'
/snap/vlc/3078/usr/share/libdrm/amdgpu.ids
```

But they don't lay it out as they should:

```plain
$ snap run --shell vlc -c 'ls /usr/share/libdrm/amdgpu.ids' 
ls: cannot access '/usr/share/libdrm/amdgpu.ids': No such file or directory
```

They need this layout in the snap:
```plain
layouts:
  /usr/share/libdrm:
    symlink: $SNAP/graphics/libdrm
```

You could try that as a fix by downloading VLC, `unsquashfs …`'ing it, adding the above layout and then `snap try squashfs-root`.

**Pull request merged**
