### PR TITLE
interfaces/seccomp/template.go: allow copy_file_range

### PR DESCRIPTION
**Pull request by anonymouse64**
This was recently introduced as an optimization to Go 1.15, and so apps that
start compiling may start to try and use it.

Note that Go 1.15 does currently fall back to using other methods if copy_file_range
returns EPERM so that apps that get denied usage of copy_file_range will fallback
to potentially slower implementations. (originally upon Go 1.15 release there
was not a fallback implementation and the app would just crash returning a non-nil
error up the stack).

See https://github.com/golang/go/issues/40893 and
https://go-review.googlesource.com/c/go/+/249257/ for more details on the Go
issue and the fallback implementation.

### CODE REVIEW

**Review by mvo5 — APPROVED** [review]
Thank you

**Review by bboozzoo — APPROVED** [review]

**Comment by bboozzoo** [comment]
Looks like the syscall was introduced a while back, and IMO being a genuinely useful one should have been allowed by the base template. This raises a question whether we might have missed other syscalls? If so, could we somehow track which syscalls were accounted for but not allowed in the base template, and which ones are deliberately not part of of the template.

**Comment by anonymouse64** [comment]
> This raises a question whether we might have missed other syscalls?

IMO, since syscalls can be time-consuming to review in bulk, I think taking a "wait and see" approach is best, since a snap that tries to use these syscalls will get EPERM, and it seems to me that most implementations such as in Go are not expecting to run in confinement, they will hard fail and we will eventually find out and can add support for them then. 

I guess the issue with this approach is a world where folks see that a syscall is not allowed due to confinement and quickly turn around and fallback to using other syscalls (as it seems Golang did), in which case users/app developers don't have enough time being blocked by this to raise it to our attention. I think the reason why Go is not a counter-example to my above rule is that it seems like they didn't find out about it until after a release and thus were pressured to fix it quickly. I'm not sure other types of app developers will be under such pressure, but perhaps I'm just self-justifying here to avoid more work in reviewing syscalls :-)

**Review by jdstrand — CHANGES_REQUESTED** [review]
This looks ok to me. It takes FDs as arguments and they must be correctly set. For them to be correctly set, the files must be `open()`d, which is mediated by standard apparmor 'r' and 'w'. copy_file_range() does have a `flags` argument, which is currently unused, but the original patchset did try to utilize this. IMO, we should guard against future unknown use of flags that might require apparmor changes to properly mediate, so please change this to be:
```
copy_file_range - - - - 0
```

While I did not test this particular rule, I did test the behavior of the glibc wrapper and `syscall(__NR_copy_file_range, ...)` under apparmor.

If you choose to not make this change, please have @alexmurray or @jrjohansen comment.

Thanks!

**Review by alexmurray — CHANGES_REQUESTED** [review]
Jamie's suggestion to be defensive with the flags argument makes a lot of sense - this sounds like a good approach to take given we don't know how flags may change the behaviour of this syscall in the future so this allows us to ensure it doesn't unexpectedly change behaviour later down the track if newer kernels / libc's etc provide additional functionality.

In this case, can the existing comment also be adjusted to document this 0 flags parameter so that if / when we have to review it again in the future we can easily refer back to this current discussion? Thanks.

**Comment by bboozzoo** [comment]
AFAICT the rule should then be (6th argument is the flags):
```
#copy_file_range(int fd_in, loff_t *off_in,
#                               int fd_out, loff_t *off_out,
#                               size_t len, unsigned int flags);
copy_file_range - - - - - 0
```

**Review by anonymouse64 — COMMENTED** [review]
@bboozzoo's push lgtm

**Comment by jdstrand** [comment]
> AFAICT the rule should then be (6th argument is the flags):
> 
> ```
> # copy_file_range(int fd_in, loff_t *off_in,
> #                                int fd_out, loff_t *off_out,
> #                                size_t len, unsigned int flags);
> copy_file_range - - - - - 0
> ```

Whoops, I forgot a dash before :)

**Review by jdstrand — APPROVED** [review]
Thanks for the update!

**Pull request merged**
