### PR TITLE
tests: don't repeat checks

### PR DESCRIPTION
**Pull request by zyga**
We were repeating journal content checks. I'm not convinced we actually
need to do so, let's see if we can drop that and simplify the related
code.

Signed-off-by: Zygmunt Krynicki <me@zygoon.pl>

### CODE REVIEW

**Comment by stolowski** [comment]
As discussed last Friday, it's probably best to consider landing this after current drama with tests is over and they stabilize, so we don't introduce new unknowns.

**Comment by mvo5** [comment]
Setting to "blocked" per Pawels comment.

**Comment by zyga** [comment]
@sergiocazzolato I'm closing this but please consider taking this patch instead of the approach you took in your PR. I think we don't need the repeated checks anymore and I would rather have that than the change to logging.

**Comment by zyga** [comment]
Aha,  there is something interesting I learned here. Closing for now.

**Pull request closed without merging**
