### PR TITLE
tests: add test to ensure /dev/input/event* for non-joysticks is denied - 2.33

### PR DESCRIPTION
**Pull request by jdstrand**
https://github.com/snapcore/snapd/pull/5240 for 2.33.

### CODE REVIEW

**Comment by jdstrand** [comment]
This test failure is unrelated. @sergiocazzolato mentioned there was a fix for it. I guess it needs to be added to 2.33?

2018-06-01 17:09:10 Failed tasks: 1
    - google:ubuntu-16.04-32:tests/main/lxd

**Comment by sergiocazzolato** [comment]
@jdstrand, there are 2 issues related to the lxd test, one is already fixed on master, for the other there is a PR #5258.

**Comment by jdstrand** [comment]
@sergiocazzolato and @mvo5 - since the failing lxd test is unrelated to this PR, can this PR be committed to 2.33?

**Comment by jdstrand** [comment]
Thanks for the reviews and merging this!

**Pull request merged**
