### PR TITLE
interfaces,overlord: move per-snap parameters from interfaces/backend Setup/SetupMany to a struct

### PR DESCRIPTION
**Pull request by Meulengracht**
In preparation of adding support for journal namespace bind mount, I need an additional parameter to fall-down to the mount backend in interfaces. But since adding a third per-snap parameter started to crowd the parameter list, I moved the existing snap.Info and confinement options parameter into a struct.

Using a struct also allowed for simpler code because now all snap.Infos contain a confinement option struct as well, where before there was checks made to ensure the lists of snap.Infos and confinement options would match.

I hope this is the right approach!

### CODE REVIEW

**Comment by stolowski** [comment]
@Meulengracht thanks for removing extra stuff from this PR! I'd however suggest to add the extra parameter related to quota/journal namespace already in this PR (just do not populate/use it so the PR remains simple) as it's easier to discuss and see the idea.

+0.99 to @mardy's idea of extending ConfinementOptions with the new quota/journal namespace, it is interesting (extending `snapInfo` isn't an option though as snap.Info should reflect what's inside `snap.yaml` only).

**Comment by Meulengracht** [comment]
I have re-added the extra parameter - to hopefully give the full picture of what I'm trying to accomplish. 

I really appreciate the input, I can absolutely see the point about 'snapInfo' being the primary parameter. Both the 'snapInfo' and 'confinementOptions' where required parameters in any case though, but my issue were that there had to be multiple lists of required parameters. 

I don't have strong feelings about this having to be the correct way forward. I like your suggestion about extending confinementOptions instead with the quota group, but I'll leave that decision up to you guys/Samuele.

IMHO it makes more sense to have one list of structs that contain all you need for each snap instead of multiple lists that must match in size.

**Review by pedronis — CHANGES_REQUESTED** [review]
what exactly do you need to know/pass to the interface backends,  the full quota group seems a bit too much information in this context? either way I agree preferring the idea of adding more fields to ConfinementOptions (but then at that level a full Quota group seems a bit much) instead of  introducing SecurityBackendSnapOptions, btw if we went with the latter we would need a different name, we almost never call *Options something that passes main information to a function.

**Comment by Meulengracht** [comment]
I need to know if the journal quota was set, and if is I need the snap group name. It just seemed more obvious to me to pass the grp pointer. I guess we could pass a 'log-namespace' string, that if is non-empty then applies the correct mount?

I'll change this to add the parameter to ConfinementOptions

**Comment by pedronis** [comment]
>  I need to know if the journal quota was set, and if is I need the snap group name. It just seemed more obvious to me to pass > the grp pointer. I guess we could pass a 'log-namespace' string, that if is non-empty then applies the correct mount?

> I'll change this to add the parameter to ConfinementOptions

can you explain where/how it's going to be used inside the backends? it sounds too specific somehow.  Also it's a small change so maybe it can actually be combined with usage

**Comment by Meulengracht** [comment]
Yes, it's needed in the mount backend, if the journal quota is set, then we need to add a bind mount from `/etc/systemd/journal.<ns>` -> `/etc/systemd/journal` to imitate what systemd is doing

**Comment by pedronis** [comment]
> Yes, it's needed in the mount backend, if the journal quota is set, then we need to add a bind mount from /etc/systemd/journal.<ns> -> /etc/systemd/journal to imitate what systemd is doing, where is the quota group name

I see, could it be expressed as  ExtraLayouts []snap.Layout ?

**Comment by Meulengracht** [comment]
Just took a look, and yes that would indeed be possible - Were you thinking adding this to the ConfinementOptions?

**Comment by pedronis** [comment]
> Just took a look, and yes that would indeed be possible - Were you thinking adding this to the ConfinementOptions?

yes, I think it makes sense for wrappers to be quota aware, but for interface backends, not so clear. So until we have different use cases that would seem the right API, if workable, between higher level and the backends

**Comment by Meulengracht** [comment]
I have now changed the approach of this, see this PR instead https://github.com/snapcore/snapd/pull/11705

**Pull request closed without merging**
