### PR TITLE
cmd/snap-seccomp/syscalls: add faccessat2

### PR DESCRIPTION
**Pull request by bboozzoo**
The libseccomp upstream updated the syscalls list with what 5.8-rc5 kernels support, see https://github.com/seccomp/libseccomp/commit/5696c896409c1feb37eb502df33cf36efb2e8e01 for details.

### CODE REVIEW

**Comment by jdstrand** [comment]
@alexmurray (cc @metorino) - fyi (nothing to do)

**Comment by anonymouse64** [comment]
> This looks fine. It should also be added to the default template. Thanks!

but to be clear this can be done in a different PR, this one is currently critical to unbreak master

**Comment by jdstrand** [comment]
> but to be clear this can be done in a different PR, this one is currently critical to unbreak master

It can be, sure (that is why I approved it as is).

**Comment by bboozzoo** [comment]
@mvo5 @pedronis can we use your superpowers to merge this PR?

**Comment by bboozzoo** [comment]
@jdstrand thanks for reminding that we need update the base template. Since we're already blocked #9037 I've pushed a patch updating the template.

**Pull request merged**
