### PR TITLE
Merging release/2.58 into beta-riscv64

### PR DESCRIPTION
**Pull request by xnox**
This is a weird merge!

This is doing $ git checkout beta-riscv64; git pull --no-rebase origin/release/2.58

This is to bring snapcraft.yaml up to date. Specifically to pull in:
* 866e5413498d03d363430714d00a71147ded3591 https://github.com/snapcore/snapd/pull/11188
* 5718321379aecca9f6945ce58e76a268da57b6db https://github.com/snapcore/snapd/pull/11197
* f79c6cab1bc906f8040c247fc96bbdfd78e56ec4 https://github.com/snapcore/snapd/pull/11487
* a13fd5ea408272ff4a471e2f5ede4e6f5f4cb8e6 https://github.com/snapcore/snapd/pull/11514
* b6a07bbc94327bca7bd60a48bb8118dcfa0f359d https://github.com/snapcore/snapd/pull/11903

In addition to all of the above the following cherry-pick is needed to unbreak `snap pack` when building things for base:core22

* 781a7b8afc397f5a6a8f2e701553339fe5d7e4f5 https://github.com/snapcore/snapd/pull/12252

Changelog:
```console
$ git log --oneline origin/beta-riscv64..HEAD -- build-aux/
1c6b8a7fc4 snapcraft: update libgcc1->libgcc-s1
0f41f5ba94 Merge remote-tracking branch 'origin/release/2.58' into beta-riscv64
b6a07bbc94 build-aux/snap: build against the snappy-dev/image PPA
a13fd5ea40 Install preseed.json via snapcraft's override-build.
f79c6cab1b snap: Add missing zlib
65419fc1e7 build-aux/snap/snapcraft.yaml: adjust comment about get-version
5718321379 build-aux/snap/snapcraft.yaml: use build-packages, don't fail dirty builds
866e541349 build-aux: detect/fix dirty git revisions while snapcraft building
8d6240ac08 Revert "many: Vendor apparmor-3.0.3 into the snapd snap"
6f5a4ac6c1 many: Vendor apparmor-3.0.3 into the snapd snap
```

The diff of changes being introduced into beta-riscv64 branch are:

$ git diff origin/beta-riscv64..HEAD -- build-aux/

```diff
diff --git a/build-aux/snap/snapcraft.yaml b/build-aux/snap/snapcraft.yaml
index 868a0af88d..cbde52e004 100644
--- a/build-aux/snap/snapcraft.yaml
+++ b/build-aux/snap/snapcraft.yaml
@@ -12,6 +12,9 @@ adopt-info: snapd-deb
 # build-base is needed here for snapcraft to build this snap as with "modern"
 # snapcraft
 build-base: core20
+package-repositories:
+  - type: apt
+    ppa: snappy-dev/image
 grade: stable
 license: GPL-3.0
 
@@ -37,6 +40,8 @@ parts:
     override-pull: |
       snapcraftctl pull
       [ -e packaging/ubuntu-20.04 ] || ln -s ubuntu-16.04 packaging/ubuntu-20.04
+      # set version, this needs dpkg-parsechangelog (from dpkg-dev) and git
+      snapcraftctl set-version "$(./mkversion.sh --output-only)"
       # Ensure that ./debian/ packaging which we are about to use
       # matches the current `build-base` release. I.e. ubuntu-16.04
       # for build-base:core, etc.
@@ -46,9 +51,18 @@ parts:
       export DEBCONF_NONINTERACTIVE_SEEN=true
       sudo -E apt-get build-dep -y ./
       ./get-deps.sh --skip-unused-check
-      # set version after installing dependencies so we have all the tools here
-      snapcraftctl set-version "$(./mkversion.sh --output-only)"
     override-build: |
+      # TODO: when something like "craftctl get-version" is ready, then we can
+      # use that, but until then, we have to re-run mkversion.sh to check if the
+      # version number was set as "dirty" from the override-pull step
+      if sh -x ./mkversion.sh --output-only | grep "dirty"; then
+        mkdir -p $SNAPCRAFT_PART_INSTALL/usr/lib/snapd
+        ( 
+          echo "dirty git tree during build detected:"
+          git status
+          git diff
+        ) > $SNAPCRAFT_PART_INSTALL/usr/lib/snapd/dirty-git-tree-info.txt
+      fi
       # unset the LD_FLAGS and LD_LIBRARY_PATH vars that snapcraft sets for us
       # as those will point to the $SNAPCRAFT_STAGE which on re-builds will 
       # contain things like libc and friends that confuse the debian package
@@ -66,6 +80,8 @@ parts:
       # bother compressing it too much)
       dpkg-buildpackage -b -Zgzip -zfast
       dpkg-deb -x $(pwd)/../snapd_*.deb $SNAPCRAFT_PART_INSTALL
+      # not included in the deb as it's only used with UC20 preseeding.
+      cp -a data/preseed.json $SNAPCRAFT_PART_INSTALL/usr/lib/snapd/
 
   # xdelta is used to enable delta downloads (even if the host does not have it)
   xdelta3:
@@ -92,6 +108,13 @@ parts:
       - liblzma5
     stage:
       - lib/*
+  # Needed by squashfs-tools and fc-cache
+  zlib:
+    plugin: nil
+    stage-packages:
+      - zlib1g
+    stage:
+      - lib/*
   # libc6 is part of core but we need it in the snapd snap for
   # CommandFromSystemSnap
   libc6:
@@ -99,7 +122,7 @@ parts:
     stage-packages:
       - libc6
       - libc-bin
-      - libgcc1
+      - libgcc-s1
     stage:
       - lib/*
       - usr/lib/*
```

This pull request is similar to the one we did recently for master-riscv64 https://github.com/snapcore/snapd/pull/12568

### CODE REVIEW

**Comment by xnox** [comment]
@Meulengracht hopefully this time around my intentions of my crazy pull request are easier to comprehend =)

**Comment by xnox** [comment]
cc: @wgrant

**Comment by Meulengracht** [comment]
> @Meulengracht hopefully this time around my intentions of my crazy pull request are easier to comprehend =)

Haha yes - it looks good to me now. I'll let @mvo5 about merging it just for my own sanity

**Comment by xnox** [comment]
Can people with powers please assign @mvo5 as the reviewer?

**Comment by xnox** [comment]
This is required to update riscv64 branch to 2.59 release.

**Comment by xnox** [comment]
I am making beta-riscv64 recipe use this branch to get 2.59 build published.

**Comment by mvo5** [comment]
Thank you

**Pull request merged**
