### PR TITLE
tests: smaller fixes for Arch tests

### PR DESCRIPTION
**Pull request by bboozzoo**
Support for `CONFIG_USER_NS` is now enabled in the default kernel package, meaning we can enable `tests/regression/lp-1618683`. 

Also, make sure that we install `go-pie` since it's used for building the package anyway.

### CODE REVIEW

**Comment by Erick555** [comment]
Are those expected?
```
2018-04-17 10:59:23 Error executing google:arch-linux-64:tests/main/static : 
-----
+ CGO_ENABLED=0
+ go build -o snapd.static github.com/snapcore/snapd/cmd/snapd
# github.com/snapcore/snapd/cmd/snapd
loadinternal: cannot find runtime/cgo
+ ldd snapd.static
	linux-vdso.so.1 (0x00007ffc8d1d9000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007f323bc86000)
	/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007f323d172000)
+ exit 1
-----
```


```
2018-04-17 11:01:33 Error executing google:arch-linux-64:tests/main/base-snaps : 
-----
+ . /home/gopath/src/github.com/snapcore/snapd/tests/lib/snaps.sh
+ echo 'Ensure a snap that requires a unavailable base snap can not be installed'
Ensure a snap that requires a unavailable base snap can not be installed
+ snap pack /home/gopath/src/github.com/snapcore/snapd/tests/lib/snaps/test-snapd-requires-base
built: test-snapd-requires-base_1.0_all.snap
+ install_local test-snapd-requires-base
+ local SNAP_NAME=test-snapd-requires-base
+ shift
++ make_snap test-snapd-requires-base
++ local SNAP_NAME=test-snapd-requires-base
++ shift
++ local SNAP_FILE=/home/gopath/src/github.com/snapcore/snapd/tests/lib/snaps/test-snapd-requires-base/test-snapd-requires-base_1.0_all.snap
++ local SNAP_DIR
+++ dirname /home/gopath/src/github.com/snapcore/snapd/tests/lib/snaps/test-snapd-requires-base/test-snapd-requires-base_1.0_all.snap
++ SNAP_DIR=/home/gopath/src/github.com/snapcore/snapd/tests/lib/snaps/test-snapd-requires-base
++ '[' '!' -f /home/gopath/src/github.com/snapcore/snapd/tests/lib/snaps/test-snapd-requires-base/test-snapd-requires-base_1.0_all.snap ']'
++ snap pack /home/gopath/src/github.com/snapcore/snapd/tests/lib/snaps/test-snapd-requires-base /home/gopath/src/github.com/snapcore/snapd/tests/lib/snaps/test-snapd-requires-base
++ echo /home/gopath/src/github.com/snapcore/snapd/tests/lib/snaps/test-snapd-requires-base/test-snapd-requires-base_1.0_all.snap
+ SNAP_FILE=/home/gopath/src/github.com/snapcore/snapd/tests/lib/snaps/test-snapd-requires-base/test-snapd-requires-base_1.0_all.snap
+ snap install --dangerous /home/gopath/src/github.com/snapcore/snapd/tests/lib/snaps/test-snapd-requires-base/test-snapd-requires-base_1.0_all.snap
error: cannot perform the following tasks:
- Ensure prerequisites for "test-snapd-requires-base" are available (no snap revision given constraints)
+ echo 'Ensure a base snap can be installed'
Ensure a base snap can be installed
+ snap pack /home/gopath/src/github.com/snapcore/snapd/tests/lib/snaps/test-snapd-base
built: test-snapd-base_1.0_all.snap
+ install_local test-snapd-base
+ local SNAP_NAME=test-snapd-base
+ shift
++ make_snap test-snapd-base
++ local SNAP_NAME=test-snapd-base
++ shift
++ local SNAP_FILE=/home/gopath/src/github.com/snapcore/snapd/tests/lib/snaps/test-snapd-base/test-snapd-base_1.0_all.snap
++ local SNAP_DIR
+++ dirname /home/gopath/src/github.com/snapcore/snapd/tests/lib/snaps/test-snapd-base/test-snapd-base_1.0_all.snap
++ SNAP_DIR=/home/gopath/src/github.com/snapcore/snapd/tests/lib/snaps/test-snapd-base
++ '[' '!' -f /home/gopath/src/github.com/snapcore/snapd/tests/lib/snaps/test-snapd-base/test-snapd-base_1.0_all.snap ']'
++ snap pack /home/gopath/src/github.com/snapcore/snapd/tests/lib/snaps/test-snapd-base /home/gopath/src/github.com/snapcore/snapd/tests/lib/snaps/test-snapd-base
++ echo /home/gopath/src/github.com/snapcore/snapd/tests/lib/snaps/test-snapd-base/test-snapd-base_1.0_all.snap
+ SNAP_FILE=/home/gopath/src/github.com/snapcore/snapd/tests/lib/snaps/test-snapd-base/test-snapd-base_1.0_all.snap
+ snap install --dangerous /home/gopath/src/github.com/snapcore/snapd/tests/lib/snaps/test-snapd-base/test-snapd-base_1.0_all.snap
test-snapd-base 1.0 installed
+ MATCH test-snapd-base
+ snap list
+ echo 'With test-snapd-base installed we now can install test-snapd-requires-base'
With test-snapd-base installed we now can install test-snapd-requires-base
+ install_local test-snapd-requires-base
+ local SNAP_NAME=test-snapd-requires-base
+ shift
++ make_snap test-snapd-requires-base
++ local SNAP_NAME=test-snapd-requires-base
++ shift
++ local SNAP_FILE=/home/gopath/src/github.com/snapcore/snapd/tests/lib/snaps/test-snapd-requires-base/test-snapd-requires-base_1.0_all.snap
++ local SNAP_DIR
+++ dirname /home/gopath/src/github.com/snapcore/snapd/tests/lib/snaps/test-snapd-requires-base/test-snapd-requires-base_1.0_all.snap
++ SNAP_DIR=/home/gopath/src/github.com/snapcore/snapd/tests/lib/snaps/test-snapd-requires-base
++ '[' '!' -f /home/gopath/src/github.com/snapcore/snapd/tests/lib/snaps/test-snapd-requires-base/test-snapd-requires-base_1.0_all.snap ']'
++ echo /home/gopath/src/github.com/snapcore/snapd/tests/lib/snaps/test-snapd-requires-base/test-snapd-requires-base_1.0_all.snap
+ SNAP_FILE=/home/gopath/src/github.com/snapcore/snapd/tests/lib/snaps/test-snapd-requires-base/test-snapd-requires-base_1.0_all.snap
+ snap install --dangerous /home/gopath/src/github.com/snapcore/snapd/tests/lib/snaps/test-snapd-requires-base/test-snapd-requires-base_1.0_all.snap
test-snapd-requires-base 1.0 installed
+ MATCH test-snapd-requires-base
+ snap list
+ echo 'Ensure the bare base works'
Ensure the bare base works
++ uname -m
+ '[' x86_64 '!=' x86_64 ']'
+ snap install --edge --devmode test-snapd-busybox-static
test-snapd-busybox-static (edge) 1.0 from 'canonical' installed
+ echo 'Ensure we can run a statically linked binary from an empty base'
Ensure we can run a statically linked binary from an empty base
+ MATCH hello
+ test-snapd-busybox-static.busybox-static echo hello
execv failed: No such file or directory
error: pattern not found, got:
-----

```

**Comment by bboozzoo** [comment]
Interesting, `google:arch-linux-64:tests/main/static` looks fine if I build the binary locally. Needs more investigation.

**Comment by bboozzoo** [comment]
This is failing because of https://bugs.archlinux.org/task/57921. We can temporarily switch to `go` instead of `go-pie`.

**Comment by Erick555** [comment]
Ok. Perhaps it could stay in AUR package as nobody reported issues there.

**Comment by bboozzoo** [comment]
FWIW this looks like a problem with Go toolchain. Consider a minimal sample like this:

```
package main

import "fmt"

func main() {
fmt.Println("hello")
}
```

When built using either `go` package or upstream `go1.10.1` and `CGO_ENABLED=0`, the resulting binary is not statically linked:

```
$ CGO_ENABLED=0 go build -buildmode=pie main.go
# command-line-arguments
loadinternal: cannot find runtime/cgo
$ ldd main
linux-vdso.so.1 (0x00007ffc57f3d000)
libc.so.6 => /usr/lib/libc.so.6 (0x00007f659f253000)
/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007f659f9c3000)
```

Version `go version devel +58b18cfda5 Tue Apr 17 14:39:08 2018 +0000 linux/amd64` behaves the same. GOCACHE=off does not seem to have any effect.

**Comment by bboozzoo** [comment]
Looks like I have it under control now. I'll drop `tests/lib/pkgbd: install go-pie on arch` patch and force push the fixes.

**Comment by Erick555** [comment]
Will it work with `go-pie`? Users who have `go-pie` already installed  will still automatically use it instead of plain `go`.

**Comment by bboozzoo** [comment]
@Erick555 yes it will (and it does work). All that `go-pie` package does is enable pie for `linux-*` targets. We still pass `-buildmode=pie`, but instead of disabling cgo, we just pass `-static` to `ld`.

**Comment by Erick555** [comment]
@bboozzoo is it worth falling back to plain `go` then?

**Comment by bboozzoo** [comment]
@Erick555 yes, I think so. I'd rather have this under control and enable PIE explicitly in PKGBUILD. Users shouldn't notice the change, `go-pie` already provides `go`.

**Comment by Erick555** [comment]
I meant using `go-pie` and  enabling PIE explicitly in PKGBUILD together. Anyway thx for this work.

**Pull request merged**
