### PR TITLE
Modify the description of the content interface

### PR DESCRIPTION
**Pull request by oparoz**
The documentation needs to reflect the reality of how the interface works.

@zyga - As discussed.

### CODE REVIEW

**Comment by niemeyer** [comment]
Thanks for the change @oparoz. Can you please sign the CLA so we take this and future changes:

    http://www.ubuntu.com/legal/contributors

@zyga Can we fix the bug instead of documenting it?

**Comment by niemeyer** [comment]
I suggest supporting $SNAP and $SNAP_DATA as explicit prefixes for those paths, and documenting them as required. Let's just keep the old behavior for compatibility purposes internally, but not document it.

**Comment by niemeyer** [comment]
(and $COMMON_DATA, as @zyga pointed out)

**Comment by niemeyer** [comment]
Closing for the time being on the above basis. Let's get this fixed!

**Comment by oparoz** [comment]
Works for me :) I had opened a bug in Launchpad, but it didn't get triaged, so I figured it wasn't important for this phase.

**Pull request closed without merging**
