### PR TITLE
spread.yaml: add fedora 27

### PR DESCRIPTION
**Pull request by sergiocazzolato**
The rawhide will set to manual before merge this PR.

### CODE REVIEW

**Comment by niemeyer** [comment]
@cachio Please watch out for our PR summary conventions (see above).

**Comment by sergiocazzolato** [comment]
@niemeyer thanks for reviewing, as we decided, just fedora-27 will be used for each PR, the rest will remain as manual. I'll push that change.

**Comment by bboozzoo** [comment]
Any chance of landing this soon?

**Comment by Conan-Kudo** [comment]
Can we please have this in? Not having any testing at all for Fedora is not good. :(

**Comment by zyga** [comment]
Please merge master

**Comment by sergiocazzolato** [comment]
Test results executed from localhost due to travis outage

**Comment by bboozzoo** [comment]
The travis build is also green now. Ready for merge?

**Pull request merged**
