### PR TITLE
many: rename systemd.Kind to Backend for a bit more clarity

### PR DESCRIPTION
**Pull request by pedronis**
add some doc comments
adjust/simplify tests using MockNewSystemd

### CODE REVIEW

**Comment by pedronis** [comment]
the need for a rename was discussed in the original PR introducing Kind

**Review by mvo5 — APPROVED** [review]
Thank you, this looks fine. One misspell warning inline though.

**Review by mardy — APPROVED** [review]
LGTM!

**Review by stolowski — APPROVED** [review]
LGTM, thanks

**Pull request merged**
