### PR TITLE
many: use snapcore/snapd/i18n instead of i18n/dumb

### PR DESCRIPTION
**Pull request by mvo5**
We have fully working i18n so we should probably use it.

A bit of an RFC branch - why do we still use i18n/dumb? We have working i18n, users who run systems with a locale set system-wide would benefit from i18n so it seems to me we want to enable it.

### CODE REVIEW

**Comment by chipaca** [comment]
we use i18n/dumb so that gettext finds the strings where they're written (on the server), but the strings are translated on the client so the server doesn't need i18n (except maybe in snapctl i think)

**Comment by chipaca** [comment]
The *raison d'être* of `i18n/dumb`, however, is because it used to be a cgo thing. This might've changed.

**Comment by mvo5** [comment]
Yeah, the original reason was that the gettext we were using was a wrapper around the c-gettext and that would have meant we link against cgo which we did not want. However the new gettext we are using is pure go so that should be fine.

Also I think the daemon needs to use the real i18n if we want i18n at all. Quite a few strings are generated on the server side like e.g. (just taking a random one from snapstate): `return nil, fmt.Errorf(i18n.G("classic confinement requires snaps under /snap or symlink from /snap to %s"), dirs.SnapMountDir)`. This one cannot be translated on the client side (which AFAICT we are not trying anyway) because at the point when it reaches the client it already has the "%s" string filed with data so we cannot find the translation in the mo file.

**Comment by chipaca** [comment]
Yes. For that to work, however, the server needs to know the client's locale; currently it doesn't.

**Comment by mvo5** [comment]
Correct, we do not support multi-languages on a single system right now. I think we should (at some point :) 

But for now this change will give us i18n on systems that have a single global language that is not "en" Unless I miss something why we should not do this, one argument might be if a system is configured with global "es" language and there are some users on the system that do not speak "es". On those systems we would indeed regress and suddenly show messages in a language they cannot speak. So maybe that is an argument for the proper fix to send "Accept-language" via the rest api.

**Comment by ogra1** [comment]
Not sure if that has been taken into accoount but snapd-glib went ahead with:
https://forum.snapcraft.io/t/getting-translated-snap-metadata-via-snapd/1242

**Pull request merged**
