### PR TITLE
 snapstate: allow setting "refresh.timer=managed" (2.34)

### PR DESCRIPTION
**Pull request by mvo5**
This is https://github.com/snapcore/snapd/pull/5440 for 2.34 (if we do another point release).

### CODE REVIEW

**Comment by mvo5** [comment]
This fails inside the fedora-28 tests with:
```
...
configure: error: C compiler cannot create executables
See `config.log' for more details
```

**Comment by bboozzoo** [comment]
The exact error is:
```
configure:2740: gcc -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2                     
-Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-st                                                
rong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1                                  
-specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasyn                                   
chronous-unwind-tables -fstack-clash-protection -mcet -fcf-protection  -Wl,-z,relro -z now conftest.c  >&5 
annobin: conftest.c: Error: plugin built for compiler version (8.0.1) but run with compiler version        
(8.1.1)                                                                                                    
cc1: error: fail to initialize plugin /usr/lib/gcc/x86_64-redhat-linux/8/plugin/annobin.so                 
configure:2744: $? = 1                                                                                     
```

As discussed on IRC, Fedora 28 image needs updating. @sergiocazzolato can you restart this build once the image is updated?

**Comment by bboozzoo** [comment]
Something fishy about the Fedora image we use in 2.34 branch. This is a diff between release/2.34 and master:
```
@@ -82,11 +82,9 @@ backends:
                 workers: 4
                 manual: true
             - fedora-28-64:
-                image: fedora-28-64-selinux-permissive
                 workers: 4

             - opensuse-42.3-64:
-                image: opensuse-cloud/opensuse-leap-42-3-v20180116
                 workers: 4
             - arch-linux-64:
                 workers: 4
```
The image used in the master branch probably got updated. The one in 2.34 did not?

**Comment by bboozzoo** [comment]
Opened #5550

**Comment by bboozzoo** [comment]
Finally green!

**Pull request merged**
