### PR TITLE
interfaces/builtin: added zfs mount options to mount-control

### PR DESCRIPTION
**Pull request by olivercalder**
Added zfs mount options to the list of supported fs-specific mount options included in the mount-control interface.

### CODE REVIEW

**Review by ernestl — APPROVED** [review]

**Review by alexmurray — APPROVED** [review]
~~I see the following options listed in `zfsprops(7)` under `Temporary Mount Point Properties":~~

~~atime/noatime
auto/noauto
dev/nodev
exec/noexec
ro/rw
relatime/norelatime
suid/nosuid
xattr/noxattr
mand/nomand
context=
fscontext=
defcontext=
rootcontext=~~

~~Should we look at adding more of these to future-proof this interface?~~

Also the various `context=` options allow setting the SELinux context for files in the mount point etc which seems quite sensitive from a security point of view, however this is constrained by needing an explicit snap declaration on the store that includes the required options - as such this requires a review on the store side for this to be granted which limits the ability for arbitrary snaps to utilise this to potentially escalate privileges etc.

As such, ACK from security for this change.

**Comment by alexmurray** [comment]
Never mind about the first suggestion to add these other options - I see they are already covered by the existing `allowedKernelMountOptions` etc in `mount-control`.

**Comment by olivercalder** [comment]
Thanks for the review @alexmurray ! If you would prefer, I would be happy to remove the `*context=` options, leaving just the `xattr` and `noxattr` options (in addition to the FS-specific ones).  What do you think?

**Comment by alexmurray** [comment]
I am happy to leave them if we think we have a use-case for them - as I said, this is protected by the nature of this interface being super privileged etc - so I think it is worthwhile keeping this as future-proof as possible if we know there is a likely use-case. Or we can wait and add them once a user/customer asks.

**Pull request merged**
