### PR TITLE
tests: use ubuntu-image 1.11 from stable channel 

### PR DESCRIPTION
**Pull request by sergiocazzolato**
This is because images create with ubuntu-image 2.0 are displaying "No
space left on device" error

### CODE REVIEW

**Review by anonymouse64 — APPROVED** [review]
LGTM

**Comment by GlenPickle** [comment]
This turns out to have been a pretty trivial fix in ubuntu-image. I created a PR to fix it: https://github.com/canonical/ubuntu-image/pull/26

We'd have to discuss with @sil2100 how quickly the snap could be updated.

**Review by bboozzoo — APPROVED** [review]
Thanks

**Comment by bboozzoo** [comment]
I've merged this branch and a commit reverting this change into #11073

**Pull request merged**
