### PR TITLE
libsnap-confine-private: string functions simplification

### PR DESCRIPTION
**Pull request by mardy**
Simple is better :-)

### CODE REVIEW

**Review by mvo5 — APPROVED** [review]
Thank you, this is indeed fluff we don't really need. I wonder if this should get a security review though? Simply because it's C and used all over the place?

**Review by MiguelPires — APPROVED** [review]
LGTM

**Review by alexmurray — APPROVED** [review]
LGTM - some spelunking shows these functions have been like this forever - and these seem like unnecessary "optimisations" which actually make them slower (by walking each string with strlen) and then having no effect since strlen / strnlen behaves in this same way anyway. So you can also consider this a security review if you want @mvo5 :)

**Review by anonymouse64 — APPROVED** [review]
lgtm

**Pull request merged**
