### PR TITLE
interfaces/gpg-keys: Enable access to system gpg_agent socket

### PR DESCRIPTION
**Pull request by Kedstar99**
The main idea of this is to give read only access to the secret gpg key of the host.
This is potentially the solution to connecting to the agent and potentially decrypting encrypted files (or mail).

https://www.gnupg.org/documentation/manuals/gnupg/Agent-Options.html#option-_002d_002dextra_002dsocket

To connect to this specific socket simply run gpg-connect-agent -S <socket>.

I still need to somewhat test this a little bit, it may be more appropriate in this case to allow access to the S.gpg-agent socket instead. In theory with some configuration in .gnupg it should connect to the extra socket and everything should just work.

I have signed the CLA and read the contributing.MD.

EDIT: Sorry for reopening but i just wanted to maybe adjust some things. I was thinking that it may be easier just to allow access to the gpg-agent socket rather than the extra socket. Although if it would be possible, it would be great to perhaps have access to the extra-socket as that would be able to limit how much potential damage a rogue snap could do with the private keys.

Looking at DMESG this file may be specifically asked for by gpg-agent and enigmail.

audit: type=1400 audit(1572395369.723:970): apparmor="DENIED" operation="connect" profile="snap.thunderbird.thunderbird" name="/run/user/1000/gnupg/S.gpg-agent" pid=14233 comm="gpg-connect-age" requested_mask="wr" denied_mask="wr" fsuid=1000 ouid=1000

audit: type=1400 audit(1572395349.623:967): apparmor="DENIED" operation="connect" profile="snap.thunderbird.thunderbird" name="/run/user/1000/gnupg/S.gpg-agent" pid=14228 comm="gpg-agent" requested_mask="wr" denied_mask="wr" fsuid=1000 ouid=1000

### CODE REVIEW

**Comment by Kedstar99** [comment]
Is there anyone I can speak to about this? I think this specifically is what is blocking enigmail working in thunderbird snap.

**Comment by ppd1990** [comment]
We have a review for similar functionality here: https://github.com/snapcore/snapd/pull/7366/files#r320877499

**Comment by Kedstar99** [comment]
Hi @ppd1990,

Thanks for pointing me to that PR. It seems to me that the design of this is being considered and at a level that is more in-depth than what I envisioned externally for this PR. All I planned for this was some way of enabling enigmail to have access to private keys to decrypt emails. I'll close this and I look forward to seeing a hopefully better designed approach for this problem.

Kind regards,
Krish

**Comment by ppd1990** [comment]
@Kedstar99 Maybe have a look at https://github.com/ppd1990/gopass-snap for gpg integration into a snap (encrypting & decrypting, persistent agent...)

**Comment by Kedstar99** [comment]
I think I have almost managed to get it to work, I am just getting a little bit of issues with pinentry-gnome3 where it seems unable to detect if gcr is present.

I am running the command manually and it says no GCR detected.

https://github.com/Kedstar99/ThunderbirdSnap

Would you mind taking a look at some point if you are free?

**Comment by Fuseteam** [comment]
i'm still running into this issue, i'm unsure how to get it working:
image

any tips where i can look? the upstream repo is over at: https://github.com/fredldotme/git-scm-snap

**Pull request closed without merging**
