### PR TITLE
tests: also check nested lxd container

### PR DESCRIPTION
**Pull request by anonymouse64**
This ensures two things, 1 that lxd as a snap inside lxd as a snap works, and 2 that snapd inside a container with config option security.nesting set to true also works.

See also https://bugs.launchpad.net/snapd/+bug/1855355

### CODE REVIEW

**Comment by mvo5** [comment]
Thanks a lot for adding this test! It looks great but also quite similar to the one we already have (main/lxd) - I wonder if we should just add the extra nesting test into that test? The upside of this would be that we only download the lxd base image once.

**Comment by pedronis** [comment]
@bboozzoo  you are proposing to do additional testing in the other test right? not to replace it with only the nesting variant?

**Comment by bboozzoo** [comment]
@pedronis yes, I think we should incorporate the relevant changes in tests/main/lxd

**Comment by mvo5** [comment]
It needs a little bit more work it seems:
```
...
+ lxd.lxc exec my-ubuntu -- lxd.lxc launch ubuntu:16.04 my-inner-ubuntu
Error: Both native and snap packages are installed on this system
       Run "lxd.migrate" to complete your migration to the snap package
-----
```

**Comment by anonymouse64** [comment]
Sorry folks, I was trying to get this running but my network was having issues last night so I couldn't confirm it was working. I will move this to the lxd test and re-open it when it is working.

**Comment by anonymouse64** [comment]
This is ready now, I confirmed it passes with (current master) on top of the revert, and it fails on top of old master without the revert.

**Comment by anonymouse64** [comment]
All of the spread tests failed because the store was having a bad day, responding to 503s for just about everything. I restarted the tests hopefully the store is happier now :crossed_fingers:

**Comment by zyga** [comment]
I've merged master to overcome fwupd test breakage.

**Comment by anonymouse64** [comment]
This is ready again

**Pull request merged**
