### PR TITLE
interfaces: add memory stats to system_observe

### PR DESCRIPTION
**Pull request by MiguelPires**
Adds memory stats to the system observe interface.

### CODE REVIEW

**Review by mardy — APPROVED** [review]
LGTM, thanks!

**Comment by mvo5** [comment]
Fwiw, this is the result of a customer ticket - I think this is fine but we need a security ACK too.

**Review by mvo5 — APPROVED** [review]

**Comment by bugraaydogar** [comment]
Don't know the customer ticket in detail but recently I made a very similar change here => https://github.com/snapcore/snapd/blob/master/interfaces/apparmor/template.go#L290

Maybe that also solves the customer's problem.

**Review by alexmurray — APPROVED** [review]
LGTM!

**Comment by mardy** [comment]
> Don't know the customer ticket in detail but recently I made a very similar change here => https://github.com/snapcore/snapd/blob/master/interfaces/apparmor/template.go#L290
> 
> Maybe that also solves the customer's problem.

Yes, both changes are correct in principle: your allows any snap to retrieve stats on its own memory usage, whereas this allows snaps using the system-observe interface to get memory stats for the whole system. It may even be that we need to go a step further, and allow (in this or in another interface) access for a snap to read the memory stats for any other process.

**Pull request merged**
