### PR TITLE
cgroup-support.c: fix link to CGROUP DELEGATION

### PR DESCRIPTION
**Pull request by jonasdn**
The old one lead to 404.

### CODE REVIEW

**Review by zyga — APPROVED** [review]
Thank you!

**Comment by zyga** [comment]
Close & reopen dance to avoid testing this in spread.

**Review by bboozzoo — APPROVED** [review]
LGTM. Thanks!

**Comment by anonymouse64** [comment]
Hi @jonasdn :-) have you signed the CLA ? if you have no worries, it sometimes takes a bit to propagate throughout the cloud so our checker can see the status

**Comment by jonasdn** [comment]
Hi! I did sign it, but only just before sending the PR, sorry for the inconvenience!

**Comment by anonymouse64** [comment]
> Hi! I did sign it, but only just before sending the PR, sorry for the inconvenience!

no worries, it usually takes a few hours sometimes a day or two to sync everywhere, I will make sure the relevant people are poked to get it updated

**Pull request merged**
