### PR TITLE
tests/main/security-device-cgroups-helper: more debugs

### PR DESCRIPTION
**Pull request by bboozzoo**
Collect more info from a failing test.

### CODE REVIEW

**Review by stolowski — APPROVED** [review]
LGTM

**Review by MiguelPires — APPROVED** [review]
LGTM

**Review by mardy — APPROVED** [review]
LGTM :-)

**Comment by bboozzoo** [comment]
@pedronis @mvo5 the PR is ready, can you land it?

**Review by anonymouse64 — APPROVED** [review]

**Pull request merged**
