### PR TITLE
advise-snap: add --dump-db which dumps the command database

### PR DESCRIPTION
**Pull request by shawnl**
This is a hook needed for my new command-not-found implementation[1], which
was written to be fast, and remove the dependency on Python.

Currently Ubuntu is running two programs (one which requires an
interpreter) and opening two huge databases
for every command_not_found_handler invocation.

I also will need a hook somewhere so snap can call "update-command-not-found"
whenever it updates its command database.

[1] https://github.com/shawnl/command-not-found

see  #5623

### CODE REVIEW

**Comment by mvo5** [comment]
Thanks for this PR! I ran `go fmt` over it and pushed to this PR. This should make CI happy :)

**Comment by shawnl** [comment]
Whoops, I thought that I didn't submit the whole patch, and forced over that....I just ran it myself and then pushed.

**Comment by mvo5** [comment]
Hey @shawnl - the PR looks good but it seems that `shawn@git.icu                       has no Launchpad account` is unkown to launchpad, could you please add it as an address to your launchpad account so that the CLA check will work? Thank you!

**Comment by shawnl** [comment]
bump

**Comment by shawnl** [comment]
What's next?

**Comment by mvo5** [comment]
Hey @shawnl ! Sorry that this was dragging on for so long. This looks fine now, we will do a followup that adds tests but that should not concern you, we will take care of it :) Thanks for your contribution and I look forward to the new fast! command-not-found :)

**Pull request merged**
