### PR TITLE
o/devicestate: pass change ID when checking remodel conflicts

### PR DESCRIPTION
**Pull request by alfonsosanchezbeato**
Pass around the current change ID when checking conflicts in LinkNewBaseOrKernel, so we can ignore our change when the checks happen. This is needed as we are creating dynamically tasks in a remodel change, and was done in the past already for the SwitchToNewGadget function (see https://github.com/snapcore/snapd/commit/a66b7d5f36f527d28f1e6921ea3474826aa32292).

### CODE REVIEW

**Review by pedronis — APPROVED** [review]
thank you

**Comment by alfonsosanchezbeato** [comment]
I've added a new spread test that exposes the issue.

**Review by andrewphelpsj — APPROVED** [review]
Looks good!

**Comment by vpetersson** [comment]
Can we get this into the next release?

**Comment by renatgalimov** [comment]
I can test the fix right after this change is in the edge channel.

**Pull request merged**
