### PR TITLE
seed: seed16: run adding snaps in parallel

### PR DESCRIPTION
**Pull request by kubiko**
sha3-384 calculation is single threaded and on multicore arm devices does not fully utilize device's potential
run addSnap routine in parallel

This can greatly improve time spent calculating sha3 on multicore arm devices with multiple seeding snaps.
e.g on 4 cores armhf device with 500M big seed, time spend calculating goes from 69s to 34s where single largest snap (200M) takes 31s on its own.
Gain can be even higher if size of snap is larger

### CODE REVIEW

**Comment by pedronis** [comment]
The idea is good assuming the device can do the necessary i/o. But the code is very racy as is. We (snapd team) will pick it up when possible and see to rewrite it.

**Comment by stolowski** [comment]
Should we close this given that preseeding will alleviate the problem?

**Comment by pedronis** [comment]
@stolowski 

> Should we close this given that preseeding will alleviate the problem?

no, this is meant to help on Core, the plan is still to pick this up

**Comment by vpetersson** [comment]
This seems like a great feature. First-boot is horribly slow on UC*, so anything that can speed that up would be very welcome by us.

**Comment by pedronis** [comment]
We landed something like this for UC 20+. We can rework seed16 to follow that blueprint if there is interest but UC20/22 are our main target atm.

**Pull request closed without merging**
