### PR TITLE
data: include snapd/mounts in preseeded blob

### PR DESCRIPTION
**Pull request by kubiko**
When collecting preseeded data, include also snapd/mounts.
This directory contains layout info and is essential to have a correct layout functionality on presseded system.

### CODE REVIEW

**Review by mardy — COMMENTED** [review]
LGTM, but you could amend the git commit message to fix the "presseded" spelling. Feel free to force-push, then.

**Comment by kubiko** [comment]
> LGTM, but you could amend the git commit message to fix the "presseded" spelling. Feel free to force-push, then.

Thank you for spotting this!
Commit re-pushed with fixed typo.

**Review by mvo5 — APPROVED** [review]
Thank you.

**Review by pedronis — APPROVED** [review]
thank you

**Pull request merged**
