### PR TITLE
go.mod: update to newer secboot/uc22 branch 

### PR DESCRIPTION
**Pull request by alfonsosanchezbeato**
This updates to the latest in secboot/uc22 branch, which includes some changes to support arm64/riscv in secboot. In turn this pulls more modern go-efilib and go-gflags, so the PR also needs to update these. The latter includes some fixes which imply some minor changes in related tests.

### CODE REVIEW

**Comment by mvo5** [comment]
Would you mind adding a small summary what will change with this newer branch?

**Comment by alfonsosanchezbeato** [comment]
> Would you mind adding a small summary what will change with this newer branch?

Sure, done now. Some details are also in the commit comments but indeed I needed to add a summary.

**Review by MiguelPires — APPROVED** [review]
LGTM

**Review by mvo5 — APPROVED** [review]
Thank you

**Comment by mardy** [comment]
LGTM, thanks!

**Review by mardy — APPROVED** [review]

**Pull request merged**
