### PR TITLE
tests: run spread tests on ubuntu 19.04

### PR DESCRIPTION
**Pull request by sergiocazzolato**
This will need a new change once the image is release and sent to the
oficial ubuntu-os-cloud gce project

### CODE REVIEW

**Comment by bboozzoo** [comment]
This probably needs some investigation. Did something change in xdg-open in 19.04? 
```
2019-04-11 18:16:01 Error executing google:ubuntu-19.04-64:tests/main/snap-handle-link : 
-----
+ . /home/gopath/src/github.com/snapcore/snapd/tests/lib/pkgdb.sh
++ . /home/gopath/src/github.com/snapcore/snapd/tests/lib/quiet.sh
+ . /home/gopath/src/github.com/snapcore/snapd/tests/lib/snaps.sh
+ echo 'URI Handler fails if snap-store is not installed and user refuses to install it'
URI Handler fails if snap-store is not installed and user refuses to install it
+ mount --bind /bin/false /usr/bin/zenity
+ snap handle-link snap://package
+ MATCH 'Snap Store required'
+ echo 'Now with snap-store installed'
Now with snap-store installed
+ install_local snap-store
+ local SNAP_NAME=snap-store
+ shift
++ make_snap snap-store
++ local SNAP_NAME=snap-store
++ shift
++ local SNAP_FILE=/home/gopath/src/github.com/snapcore/snapd/tests/lib/snaps/snap-store/snap-store_1.0_all.snap
++ local SNAP_DIR
+++ dirname /home/gopath/src/github.com/snapcore/snapd/tests/lib/snaps/snap-store/snap-store_1.0_all.snap
++ SNAP_DIR=/home/gopath/src/github.com/snapcore/snapd/tests/lib/snaps/snap-store
++ '[' '!' -f /home/gopath/src/github.com/snapcore/snapd/tests/lib/snaps/snap-store/snap-store_1.0_all.snap ']'
++ snap pack /home/gopath/src/github.com/snapcore/snapd/tests/lib/snaps/snap-store /home/gopath/src/github.com/snapcore/snapd/tests/lib/snaps/snap-store
++ '[' -f /home/gopath/src/github.com/snapcore/snapd/tests/lib/snaps/snap-store/snap-store_1.0_all.snap ']'
++ echo /home/gopath/src/github.com/snapcore/snapd/tests/lib/snaps/snap-store/snap-store_1.0_all.snap
+ SNAP_FILE=/home/gopath/src/github.com/snapcore/snapd/tests/lib/snaps/snap-store/snap-store_1.0_all.snap
+ snap install --dangerous /home/gopath/src/github.com/snapcore/snapd/tests/lib/snaps/snap-store/snap-store_1.0_all.snap
snap-store 1.0 installed
+ MATCH 'Fake snap got snap://package'
+ snap handle-link snap://package
+ [[ ubuntu-19.04-64 != ubuntu-1[46].04-* ]]
+ echo 'The same should work with xdg-open'
The same should work with xdg-open
+ MATCH 'Fake snap got snap://package'
+ xdg-open snap://package
/usr/bin/xdg-open: 870: /usr/bin/xdg-open: x-www-browser: not found
/usr/bin/xdg-open: 870: /usr/bin/xdg-open: firefox: not found
/usr/bin/xdg-open: 870: /usr/bin/xdg-open: iceweasel: not found
/usr/bin/xdg-open: 870: /usr/bin/xdg-open: seamonkey: not found
/usr/bin/xdg-open: 870: /usr/bin/xdg-open: mozilla: not found
/usr/bin/xdg-open: 870: /usr/bin/xdg-open: epiphany: not found
/usr/bin/xdg-open: 870: /usr/bin/xdg-open: konqueror: not found
/usr/bin/xdg-open: 870: /usr/bin/xdg-open: chromium: not found
/usr/bin/xdg-open: 870: /usr/bin/xdg-open: chromium-browser: not found
/usr/bin/xdg-open: 870: /usr/bin/xdg-open: google-chrome: not found
/usr/bin/xdg-open: 870: /usr/bin/xdg-open: www-browser: not found
/usr/bin/xdg-open: 870: /usr/bin/xdg-open: links2: not found
/usr/bin/xdg-open: 870: /usr/bin/xdg-open: elinks: not found
/usr/bin/xdg-open: 870: /usr/bin/xdg-open: links: not found
/usr/bin/xdg-open: 870: /usr/bin/xdg-open: lynx: not found
/usr/bin/xdg-open: 870: /usr/bin/xdg-open: w3m: not found
xdg-open: no method available for opening 'snap://package'
grep error: pattern not found, got:
-----
```

**Comment by bboozzoo** [comment]
Some more details from the spread test:
```
$ cat /usr/share/applications/snap-handle-link.desktop 
[Desktop Entry]
Name=Handler for snap:// URIs
Comment=Prompt the user to install gnome-software then pass control to it
Exec=/usr/bin/snap handle-link %U
MimeType=x-scheme-handler/snap;
NoDisplay=true
Type=Application
$ xdg-mime query default x-scheme-handler/snap
org.gnome.Software.desktop
$ grep snap /usr/share/applications/defaults.list 
x-scheme-handler/snap=org.gnome.Software.desktop
$ ls /usr/share/applications/org.gnome.Software.desktop
ls: cannot access '/usr/share/applications/org.gnome.Software.desktop': No such file or directory
```
Looks like gnome software is the default handler for `snap://...`, but it's not installed, so I have no idea why xdg-desktop would fall back to trying a browser rather than the next app that declares the mime type. Maybe @jhenstridge has some ideas.

**Comment by stolowski** [comment]
Can image: be updated now?

**Comment by sergiocazzolato** [comment]
@bboozzoo I see the test snap-handle-link works well if I don't pre-install the package evolution-data-server

**Comment by bboozzoo** [comment]
Maybe it's a bug in desktop-file-utils or xdg-utils. Anyways I could work around that by doing:
```
$ mkdir -p ~/.config
$ xdg-mime default snap-handle-link.desktop x-scheme-handler/snap 
$ xdg-open snap:///package
Fake snap got snap:///package
```
For some reason, xdg-open is not smart enough to use another handler when the default one does not exist.

For that matter, /usr/share/applications/defaults.list` is shipped by `desktop-file-utils`. Upon further investigation, the default assignment to use GNOME Software for opening `snap://..` is listed there. The defaults are not in Debian salsa, they are brought in by Ubuntu packaging.

@sergiocazzolato if you can get a hold of @jhenstridge and confirm it's a problem with xdg-open/desktop-file-utils, then filing a bug would be appropriate.

For now, I think you can just implement the workaround I did above. I belive `~/.config/mimeapps.list` is the only file that's modified, so it's probably best if you make a copy of that in `prepare` and bring it back in `restore`.

**Comment by sergiocazzolato** [comment]
@bboozzoo thanks for the research, I already updated the PR with that workaround.

**Pull request merged**
