### PR TITLE
daemon: replace shutdownServer with net/http's native shutdown support

### PR DESCRIPTION
**Pull request by jhenstridge**
While working on the session agent code, @chipaca suggested I not reuse the `shutdownServer` code in the daemon package and instead use the native shutdown support added to http.Server in Go 1.8.

That turned out to be fairly easy to do there, so I had a go removing `shutdownServer` all together.  I think I've maintained the same semantics as before, but here are some notes to help review:

1. There is a new `ConnTracker` type that can be plugged into an `http.Server`'s `ConnState` callback, and implements the Opinionator `CanStandBy` interface.  As it isn't responsible for the actual shutdown process, it only needs to track active connections.

2. The `snapServe` and `snapdServe` instances have been replaced with a single `http.Server` instance that listens on both sockets.  The two old servers shared the same handler, with `Command.canAccess` distinguishing connections on the two sockets with:

       isSnap := (socket == dirs.SnapSocket)

3. I am passing a context derived from `context.Background` to `http.Server.Shutdown`.  Using a context derived from the tomb won't result in a graceful shutdown, since it has already been cancelled at this point.

### CODE REVIEW

**Comment by jhenstridge** [comment]
Made a second simplification: we don't actually need two `http.Server` instances: we can just call Serve on the single instance twice.  Previously both instances shared the same handler, and socket based security checks are handled via the ucrednet code.

**Comment by chipaca** [comment]
I'm asking Samuele to take a look at this one as he wrote the original code AFAIR.

**Comment by pedronis** [comment]
The force push make it unclear to me what @chipaca actually approved ?? we tend not to force push at all once a PR was commented one.

**Comment by pedronis** [comment]
@jhenstridge sorry, I forgot you cannot merge? anyway my main point was to update the PR description to explain the entirety now of the change.

**Comment by pedronis** [comment]
@jhenstridge  @chipaca mmh, I merged master into this without conflicts to see if it would help with the spread failure, but now the unit tests of daemon fail in travis. they work locally here though. I don't have time to dig more...

**Comment by jhenstridge** [comment]
I think the problem is the `snapdListener.Close()` and `snapListener.Close()` calls in the `Stop` method.  `http.Server.Shutdown` will also try to close the listening sockets, and there seems to be a race over whether that will succeed or return `net.OpError`.

I think the right option here is to move the Shutdown() calls to where the current Close() calls are, with Shutdwon() called in a goroutine.  I think I'll need to split back into two http.Server instances too, so we can shut down the snapd socket before the snapctl socket.  I'll see what I can do.

**Comment by pedronis** [comment]
> I think the right option here is to move the Shutdown() calls to where the current Close() calls are, with Shutdwon() called in a goroutine.

this doesn't make sense to me, I'm missing something, but we really want to close and shutdown separately. I'm surely missing something

**Comment by pedronis** [comment]
this recent code in the stdlib itself (>=1.11) is interesting:

https://github.com/golang/go/blob/release-branch.go1.11/src/net/http/server.go#L2810

**Comment by jhenstridge** [comment]
> this doesn't make sense to me, I'm missing something, but we really want to close and shutdown separately. I'm surely missing something

The new `http.Server.Shutdown` method is effectively "close listening socket, disallow new requests, and wait for active requests to complete".  If we want to continue shutting down other parts of the daemon while waiting for requests to complete, we'd need to call it in a goroutine.

**Comment by pedronis** [comment]
> this doesn't make sense to me, I'm missing something, but we really want to close and shutdown separately. I'm surely missing something

> The new http.Server.Shutdown method is effectively "close listening socket, disallow new requests, and wait for active requests to complete". If we want to continue shutting down other parts of the daemon while waiting for requests to complete, we'd need to call it in a goroutine.

sorry, I still don't understand the conclusion. When confronted with a race, adding more concurrency doesn't sound like a solution.  I suppose I need to understand where those close errors come from and why we don't get them always...

**Comment by pedronis** [comment]
also notice, I now tried locally, it seems definitely that we always get this with 1.9 but not with 1.10 afaict

**Comment by pedronis** [comment]
@jhenstridge given that it seems I can now reproduce, I'm debugging this locally

**Comment by jhenstridge** [comment]
> sorry, I still don't understand the conclusion. When confronted with a race, adding more concurrency doesn't sound like a solution. I suppose I need to understand where those close errors come from and why we don't get them always...

My thought was to replace the existing Listener.Close calls with Server.Shutdown in a goroutine.  Then add some synchronisation at the point I'm currently calling Server.Shutdown to instead wait for the shutdown to complete (up to the timeout).  It's not a perfect equivalent since it loses the Close call as a synchronisation point.

That onceCloseListener type you found might be a more promising solution though.  Wrapping the listeners in a local copy of that would likely fix the race.

**Comment by pedronis** [comment]
@jhenstridge 

> That onceCloseListener type you found might be a more promising solution though. Wrapping the listeners in a local copy of that would likely fix the race.

yes, I'm exploring that right now

**Comment by pedronis** [comment]
done, @chipaca @jhenstridge a look over the new bits would be appreciated

**Comment by jhenstridge** [comment]
Your changes look good.  I made one small typo correction in the name of a test, but other than that it looked like a reasonable adaptation of the onceCloseListener code.

**Pull request merged**
