### PR TITLE
Change file names that are breaking go modules

### PR DESCRIPTION
**Pull request by slimjim777**
Fix file names as they break `go mod` when pulling in snapd into another project

Thanks for helping us make a better snapd!
Have you signed the [license agreement](https://www.ubuntu.com/legal/contributors) and read the [contribution guide](https://github.com/snapcore/snapd/blob/master/CONTRIBUTING.md)?

### CODE REVIEW

**Comment by slimjim777** [comment]
> I suspect the second rename needs tests to be adjusted

It was the cla_check.py that failed as the email is connected to a different LP account that I use for testing. I've signed the CLA for that account now. Can you trigger the Travis checks again?

**Comment by chipaca** [comment]
What are you using snapd as a library for?

**Comment by slimjim777** [comment]
> What are you using snapd as a library for?

Mainly for assertion handling. It is used in the Serial Vault, but this application is related to IoT use cases where the device sends the model/serial assertions to a cloud service for identification. So the assertions handling is needed on both the client and server side.

**Comment by chipaca** [comment]
OK. Please note we don't support Go versions other than 1.9 and 1.10, though.

**Comment by slimjim777** [comment]
> OK. Please note we don't support Go versions other than 1.9 and 1.10, though.

Understood. However, this is a small change and is good for forward compatibility. Version 1.10 is already a year old, and this removes a blocker for newer projects that are using the latest stable release.

**Comment by anonymouse64** [comment]
I retriggered the tests and they failed, but I can try to take this over when I get some spare cycles

**Comment by zyga** [comment]
Hello

Can you please re-base this on master. I some of the files this was touching were removed.

**Comment by zyga** [comment]
Thank you @slimjim777

**Pull request closed without merging**
