### PR TITLE
wrappers: use a revision-agnostic paths when rewriting a desktop file

### PR DESCRIPTION
**Pull request by oSoMoN**

### CODE REVIEW

**Comment by mardy** [comment]
The change itself is uncontroversial, so +1 from me on that, but what puzzles me is that the current implementation causes a problem. I would expect the `.desktop` file to be regenerated after each upgrade, so even using the revision number should be correct.

In other words, I'm wondering if we aren't hiding a bigger problem here.

**Comment by oSoMoN** [comment]
> The change itself is uncontroversial, so +1 from me on that, but what puzzles me is that the current implementation causes a problem. I would expect the `.desktop` file to be regenerated after each upgrade, so even using the revision number should be correct.
> 
> In other words, I'm wondering if we aren't hiding a bigger problem here.

Yes you're right, the desktop file is being regenerated after each refresh. However people and software do all sorts of things, including copying around desktop files (for instance to `~/.local/share/applications/`), and these copies aren't kept up-to-date. I wouldn't be surprised if there was some code in the wild that parses desktop files and stores a subset of the desktop entries in a custom format, and that wouldn't be kept up-to-date either.

**Comment by mardy** [comment]
> However people and software do all sorts of things, including copying around desktop files (for instance to `~/.local/share/applications/`), and these copies aren't kept up-to-date. I wouldn't be surprised if there was some code in the wild that parses desktop files and stores a subset of the desktop entries in a custom format, and that wouldn't be kept up-to-date either.

Thanks, this makes sense. LGTM then!

**Review by mardy — APPROVED** [review]

**Review by MiguelPires — APPROVED** [review]
LGTM

**Comment by pedronis** [comment]
I'm not against the change in itself, but do we understand what happens in the bug scenarios? are we getting new versions of a snap without going through the unlink/link process?  desktop files are not the only files that we expect to change/be regenerated in that scenario? can somebody articulate what is happening in the bug scenarios?

**Comment by pedronis** [comment]
Also have we tried if this doesn't create its own problems? There's a short window between this file being written and the current symlink existing, well there be races where the icons don't appear?

**Comment by oSoMoN** [comment]
It turns out [LP: #1964036](https://bugs.launchpad.net/ubuntu/+source/firefox/+bug/1964036) wasn't caused by snapd hardcoding the revision number in the Icon path in generated desktop files (see the latest comments in the bug for details).
So I've removed the link to that bug.

Still, a not-so-uncommon use case that I've seen described in the wild is for people to copy `/var/lib/snapd/desktop/applications/firefox_firefox.desktop` to `~/.local/share/applications` and modify the copy to suit their custom workflow (for example to add custom actions, or ensure that by default the application is always opened on a private window).

Desktop environment will override the original desktop file written by snapd with the custom one in the user's home directory, and all is good until the next firefox refresh, where the icon will disappear, because the hardcoded path in the copy of the desktop file wasn't updated.

**Comment by pedronis** [comment]
@oSoMoN as I wrote the desktop file is written before the current link is created, so I'm not sure this code change is entirely safe in the base scenario. We have discussed moving the creation of the desktop files later, when we connect the interfaces or so, but this wasn't done so far.

**Comment by oSoMoN** [comment]
Ok, so maybe this should be put on hold until the creation of the desktop files is deferred to a later phase?
It doesn't qualify as an urgent fix, so it can wait.

**Pull request closed without merging**
