### PR TITLE
store & many: a mechanical branch shortening store names

### PR DESCRIPTION
**Pull request by chipaca**
`store.NewUbuntuStoreSnapRepository` → `store.New`
`store.SnapUbuntuStoreRepository` → `store.Store`
`store.SnapUbuntuStoreConfig` → `store.Config`

bliss

### CODE REVIEW

**Comment by niemeyer** [comment]
\o/

**Comment by chipaca** [comment]
Rebased ontop of #1545 so maybe (compare with that directly)[https://github.com/chipaca/snappy/compare/kill-snappy...store-new].

**Comment by mvo5** [comment]
:+100:

**Comment by mvo5** [comment]
+:100:

**Pull request merged**
