### PR TITLE
cmd/snap: use snap-exec from core with a classic snap when reexecing

### PR DESCRIPTION
**Pull request by mwhudson**

### CODE REVIEW

**Comment by mwhudson** [comment]
> +1, we may need to adjust snap-confine's apparmor profile to allow this (needs checking)

Wouldn't the tests catch that? I don't think the travis failure here is my fault.

**Comment by bboozzoo** [comment]
I've restarted travis since it hit a timeout.

**Comment by bboozzoo** [comment]
Similar change, but including using distro local snap-exec also, was introduced in #4432. Can this PR be closed now?

**Comment by mwhudson** [comment]
Ah yes that makes this redundant I think.

**Pull request closed without merging**
