### PR TITLE
snap: add deprecation noticed to "snap run --gdb"

### PR DESCRIPTION
**Pull request by mvo5**
Now that we promoted "snap run --gdbserver" the "snap run --gdb" option should be deprecated. We plan to not improve it and it needs to run as root, the program and gdb share a pty and it's overall not great. So let's mark it deprecated and point users to `snap run --gdbserver` instead.

Based on https://github.com/snapcore/snapd/pull/9908

### CODE REVIEW

**Review by anonymouse64 — APPROVED** [review]
lgtm

**Review by stolowski — APPROVED** [review]
Makes sense, thank you!

**Comment by mvo5** [comment]
Added Samuele as this is a user facing change just to double check he is aware/okay with it.

**Review by pedronis — COMMENTED** [review]
this looks reasonable

**Review by pedronis — APPROVED** [review]

**Pull request merged**
