### PR TITLE
image,cmd/snap,tests: add support for store-wide cohort keys

### PR DESCRIPTION
**Pull request by xnox**
image,cmd/snap,tests: add support for store-wide cohort keys

Add hidden UBUNTU_STORE_COHORT_KEY environment variable to
prepare-image, which works like the --cohort option in the download
command. This is to be used by livecd-rootfs during classic image
building with the store-wide any-snap cohort keys. This is required to
move livecd-rootfs from using download, to using prepare-image.

### CODE REVIEW

**Comment by zyga** [comment]
@xnox you need to reformat the code with gofmt from go 1.6, I'm afraid.

**Comment by pedronis** [comment]
The cohorts that we fully support officially in snapd (as produced by snap create-cohort) are per-snap, so a global user visible single cohort option like this doesn't make sense, because it would confused end users.

What we can do, is support this use case (as we do for other things) setting this via an env variable.

**Comment by xnox** [comment]
> The cohorts that we fully support officially in snapd (as produced by snap create-cohort) are per-snap, so a global user visible single cohort option like this doesn't make sense, because it would confuse end users.
> 
> What we can do, is support this use case (as we do for other things) setting this via an env variable.

@pedronis what should the env variable be called? `UBUNTU_STORE_COHORT_KEY` ?

@pedronis `snap create-cohort \*` does create the right any snap cohort key. So i guess, supporting per-snap cohort keys, is simply a superset. And if there was a per-snap cohort key, one could specify the star one, for every single snap.

How would you want the per-snap cohort keys look like, on the command line?
```
--snap=core18=latest/stable@MSBDU08wNEpoYXYyeUswdXo5N2NyMGlw...
or
--cohort=core18=MSBDU08wNEpoYXYyeUswdXo5N2NyMGlw...
``` 

And do you want to propagate the cohort-keys via seed.yaml to the installed systems? (or have that as an option) One might want consistent images, but not necessarily consistent cohorts when those images are deployed.

**Comment by pedronis** [comment]
> @pedronis what should the env variable be called? UBUNTU_STORE_COHORT_KEY ?

let's start just with this, yes that var name seems alright.

Capturing cohorts inside images is not very useful I think, we will work on a feature called validation-sets that makes can achieve similar things and makes more sense, for the lock the image itself, vs use the same snaps at build time.

**Comment by xnox** [comment]
> @xnox you need to reformat the code with gofmt from go 1.6, I'm afraid.



> > @pedronis what should the env variable be called? UBUNTU_STORE_COHORT_KEY ?
> 
> let's start just with this, yes that var name seems alright.
> 
> Capturing cohorts inside images is not very useful I think, we will work on a feature called validation-sets that can achieve similar things and makes more sense, for locking the image itself, vs use the same snaps at build time.

Sounds good! Let me try to fix this all up then.

**Comment by xnox** [comment]
@pedronis Can you please review this? (zyga marked you as the reviewer).

The matching livecd-rootfs code that is using this is ready now too, and tested against the Ubuntu Server Live image at https://code.launchpad.net/~xnox/livecd-rootfs/+git/livecd-rootfs/+merge/383947

**Comment by pedronis** [comment]
I will look at this early next week

**Pull request merged**
