### PR TITLE
recovery: update fde-utils

### PR DESCRIPTION
**Pull request by cmatsuoka**
Update ubuntu-core-fde-utils to the latest version, and refactor
the recovery code to use the new API. Also remove unused
recovery code.

Signed-off-by: Claudio Matsuoka <claudio.matsuoka@canonical.com>

### CODE REVIEW

**Comment by zyga** [comment]
@cmatsuoka unit tests seem to fail, required packaging changes missing?

**Comment by cmatsuoka** [comment]
We're building with go 1.9.7 and go-tpm2 uses `strings.Builder` which was introduced in go 1.10. I'll ask @chrisccoulson to change go-tpm2 to be buildable with go 1.9.

**Comment by xnox** [comment]
Given this targets uc20, shouldn't we aim to use newer go? Like 1.12?

**Comment by cmatsuoka** [comment]
We're using different versions in tests, including newer ones, and the 1.9 series.

**Pull request merged**
