### PR TITLE
tests: avoid checking TRUST_TEST_KEYS on restore on remodel-base test

### PR DESCRIPTION
**Pull request by sergiocazzolato**
As TRUST_TEST_KEYS is false, the restore is not being executed and the
model is not restored making the reset helper fail.

### CODE REVIEW

**Review by mvo5 — APPROVED** [review]
Thanks, that is a nice catch

**Review by mvo5 — APPROVED** [review]
Nice!

**Review by anonymouse64 — COMMENTED** [review]
This seems okay to me, but I notice that the PR from @bboozzoo to enable REBOOT in the restore section is still open: https://github.com/snapcore/spread/pull/85 so I'm not sure that this will actually work? Unless I'm missing something or we are using a version of spread which has that PR/patch applied already...

/me also notices that it is time for a biyearly check-up on that PR

**Comment by mvo5** [comment]
> This seems okay to me, but I notice that the PR from @bboozzoo to enable REBOOT in the restore section is still open: [snapcore/spread#85](https://github.com/snapcore/spread/pull/85) so I'm not sure that this will actually work? Unless I'm missing something or we are using a version of spread which has that PR/patch applied already...
> 
> /me also notices that it is time for a biyearly check-up on that PR

This bug only exists with bash-4.3 AFAIK, in 18.04 we have bash-4.4 so this particular issue is fixed and the test in question only runs on 18.04 systems. So I think we are good here. But it would be nice to workaround it in spread so that we can use this on UC16 too.

**Comment by bboozzoo** [comment]
I see this sequence in spread tests:
```
2021-12-06 19:31:45 Restoring google:ubuntu-core-18-64:tests/core/remodel-base (dec061913-891707)...
...
2021-12-06 19:36:45 WARNING: dec061913-891707 (google:ubuntu-core-18-64:tests/core/remodel-base) running late. Current output:
...
2021-12-06 19:37:25 Rebooting on dec061913-891707 (google:ubuntu-core-18-64:tests/core/remodel-base) as requested...
```
so it seems that reboot happened. Perhaps we should merge it then, close the other PR and just remember to avoid reboots on 16.04.

**Comment by sergiocazzolato** [comment]
Right I tested yesterday and it worked: https://paste.ubuntu.com/p/W9PtqVZgrR/

**Comment by anonymouse64** [comment]
Thanks for the clarification folks, I hadn't put together that the existing limitation that prompted that spread PR was just for old bash on xenial, etc.

**Pull request merged**
