### PR TITLE
integration-tests: look for ubuntu-device-flash on PATH before calling sudo

### PR DESCRIPTION
**Pull request by mwhudson**
My sudo doesn't preserve PATH and I don't have ubuntu-device-flash on the default one...

### CODE REVIEW

**Comment by zyga** [comment]
Looks good to me

**Comment by zyga** [comment]
You need to teach your $EDITOR about `go fmt`:

```
Formatting wrong in following files
integration-tests/testutils/image/image.go
```

**Comment by mwhudson** [comment]
heh that's what i get for submitting quick hacks without checking anything. please take another look.

**Comment by mvo5** [comment]
:+1:

**Comment by mwhudson** [comment]
So can someone merge this?

**Pull request merged**
