### PR TITLE
tests: remove quoting from [[ ]] when globs

### PR DESCRIPTION
**Pull request by zyga**
It seems that shell has a peculiar quoting rules when [[ ]] expressions
are used. [[ "foo" == f* ]] returns 0 while [[ "foo" == "f*" ]] returns 1.
The glob magic is on only if the expression on the right hand side is
unquoted.

Signed-off-by: Zygmunt Krynicki <zygmunt.krynicki@canonical.com>

### CODE REVIEW

**Comment by morphis** [comment]
LGTM, @zyga btw. are we using signed-off-by for snapd? I never used it so far and we should make it either a common thing or everybody does or drop it.

**Comment by ogra1** [comment]
double brackets are a bash only feature, please do not use it if you can avoid it or make sure that either /bin/sh points to /bin/bash in your environment or your shebang is explicitly set to #! /bin/bash (to be more compatible we should really make sure to only use POSIX shell unless it is unavoidable)
see https://wiki.ubuntu.com/DashAsBinSh#A.5B.5B

**Comment by chipaca** [comment]
@ogra1 this is in a spread `task.yaml`, which is bash and not sh

**Comment by ogra1** [comment]
@chipaca well, as long as we are sure this never runs in other distros or setups ... it doesnt do any harm to use [ ] over [[ ]] though (and makes no difference in execution apart from being portable)

**Comment by chipaca** [comment]
@ogra1 except that the reason it's using `[[` instead of `[` is to get the pattern matching which `[` does not provide :-)
And sure, it could be done with grep instead.

**Comment by ogra1** [comment]
case "$SPREAD_SYSTEM" in
    debian-*)
        exit 0
        ;;
esac

... about ten times as fast and more efficient ... (and portable as well)

**Comment by chipaca** [comment]
After re-running spread a number of times, I need to ask: are you sure you want to exit early from the test when the system *isn't* debian? I'm suspecting you meant the opposite.

**Comment by zyga** [comment]
@morphis can you have a look at @chipaca's question please?

**Comment by morphis** [comment]
> After re-running spread a number of times, I need to ask: are you sure you want to exit early from the test when the system isn't debian? I'm suspecting you meant the opposite.

The test should be $SPREAD_SYSTEM = debian-* instead of $SPREAD_SYSTEM != debian-*

This should solve the still failing CI.

@zyga Can you change that?

**Comment by chipaca** [comment]
@morphis wouldn't it make sense to make it be `!= ubuntu-*`?

**Comment by morphis** [comment]
> @morphis wouldn't it make sense to make it be != ubuntu-*?

We could but I will propose a change before we land any other SPREAD_SYSTEM which will make this check superfluous so lets fix this the easy way for now.

**Pull request merged**
