### PR TITLE
many: update vendored apparmor to 4.0.1

### PR DESCRIPTION
**Pull request by alexmurray**
Thanks for helping us make a better snapd!
Have you signed the [license agreement](https://www.ubuntu.com/legal/contributors) and read the [contribution guide](https://github.com/snapcore/snapd/blob/master/CONTRIBUTING.md)?

### CODE REVIEW

**Comment by alexmurray** [comment]
Closing and reopening to retrigger github actions.

**Comment by Meulengracht** [comment]
@alexmurray is this still relevant?

**Comment by alexmurray** [comment]
Yes :) - I think I need to rebase it on master though so will try freshen it up again soon.

**Comment by alexmurray** [comment]
Updated to use the new 4.0.0 beta3 upstream release of apparmor and rebased on current snapd master.

**Comment by alexmurray** [comment]
There is at least one real spread test failure due to this PR - tests/main/snapd-homedirs-vendored - which downloads the current snapd snap, and repacks it with the contents of the snapd deb built from this PR - this fails since the repacked snap now has a snapd which expects the vendored apparmor to be version 4.0 (and hence to contain the 4.0 abi definition) but the snap downloaded from edge only has apparmor 3.0 as the vendored version. I can't think of a good way to fix this and so this test will always fail when upgrading to new apparmor major versions like this. Thought @pedronis @zyga @bboozzoo?

Marking this PR as ready for review now though since this is the only spread failure that looks legitimate - the rest appear to be transient issues or already failing on master.

**Comment by zyga** [comment]
I would hold off until we get a fixed copy of apparmor 4 released upstream.

**Comment by ernestl** [comment]
Removing this from 2.63 ( see https://github.com/snapcore/snapd/pull/13354#issuecomment-2011904861)

**Comment by alexmurray** [comment]
@ernestl When is the deadline for 2.63? It is possible there will be a fixed version of apparmor before then.

**Comment by ernestl** [comment]
> @ernestl When is the deadline for 2.63? It is possible there will be a fixed version of apparmor before then.

We do not have 100% certainty yet, but likely between 5 and 12 April.

**Comment by alexmurray** [comment]
@ernestl any chance we can target this for 2.64? Also @pedronis @zyga @bboozzoo any chance you could weigh in on my question above^^^ https://github.com/snapcore/snapd/pull/13354#issuecomment-2011246767 re the failing spread tests?

**Comment by ernestl** [comment]
**Agreed strategy:**
 - Wait for security SRU to Noble to conclude (likely approx 2 weeks)
 - Wait to gauge performance/feedback
 - Aim to release this as part of 2.64 with preliminary release process kick-off start July.

**Comment by zyga** [comment]
I've rebased this and pushed as a draft to https://github.com/snapcore/snapd/pull/14150 to see test results and keep rebasing without breaking what you did here. I want to be able to compare the results in the end.

**Comment by alexmurray** [comment]
Thanks for the heads up @zyga - let me know if you need me to do anything.

**Comment by zyga** [comment]
I've dismissed my review request since I've opened https://github.com/snapcore/snapd/pull/14150 with some additional changes.

**Comment by zyga** [comment]
This has landed through https://github.com/snapcore/snapd/pull/14150

**Pull request closed without merging**
