### PR TITLE
tests/main/cgroup-tracking-failure: Make it pass when run alone

### PR DESCRIPTION
**Pull request by valentindavid**
This test does not behave the same if it was run alone or after other
tests like `tests/main/cgroup-tracking` or
`tests/main/cgroup-tracking`. So we need to simulate the other tests
bad cleanup to make it succeed alone.

It is not possible to properly cleanup the root session without having
all ssh connection restarted.

### CODE REVIEW

**Comment by bboozzoo** [comment]
It's a bit worrying that the previous restore did not clean up things properly. Did you have a chance to investigate that more deeply?

**Comment by valentindavid** [comment]
> It's a bit worrying that the previous restore did not clean up things properly. Did you have a chance to investigate that more deeply?

`tests.session restore` has a condition if user is root. And in this case does not do everything. I think that we need to log out completely to be able to restore properly. Or reboot.

**Review by bboozzoo — APPROVED** [review]
I hoped that maybe we could drop some bits of the test that poke session things are root, but the test is rather specific about the scenarios it tries, so it probably makes sense to live that code and add a workaround for session cleanup.

**Review by mardy — APPROVED** [review]
The workaround is small, confined in a single point and well commented, so it definitely LGTM.

**Pull request merged**
