### PR TITLE
build-aux: use core20 as base for the snapd snap build

### PR DESCRIPTION
**Pull request by mardy**
This was created just as an experiment, but it turns out that the spread is green, so maybe it's something we can consider :-)

### CODE REVIEW

**Comment by mardy** [comment]
Closing and reopening to run the nested tests, too.

**Review by mvo5 — APPROVED** [review]
This looks great. However one open question is what to do about i386 - it's no longer build with 20.04 afaict

**Comment by mvo5** [comment]
> This looks great. However one open question is what to do about i386 - it's no longer build with 20.04 afaict

Maybe this is fine actually - I see that i386  still selectable in the LP builds even with core20 as the base.

**Comment by xnox** [comment]
> > This looks great. However one open question is what to do about i386 - it's no longer build with 20.04 afaict
> 
> Maybe this is fine actually - I see that i386 still selectable in the LP builds even with core20 as the base.

that's just filters. it will not build i386 with build-base core20.

But also we don't need it anymore.

i386 has never been supported as a host architecture under ESM for Ubuntu. Bionic was the last release that built i386 .deb. And is going ESM next week.

Thus we should just stop building i386 builds of snapd, but keep it published as is, in Bionic i386.deb & latest/stable i386 deb, as frozen in time.

If a need ever arises to ship security fix of snapd in bionic, we will do a targetted bugfix only build.

**Comment by xnox** [comment]
All of these things can be already merged into master-riscv64 as it is already using build-base:core20.
Also, we could separate and merge individual pieces of this PR into master - i.e. dropping fontconfig caches will help a lot, and can be merged stand alone.

**Comment by mvo5** [comment]
This is closed in favor of https://github.com/snapcore/snapd/pull/12679 - the i386 build issue makes it unlikely that it can be used and most likely we will have to (cross) build our own (like the other PR is doing)

**Pull request closed without merging**
