### PR TITLE
cmd: fix C formatting

### PR DESCRIPTION
**Pull request by zyga**
Signed-off-by: Zygmunt Krynicki <zygmunt.krynicki@canonical.com>

### CODE REVIEW

**Comment by zyga** [comment]
It's applied automatically but let me double-check that.

**Comment by zyga** [comment]
@bboozzoo good catch, the snap-update-ns directory was not included. This is fixed now.

**Comment by mvo5** [comment]
We will loose `git blame`ability for a lot of code once this is applied. Maybe unavoidable if we really want to have `make fmt` for everything.

**Comment by zyga** [comment]
We can look past the format change with git log, that code doesn't have that much churn going on.

**Pull request merged**
