### PR TITLE
systemd: add `WantedBy=default.target` to snap mount units

### PR DESCRIPTION
**Pull request by mardy**
When booting in OEM configuration mode, the systemd target is set to
`oem-config.target` instead of the usual `multi-user.target`; if our
mount units require solely the multi-user target, which is not reached
during OEM configuration mode, they won't be started.

So, let's add `default.target` to our mount units: this target is a
symbolic link to the system default target, which is usually
`multi-user.target` for a desktop session.

Most likely, there's no need to keep `multi-user.target` in the
`WantedBy` line, but since this is a hotfix, let's take a defensive
approach and keep it until we have the time to verify that removing it
does not cause any regression.

Fixes LP:#1983528

### CODE REVIEW

**Review by alexmurray — APPROVED** [review]
LGTM. Eventually I think we should replace all uses of multi-user.target with default.target in all the generated and static systemd unit/service files.

**Review by MiguelPires — APPROVED** [review]
LGTM

**Review by jhenstridge — APPROVED** [review]
Looks good to me.

I was initially concerned that this might add the mount to whatever the current `default.target` is, and not activate on the new default during OEM first boot but I don't think that's the case. I've got a few services on my system enabled through `/etc/systemd/system/default.target.wants`, and they seem to start with the default `graphical.target`.

**Comment by alexmurray** [comment]
@jhenstridge when using default.target it gets symlinked as `/etc/systemd/system/default.target.wants/xxx` so then no matter what the default target is actually it gets used - not sure why this isn't used more often - most packages and even systemd itself seems to use multi-user.target...

**Comment by xnox** [comment]
No unit should ever have dependencies on `default.target` as per systemd upstream.

The default.target can be set to emergency.target, basic.target, system-update.target during which such mounts are undesired or harmful. (lack of resources, extreme memory pressure, etc).

It makes more sense for mount units to have:

```
[Mount]
After=local-fs.target zfs.target

[Install]
WantedBy=local-fs.target
```

Such that once all `/etc/fstab` listed stuff is mounted, snaps What= path is available and should be mounted.

**Comment by mardy** [comment]
> No unit should ever have dependencies on `default.target` as per systemd upstream.
> 
> The default.target can be set to emergency.target, basic.target, system-update.target during which such mounts are undesired or harmful. (lack of resources, extreme memory pressure, etc).

What you write makes a lot of sense, and thanks for the hint on using the local-fs target. We are still considering the various options, but just to unlock the 22.04.1 point release we'll go with this fix here, unless it turns out that it's not working.

We will definitely come back to this and implement your suggestion, plus a few other approaches (like the one in https://github.com/snapcore/snapd/pull/12016, and maybe adding something to the snapd unit to prevent it from starting if the mount unit have not been activated).

**Comment by xnox** [comment]
@mardy 
https://manpages.ubuntu.com/manpages/kinetic/en/man7/systemd.special.7.html#:~:text=on%20this%20unit.-,default.target,-The%20default%20unit

https://manpages.ubuntu.com/manpages/kinetic/en/man7/bootup.7.html

Are the relevant pages. normally default.target is a symlink of the default boot target one must boot to...... however one can override that out of band without touching disk via kernel commandline; reboot args; and many other ways. Such that "default.target" might be one thing; and yet one is booting to something else which is _not_ called default.target, and again your units will not start.

after local-fs.target or part of basic.target are much better locations to do snaps mounting. See the diagrams in the second manpage i have linked above.

It very much depends on what things you require in the runtime around you: i.e. do you need sockets to things, do you need snapd.service running, etc.

**Pull request merged**
