### PR TITLE
tests: make main/help run on opensuse and fedora again

### PR DESCRIPTION
**Pull request by chipaca**
This _will fail_ because we've not kept the spec files up to date.

I know nothing about spec files, and I don't intend to learn.... who can fix this? Please fix this.

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
@chipaca I've fixed for Fedora in #3577.

**Comment by Conan-Kudo** [comment]
@chipaca This was merged in already for Fedora with #3584. So, you can close this now.

**Comment by chipaca** [comment]
@Conan-Kudo aren't we still missing similar work for opensuse?

**Comment by Conan-Kudo** [comment]
@chipaca the openSUSE spec needs to be fixed, yes, but @zyga or @morphis is on it. Now that I've made my changes, they know what to do for openSUSE.

**Pull request closed without merging**
