### PR TITLE
osutil: fix parsing super-block options with spaces

### PR DESCRIPTION
**Pull request by zyga**
On any Windows + WSL 2 + Docker system, running any snap command is immediately preceded by the two errors:
```
  2023/06/17 23:59:52.071511 system_key.go:129: cannot determine nfs usage in
  generateSystemKey: cannot parse mountinfo: incorrect number of tail fields,
  expected 3 but found 4
  2023/06/17 23:59:52.080033 cmd_run.go:1046: WARNING: cannot create user data
  directory: cannot determine SELinux status: failed to obtain SELinux mount
  path: incorrect number of tail fields, expected 3 but found 4
```
Those errors confuse tools that parse program output and generally cause a lot of havoc.

The root of the issue is caused by this specific entry in /proc/self/mountinfo (not wrapped to preserve the problematic part more prominently):
```
  1146 77 0:149 / /Docker/host rw,noatime - 9p drvfs rw,dirsync,aname=drvfs;path=C:\Program Files\Docker\Docker\resources;symlinkroot=/mnt/,mmap,access=client,msize=262144,trans=virtio
```
Note that the super-block mount option contains a key=value pair where the value contains un-escaped spaces. Historically mountinfo has been an utter mess to parse, with several bugs in both the userspace parsing and several bugs in the fragile kernel interface generating the contents of said file.

To work around this problem allow spaces in the super-block options and silently parse them as if they had been escaped correctly.

### CODE REVIEW

**Comment by zyga** [comment]
Hey @alexmurray - this is a small patch that makes snaps usable on WSL if you also happen to have Docker installed - please tell me if the way the change is made is sensible, or of some other approach is viable in Your eyes. Thanks!

**Comment by alexmurray** [comment]
hey @zyga  - apologies I'm taking to long to get to this - I hope to take a proper look tomorrow so with any luck it should be done on my side in 24h

**Review by alexmurray — APPROVED** [review]
LGTM - whilst this change adds some complexity and makes this already fragile code a bit more fragile, I think it is definitely worth it to support this reasonably common use-case.  The nature of /proc/mountinfo lacking good uniform escaping etc means we have to try and be more lenient. Also this is already a trusted input so it doesn't add any extra risk to add this complexity.

Thanks @zyga.

**Comment by zyga** [comment]
@mvo5 could this be considered for the next release?

**Review by mvo5 — APPROVED** [review]
Thanks! I like this! I tweaked the naming and added a small comment. But did not change anything else.

**Pull request merged**
