### PR TITLE
vendor: bump github.com/canonical/go-tpm2 revision

### PR DESCRIPTION
**Pull request by mvo5**
This bumps the version of go-tpm2 to hopefully include all the fixes
required for sha3 support in the TPM that the Taipei needs.

It's a bit unclear if any of the recent changes since 2021-03-14T16:00:24 will help with the sha3 issue that Taipei has so I added Chris as reviewer.

### CODE REVIEW

**Comment by chrisccoulson** [comment]
The recent changes aren't really necessary for this, although I am about to open a secboot PR to move to the latest version (I need some new APIs for another project, and I'm also going to start updating the tests to use go-tpm2/testutil)

**Review by bboozzoo — APPROVED** [review]
FWIW the bump looks good to me

**Comment by anonymouse64** [comment]
Hmm 21.04 still failed to prepare here not finding the `go` command, I wonder if we need another master merge here?

**Comment by pedronis** [comment]
@mvo5 this seems to have real failures but unsure

**Comment by mvo5** [comment]
Closing as we don't really need this currently. The initial reason this was opened was sha3 support in the tpm but that is already in.

**Pull request closed without merging**
