### PR TITLE
usersession/userd: add msteams url support

### PR DESCRIPTION
**Pull request by call-a3**
I mirrored #8254 to add Microsoft Teams support. I'm aware a more generic/structural solution should be found, but this helps out in the mean time.

### CODE REVIEW

**Comment by mvo5** [comment]
Thanks for the PR! This needs a security review so it might take a little bit to review, my apologies for this. But once that's out of the way this looks fine.

**Comment by jdstrand** [comment]
> Again, I don't want to not merge this PR, just that xdg-desktop-portal may already be solving this issue for you today with the candidate channel of snapd.

Note that the xdg-desktop-portal review did not got through the security team. Looking at https://github.com/snapcore/snapd/pull/8289/files#diff-ec54ac50e412d58d8f1ed2c3e239c4b9R165, IME this is roughly equivalent to simply removing allowedURLSchemes and url parsing checks from userd (ie, with PR 8289, we may as well just send the uri straight to the system's xdg-open, which we were previously overly cautious about, but more recently less so). Again, I've not reviewed the xdg-desktop-portal code opening helper applications, so maybe it is ok, but I don't see where that happened in PR 8289 or PR 7963. (cc @mvo5 and @jhenstridge).

**Comment by bboozzoo** [comment]
I've merged master and pushed to include some fixes that landed in the meantime.

**Comment by jhenstridge** [comment]
> Again, I've not reviewed the xdg-desktop-portal code opening helper applications, so maybe it is ok, but I don't see where that happened in PR 8289 or PR 7963. (cc @mvo5 and @jhenstridge).

The current policy in xdg-desktop-portal is described in https://github.com/flatpak/xdg-desktop-portal/pull/419

In short, it will avoid presenting the file chooser in these situations:

1. it is an `http`, `https`, `ftp`, `mailto`, `webcal`, or `calendar` link, or of mime type `inode/directory`, and there is a default app for that scheme/content type.
2. if there is only a single app that can handle the file
3. the user has repeatedly picked the same choice more times than a certain threshold (defaulting to 3).

It is also possible for the user to force the app chooser to display on either a per content type/scheme basis, or (content type, calling app) basis, as described here:

https://github.com/flatpak/xdg-desktop-portal/wiki/The-Permission-Store#the-desktop-used-apps-table

The sandboxed application can also request that the app chooser always be displayed, but that is not really relevant to the security of the interface.

**Pull request merged**
