### PR TITLE
interfaces/system-packages-doc: allow read-only access to /usr/share/gtk-doc

### PR DESCRIPTION
**Pull request by jbicha**
See https://launchpad.net/bugs/1960546

I'd like to have this in Ubuntu 22.04 LTS.

An unrelated [bug](https://launchpad.net/bugs/1966418) makes devhelp not work in Ubuntu's default session for me.

### CODE REVIEW

**Review by bboozzoo — APPROVED** [review]
LGTM, let's see if https://github.com/snapcore/snapd/pull/11615 ends up moving to a more generic rule, in which case it will already cover the path access from this PR.

**Review by stolowski — APPROVED** [review]
LGTM, thanks

**Comment by jbicha** [comment]
Oh, minor typo in the commit message: should be "read-only" instead of "ready-only". Not sure that it's worth redoing the checks for that.

**Comment by jbicha** [comment]
> Oh, minor typo in the commit message: should be "read-only" instead of "ready-only". Not sure that it's worth redoing the checks for that.

Never mind. I am going to repush to my branch because there's another typo that does need to be fixed.

**Comment by bboozzoo** [comment]
@jbicha hope you don't mind, I've pushed a couple of patches: a merge from master to take care of the conflicts, little apparmor profile update and a updated the spread test to verify that gtk-doc can indeed be accessed.

**Pull request merged**
