### PR TITLE
tests: drop any-python wrapper

### PR DESCRIPTION
**Pull request by bboozzoo**
Python 3 should be available everywhere at this point. Try dropping the wrapper.

### CODE REVIEW

**Review by mvo5 — APPROVED** [review]
Looks fine (assuming tests are green)

**Comment by bboozzoo** [comment]
Most of the tests are green, the failures are unrelated (deltas and a 408 fetching some snaps on 21.04)

**Review by anonymouse64 — APPROVED** [review]
lgtm

**Review by stolowski — APPROVED** [review]
Thanks!

**Review by sergiocazzolato — APPROVED** [review]
nice, thanks

**Pull request merged**
