### PR TITLE
spread.yaml: set default kernel channel to beta

### PR DESCRIPTION
**Pull request by alfonsosanchezbeato**
Channel for kernel cannot be edge as that one is not signed with Canonical keys anymore.

### CODE REVIEW

**Comment by Meulengracht** [comment]
I'm seeing some failures related to such things as:
```
Error: 2023-10-18 08:53:54 Error restoring google:ubuntu-core-18-64:tests/lib/tools/suite/version-compare (oct180740-909701) : 
-----
+ /home/gopath/src/github.com/snapcore/snapd/tests/lib/prepare-restore.sh --restore-suite-each-minimal-no-snaps
+ set -e
+ . /home/gopath/src/github.com/snapcore/snapd/tests/lib/pkgdb.sh
+ . /home/gopath/src/github.com/snapcore/snapd/tests/lib/random.sh
+ . /home/gopath/src/github.com/snapcore/snapd/tests/lib/state.sh
++ SNAPD_STATE_PATH=/var/tmp/snapd-tools/snapd-state
++ SNAPD_STATE_FILE=/var/tmp/snapd-tools/snapd-state/snapd-state.tar
++ SNAPD_ACTIVE_UNITS=/var/tmp/snapd-tools/runtime-state/snapd-active-units
+ case "$1" in
+ restore_suite_each minimal-no-snaps
+ local variant=minimal-no-snaps
+ rm -f /var/tmp/snapd-tools/runtime-state/audit-stamp
+ tests.cleanup restore
+ tests.backup restore
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
```

Is this a different bug or do wer have any idea of why this happens, this is for UC 18 tests

**Comment by alfonsosanchezbeato** [comment]
I have reverted 2fc15b668e08c353164ed75ff1b8b1863cc7b836 as according to https://bugs.launchpad.net/launchpad/+bug/2039251 this launchpad issue has been fixed and released (see also https://bugs.launchpad.net/ubuntu/+source/software-properties/+bug/2039411)

**Review by sergiocazzolato — APPROVED** [review]
Nice

**Review by Meulengracht — APPROVED** [review]
+1!

**Pull request merged**
