### PR TITLE
fixme: rename ubuntu*architectures to dpkg*architectures

### PR DESCRIPTION
**Pull request by ardaguclu**
As stated in the arch package;
`FIXME: rename all Ubuntu*Architecture() to SnapdArchitecture() (or DpkgArchitecture)`

This package does not only deal about Ubuntu architectures, it actually covers Debian equivalent architectures and that's why, architecture has been renamed as DpkgArchitecture and it's related packages also made compatible with it.

### CODE REVIEW

**Comment by zyga** [comment]
Looking at test failures I think there's one more place to apply the replacement:
```
dpkg-source: info: using patch list from debian/patches/series
patching file cmd/snap-seccomp/main.go
Hunk #1 FAILED at 180.
1 out of 1 hunk FAILED
patching file cmd/snap-seccomp/main_test.go
Hunk #1 FAILED at 32.
1 out of 1 hunk FAILED
```

@ardaguclu can you please look at updating `debian/patches/*` for cases of `UbuntuArchitecture` rename?

**Comment by mvo5** [comment]
@ardaguclu Please also let us know if the patch refreshing is troublesome, it can be so if its too annoying just let us know and we will do it for you :) sorry for this extra hurdle :/

**Comment by ardaguclu** [comment]
@mvo5 @zyga I looked at cmd/snap-seccomp, but it has been already renamed. And I do not figure out how to generate debian-sid/patches. Are they auto generated?, or should we change necessarily parts manually?.

Only place left as UbuntuArchitecture in the code base is in "0003-cmd-snap-seccomp-skip-tests-that-use-m32.patch", I guess, it should be changed for working tests.

**Comment by mvo5** [comment]
@ardaguclu No worries, I looked at the issue and pushed a small fix and avoids changing the debian/patches (see the commit message for details, hope you like it/agree with it). If you are interessted, the debian/patches stuff is managed via "quilt"(1) and popular for debian packaging but not used outside much because nowdays everyone else uses more powerful tools like "git" :)

**Comment by ardaguclu** [comment]
Thanks a lot. Fix is ok for me.

**Comment by zyga** [comment]
Hey @mvo5 - I think your patch needs to be patched:
```
+ dpkg-buildpackage -S --no-sign
dpkg-buildpackage: info: source package snapd
dpkg-buildpackage: info: source version 2.40-2
dpkg-buildpackage: info: source distribution UNRELEASED
dpkg-buildpackage: info: source changed by Jamie Strandboge <jamie@ubuntu.com>
 dpkg-source --before-build .
dpkg-source: info: using options from snapd/debian/source/options: --include-removal
dpkg-source: info: using patch list from debian/patches/series
dpkg-source: info: applying 0001-cmd-snap-seccomp-use-upstream-seccomp-package.patch
dpkg-source: info: applying 0002-cmd-snap-seccomp-skip-tests-that-fail-on-4.19.patch
dpkg-source: info: applying 0003-cmd-snap-seccomp-skip-tests-that-use-m32.patch
patching file cmd/snap-seccomp/main_test.go
Hunk #1 FAILED at 185.
1 out of 1 hunk FAILED
dpkg-source: info: the patch has fuzz which is not allowed, or is malformed
dpkg-source: info: if patch '0003-cmd-snap-seccomp-skip-tests-that-use-m32.patch' is correctly applied by quilt, use 'quilt refresh' to update it
dpkg-source: info: restoring quilt backup files for 0003-cmd-snap-seccomp-skip-tests-that-use-m32.patch
dpkg-source: error: LC_ALL=C patch -t -F 0 -N -p1 -u -V never -E -b -B .pc/0003-cmd-snap-seccomp-skip-tests-that-use-m32.patch/ --reject-file=- < snapd/debian/patches/0003-cmd-snap-seccomp-skip-tests-that-use-m32.patch subprocess returned exit status 1
dpkg-buildpackage: error: dpkg-source --before-build . subprocess returned exit status 2
```

**Comment by mvo5** [comment]
@zyga Done - the patch is refreshed and I pushed a new version.

Fun side note - this is actually your patch :)
```
$ grep From: packaging/debian-sid/patches/0003-cmd-snap-seccomp-skip-tests-that-use-m32.patch
From: Zygmunt Krynicki <me@zygoon.pl>
```

**Pull request merged**
