### PR TITLE
github: add github workflow

### PR DESCRIPTION
**Pull request by sd-hd**
An github CI/CD workflow for building and releasing snapd on github.

### CODE REVIEW

**Comment by anonymouse64** [comment]
When does this create a release? I can't tell from the github actions yaml what triggers the release to be created.

**Comment by sd-hd** [comment]
> When does this create a release? I can't tell from the github actions yaml what triggers the release to be created.

Actually for every tag on git-push.

But, snapd action didn't build correctly. Need to figure out, where the problem is. Other snap's works...

**Comment by sd-hd** [comment]
added this secrets, to make the workflow controlable:
* GITHUB_ACTION_ENABLED
* PUBLISH_GITHUB
* PUBLISH_SNAPCRAFT_STORE

**Comment by jhenstridge** [comment]
Not a full review, but a few general points:

1. I agree with @anonymouse64 that it would be better to start with a workflow that runs on pull requests rather than releases.  So doing a Snapcraft build, lint with review-tools, then `actions/upload-artifact` to save the result.  If you do this, I'd strip out all the secrets parts, since they won't be available to PRs from people who are not members of snapcore.

2. snapd has no tags matching "3.9.[0-9]+**" or "v3.9.[0-9]+**", so it isn't clear this would ever run as is.  Also, if you are building a workflow to build releases, it should probably trigger on the tag even rather than pushes.

3. We should be careful about using actions from random third parties (myself included).  The frabert/replace-string-action action looks like the kind of thing that could be replaced with a single line script.  Something like the following could do:

       - id: git-tag
         run: echo "::set-output name=replaced::$(echo "${{ github.ref }}" | sed "s|refs/tags/||")"

4. Don't use reference an action with `@master`: the action author will create a release tag when things are ready to use.

**Comment by sd-hd** [comment]
@anonymouse64 
@jhenstridge 

Thank you :-) 

I already started to work on a version which triggers on pull-request.

I don't know if we should upload it as an artifact. (Not sure yet, if an artifact can attached to a comment ? 

I try to build an action to use the file api (`uploadAsset`), which works like the upload file function of the comment-interface ?!

**Comment by sd-hd** [comment]
@anonymouse64 
bad news. 
The comment function of PR's are using this endpoint: `https://github.com/upload/policies/assets`

But inside `octokit` these endpoints are not exported. 

So things are getting too complicated, for just uploading releases directly into the comment's. 
a) someone could look how octokit autogenerate the endpoints, and maybe fix it. Or, ...
b) directly use the plain rest api...

Don't know if i have time for it. Sorry ;-)

**Comment by anonymouse64** [comment]
We have since moved to using GitHub Actions for PR jobs, if this PR could perhaps be refactored to do something like the microk8s repo and build a snap of the snapcraft snap and store it in artifacts, that would be a useful addition, otherwise I think we should close this PR. 

See https://github.com/ubuntu/microk8s/blob/master/.github/workflows/build-snap.yml#L32-L36

**Comment by anonymouse64** [comment]
Actually that ended up being fairly easy with @jhenstridge's action build, so I proposed it here: https://github.com/snapcore/snapd/pull/9048

I'm going to close this for now, but feel free to re-open if you would like to work on a new feature as detailed in previous comments here

**Pull request closed without merging**
