### PR TITLE
osutil: now that we require golang-1.10, use user.LookupGroup()

### PR DESCRIPTION
**Pull request by jdstrand**

### CODE REVIEW

**Comment by zyga** [comment]
I believe the tests are failing because, now with absence of cgo, the default build mode used on travis does not result in the creation of a BuildID in the generated binary.

**Comment by jdstrand** [comment]
Hrmm, I due to failures in https://github.com/snapcore/snapd/pull/6681 where I was told by @zyga that I was not allowed to use cgo functions in snapd (there was a spread test failure where with CGO=0 osutil.FindUid() and osutil.FindGid() could not be found (since osutil/group.go used import C). We discussed on IRC and decided that dropping the C code out of osutil/group.go would resolve that issue.

Doing that has the side effect of (at least on xenial, which is what the travis failure built on; there is no issue on bionic):
```
=== RUN   Test

----------------------------------------------------------------------
FAIL: system_key_test.go:50: systemKeySuite.SetUpTest

system_key_test.go:64:
    c.Assert(err, IsNil)
... value *errors.errorString = &errors.errorString{s:"executable does not contain a build ID"} ("executable does not contain a build ID")


----------------------------------------------------------------------
PANIC: system_key_test.go:131: systemKeySuite.TestInterfaceSystemKeyMismatchHappy

... Panic: Fixture has panicked (see related PANIC)
OOPS: 135 passed, 1 FAILED, 5 MISSED
--- FAIL: Test (0.14s)
FAIL
FAIL	github.com/snapcore/snapd/interfaces	0.144s
```

@mvo5, @zyga - I don't know how to proceed. This seems like a toolchain issue.

**Comment by zyga** [comment]
@jdstrand I promise to look at and fix this next week. I'm about to EOD now.

**Comment by jdstrand** [comment]
> @jdstrand I promise to look at and fix this next week. I'm about to EOD now.

Thanks, fyi, for now in https://github.com/snapcore/snapd/pull/6681 I'm going to use user.LookupUser and user.LookupGroup directly instead of osutil.FindUid and osutil.FindGid to unblock that PR.

**Comment by bboozzoo** [comment]
Checked out the PR locally and got this:
```
START: system_key_test.go:50: systemKeySuite.SetUpTest
system_key_test.go:64:
    c.Assert(err, IsNil)
... value *errors.errorString = &errors.errorString{s:"executable does not contain a build ID"} ("executable does not contain a build ID")
```
Does not look like a xenial specific issue.

**Comment by bboozzoo** [comment]
Interesting. This is a test binary built from the branch:
```
maciek@galeon:snapcore/snapd/interfaces (git)-[pull/6759] readelf interfaces.test -n  

Displaying notes found in: .note.go.buildid
  Owner                 Data size       Description
  Go                   0x00000053       Unknown note type: (0x00000004)
   description data: 6e 49 7a 5f 68 43 79 48 6d 74 77 35 4c 77 65 39 64 5f 31 39 2f 61 61 76 6c 55 61 72 4f 5a 34 64 49 77 72 72 65 41 59 47 67 2f 4c 49 79 59 2d 41 72 64 31 64 64 43 4d 65 49 76 74 6d 41 64 2f 52 76 4b 65 32 4c 6e 6a 6e 4c 67 6c 32 75 34 47 6f 6a 55 4b 
```
And master:
```
maciek@galeon:snapcore/snapd/interfaces (git)-[master] go test -c -a -v -x
...
maciek@galeon:snapcore/snapd/interfaces (git)-[master] readelf interfaces.test -n 

Displaying notes found in: .note.gnu.build-id
  Owner                 Data size       Description
  GNU                  0x00000014       NT_GNU_BUILD_ID (unique build ID bitstring)
    Build ID: 6ed57d008d18b15abb949ae30e6a670fd77fc62b

Displaying notes found in: .note.ABI-tag
  Owner                 Data size       Description
  GNU                  0x00000010       NT_GNU_ABI_TAG (ABI version tag)
    OS: Linux, ABI: 3.2.0

Displaying notes found in: .note.go.buildid
  Owner                 Data size       Description
  Go                   0x00000053       Unknown note type: (0x00000004)
   description data: 66 6f 75 5a 54 59 76 4e 7a 7a 2d 49 52 5f 75 67 50 70 72 44 2f 61 61 76 6c 55 61 72 4f 5a 34 64 49 77 72 72 65 41 59 47 67 2f 4c 49 79 59 2d 41 72 64 31 64 64 43 4d 65 49 76 74 6d 41 64 2f 77 32 5a 45 5a 59 72 79 47 4c 6b 74 42 51 79 62 52 6a 6f 74 
```
Same go 1.12.4 toolchain. Somehow, the branch build is missing GNU build ID entirely.

**Comment by mvo5** [comment]
It looks like it is the missing import "C" that causes this issue. Just adding `import "C"` it back into osutil/group.go works around the problem. I think the issue is that without any "import C" no gnu tools are needed to build so no gnu build id is generated.

So I think we have some options here:
a) re-add `import "C"` with a  comment why we do it
b) build with buildmode=pie (not really an option because it is dangerous on 32 bit systems)
c) change our code in osutil.ReadBuildID to look for the Go build ID 

I personally like (c).

**Comment by bboozzoo** [comment]
I think we can rule out (b), PIE is not needed to get build ID.

Option (a) feels like a bug in Go toolchain. With the patch, the code in osutil/group.go does not call out to anything C related, so importing "C" is just a workaround. Besides, gcc is involved in he build process of the test binary anyway.

I'd vote for option (c).

**Comment by mvo5** [comment]
A trivial implementation would be http://paste.ubuntu.com/p/CJ5K8GRHBG/ it has a bunch of duplicated code but its easy to fix, will do a PR in a bit.

**Comment by mvo5** [comment]
I created https://github.com/snapcore/snapd/pull/6782 - once that (or something like it) is merged this should be no longer fail.

**Comment by mvo5** [comment]
This still fails in the tests because with go-1.9 the tests will not write a build-id into the binaries but the test will look at /proc/self/exe, i.e. the generated test binary. go1.10 fixes this. It seems like we need to adjust the tests to go-build a test binary for the system-key test or to (somehow?) change the building of the tests so that they include the build-id.

**Comment by bboozzoo** [comment]
We could bump Travis go version to 1.10. Looks like it's effectively the oldest version we build with anyway.

**Comment by bboozzoo** [comment]
#6799 will update Travis Go to 1.10.x. Then this PR should build just fine.

**Comment by bboozzoo** [comment]
And the unit tests are green!

**Comment by bboozzoo** [comment]
```
2019-04-30 13:48:30 Error executing google:centos-7-64:tests/main/base-snaps : 
-----
+ . /home/gopath/src/github.com/snapcore/snapd/tests/lib/snaps.sh
+ echo 'Ensure a snap that requires a unavailable base snap can not be installed'
Ensure a snap that requires a unavailable base snap can not be installed
+ install_local test-snapd-requires-base
+ local SNAP_NAME=test-snapd-requires-base
+ shift
++ make_snap test-snapd-requires-base
++ local SNAP_NAME=test-snapd-requires-base
++ shift
++ local SNAP_FILE=/home/gopath/src/github.com/snapcore/snapd/tests/lib/snaps/test-snapd-requires-base/test-snapd-requires-base_1.0_all.snap
++ local SNAP_DIR
+++ dirname /home/gopath/src/github.com/snapcore/snapd/tests/lib/snaps/test-snapd-requires-base/test-snapd-requires-base_1.0_all.snap
++ SNAP_DIR=/home/gopath/src/github.com/snapcore/snapd/tests/lib/snaps/test-snapd-requires-base
++ '[' '!' -f /home/gopath/src/github.com/snapcore/snapd/tests/lib/snaps/test-snapd-requires-base/test-snapd-requires-base_1.0_all.snap ']'
++ snap pack /home/gopath/src/github.com/snapcore/snapd/tests/lib/snaps/test-snapd-requires-base /home/gopath/src/github.com/snapcore/snapd/tests/lib/snaps/test-snapd-requires-base
++ '[' -f /home/gopath/src/github.com/snapcore/snapd/tests/lib/snaps/test-snapd-requires-base/test-snapd-requires-base_1.0_all.snap ']'
++ echo /home/gopath/src/github.com/snapcore/snapd/tests/lib/snaps/test-snapd-requires-base/test-snapd-requires-base_1.0_all.snap
+ SNAP_FILE=/home/gopath/src/github.com/snapcore/snapd/tests/lib/snaps/test-snapd-requires-base/test-snapd-requires-base_1.0_all.snap
+ snap install --dangerous /home/gopath/src/github.com/snapcore/snapd/tests/lib/snaps/test-snapd-requires-base/test-snapd-requires-base_1.0_all.snap
error: cannot perform the following tasks:
- Ensure prerequisites for "test-snapd-requires-base" are available (no snap revision available as specified)
+ echo 'Ensure a base snap can be installed'
Ensure a base snap can be installed
+ install_local test-snapd-base
+ local SNAP_NAME=test-snapd-base
+ shift
++ make_snap test-snapd-base
++ local SNAP_NAME=test-snapd-base
++ shift
++ local SNAP_FILE=/home/gopath/src/github.com/snapcore/snapd/tests/lib/snaps/test-snapd-base/test-snapd-base_1.0_all.snap
++ local SNAP_DIR
+++ dirname /home/gopath/src/github.com/snapcore/snapd/tests/lib/snaps/test-snapd-base/test-snapd-base_1.0_all.snap
++ SNAP_DIR=/home/gopath/src/github.com/snapcore/snapd/tests/lib/snaps/test-snapd-base
++ '[' '!' -f /home/gopath/src/github.com/snapcore/snapd/tests/lib/snaps/test-snapd-base/test-snapd-base_1.0_all.snap ']'
++ snap pack /home/gopath/src/github.com/snapcore/snapd/tests/lib/snaps/test-snapd-base /home/gopath/src/github.com/snapcore/snapd/tests/lib/snaps/test-snapd-base
++ '[' -f /home/gopath/src/github.com/snapcore/snapd/tests/lib/snaps/test-snapd-base/test-snapd-base_1.0_all.snap ']'
++ echo /home/gopath/src/github.com/snapcore/snapd/tests/lib/snaps/test-snapd-base/test-snapd-base_1.0_all.snap
+ SNAP_FILE=/home/gopath/src/github.com/snapcore/snapd/tests/lib/snaps/test-snapd-base/test-snapd-base_1.0_all.snap
+ snap install --dangerous /home/gopath/src/github.com/snapcore/snapd/tests/lib/snaps/test-snapd-base/test-snapd-base_1.0_all.snap
test-snapd-base 1.0 installed
+ snap list
+ MATCH test-snapd-base
+ echo 'With test-snapd-base installed we now can install test-snapd-requires-base'
With test-snapd-base installed we now can install test-snapd-requires-base
+ install_local test-snapd-requires-base
+ local SNAP_NAME=test-snapd-requires-base
+ shift
++ make_snap test-snapd-requires-base
++ local SNAP_NAME=test-snapd-requires-base
++ shift
++ local SNAP_FILE=/home/gopath/src/github.com/snapcore/snapd/tests/lib/snaps/test-snapd-requires-base/test-snapd-requires-base_1.0_all.snap
++ local SNAP_DIR
+++ dirname /home/gopath/src/github.com/snapcore/snapd/tests/lib/snaps/test-snapd-requires-base/test-snapd-requires-base_1.0_all.snap
++ SNAP_DIR=/home/gopath/src/github.com/snapcore/snapd/tests/lib/snaps/test-snapd-requires-base
++ '[' '!' -f /home/gopath/src/github.com/snapcore/snapd/tests/lib/snaps/test-snapd-requires-base/test-snapd-requires-base_1.0_all.snap ']'
++ '[' -f /home/gopath/src/github.com/snapcore/snapd/tests/lib/snaps/test-snapd-requires-base/test-snapd-requires-base_1.0_all.snap ']'
++ echo /home/gopath/src/github.com/snapcore/snapd/tests/lib/snaps/test-snapd-requires-base/test-snapd-requires-base_1.0_all.snap
+ SNAP_FILE=/home/gopath/src/github.com/snapcore/snapd/tests/lib/snaps/test-snapd-requires-base/test-snapd-requires-base_1.0_all.snap
+ snap install --dangerous /home/gopath/src/github.com/snapcore/snapd/tests/lib/snaps/test-snapd-requires-base/test-snapd-requires-base_1.0_all.snap
test-snapd-requires-base 1.0 installed
+ snap list
+ MATCH test-snapd-requires-base
+ echo 'Ensure the bare base works'
Ensure the bare base works
++ uname -m
+ '[' x86_64 '!=' x86_64 ']'
+ snap install --edge --devmode test-snapd-busybox-static
test-snapd-busybox-static (edge) 1.0 from Canonical* installed
+ echo 'Ensure we can run a statically linked binary from an empty base'
Ensure we can run a statically linked binary from an empty base
+ MATCH hello
+ test-snapd-busybox-static.busybox-static echo hello
execv failed: No such file or directory
grep error: pattern not found, got:
-----
```
Digging deeper, `snap-exec` is not a static binary. Since it's a snap with base, we mount the host's $(libexecdir)/snapd into the snap mount namespace under /usr/lib/snapd.

**Comment by pedronis** [comment]
what's the status of this?

**Comment by bboozzoo** [comment]
I investigated this a bit before and can push a tweak to the Fedora/CentOS packaging.

**Comment by bboozzoo** [comment]
Having merged latest master, the binaries seemed to be build correctly on Fedora 30. Let's see if it fails under spread.

**Comment by bboozzoo** [comment]
The Travis job is green now.

**Comment by jdstrand** [comment]
Thanks for everyone's help with this! Who knew it would be so involved :)

**Pull request merged**
