### PR TITLE
many: fix formatting w/ latest go version

### PR DESCRIPTION
**Pull request by MiguelPires**
Fix formatting when running the latest version (1.17) of gofmt. The relevant part of the go release's changelog is [here](https://go.dev/doc/go1.17#gofmt)

### CODE REVIEW

**Review by mvo5 — APPROVED** [review]
Thank you, this looks fine to me

**Review by bboozzoo — APPROVED** [review]
LGTM

**Review by mardy — APPROVED** [review]
You could add the "skip-spread" label on this one, then you will be able to merge it yourself.

**Comment by bboozzoo** [comment]
This one is ready too, @pedronis @mvo5 can you land it?

**Pull request merged**
