### PR TITLE
interfaces: misc policy fixes

### PR DESCRIPTION
**Pull request by jdstrand**
* interfaces: adjust system-observe to allow non-process-specific /proc files. Closes LP#1583794
* interfaces: adjust opengl to use @{PROC} and add FIXME comment
* interfaces: allow read access to oom_adj and oom_score and a note about write

### CODE REVIEW

**Comment by niemeyer** [comment]
LGTM, thanks!

**Comment by jdstrand** [comment]
retest this please

**Comment by niemeyer** [comment]
retest this please

**Comment by niemeyer** [comment]
retest this please

**Comment by elopio** [comment]
sorry, IS asked us to leave some wrong instance behind so they could debug them, and that made us hit the quota limit.

**Comment by elopio** [comment]
retest this please

**Pull request merged**
