### PR TITLE
interfaces/serial-port: add Qualcomm serial port devices to allowed list

### PR DESCRIPTION
**Pull request by tsunghanliu**
Add support for two Qualcomm serial port devices.

ttyMSMX: drivers/tty/serial/msm_serial.c
ttyHSX: drivers/tty/serial/qcom_geni_serial.c

### CODE REVIEW

**Review by anonymouse64 — APPROVED** [review]
lgtm, thanks for this change

**Review by alexmurray — APPROVED** [review]
LGTM - thanks.

**Comment by tsunghanliu** [comment]
If we will have another 2.50.x point release, can we cherry-pick this PR to the 2.50 branch? Thanks.

**Comment by anonymouse64** [comment]
@tsunghanliu I milestoned this for 2.50, so if we do another 2.50.2 release it will be cherry-picked

**Pull request merged**
