### PR TITLE
interfaces/builtin/gpio_control: add support for accessing gpiochip* devices

### PR DESCRIPTION
**Pull request by bboozzoo**
Add supported for /dev/gpiochip* devices implementing the new GPIO character
device kernel APIs.

Related: SNAPDENG-25370

### CODE REVIEW

**Comment by bboozzoo** [comment]
The `test-snapd-gpio-control` name has been successfully registered and I'm waiting for manual approval of the snap blob uploads because of `allow-installation: false` in gpio-control base declaration.

**Review by zyga — APPROVED** [review]
Looks great. My only comment is to ensure this does not cause any regressions in testing outside of the classic Google cloud setup we use during CI

**Review by alexmurray — APPROVED** [review]
LGTM - also I granted use of the gpio-control interface to this snap in the snap store and it is now passing automated review and ready to release - @bboozzoo can you please release it then retrigger the spread tests?

**Comment by bboozzoo** [comment]
> LGTM - also I granted use of the gpio-control interface to this snap in the snap store and it is now passing automated review and ready to release - @bboozzoo can you please release it then retrigger the spread tests?

Thanks for granting the interface. The test is passing locally with spread now. I've rebased on top of master, tweaked MATCH patters and pushed.

**Review by Meulengracht — APPROVED** [review]
Thank you!

**Pull request merged**
