### PR TITLE
daemon: auto-install default provider for the content snap

### PR DESCRIPTION
**Pull request by mvo5**
This is a bit of an RFC branch, it adds the ability for snapd to auto-install the default provider of the content plugs of the snap. This means that a snap can write something like:
```
name: content-plug-snap
version: 1.0
plugs:
 content:
  target: ./import
  content: mylib
  default-provider: content-slot-snap
```
and when it gets installed a snap with the name `content-slot-snap` gets automatically installed.

### CODE REVIEW

**Comment by pedronis** [comment]
ubuntu-core is a bit/was a bit of a special case, it seems a bit strange to have this logic at the daemon level, it would seem to belong somehow in snapstate and overlord

**Comment by mvo5** [comment]
@pedronis Thanks for your feedback. We can move it into snapstate of course, this means we need to pass *snap.Info into it. I think we do this, we should also do the ubuntu-core part there, no?

**Comment by pedronis** [comment]
I think so, the question is how should the interface look like? we want Install* to also try to install prerequisites usually

**Comment by niemeyer** [comment]
We should also consider when to install the default provider or not (it's a _default_ after all) and whether to leverage some sort of automatic task creation for the first time.

Can we please talk about this over a HO?

I'm closing it for the time being as it sounds like we have agreement over tweaking it in some direction.

**Pull request closed without merging**
