### PR TITLE
tests: adding support for fedora-34

### PR DESCRIPTION
**Pull request by sergiocazzolato**
This pr is to add the needed changes to make tests work on fedora-34-64 image

### CODE REVIEW

**Comment by bboozzoo** [comment]
The Fedoar 34 image needs an update, we have an older kernel (5.11.12):
```
2021-05-07 08:26:28 Starting shell to debug...
google:fedora-34-64 .../tests/main/snap-info# uname -a
Linux may070613-803453 5.11.12-300.fc34.x86_64 #1 SMP Wed Apr 7 16:31:13 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

But installing snapd pulls in the kernel-modules package, which updates the kernel to 5.11.17:
```
google:fedora-34-64 .../tests/main/snap-info# rpm -qa \*kernel\*
kernel-core-5.11.12-300.fc34.x86_64
kernel-core-5.11.17-300.fc34.x86_64
kernel-modules-5.11.17-300.fc34.x86_64
kernel-srpm-macros-1.0-4.fc34.noarch
kernel-headers-5.11.16-300.fc34.x86_64
```

**Review by mvo5 — APPROVED** [review]

**Comment by sergiocazzolato** [comment]
@bboozzoo, any idea?
There are still 2 tests failing:
tests/main/snap-mgmt: https://paste.ubuntu.com/p/mJKDMYjzYZ/ 
tests/main/snap-user-service-socket-activation: https://paste.ubuntu.com/p/kNx7pypkn8/ 

Both tests are failing on this line: https://github.com/snapcore/snapd/blob/master/tests/lib/prepare-restore.sh#L776

**Comment by bboozzoo** [comment]
Hm I suspect this may be related to socket activation, how the socket files (and the prefix path) is created by user's systemd instance (for root admin_t in particular), but there's a missing rule that makes the files (and directories) to be relabeled as snappy_home_t.

**Comment by bboozzoo** [comment]
Filed a bug in Fedora https://bugzilla.redhat.com/show_bug.cgi?id=1960576 in the meantime, I'm checking a small fix in our test suite to workaround the problem.

**Comment by sergiocazzolato** [comment]
@bboozzoo centos7 failed with this error 
+ systemctl --user daemon-reexec
Failed to get D-Bus connection: No such file or directory
-----
Other systems are ok

**Comment by bboozzoo** [comment]
> @bboozzoo centos7 failed with this error
> 
>     * systemctl --user daemon-reexec
>       Failed to get D-Bus connection: No such file or directory
> 
> 
> Other systems are ok

duh, what a bummer ;)

**Review by bboozzoo — APPROVED** [review]
LGTM

**Comment by bboozzoo** [comment]
@mvo5 can you land this? The failure on core18 is unrelated and we're stuck with debian 9 as required.

**Pull request merged**
