### PR TITLE
tests: add fedora-38 and remove fedora-36

### PR DESCRIPTION
**Pull request by sergiocazzolato**
This change adds fedora 38 and removes support for fedora 36

### CODE REVIEW

**Comment by ZeyadYasser** [comment]
I think it is strange that those tests are failing for `fedora-38`
    - `google:fedora-38-64:tests/main/cgroup-devices-v2`
    - `google:fedora-38-64:tests/main/document-portal-activation`
They shouldn't even be running since `fedora` is not listed in the systems section in [cgroup-devices-v2](https://github.com/snapcore/snapd/blob/f1e72fa0bd5eda1bb45161aec9b6edbfe30a9af4/tests/main/cgroup-devices-v2/task.yaml#L4) and [document-portal-activiation](https://github.com/snapcore/snapd/blob/f1e72fa0bd5eda1bb45161aec9b6edbfe30a9af4/tests/main/document-portal-activation/task.yaml#L21)

**Comment by Meulengracht** [comment]
> I think it is strange that those tests are failing for `fedora-38` - `google:fedora-38-64:tests/main/cgroup-devices-v2` - `google:fedora-38-64:tests/main/document-portal-activation` They shouldn't even be running since `fedora` is not listed in the systems section in [cgroup-devices-v2](https://github.com/snapcore/snapd/blob/f1e72fa0bd5eda1bb45161aec9b6edbfe30a9af4/tests/main/cgroup-devices-v2/task.yaml#L4) and [document-portal-activiation](https://github.com/snapcore/snapd/blob/f1e72fa0bd5eda1bb45161aec9b6edbfe30a9af4/tests/main/document-portal-activation/task.yaml#L21) which is the case for `fedora-37` as expected.

It's a super good observation, but actually if you look closely you'll notice they are prefixed by `-`, which means it should *not* run on those systems. So if the tests are failing we need to determine whether it's a real issue, but this should be out of scope for this PR @sergiocazzolato

**Review by Meulengracht — APPROVED** [review]
LGTM

**Comment by ZeyadYasser** [comment]
> if you look closely you'll notice they are prefixed by `-`, which means it should _not_ run on those systems. So if the tests are failing we need to determine whether it's a real issue

Thank you for pointing this out, my bad.

**Pull request merged**
