### PR TITLE
interfaces: allow read access to /proc/tty/drivers to modem-manager and ppp

### PR DESCRIPTION
**Pull request by stolowski**
Allow read access to /proc/tty/derivers for modem-manager and ppp interfaces.
The /proc/tty/drivers can be used by apps to determine whether a tty device is a serial port.

The drivers file lists all existing ttys on the system, e.g.
```
/dev/tty             /dev/tty        5       0 system:/dev/tty
/dev/console         /dev/console    5       1 system:console
/dev/ptmx            /dev/ptmx       5       2 system
/dev/vc/0            /dev/vc/0       4       0 system:vtmaster
ttyprintk            /dev/ttyprintk   5       3 console
max310x              /dev/ttyMAX   204 209-224 serial
serial               /dev/ttyS       4 64-111 serial
pty_slave            /dev/pts      136 0-1048575 pty:slave
pty_master           /dev/ptm      128 0-1048575 pty:master
unknown              /dev/tty        4 1-63 console
```

This is a followup to #9627.

Similar change could be done to serial-port, but there is a question whether it should be a permanent rule there.

### CODE REVIEW

**Review by anonymouse64 — APPROVED** [review]
Thanks for following up on this

**Review by mvo5 — APPROVED** [review]
Indeed, thank you!

**Comment by mvo5** [comment]
@alexmurray Hey, do you think you could have a quick look at this one?

**Review by alexmurray — APPROVED** [review]
LGTM - thanks :)

**Pull request merged**
