### PR TITLE
osutil: fix create-user on classic systems

### PR DESCRIPTION
**Pull request by jaymell**
Prevent create-user on classic systems, provide test for it and update other tests as appropriate.

### CODE REVIEW

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by mvo5** [comment]
Very nice, thank you! :+1:

**Comment by niemeyer** [comment]
Why do we have to prevent it?

**Comment by niemeyer** [comment]
@mvo5 Tells me that's because --extrausers doesn't work on classic. Is that why?

If so, can we please fix it instead of breaking it permanently?  The idea of allowing root to create a local user with help from those APIs is a generic concept rather than specific to snappy images.

**Comment by jaymell** [comment]
I really like the idea of this functionality working generically -- PR was a response to this: https://bugs.launchpad.net/snappy/+bug/1608807

I think the create-user functionality would need to use 'useradd' as support for the 'adduser' functionality currently used by snapd doesn't work on out-of-box xenial (or other distros, for that matter). 

I'd like to try and make this work.

**Comment by niemeyer** [comment]
Sounds good, let's do it then!

I suggest just fixing the --extrausers flag as a first step, as that's very cheap. Just "if !OnClassic, add flag" should do it.

We can then generalize the !xenial case separately.

**Comment by jaymell** [comment]
It looks like testing release.OnClassic in osutil creates an import cycle (since OnClassic is just a call to osutil.FileExists("/var/lib/dpkg/status")). Not immediately sure of the best way to resolve that. Moving the release package into osutil seems drastic, but I suppose it's one possibility.

**Comment by jaymell** [comment]
Closing this, as the focus has changed, and new work will be done in a different branch.

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Pull request closed without merging**
