### PR TITLE
changed snapd to snap

### PR DESCRIPTION
**Pull request by liu-xiao-guo**
https://github.com/snapcore/snapd/blob/master/docs/autoupdate.md, the command:

systemctl status -l snapd.refresh.service

is not right, and the correct one should be:

systemctl status -l snap.refresh.service

For the rest if the command, it is the same.

### CODE REVIEW

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by chadmiller** [comment]
Maybe nicer not to change names without a good reason. In snapd 2.0.10

> $ systemctl  |grep refresh
>   snapd.refresh.timer

**Comment by caldav** [comment]
Is it a pending change? Using the latest build from the snapd daily PPA (2.11+ppa177-1), here is what I see:

```
systemctl status -l snap.refresh.service
● snap.refresh.service
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead)
```

```
systemctl status -l snapd.refresh.service
● snapd.refresh.service - Automatically refresh installed snaps
   Loaded: loaded (/lib/systemd/system/snapd.refresh.service; static; vendor preset: enabled)
   Active: inactive (dead) since lun. 2016-08-01 09:42:11 CEST; 21s ago
     Docs: man:snap(1)
  Process: 16894 ExecStart=/usr/bin/snap refresh (code=exited, status=0/SUCCESS)
 Main PID: 16894 (code=exited, status=0/SUCCESS)

août 01 09:42:10 artemis snoopy[16894]: [uid:0 sid:16894 tty:(none) cwd:/ filename:/usr/bin/snap]: /usr/bin/snap refresh
août 01 09:42:10 artemis systemd[1]: Starting Automatically refresh installed snaps...
août 01 09:42:11 artemis snap[16894]: All snaps up-to-date.
août 01 09:42:11 artemis systemd[1]: Started Automatically refresh installed snaps.
```

**Comment by niemeyer** [comment]
The systemctl unit name is indeed "snapd.refresh.service", so documentation seems right currently.

Have you observed problems about this somewhere else?

Also, for the record, this timer is likely going to be removed altogether at some point, in favor of a more flexible internal implementation.

**Comment by liu-xiao-guo** [comment]
what is your snapd version? 2.11+ ? For my case, it is:

liuxg@liuxg:~$ snap --version
snap    2.0.10
snapd   2.0.10
series  16
ubuntu  16.04

It seems that systemctl status -l snap.refresh.service works for me right now.

**Pull request closed without merging**
