### PR TITLE
interfaces: allow access to new ibus abstract socket path

### PR DESCRIPTION
**Pull request by jdstrand**
interfaces: allow access to new ibus abstract socket path (Closes LP#1580463)

### CODE REVIEW

**Comment by jdstrand** [comment]
retest this please

**Comment by chipaca** [comment]
:+1:

**Comment by niemeyer** [comment]
Sweet!

**Comment by jdstrand** [comment]
Note, for completeness this should only be allowed in the unity7 interface (which is what this PR is for) because talking to ibus-daemon allows key sniffing via:

`dbus-monitor` --address "$IBUS_ADDRESS" "member='ProcessKeyEvent'"`

where $IBUS_ADDRESS is what can be found in ~/.config/ibus/bus/*. I'll be sure to add a comment in a future PR.

**Pull request merged**
