### PR TITLE
o/configstate/configcore: add hdmi_timings to pi-config

### PR DESCRIPTION
**Pull request by sergey-borovkov**
Required for supporting custom resolutions/working with certain devices.
See https://www.raspberrypi.org/documentation/configuration/config-txt/video.md

Thanks for helping us make a better snapd!
Have you signed the [license agreement](https://www.ubuntu.com/legal/contributors) and read the [contribution guide](https://github.com/snapcore/snapd/blob/master/CONTRIBUTING.md)?

Yes, I did sign it before.

### CODE REVIEW

**Review by anonymouse64 — APPROVED** [review]
LGTM, thanks

**Review by mvo5 — COMMENTED** [review]
This looks fine. I guess if someone sets this incorrectly the screen will no longer show anything? I guess that's a risk some of the other options have as well so I think it's fine.

**Comment by sergey-borovkov** [comment]
> This looks fine. I guess if someone sets this incorrectly the screen will no longer show anything? I guess that's a risk some of the other options have as well so I think it's fine.

Yes, it’s the same behaviour as a lot of other options (hdmi mode, and gpu mem for instance)

**Comment by anonymouse64** [comment]
> I guess that's a risk some of the other options have as well so I think it's fine.

We eventually have plans to implement stricter validation of these settings to prevent less foot shooting, but we don't need to block this PR on that work I think

**Review by mvo5 — APPROVED** [review]

**Comment by vpetersson** [comment]
Do we have an update on when this will be merged? Need to communicate when this will be available (in stable) to a customer that this is blocking.

**Comment by vpetersson** [comment]
Thanks @anonymouse64. Is there a time frame for when 2.5 will make it to stable?

**Comment by anonymouse64** [comment]
I can't comment on that, I don't really know, but we did just discuss 2.49.2 today which is needed for other things and probably will be available in the next month or so, and this is small enough that we should be able to pull it in.

**Pull request merged**
