### PR TITLE
data/systemd: do not run snapd.system-shutdown if finalrd is available

### PR DESCRIPTION
**Pull request by xnox**
finalrd is superior implementation, is available on core20 and is
being evaluated for backport to core18.

### CODE REVIEW

**Comment by xnox** [comment]
I don't know what "invalid pr title means" as it gives no guidance as to what it should be.

**Comment by xnox** [comment]
alternative to this, I can upload finalrd that disables snapd.system-shutdown.service if finalrd has started.

**Comment by anonymouse64** [comment]
> I don't know what "invalid pr title means" as it gives no guidance as to what it should be.

@xnox for the record, reading the travis log tells you the issue:

```
Checking pull request summary
If finalrd is available, do not run snapd.system-shutdown service.
Invalid PR title: "If finalrd is available, do not run snapd.system-shutdown service."
Please provide a title in the following format:
module: short description
E.g.:
daemon: fix frobinator bug
```

I have fixed the PR title for you and re-triggered the jobs

**Comment by xnox** [comment]
@anonymouse64 

I concur data/systemd is the obvious choice:

```
$ git log --no-decorate --oneline data/systemd | sed -n 's/:.*//p' | sed 's/^...........//' | sort | uniq -c | sort -g
      1 cmd,data
      1 cmd/snap-confine
      1 cmd/snap-update-ns
      1 core-fixup
      1 core-fixup.sh
      1 data/systemd,packaging/debian
      1 data/systemd,packaging/ubuntu-*
      1 data/systemd/snapd.failure.service.in
      1 data/systemd/snapd.recovery-chooser-trigger
      1 data/systemd/snapd.run-from-snap
      1 data/systemd, wrappers
      1 fixup! data/systemd
      1 packaging
      1 snap-bootstrap
      1 snapd.apparmor.service.in
      1 snapd.core-fixup.service.in
      1 snapd.failure.service.in
      1 snapstate
      1 tests
      2 data/systemd/snapd.recovery-chooser-trigger.service
      2 Merge branch 'master' of github.com
      2 snapd.run-from-snap
      2 wrappers
      6 data
      6 snapd.core-fixup.sh
      6 systemd
      7 many
     16 data/systemd
```

**Comment by xnox** [comment]
Has this landed in edge?

**Comment by anonymouse64** [comment]
@xnox yes it has, see

```
$ grep finalrd /snap/snapd/current/lib/systemd/system/snapd.system-shutdown.service 
ConditionPathExists=!/usr/bin/finalrd
```

**Comment by xnox** [comment]
@anonymouse64 yet i still see system-shutdown.service running. I wonder if by the time condition is checked (on shutdown) the core is already umounted and thus /usr/bin/finalrd is no longer there.

Yet snapd.system-shutdown.service is still hooked into the shutdown target and "wanted by" final.target.

How can I ensure that the snapd.system-shutdown.service is _not_ enabled on core20 systems?

**Comment by xnox** [comment]
@anonymouse64 let me doublecheck what is running.

**Pull request merged**
