### PR TITLE
tests: migrate test from boot.sh helper to boot-state tool

### PR DESCRIPTION
**Pull request by sergiocazzolato**
This PR includes:
 - Tests migrated from boot.sh to boot-state
 - Boot.sh helper removed

### CODE REVIEW

**Comment by mvo5** [comment]
Please make sure we squash merge this one in case we need to cherry pick it to 2.48 (to ensure that cherry-picks from master to 2.48 are painless when we have e.g. new tests that use the boot-state tool).

**Review by bboozzoo — APPROVED** [review]
LGTM

**Comment by sergiocazzolato** [comment]
@mvo5 it is not needed for 2.48, thanks

**Comment by mvo5** [comment]
@sergiocazzolato Please check https://github.com/snapcore/snapd/pull/9611#issuecomment-726650568 - it's not needed right now but once we start using boot-state tool and we need to cherry-pick things from master back into 2.48 this will be painful. This is why I would have prefered the squash merge. It's just 4 commits fortunately so if we need this in 2.48 we can just do a backport of those 4.

**Pull request merged**
