### PR TITLE
interfaces/mount-observe: add quotactl with arg filtering (LP: #1626359)

### PR DESCRIPTION
**Pull request by jdstrand**

### CODE REVIEW

**Comment by mvo5** [comment]
Test failure is due to missing `go fmt interfaces/builtin/mount_observe.go`( https://travis-ci.org/snapcore/snapd/jobs/196731125#L408)

**Comment by jdstrand** [comment]
@mvo5 - thanks! Fixed.

**Comment by jdstrand** [comment]
@zyga, yes, the referenced bug: LP: #1626359. This isn't adding quota support though-- it is allowing apps to see if they are running under quota and get information about quotas. This is needed by transmission for example.

**Comment by jdstrand** [comment]
xenial-ppc64el failure is unrelated: - autopkgtest:ubuntu-16.04-ppc64el:tests/unit/gccgo (FAIL: overlord_test.go:306: overlordSuite.TestEnsureLoopMediatedEnsureBeforeOutsideEnsure)

**Comment by jdstrand** [comment]
yakkety-amd64 failure is unrelated - autopkgtest:ubuntu-16.10-amd64:tests/unit/gccgo (FAIL: overlord_test.go:345: overlordSuite.TestEnsureLoopPrune)

**Pull request merged**
