### PR TITLE
interfaces/u2f-devices: add Swissbit iShield Key

### PR DESCRIPTION
**Pull request by swissbit-csteuer**
This PR adds support for the Swissbit iShield Key series which supports FIDO2 (U2F/CTAP).

dmesg output:
```
[ 2300.560476] usb 1-1: USB disconnect, device number 22
[ 2301.471451] usb 1-1: new full-speed USB device number 23 using xhci_hcd
[ 2301.629671] usb 1-1: New USB device found, idVendor=1370, idProduct=0911, bcdDevice= 0.01
[ 2301.629699] usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[ 2301.629706] usb 1-1: Product: iShield Key Pro
[ 2301.629712] usb 1-1: Manufacturer: Swissbit
```

Reference: https://www.swissbit.com/en/products/ishield-key

### CODE REVIEW

**Comment by swissbit-csteuer** [comment]
Can we do anything to assist, like providing hardware samples, additional information etc. ?

**Review by alexmurray — APPROVED** [review]
I can't seem to find any public documentation which refers to this ProductID, however the VendorID is correct as per http://www.linux-usb.org/usb.ids - so this seems reasonable to me.

**Review by mvo5 — APPROVED** [review]
Thank you

**Comment by swissbit-csteuer** [comment]
@alexmurray @mvo5 Thank you for reviewing and merging this

**Pull request merged**
