### PR TITLE
interfaces/builtin: add usbmuxd interface

### PR DESCRIPTION
**Pull request by qmfrederik**
This patch adds the usbmuxd interface, providing access to iOS devices.

Multiple applications can access the same iOS device at the same time.
To avoid concurrency issues, access to iOS devices via USB is managed by
usbmuxd, the USB multiplexing daemon. This daemon  has exclusive
access to the devices, and exposes the `/var/run/usbmuxd` socket, which
can be used by client applications.

The implementation is modeled after the docker interface. There isn't an
`usbmuxd-support` interface yet; that could come as a follow-up PR.
Meanwhile, this should unblock scenarios where `usbmuxd` has been
installed via the traditional package managers.

### CODE REVIEW

**Comment by qmfrederik** [comment]
I signed the CLA just before submitting the PR, hopefully CI gets notified ;-).

**Review by anonymouse64 — COMMENTED** [review]
Hi, thanks for submitting this contribution! 

The PR looks fine in practice, but I marked it blocked because I think before we add more interfaces that are like docker, we need to finish having an internal conversation about how to handle these kinds of interfaces allowing access to a global resource such as a socket file, because we currently have the issue with the docker socket where the socket can be both provided by a snap itself (i.e. the docker snap) and provided by a traditional linux package which is not confined and the problem arises that snapd doesn't know easily which version of the interface to grant to clients. It seems that although currently usbmuxd is not a snap package, there is a good chance one will exist if work on a usbmuxd-support interface is planned or being explored and we would then end up with the same problem where strictly confined snap clients of usbmuxd get a poor experience with auto-connection of interfaces.

CC @pedronis

**Comment by qmfrederik** [comment]
Thanks for the prompt reply!

> It seems that although currently usbmuxd is not a snap package, there is a good chance one will exist if work on a usbmuxd-support interface is planned or being explored

Absolutely, I'd actually consider contributing such a package once the infrastructure is in place.

The upstream libimobiledevice/usbmuxd project frequently provides patches which give you compatibility with new versions of iOS, but these patches often do not make it to the Linux distro's - so I assume it would be a great candidate for a snap.

It's perhaps worth mentioning that the default usbmuxd daemon will only start when you connect an iOS device to your computer, and shut down when you disconnect the latest device. Not sure whether this is a behavior that could be replicated by a snap package.

> we need to finish having an internal conversation about how to handle these kinds of interfaces allowing access to a global resource

Just so I get my expectations right, what timeline would you anticipate here?

**Review by zyga — COMMENTED** [review]
Technically looks correct. 

Since Ian already mentioned the path problem, I would love to offer an alternative. The implicit slot could provide a `socket-path` attribute that currently just points to the fixed location (though we'd have to make it fixed), which would eventually open up for the possibility of introducing a snapped daemon with a different socket path.

This would be quite an exercise of the associated logic, as users should then actually use that path, rather than hard-coding a location.

**Comment by qmfrederik** [comment]
> which would eventually open up for the possibility of introducing a snapped daemon with a different socket path.

Does this mean you consider the possibility of having two daemons running at the same time, one deployed via a snap package and one deployed via a traditional Linux package?

**Comment by pedronis** [comment]
is there still interest in this? there was no more discussion here

**Comment by Meulengracht** [comment]
@qmfrederik I'll close this soon if there is no communication from you, is this still relevant?

**Comment by qmfrederik** [comment]
@Meulengracht I think the problem is still relevant, but I'm working on other things nowadays, so I'll close the PR.

**Comment by Meulengracht** [comment]
If it ever becomes relevant again feel free to reopen

**Pull request closed without merging**
