### PR TITLE
certs.go: fix typo in error msg, "exiting" -> "existing"

### PR DESCRIPTION
**Pull request by rpjday**

### CODE REVIEW

**Review by mvo5 — APPROVED** [review]
Thank you!

**Review by MiguelPires — APPROVED** [review]
Thanks. I closed and opened so the tests run without spread

**Comment by rpjday** [comment]
What is the rationale for the "Needs documentation" label? Is there some required documentation I should be submitting besides what is in the commit?

**Comment by MiguelPires** [comment]
> What is the rationale for the "Needs documentation" label? Is there some required documentation I should be submitting besides what is in the commit?

That label is added automatically when code in some packages is modified, as a reminder to change/add documentation. It isn't necessary here

**Pull request merged**
