### PR TITLE
spread: switch to CentOS 8 Stream image

### PR DESCRIPTION
**Pull request by bboozzoo**
CentOS 8 has hit EOL and is now delivered as CentOS 8 Stream offering.

See: https://www.centos.org/centos-stream/

### CODE REVIEW

**Review by stolowski — APPROVED** [review]
LGTM

**Review by MiguelPires — COMMENTED** [review]
This will apply the previous system exclusions (`system: [-centos-8]`) meant for CentOS Linux 8 to CentOS 8 Stream. Do we know if they're still necessary?

**Comment by bboozzoo** [comment]
> This will apply the previous system exclusions (`system: [-centos-8]`) meant for CentOS Linux 8 to CentOS 8 Stream. Do we know if they're still necessary?

I'll drop them and do a test run locally. FWIW the package doesn't build now as our steps to install go don't work anymore :confused:

**Comment by bboozzoo** [comment]
@MiguelPires I've enable one of the tests that was previously explicitly excluded from centos 8

**Review by MiguelPires — APPROVED** [review]
LGTM, thank you

**Review by mardy — APPROVED** [review]
LGTM!

**Review by anonymouse64 — APPROVED** [review]
thanks for adding this!

**Pull request merged**
