### PR TITLE
interface: make theme access functions generic so can be reused for other interfaces

### PR DESCRIPTION
**Pull request by robert-ancell**

### CODE REVIEW

**Review by jhenstridge — COMMENTED** [review]
Do the `go test ./daemon` unit tests pass with this? I suspect you'll also need some changes to api_themes_test.go and api_accessories_test.go: in particular, updating the `expectReadAccess` and `expectWriteAccess` calls.

**Review by jhenstridge — APPROVED** [review]
Looks good. This will avoid the need for almost identical access checkers for the prompting API.

**Review by olivercalder — APPROVED** [review]
This looks great, thanks!

**Review by mvo5 — APPROVED** [review]
Thank you, this is very nice

**Pull request merged**
