### PR TITLE
asserts: required account key name header

### PR DESCRIPTION
**Pull request by emgee**
The `name` header was added but left optional until existing assertions were updated. afaict, all account-key asserts now have a `name` so it should be safe to make it required now.

Depends on https://github.com/snapcore/snapd/pull/1852.

### CODE REVIEW

**Comment by cjwatson** [comment]
+1

**Comment by niemeyer** [comment]
Thanks for the fix. Tests seem broken ATM:
```
+ snap ack testrootorg-store.account-key
error: cannot assert: cannot decode request body into an assertion: assertion account-key: "name" header is mandatory
```

**Comment by emgee** [comment]
Yep, looking at the tests atm.

**Comment by emgee** [comment]
@niemeyer @cjwatson, rebased and fixed the spread tests ... now all green here.

However, I've been seeing a consistent main/ack failure on linode:ubuntu-core-16-64 when running the test manually. It *looks* like it's unrelated to this branch but it's hard to know for sure:

```
2016/09/07 14:23:42 Error preparing linode:ubuntu-core-16-64:tests/main/ :
[...]
Setting up snapd (2.14.2~16.04ubuntu4) ...
+ snap install --edge ubuntu-core
error: cannot install "ubuntu-core": cannot get details for snap "ubuntu-core" in channel "edge": got unexpected HTTP status code 500 via GET to "http://localhost:11028/snaps/details/ubuntu-core?channel=edge&confinement=strict"
```

**Pull request merged**
