### PR TITLE
travis: switch to container based test runs

### PR DESCRIPTION
**Pull request by mvo5**

### CODE REVIEW

**Comment by zyga** [comment]
@mvo5 the build failed on missing development libraries for seccomp and presumably other things. I don't think we can work around that easily.

**Comment by zyga** [comment]
I think this is a no-go unless you have a way to solve the problem of installing packages. I'll close this for now, feel free to reopen.

**Comment by mvo5** [comment]
@zyga look at the last commit, this problem of installing packages got solved before you closed it.

**Comment by mvo5** [comment]
@zyga ups, sorry, there was no last commit, I squashed, sorry for that.

**Comment by mvo5** [comment]
It fails with "2017-09-28 12:51:10 Cannot allocate linode:ubuntu-14.04-64: backend "linode" missing Linode API key" which is slightly odd. Gustavo indicated he has an idea about what might go wrong.

**Pull request merged**
