### PR TITLE
spread: try to enable Fedora once more

### PR DESCRIPTION
**Pull request by bboozzoo**

### CODE REVIEW

**Comment by sergiocazzolato** [comment]
Still failing, I am trying to reproduce the error locally
Error: Unable to find a match

**Comment by bboozzoo** [comment]
We're trying to install `golang(github.com/Thomasdezeeuw/ini)` but there's no Fedora package providing this Go package.

We'll probably need to switch to another 'ini' package that's already in the repositories of Ubuntu, Debian and Fedora or find another way of solving this.

```
+ quiet dnf -y --refresh install /usr/bin/rst2man /usr/bin/shellcheck autoconf automake 'compiler(go-compiler)' gcc gettext glibc-static gnupg 'golang(github.com/Thomasdezeeuw/ini)' 'golang(github.com/boltdb/bolt)' 'golang(github.com/cheggaaa/pb)' 'golang(github.com/coreos/go-systemd/activation)' 'golang(github.com/godbus/dbus)' 'golang(github.com/godbus/dbus/introspect)' 'golang(github.com/gorilla/mux)' 'golang(github.com/jessevdk/go-flags)' 'golang(github.com/mvo5/uboot-go/uenv)' 'golang(github.com/ojii/gettext.go)' 'golang(github.com/seccomp/libseccomp-golang)' 'golang(golang.org/x/crypto/openpgp/armor)' 'golang(golang.org/x/crypto/openpgp/packet)' 'golang(golang.org/x/crypto/sha3)' 'golang(golang.org/x/crypto/ssh/terminal)' 'golang(golang.org/x/net/context)' 'golang(golang.org/x/net/context/ctxhttp)' 'golang(gopkg.in/check.v1)' 'golang(gopkg.in/macaroon.v1)' 'golang(gopkg.in/mgo.v2/bson)' 'golang(gopkg.in/retry.v1)' 'golang(gopkg.in/tomb.v2)' 'golang(gopkg.in/yaml.v2)' indent libseccomp-static libtool 'pkgconfig(glib-2.0)' 'pkgconfig(libcap)' 'pkgconfig(libseccomp)' 'pkgconfig(libudev)' 'pkgconfig(systemd)' 'pkgconfig(udev)' selinux-policy selinux-policy-devel systemd valgrind xfsprogs-devel
quiet: dnf
-y
--refresh
install
/usr/bin/rst2man
/usr/bin/shellcheck
autoconf
automake
compiler(go-compiler)
gcc
gettext
glibc-static
gnupg
golang(github.com/Thomasdezeeuw/ini)
golang(github.com/boltdb/bolt)
golang(github.com/cheggaaa/pb)
golang(github.com/coreos/go-systemd/activation)
golang(github.com/godbus/dbus)
golang(github.com/godbus/dbus/introspect)
golang(github.com/gorilla/mux)
golang(github.com/jessevdk/go-flags)
golang(github.com/mvo5/uboot-go/uenv)
golang(github.com/ojii/gettext.go)
golang(github.com/seccomp/libseccomp-golang)
golang(golang.org/x/crypto/openpgp/armor)
golang(golang.org/x/crypto/openpgp/packet)
golang(golang.org/x/crypto/sha3)
golang(golang.org/x/crypto/ssh/terminal)
golang(golang.org/x/net/context)
golang(golang.org/x/net/context/ctxhttp)
golang(gopkg.in/check.v1)
golang(gopkg.in/macaroon.v1)
golang(gopkg.in/mgo.v2/bson)
golang(gopkg.in/retry.v1)
golang(gopkg.in/tomb.v2)
golang(gopkg.in/yaml.v2)
indent
libseccomp-static
libtool
pkgconfig(glib-2.0)
pkgconfig(libcap)
pkgconfig(libseccomp)
pkgconfig(libudev)
pkgconfig(systemd)
pkgconfig(udev)
selinux-policy
selinux-policy-devel
systemd
valgrind
xfsprogs-devel
quiet: exit status 1. Output follows:
Last metadata expiration check: 0:00:00 ago on Tue Jan 16 10:21:52 2018.
Failed to set locale, defaulting to C
Package gcc-7.2.1-2.fc26.x86_64 is already installed, skipping.
Package gettext-0.19.8.1-9.fc26.x86_64 is already installed, skipping.
No package golang(github.com/Thomasdezeeuw/ini) available.
Package systemd-233-6.fc26.x86_64 is already installed, skipping.
Package systemd-233-6.fc26.x86_64 is already installed, skipping.
Package selinux-policy-3.13.1-260.9.fc26.noarch is already installed, skipping.
Package systemd-233-6.fc26.x86_64 is already installed, skipping.
Error: Unable to find a match
quiet: end of output.
```

**Comment by bboozzoo** [comment]
We can close this one if #4336 is going to land soon

**Comment by sergiocazzolato** [comment]
@bboozzoo #4336  is having same problem than this one. 

It is weird because during the last execution one machine have started and ran the tests and the other 2 have failed with this dependency issue. So if the package is not available, why 1 machine could run?

**Pull request merged**
