### PR TITLE
cmd/snap: make 'snap list' shorten latest/$RISK to $RISK

### PR DESCRIPTION
**Pull request by chipaca**
With the code currently on master, 'snap list' would print `latest`
for any snaps tracking `latest/stable`. This is not what we want.  (We
want to show `latest/stable`, but that will come as part of the sticky
tracks work).

### CODE REVIEW

**Comment by bboozzoo** [comment]
Spread job fails now:
```
2019-10-31 00:47:40 Error executing google:ubuntu-19.04-64:tests/main/listing : 
-----
+ echo 'List prints core snap version'
List prints core snap version
+ NUMERIC_VERSION='[0-9]+(\.[0-9]+)*'
+ CORE_GIT_VERSION='[0-9]{2}-[0-9.]+(~[a-z0-9]+)?(\+git[0-9]+\.[0-9a-f]+)?'
+ SNAPD_GIT_VERSION='+[0-9.]+(~[a-z0-9]+)?(\+git[0-9]+\.[0-9a-z]+)?'
+ FINAL_VERSION='[0-9]{2}-[0-9.]+(~[a-z0-9]+)?(\+[0-9]+\.[0-9a-f]+)?'
+ SIDELOAD_REV='x[0-9]+'
+ NUMBER_REV='[0-9]+'
+ NAME=core
+ VERSION='[0-9]{2}-[0-9.]+(~[a-z0-9]+)?(\+git[0-9]+\.[0-9a-f]+)?'
+ REV='[0-9]+'
+ PUBLISHER='canonical\*'
+ TRACKING=-
+ NOTES=core
+ '[' google = google -o google == qemu ']'
+ '[' ubuntu-19.04-64 = ubuntu-core-16-64 ']'
+ '[' google = google -o google == qemu ']'
+ '[' ubuntu-19.04-64 = ubuntu-core-18-64 ']'
+ '[' 0 = 1 ']'
+ '[' -n '' ']'
+ '[' google = external ']'
+ '[' google = external ']'
+ TRACKING=latest/edge
+ expected='^core +[0-9]{2}-[0-9.]+(~[a-z0-9]+)?(\+git[0-9]+\.[0-9a-f]+)? +[0-9]+ +latest/edge +canonical\* +core.*$'
+ MATCH '^core +[0-9]{2}-[0-9.]+(~[a-z0-9]+)?(\+git[0-9]+\.[0-9a-f]+)? +[0-9]+ +latest/edge +canonical\* +core.*$'
+ snap list --unicode=never
grep error: pattern not found, got:
Name                  Version                  Rev   Tracking  Publisher   Notes
core                  16-2.42+git1539.2b0626f  8033  edge      canonical*  core
test-snapd-tools      1.0                      x1    -         -           -
test-snapd-tools_foo  1.0                      x1    -         -           -
-----
```

**Comment by pedronis** [comment]
> (We
want to show latest/stable, but that will come as part of the sticky
tracks work).

correct

**Comment by anonymouse64** [comment]
ah spread shellcheck issue:

```
2019-10-31 16:34:03 Error executing google:ubuntu-18.04-64:tests/unit/spread-shellcheck : 
-----
+ testdir=/home/gopath/src/github.com/snapcore/snapd/tests/unit/spread-shellcheck
+ cd /home/gopath/src/github.com/snapcore/snapd
+ CAN_FAIL=/home/gopath/src/github.com/snapcore/snapd/tests/unit/spread-shellcheck/can-fail
+ ./spread-shellcheck spread.yaml tests
ERROR:root:shellcheck failed for file tests/main/listing/task.yaml in sections: execute; error log follows
ERROR:root:tests/main/listing/task.yaml: section 'execute':

In - line 40:
    TRACKING=(latest/)?stable
    ^-----------------------^ SC2037: To assign the output of a command, use var=$(cmd) .
                      ^-----^ SC2211: This is a glob used as a command name. Was it supposed to be in ${..}, array, or is it missing quoting?


In - line 54:
    TRACKING=(latest/)?$CORE_CHANNEL
    ^-- SC2037: To assign the output of a command, use var=$(cmd) .
                      ^------------^ SC2211: This is a glob used as a command name. Was it supposed to be in ${..}, array, or is it missing quoting?
                       ^-----------^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
    TRACKING=(latest/)?"$CORE_CHANNEL"

For more information:
  https://www.shellcheck.net/wiki/SC2037 -- To assign the output of a command...
  https://www.shellcheck.net/wiki/SC2211 -- This is a glob used as a command ...
  https://www.shellcheck.net/wiki/SC2086 -- Double quote to prevent globbing ...

ERROR:root:validation failed for the following non-whitelisted files:
 - tests/main/listing/task.yaml
-----
```

:thinking:

**Comment by chipaca** [comment]
Nice. I'll fix that when I push with the seccomp fixes.

**Pull request merged**
