### PR TITLE
bootloader: do not specify Core version in grub entry

### PR DESCRIPTION
**Pull request by valentindavid**
Ubuntu Core 22 now shows ""Run Ubuntu Core 20" as boot entry.

### CODE REVIEW

**Review by alfonsosanchezbeato — COMMENTED** [review]
You need to regenerate `grub_cfg_asset.go` after changing config - see https://github.com/snapcore/snapd/blob/master/bootloader/assets/generate.go#L22

**Comment by alfonsosanchezbeato** [comment]
Closing/reopening to run nested tests

**Review by alfonsosanchezbeato — APPROVED** [review]
LGTM, thanks

**Review by mvo5 — APPROVED** [review]
Thank you

**Pull request merged**
