### PR TITLE
Set dh build directory explicitly, rather than guessing it.

### PR DESCRIPTION
**Pull request by mwhudson**

### CODE REVIEW

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by zyga** [comment]
whitelist this please

**Comment by zyga** [comment]
Seems to fail in CI:
```
strings: '/bin/snapd': No such file
debian/rules:27: recipe for target 'override_dh_auto_test' failed
```

What is the motivation behind this change?

**Comment by mwhudson** [comment]
> Seems to fail in CI:
> 
> strings: '/bin/snapd': No such file
> debian/rules:27: recipe for target 'override_dh_auto_test' failed

Oops, missed that merging forwards. Fixed.

> What is the motivation behind this change?

The comment I'm deleting "we need the builddir; is there a simpler way to get it?"

**Comment by mvo5** [comment]
:+1:

**Pull request merged**
