### PR TITLE
cmd/snap-boostrap, boot: use /run/mnt/data instead of ubuntu-data

### PR DESCRIPTION
**Pull request by bboozzoo**
As agreed, in preparation for support of recovery mode, we're changing the mount point of system data from /run/mnt/ubuntu-data to /run/mnt/data. This is a prerequisite for #8010.

### CODE REVIEW

**Comment by bboozzoo** [comment]
Spread job didn't run. I'll restart the workflow.

**Comment by bboozzoo** [comment]
Well, turns out you can't restart a successful workflow.

**Comment by anonymouse64** [comment]
I've figured out what the issue is here or at least how to unblock us on this, but it requires changes to the initrd, but the good news is that we can drop the compatibility mount now.

**Comment by anonymouse64** [comment]
Still, marking as blocked until the initrd changes are made

**Comment by anonymouse64** [comment]
A branch which implements the required changes in the initrd to support only using /run/mnt/data is here: https://code.launchpad.net/~anonymouse67/ubuntu-core-initramfs/+git/ubuntu-core-initramfs/+ref/feature/uc20-run-mnt-data

Note that I haven't figured out how to make the initrd compatible with both /run/mnt/data and /run/mnt/ubuntu-data simultaneously, which would be desirable while things move their way through the pipeline on either end, so applying the above patch would break booting until a snap-bootstrap that only mounts /run/mnt/data makes it's way into snapd and snap-bootstrap in the initrd.

**Comment by anonymouse64** [comment]
Okay, this is ready to review again, this PR now implements the following layouts:

## initramfs
`/run/mnt/data` 
* is where the booting system will store it's own data while running
* is a tmpfs for install,recover modes
* is the real ubuntu-data during run mode

`/run/mnt/host/data`

* is where recover mode will mount ubuntu-data physical partition

`/run/mnt/ubuntu-data`

* is never used from initramfs

## userspace snapd

`/run/mnt/ubuntu-data`

* is where install mode will setup the rootfs for run mode, is backed by physical partition ubuntu-data
* shouldn't exist during any other mode

`/run/mnt/data` 

* is where we have the running system's info, i.e. at initial bootup of snapd during install mode, this will have a `mode=install` modeenv that the initramfs writes there

`/run/mnt/host/data`

* is where recover mode could use/look at ubuntu-data physical partition if needed some day

**Pull request merged**
