### PR TITLE
tests: re-enable tests for /dev/pts on core

### PR DESCRIPTION
**Pull request by zyga**
Signed-off-by: Zygmunt Krynicki <zygmunt.krynicki@canonical.com>

### CODE REVIEW

**Comment by niemeyer** [comment]
```

**Comment by niemeyer** [comment]
```
0.09s2017-03-20 12:58:43 Error executing linode:ubuntu-core-16-64:tests/main/security-devpts : 
-----
+ echo 'Then the pts device follows confinement rules'
Then the pts device follows confinement rules
+ expect -d -f pts.exp
/bin/bash: line 50: expect: command not found
-----
```

**Comment by pedronis** [comment]
we need the expect snap to make this work

**Comment by zyga** [comment]
I'm closing this as @fgimenez has picked it up with the expect as a snap.

**Pull request closed without merging**
