### PR TITLE
wrappers: add RestartServices function and ReloadOrRestart to systemd (3/N)

### PR DESCRIPTION
**Pull request by stolowski**
Add RestartServices helper to wrappers, it's going to be used for `snap set restart [--reload]` semantics in service-control task.

### CODE REVIEW

**Comment by anonymouse64** [comment]
This looks fine, but I don't follow why we need --reload? Can you elaborate on why we need this?

**Comment by stolowski** [comment]
> This looks fine, but I don't follow why we need --reload? Can you elaborate on why we need this?

This is to support `snap restart --reload`.

**Comment by anonymouse64** [comment]
> This is to support snap restart --reload.

Sorry I don't recall being involved in this discussion, so apologies for the silly questions, but stepping back why we need `snap restart --reload`? Is this part of the preseed work?

**Comment by stolowski** [comment]
> > This is to support snap restart --reload.
> 
> Sorry I don't recall being involved in this discussion, so apologies for the silly questions, but stepping back why we need `snap restart --reload`? Is this part of the preseed work?

No, it's unrelated to preseeding. It's part of changes to services & service-control task, previously snap restart --reload would invoke snapctl without wrappers, this is going to be unified now to go through wrappers (always).

**Comment by anonymouse64** [comment]
Ah I'm a fool I didn't realize that snap restart --reload was a thing we support already! :facepalm:

**Pull request merged**
