### PR TITLE
cmd/snap-preseed: initialize snap.SanitizePlugsSlots for gadget in seeds

### PR DESCRIPTION
**Pull request by stolowski**
Initialize SanitizePlugsSlots method, otherwise we panic on readInfo if gadget is present, e.g.

```
panic: SanitizePlugsSlots function not set

goroutine 1 [running]:
github.com/snapcore/snapd/snap.glob..func1(0xc4200b2000)
        /build/snapd/parts/snapd-deb/build/_build/src/github.com/snapcore/snapd/snap/info.go:1133 +0x3b
github.com/snapcore/snapd/snap.infoFromSnapYaml(0xc42012e000, 0x14c, 0x34c, 0xc420127a68, 0x0, 0x0, 0x55571e6392b0)
        /build/snapd/parts/snapd-deb/build/_build/src/github.com/snapcore/snapd/snap/info_snap_yaml.go:227 +0x8cb
github.com/snapcore/snapd/snap.infoFromSnapYamlWithSideInfo(0xc42012e000, 0x14c, 0x34c, 0xc4204b2100, 0xc420127a68, 0x34c, 0x0, 0x0)
        /build/snapd/parts/snapd-deb/build/_build/src/github.com/snapcore/snapd/snap/info.go:1074 +0x4f
github.com/snapcore/snapd/snap.ReadInfoFromSnapFile(0x55571e9a6380, 0xc42004c610, 0xc4204b2100, 0xc42004c610, 0x0, 0x0)
        /build/snapd/parts/snapd-deb/build/_build/src/github.com/snapcore/snapd/snap/info.go:1212 +0x9d
github.com/snapcore/snapd/seed.readInfo(0xc42001a240, 0x3f, 0xc4204b2100, 0x0, 0x55571e64d0f1, 0x6)
        /build/snapd/parts/snapd-deb/build/_build/src/github.com/snapcore/snapd/seed/helpers.go:102 +0x89
github.com/snapcore/snapd/seed.(*seed16).LoadMeta(0xc4201940a0, 0x55571e9a1880, 0xc420213460, 0xc420186240, 0x0)
        /build/snapd/parts/snapd-deb/build/_build/src/github.com/snapcore/snapd/seed/seed16.go:265 +0x5f1
main.glob..func1(0x55571e64c34c, 0x1, 0x0, 0x0, 0x55571e64c74b, 0x4)
        /build/snapd/parts/snapd-deb/build/_build/src/github.com/snapcore/snapd/cmd/snap-preseed/preseed_linux.go:115 +0x16b
main.prepareChroot(0x7fff5943e342, 0x31, 0x0, 0x0, 0x0, 0x0)
        /build/snapd/parts/snapd-deb/build/_build/src/github.com/snapcore/snapd/cmd/snap-preseed/preseed_linux.go:220 +0x28b
main.run(0xc420177c00, 0xc42000c090, 0x1, 0x1, 0x0, 0xc42000e2c0)
        /build/snapd/parts/snapd-deb/build/_build/src/github.com/snapcore/snapd/cmd/snap-preseed/main.go:102 +0x130
main.main()
        /build/snapd/parts/snapd-deb/build/_build/src/github.com/snapcore/snapd/cmd/snap-preseed/main.go:64 +0x72
```

### CODE REVIEW

**Comment by tsunghanliu** [comment]
with this PR, I'm now able to finish the process of `snap-preseed`.

```
/usr/lib/snapd/snap-preseed /home/vagrant/image-builds/work/root
starting to preseed root: /home/vagrant/image-builds/work/root
using snapd binary: /tmp/snapd-preseed/usr/lib/snapd/snapd (2.48.2)
AppArmor status: apparmor is enabled and all features are available
2021/01/29 16:38:37.003978 main.go:57: running for preseeding
2021/01/29 16:38:37.014601 daemon.go:347: started snapd/2.48.2 (series 16; classic) ubuntu/20.04 (amd64) linux/5.4.0-40-generic.
2021/01/29 16:38:37.064958 daemon.go:440: adjusting startup timeout by 30s (pessimistic estimate of 30s plus 5s per snap)
2021/01/29 16:38:37.128847 helpers.go:105: error trying to compare the snap system key: system-key missing on disk
2021/01/29 16:38:40.241127 daemon.go:514: stopping snapd as requested
2021/01/29 16:38:40.241433 daemon.go:589: gracefully waiting for running hooks
2021/01/29 16:38:40.241543 daemon.go:591: done waiting for running hooks
unmounting: /tmp/snapd-preseed
```

**Review by bboozzoo — APPROVED** [review]
LGTM

**Review by mvo5 — APPROVED** [review]
Thank you!

**Review by anonymouse64 — APPROVED** [review]
LGTM, thanks for this

**Pull request merged**
