### PR TITLE
sandbox/apparmor: use host abi 4.0 or 3.0 if present

### PR DESCRIPTION
**Pull request by zyga**
When using apparmor_parser from the host, pin the supported policy to ABI 4.0 or 3.0 if one is present on the host.

This is a twist on https://github.com/snapcore/snapd/pull/13715 as suggested by @alexmurray 

Interestingly, and unexpectedly, this ALSO works, even though we started to pin to 3.0 to avoid an apparent bug in 4.0. Go figure?

CC @alexmurray and @Meulengracht for awareness.

### CODE REVIEW

**Comment by alexmurray** [comment]
So we have a few different cases here.

1. using the host apparmor_parser
2. using the snapd.snap's vendored apparmor_parser

with the hosts parser we don't know what version it will be, but we know that if it ships a given abi file then it should support it, and we should default to the newest abi so that we generate policy for the maximum amount of features.

with the snapd.snap - it vendors apparmor_parser 3.0 so we can only use the 3.0 abi there - we can't use a 4.0 abi since firstly it isn't present in the snap (ie the file abi/4.0 just doesn't exist) and secondly it may not understand all the attributes listed in such a newer abi.

There is a separate PR to update the snapd.snap to 4.0 which will bring it in-line with this change here.

As to why this works @zyga - I don't think there is a bug in 4.0, but just that we never pinned the ABI at all when using the hosts parser so even if it supported the 4.0 abi (ie in noble) it never actually used it since we never told it to assume that abi - now with your change, we do tell it to assume that abi and so the generated policy is correct.

The cases when using the host parser are:

2.x: pins to the kernel ABI by default, there is no other concept of pinning
3.x: by default doesn't pin to any abi except one hard-coded in the parser EXCEPT on Ubuntu we distro-patched it to pin to an ABI called `kernel-5.4-outoftree-network` which is essentially equivalent to the 3.0 abi
4.x: by default doesn't pin to any abi except the hard-coded one in the parser AND we don't distro-patch it on Ubuntu anymore

So for any Ubuntu release pre-4.x the policy effectively *was* pinned to an ABI that snapd expected. cc @jrjohansen does this sound right to you?

**Review by alexmurray — APPROVED** [review]
LGTM - thanks for all the work on this @zyga.

**Comment by alexmurray** [comment]
As to the original issue, I think we might have been hitting something like https://gitlab.com/apparmor/apparmor/-/issues/374 from upstream

**Comment by jrjohansen** [comment]
> So we have a few different cases here.
> 
> 1. using the host apparmor_parser
> 2. using the snapd.snap's vendored apparmor_parser
> 
> with the hosts parser we don't know what version it will be, but we know that if it ships a given abi file then it should support it, and we should default to the newest abi so that we generate policy for the maximum amount of features.
> 
No. This can and will result in breakage. Let me break it down

AppArmor 2.10 - does not support abi files. We could backport support but I am unsure if debian would take such a patch.
AppArmor 2.11-2.13 ignore abi files, they will parse them but they mean nothing to them
AppArmor 3+ support abi files, but the contents of the abi file do not necessarily mean that the parser supports the feature (eg. <kernel> may have stuff that is not supported by the parser).

worse, the declared abi is what you are asserting the policy was created with or at least tested against. If you pick up a newer abi file than the policy was created against, if the kernel and parser support them the new features in the abi will be enabled and enforced. Which can lead to failures, because the policy is not designed with them in mind (missing rules are default deny).

Eg. Lets take user namespace restrictions. snap policies weren't originally authored with them in mind, they need to add the new interface. But if the snap hasn't added the interface and tries to run on noble it will break if it is using user namespace.

The abi files are handled in such a way that features in the abi file that the parser doesn't know about will be ignored, and won't get compiled in or enforced. So you can give it new abi files it doesn't understand.

If you always wanted to enforce maximum features, without worrying about breakage due to policy not containing newer rules then you would use
  abi=<kernel>,

this is essentially what apparmor 2.x does if you don't use pinning. Its great for getting bug reports around policy that needs updated, but is not viable in deployment. It has also lead to kernel features being reverted because some distros don't pin and the kernel dev was not willing to pin.

> with the snapd.snap - it vendors apparmor_parser 3.0 so we can only use the 3.0 abi there - we can't use a 4.0 abi since firstly it isn't present in the snap (ie the file abi/4.0 just doesn't exist) and secondly it may not understand all the attributes listed in such a newer abi.

I agree we shouldn't use abi's that don't exist in the snap. The abi file could easily be patched in or snapd can be updated to vendor noble's apparmor and get the 4.0 abi that way.

The abi file having features that the parser does not understand is okay. It will ignore them. However policy can't have those feature rules if it doesn't understand them or it will break. We are working on fixes for this so that policy can ship information on how to parse missing features, so it can parse and ignore, as well as conditionals where the parser can just skip stuff in the conditional, but we don't have that yet.

> 
> There is a separate PR to update the snapd.snap to 4.0 which will bring it in-line with this change here.
> 
> As to why this works @zyga - I don't think there is a bug in 4.0, but just that we never pinned the ABI at all when using the hosts parser so even if it supported the 4.0 abi (ie in noble) it never actually used it since we never told it to assume that abi - now with your change, we do tell it to assume that abi and so the generated policy is correct.
> 
There is certainly some kind of regression in apparmor 4.0, I am not sure exactly what it is. I suspect it is to do with the new network code in apparmor 4, and it actually might already be fixed with the beta3 release I cut yesterday. I will be hunting for it this week.

For debian, and jammy using the system parser the abi is pinned, and that is why it should work for them. I don't understand how the vendored apparmor 3.x would work in this case as it should be using the default abi, because snap is not pinning nor specifying abi.

The noble apparmor 4 should behave the same as the vendored apparmor 3, that is if there is no pin, and no in policy abi the compile should fallback to the default abi.

> The cases when using the host parser are:
> 
> 2.x: pins to the kernel ABI by default, there is no other concept of pinning 3.x: by default doesn't pin to any abi except one hard-coded in the parser EXCEPT on Ubuntu we distro-patched it to pin to an ABI called `kernel-5.4-outoftree-network` which is essentially equivalent to the 3.0 abi 4.x: by default doesn't pin to any abi except the hard-coded one in the parser AND we don't distro-patch it on Ubuntu anymore
> 

First for abi support I will be very specific

2.x defaults the abi=<kernel>, setting a pin in the conf file overrides this.  debian pins, ubuntu generally has not except the SRU for jammy, and suse, arch do not. Other distros tend to follow the pattern of their parent.
3.x supports pinning, as well as abi rules. the priority is
  1. override-policy-abi  pin: pins 2.x policy, overrides 3.x declared abi
  2. policy declared abi
  3. policy-features/features-file pin.  Allows pinning policy that does not declare an abi
  4. no pin, no abi:  2.x defaults to abi=<kernel> ,  3+ defauts to abi=<default abi>, where the default abi is roughly equivalent to the upstream kernel abi a little before 3.0 was released + out of tree networking (its basically focal kernel abi iirc). It is slightly different from kernel-5.4-outoftree-network, in that it is missing xattr attachment conditions but supports capabilities bpf and perfmon.

AFAIK Ubuntu has not pinned except on releases which received the posix mqueue SRU. This was done so that existing policy would not break.

> So for any Ubuntu release pre-4.x the policy effectively _was_ pinned to an ABI that snapd expected. cc @jrjohansen does this sound right to you?

Hopefully above covered all the cases. But historically, especially for snapd which has to work on different distros, there has been a mix of pinned, and unpinned policy. The move to 3.x (between focal and jammy) moved all policy we shipped to having an abi declared, but snap, lxd, libvirt, and policy shipped as part of the package would continue to rely on 2.x style pinning.

Again:
Ubuntu: only pin on releases with mqueue SRU
Debian: always pinned
Suse: does not pin
Arch: does not pin
Mint: afaik does not pin, did not pickup mqueue SRU
popOS: same as Mint
others, tend to follow their parent distro

**Comment by alexmurray** [comment]
So we have 2 cases where apparmor 3.x is used:

1. where it comes from the host (e.g. on Ubuntu 22.04 LTS) - in which case we pinned to the 5.4-outoftree-network abi
2. when using the snapd snap which vendors apparmor 3.x - in which case we *do* pin to the 3.0 abi - https://github.com/snapcore/snapd/blob/a5a64587a0aa0d4d9ed52fc4ec8ca427308eed7a/sandbox/apparmor/apparmor.go#L479

So noble apparmor 4.x is *NOT* the same as vendored 3.x since vendored 3.x does specify to pin the 3.0 abi.

Also we pinned to 3.0 abi in all ubuntu releases that shipped apparmor 3.x as far as I recall.

**Comment by jrjohansen** [comment]
> So we have 2 cases where apparmor 3.x is used:
> 
3 cases

> 1. where it comes from the host (e.g. on Ubuntu 22.04 LTS) - in which case we pinned to the 5.4-outoftree-network abi
on hosts that got the SRU, this is the case for focal and jammy

> 2. when using the snapd snap which vendors apparmor 3.x - in which case we _do_ pin to the 3.0 abi - https://github.com/snapcore/snapd/blob/a5a64587a0aa0d4d9ed52fc4ec8ca427308eed7a/sandbox/apparmor/apparmor.go#L479
> 
ah, I had missed/forgotten that snapd was pinning the abi

case 3. releases which have not pinned the abi. These would be older releases. Or dev releases

> So noble apparmor 4.x is _NOT_ the same as vendored 3.x since vendored 3.x does specify to pin the 3.0 abi.
> 
correct. It does raise the question of whether we should add a pin, and what that pin should be.

> Also we pinned to 3.0 abi in all ubuntu releases that shipped apparmor 3.x as far as I recall.

nope. Only for the releases that got the SRU. With apparmor 3 we moved all policy we ship to declaring abi in policy. Policy that we don't control, got to behave as it did before. I just checked mantic and lunar, they are not pinned. Focal and Jammy got the SRU and are pinned.

**Comment by jrjohansen** [comment]
> As to the original issue, I think we might have been hitting something like https://gitlab.com/apparmor/apparmor/-/issues/374 from upstream

Yes, this is where I expect the bug/regression. The network code changed a lot in 4.0. There have been a lot of bug fixes since beta2, we need to test and see if beta3 fixes this, or there is another bug lurking.

**Review by jrjohansen — APPROVED** [review]
This looks fine

**Review by jrjohansen — COMMENTED** [review]
So the prefer apparmor 4.0 ABI if available patch, the code is fine but I worry about the potential fallout.

AppArmor 4.0 introduces some new features (eg. user namespace medation). By preferring it, snap is asserting policy for the snap is good and has been tested with the features in the abi.

So for example a snap that uses user namespaces, and was published with a 3.0 apparmor, will all of a sudden break because snap is now compiling policy with the 4.0 abi. It will need a new interface over what it didn't before. This is fine when trying to build/repackage an application, however it is a very poor experience for an already deployed application.

Short term, generically I think it is safer to stick with a single ABI unless we know we want to enable certain features.

Long term, the abi for a givens snap should be declared in some way as part of the manifest, probably at build time. Defaulting to the most recent ABI supported. Specifying a different ABI, would need to be an exception, that would have to get approval.

Ideally interfaces should also carry an abi tag. Currently an include having a different abi than the profile will result in a warning that can be promoted to an error. But the plan is to make it so there is more intelligence around abi in an include or block, so if an include supports more than the base profile then it could be more intelligent about when to allow, warn or error.

I have used include here, as that is the apparmor internal mechanism but we could make this work with snap interfaces as well.

**Review by ernestl — APPROVED** [review]
Looks good, thanks

**Comment by alexmurray** [comment]
> So for example a snap that uses user namespaces, and was published with a 3.0 apparmor, will all of a sudden break because snap is now compiling policy with the 4.0 abi. It will need a new interface over what it didn't before. This is fine when trying to build/repackage an application, however it is a very poor experience for an already deployed application.

When introducing the userns support in snapd, we explicitly added a new interface for this, plus we updated the various other interfaces that we know likely did need it too (like browser-support and lxd-support etc) - so I don't think there is much risk here - but I agree there is some risk of causing regressions, however given the general dangers of unprivileged userns I think it is worth the risk of regression, and the fix is quite painless - affected snaps can just add `plugs: userns` and will work again.

**Comment by zyga** [comment]
I will now rebase this on master, fix capitalisation of ABI in the code and update the commit description to explain why things are being changed better. Please don't merge before that is pushed.

**Comment by jrjohansen** [comment]
> > So for example a snap that uses user namespaces, and was published with a 3.0 apparmor, will all of a sudden break because snap is now compiling policy with the 4.0 abi. It will need a new interface over what it didn't before. This is fine when trying to build/repackage an application, however it is a very poor experience for an already deployed application.
> 
> When introducing the userns support in snapd, we explicitly added a new interface for this, plus we updated the various other interfaces that we know likely did need it too (like browser-support and lxd-support etc) - so I don't think there is much risk here - but I agree there is some risk of causing regressions, however given the general dangers of unprivileged userns I think it is worth the risk of regression, and the fix is quite painless - affected snaps can just add `plugs: userns` and will work again.

sure but it breaks the user when it does fail. Its easy to fix, but not necessarily for the user. Nor is it just userns support. abi 4.0 will break applications on some newer capabilities, posix mqueue, It would be even worse if we had added af_inet, or io_uring.

So for 4.0 vs. 3.0 it can break but hopefully not too much. So for this pull request as long as people are aware of what can happen, sure I am fine with it. Long term I think we need a better plan than just favoring a more recent abi.

**Review by Meulengracht — APPROVED** [review]

**Pull request merged**
