### PR TITLE
tests: use --snap instead of --extra-snaps to create the core image

### PR DESCRIPTION
**Pull request by sergiocazzolato**
This is to make ubuntu-image happy and be able to create the core images
Also updated the output parameter, now output-dir is used

Next step in a following pr is to fix the nested helper

### CODE REVIEW

**Review by anonymouse64 — DISMISSED** [review]
lgtm if the CI is happy

**Comment by anonymouse64** [comment]
uc18 needs some work still:
```
+ /snap/bin/ubuntu-image snap -w /home/image /home/image/pc.model --channel edge --snap /home/image/snapd_2.53.2+git628.g35bb479-dirty_amd64.snap --output-dir /home/image
Fetching pc-kernel
Fetching core18
Fetching pc
WARNING: "snapd" installed from local snaps disconnected from a store cannot be refreshed subsequently!
Copying "/home/image/snapd_2.53.2+git628.g35bb479-dirty_amd64.snap" (snapd)
WARNING: volumes:pc:structure:2:filesystem_label used for defining partition roles; use role instead
+ rm -f './pc-kernel_*.snap' './pc-kernel_*.assert' ./pc-kernel.snap ./pc-kernel.assert './pc_*.snap' './pc_*.assert' ./snapd_14091.snap ./snapd_14091.assert ./core20.snap ./core20.assert
+ os.query is-core20
+ LOOP_PARTITION=3
+ os.query is-core20
+ truncate --size=+400M /home/image/core18-amd64.img
+ sgdisk /home/image/core18-amd64.img -e
Creating new GPT entries.
Warning: The kernel is still using the old partition table.
The new table will be used at the next reboot or after you
run partprobe(8) or kpartx(8)
The operation has completed successfully.
+ parted -s /home/image/core18-amd64.img resizepart 3 100%
Error: Partition doesn't exist.
```

**Comment by sergiocazzolato** [comment]
I see some errors related to:
Write on output file failed because No space left on device

This new ubuntu-image version seems to be creating images with some issues

**Comment by bboozzoo** [comment]
I've cherry picked the commits from this branch and #11077 into #11073 so that we have one branch with all the fixes for ubuntu-image 2.0

**Pull request closed without merging**
