### PR TITLE
tests: add tags to identify the tests that cover the basic functionalities of snapd

### PR DESCRIPTION
**Pull request by sergiocazzolato**
The idea of this change is to tag tests, those tags can be used then by
spread to define which tests have to be executed.

This first change includes the basic tests, which cover the basic
functionalities of snapd. Next step is to define which tests cover
alternative paths of the features, which cover errors, which are
regressions, etc.

### CODE REVIEW

**Review by mardy — APPROVED** [review]
LGTM, that's a great idea!

**Review by bboozzoo — COMMENTED** [review]
Is there a corresponding PR in spread that adds tags support or has it already landed?

**Comment by sergiocazzolato** [comment]
@bboozzoo hi, yes, there is a pr for that https://github.com/snapcore/spread/pull/82

Thanks for the review

**Comment by pedronis** [comment]
we probably need a README somewhere to explain the tags. Also could you explain a bit how you chose the tests?

I would consider this two tests possibly basic functionality tests for core for example:

tests/core/kernel-snap-refresh-on-core/task.yaml
tests/core/enable-disable-units-gpio/task.yaml

I could think of others, I understand that we don't want to mark all tests as basic. I also wonder if we should the reverse and tag tests that are not basic instead?

**Review by stolowski — APPROVED** [review]
LGTM but there is a conflict.

**Comment by anonymouse64** [comment]
So we have 615 spread test task.yaml's in snapt (excluding the nested suite and also the snap-confine suite which I don't even think we run anymore).

I think in order to approve this PR we need to sit down and go through all 615 of those to decide which ones are basic and which aren't. Since this would be a monumentous task for a single PR, I suggest breaking this up by suite, for example we have some smaller suites which should be easier to audit one at a time, see:
```
$ find . -name task.yaml | grep -v ./cmd/snap-confine | grep -v ./tests/nested/ | grep -Po './tests/\K[^\/]+' | sort | uniq -c | sort -h -r
    455 main
     65 core
     55 regression
     18 lib
      6 nightly
      4 upgrade
      4 unit
      4 smoke
      3 completion
      1 tests.pkgs
      1 tests.cleanup
      1 tests.backup
      1 retry
      1 os.query
      1 not
      1 log-parser
      1 log-analyzer
      1 cross
```

We could probably skip the `lib` suite (and all the other single test containing task.yaml suites), since that's not "basic" for snapd, so that leaves looking at `core`, `regression`, and `nightly` first. There might also be some smart way to split up `main` too, but still auditing 455 files seems easier than 615 all at once in a single PR.

**Review by anonymouse64 — CHANGES_REQUESTED** [review]
See previous comment, I'd like this PR to be closed (or this one converted to a single smaller suite) so we can more easily audit this

**Comment by sergiocazzolato** [comment]
@anonymouse64 agree with you, I'll start wit core suite.

**Pull request closed without merging**
