### PR TITLE
integration-tests: added tests for short package names in the store

### PR DESCRIPTION
**Pull request by elopio**

### CODE REVIEW

**Comment by mvo5** [comment]
Thanks for the branch and pardon my ignorance. I'm just curious what exactly is this testing? That the store has a minimal length of 2 chars for a package name and that we can deal with that? If so, why do we explicitly test this? Nothing wrong with it, I'm just curious if there was a reason this came up :)

**Comment by fgimenez** [comment]
:+1: @mvo5 these tests come from the SDoC test recommendations document from Jean-Baptiste's team

Thanks!

**Comment by elopio** [comment]
@mvo5 as Federico said, this is a test requested by the platform QA team. It's good to check that we can handle short queries to the store, and that snaps with the shortest name possible can work. They don't add a lot of value, but add some. The interesting part comes with the tests for the longest possible names. I didn't add them to this PR because I reported three bugs to snapcraft and the store related to that. Only one is a blocker, https://bugs.launchpad.net/bugs/1590624 so it should be doable soon.

**Comment by niemeyer** [comment]
As discussed online, let's please do all new integration tests in spread form now on.

Let's please put this under tests/snap-names, so we can group similar checks there (funny chars rejected, max length, etc).

**Pull request closed without merging**
