### PR TITLE
store: use as much from snap-yaml as possible if available

### PR DESCRIPTION
**Pull request by pedronis**
then applies any store only/store override data

this should help make any pre-download checks/validations work correctly

### CODE REVIEW

**Review by mvo5 — COMMENTED** [review]
Fwiw, I love this change, why is it draft only?

**Comment by pedronis** [comment]
> Fwiw, I love this change, why is it draft only?

just wanting to make sure there are no unforeseen issues from the spread tests, also would like feedback from @jhenstridge

**Review by mvo5 — APPROVED** [review]
Thank you, I love this!

**Review by jhenstridge — APPROVED** [review]
This looks reasonable.

I tried installing the snapd built by CI, and it correctly errored out on `snap install ubuntu-desktop-session` (a snap that relies on `experimental.user-daemons`), where stable snapd lets the install proceed.

**Comment by mvo5** [comment]
I checked the failing tests and it's only fwupd on arch from the required set which is fixed in master (and unrelated) so I will merge it.

**Pull request merged**
