### PR TITLE
snap-confine: run as ordinary user, with capabilities

### PR DESCRIPTION
**Pull request by mardy**
This seems to work. existing namespace can be joined, new namespace can be created. snap-update-ns works too.

NOT FOR MERGING

I'll clean this up and split it as needed

### CODE REVIEW

**Comment by zyga** [comment]
@mardy this is very interesting! I have not read the diff yet but I want to ask you to check how much back can this go.

I've tried doing this very early on in the snap-confine life-cycle but reached a limitation, where the kernel really required root, not a capability, for some of the operations I was doing. I don't recall which operation that was, but either some of the mounts or pivot root, most likely.

IIRC, this was broken on some old version of Fedora or CentOS of the day. Perhaps (most likely) those are EOL now, but the point is that there _is_ a limit on the kernel version that this will most likely impose.

Having this limit documented is valuable.

**Comment by mardy** [comment]
> I've tried doing this very early on in the snap-confine life-cycle but reached a limitation, where the kernel really required root, not a capability, for some of the operations I was doing. I don't recall which operation that was, but either some of the mounts or pivot root, most likely.

I didn't meet this. What I'm currently stuck on is that capabilities don't seem to work under LXD; I wrote a [forum post about it](https://discuss.linuxcontainers.org/t/dac-override-capability-not-working-in-unprivileged-container/15665), but it hasn't received much attention yet. I wonder if you might have any idea about it? Or maybe it's related to the issue that you met before?

**Comment by zyga** [comment]
@mardy I had a look at the lxd code but I would have to dig a bit more to understand that on a Friday evening. If you ignore LXD for a moment, can you run the snapd test suite successfully? Note that in some places the mocking/setup code could restore the setuid root logic due to re-packaging and other hacks.

**Comment by mardy** [comment]
> @mardy I had a look at the lxd code but I would have to dig a bit more to understand that on a Friday evening. If you ignore LXD for a moment, can you run the snapd test suite successfully?

Yes, it's the LXD tests that are failing. I think I resolved all the other issues I encountered.

> Note that in some places the mocking/setup code could restore the setuid root logic due to re-packaging and other hacks.

I don't think this applies, because for the time being I'm not changing the fact that snap-confine has the setuid bit: it still starts as euid 0, but immediately drops to the normal user and uses capabilities instead; so, packaging should not be affected.

The next step would be to get rid of the setuid bit altogether and use capabilities set as filesystem attributes.

**Comment by mvo5** [comment]
This is great stuff but we don't have the capacity to work on it so I'm closing it for now with the appropriate label to pick it up again.

**Pull request closed without merging**
