### PR TITLE
many: remove all `device-setup` fde-setup code

### PR DESCRIPTION
**Pull request by mvo5**
When we initially worked on the inline-cryto-engine (ICE) code we
had a design based on the fde-setup hook that would return a
`device-setup` feature as a hint that ICE should be used. It
turned out this design was impractical and we moved to a much
better approach that got merged in
https://github.com/snapcore/snapd/pull/12589
and relies on support for ICE in the kernel and cryptsetup.

With that new approach all the code that was supporting the
`device-setup/device-unlock` approach can be removed now.

### CODE REVIEW

**Review by pedronis — APPROVED** [review]
thanks, I removed also the device-unlock support and tweaked the changes in api_debug.go and client

**Review by alfonsosanchezbeato — APPROVED** [review]
LGTM (so nice to have PRs actually removing code :slightly_smiling_face:)

**Comment by mvo5** [comment]
Thanks for the extra commits @pedronis ! This looks great.

**Comment by mvo5** [comment]
I re-ran the failed nested `tests/nested/manual/uc20-fde-hooks-v1`:
```
...
2023-04-05 17:49:30 Preparing qemu-nested:ubuntu-20.04-64:tests/nested/manual/ (qemu-nested:ubuntu-20.04-64)...
2023-04-05 17:49:59 Preparing qemu-nested:ubuntu-20.04-64:tests/nested/manual/uc20-fde-hooks-v1 (qemu-nested:ubuntu-20.04-64)...
2023-04-05 17:58:29 Executing qemu-nested:ubuntu-20.04-64:tests/nested/manual/uc20-fde-hooks-v1 (qemu-nested:ubuntu-20.04-64) (1/1)...
2023-04-05 17:58:29 Restoring qemu-nested:ubuntu-20.04-64:tests/nested/manual/uc20-fde-hooks-v1 (qemu-nested:ubuntu-20.04-64)...
2023-04-05 17:58:46 Restoring qemu-nested:ubuntu-20.04-64:tests/nested/manual/ (qemu-nested:ubuntu-20.04-64)...
2023-04-05 17:58:48 Restoring qemu-nested:ubuntu-20.04-64 (qemu-nested:ubuntu-20.04-64)...
2023-04-05 17:58:48 Discarding qemu-nested:ubuntu-20.04-64...
2023-04-05 17:58:48 Successful tasks: 1
2023-04-05 17:58:48 Aborted tasks: 0
```

**Pull request merged**
