### PR TITLE
Revert "snap, client, daemon, store: use and expose "media" more (#5906)"

### PR DESCRIPTION
**Pull request by chipaca**
This reverts commit 08bbeb7289fb943ab6c78432579eaceae555ac71 (#5906).

### CODE REVIEW

**Comment by chipaca** [comment]
Heads up @robert-ancell :-(

**Comment by robert-ancell** [comment]
I don't see an issue offering both screenshots and media. The screenshots field is deprecated and clients should migrate to using media. We expose that in the snapd-glib API by using deprecated flags that tell the developer at compile time to migrate.

Please don't revert this already released change - we already consume this API and this would be an API break. If the intention is to filter the media field to not include screenshots to avoid the duplication then let's just do that change instead. IMO that will be more complex for clients than the current solution but it is better than starting again.

**Comment by niemeyer** [comment]
> Please don't revert this already released change - we already consume this API and this would be an API break.

Wait, what? Is that already in a production release? The affecting change was merged 13 days ago.

Per the note above, we do plan to offer you the data you need. What's at stake here is how this will be designed into the API.

**Comment by chipaca** [comment]
We've come to an agreement that makes this revert unnecessary. More news soon.

**Pull request closed without merging**
