### PR TITLE
o/c/configcore: add faillock configuration

### PR DESCRIPTION
**Pull request by valentindavid**
This creates/removes a marker file `/etc/writable/faillock.enabled` to enable `pam_faillock` on Ubuntu Core.

See https://github.com/snapcore/core-base/pull/81

### CODE REVIEW

**Comment by valentindavid** [comment]
For https://github.com/snapcore/core-base/pull/81

**Comment by alfonsosanchezbeato** [comment]
Could you please provide a more detailed commit message? What is this doing and why do we need it?

**Comment by valentindavid** [comment]
> Could you please provide a more detailed commit message? What is this doing and why do we need it?

I have added a bit more information. But why do we need it? I do not know.

**Review by mvo5 — COMMENTED** [review]
Thanks for this! It looks nice - two bike-sheed questions inline (and I twweaked some tiny bits myself)

**Review by mvo5 — APPROVED** [review]
Thank you!

**Review by Meulengracht — APPROVED** [review]
Thanks! +1

**Review by alfonsosanchezbeato — APPROVED** [review]
LGTM

**Pull request merged**
